### ISSUE TITLE
Gitpod Online Demo with hot reload?

### ISSUE THREAD

**Issue by tang-fe** [apitable/apitable#1001]
## The online Demo can't react to code changes.

Even if I have deleted most of the code and only kept the Dockerfiles, the preview is still working fine.

What I want is a real online development environment with hot reload, which means that if I make changes to the code, the browser will display what I have modified.

**Comment by mr-kelly** [comment]
The Gitpod demo is based on Docker. If you want to use hot reloading, you should run the development environment.

To run a development environment, please refer to the developer guide at:

https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md
