### ISSUE TITLE
fix: 社区版重新 pull 部署后，新注册用户无法创建/加入空间

### ISSUE THREAD

**Issue by MasonChow** [apitable/apitable#1008]
**描述Bug**

社区版重新 pull 部署后，新注册用户无法创建/加入空间

**重现步骤**
重现行为的步骤：
1. 注册一个帐号
2. 创建空间，点击按钮没反应，控制台 network create 接口 500。
3. 已注册的空间发出邀请加入报同样错误

**期望行为**
可以正常加入空间 / 提供可以进行升级修复的 sql 脚本执行

**屏幕截图**

web控制台

<img width="1605" alt="image" src="https://github.com/apitable/apitable/assets/12403684/46b2c541-3e40-4c46-a3c2-268719cd89b1">

**电脑版（请填写以下信息）：**
 - 版本号：latest
 - 操作系统：macos 
 - 浏览器：Chrome

**智能手机（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 设备：[例如 iPhone6]
 - 操作系统：[例如 iOS8.1]
 - 浏览器：[例如内置浏览器，Safari]

**其他上下文**

backend 日志显示 mysql 缺失字段

```
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'unit_id' in 'field list'
### The error may exist in com/apitable/organization/mapper/UnitMapper.java (best guess)
### The error may involve com.apitable.organization.mapper.UnitMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO apitable_unit  ( id, unit_id, space_id, unit_type, unit_ref_id )  VALUES  ( ?, ?, ?, ?, ? )
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'unit_id' in 'field list'
```

<img width="868" alt="image" src="https://github.com/apitable/apitable/assets/12403684/ca641579-2464-4a38-b529-ffec75cb476b">

**Comment by ziqiangai** [comment]
Yes, We added some fields in version 0.21.
https://github.com/apitable/apitable/blob/71f817521309247afdf435ecbb7245cac273ad78/init-db/src/main/resources/db/changelog/0.21/20230517_changeset.xml#L25-L31

You can try `make up` command.

**Comment by MasonChow** [comment]
@Exclamation-mark is work, thx 🙏
