### ISSUE TITLE
bug: widget Chinese garbled characters

### ISSUE THREAD

**Issue by Jack20152019** [apitable/apitable#1011]
中文下，小程序的描述乱码

**Comment by Jack20152019** [comment]
机器人中文下也乱码

**Comment by ChambersChan** [comment]
@Jack20152019 你好，问题已在上周修复。可以重新make up启动，或者根据自己的启动方式，主动拉取更新最新的 init-appdata 镜像后即可恢复。

**Comment by Jack20152019** [comment]
apitable/init-db和apitablt/init-appdate这两个镜像都试过啦，启动不起来，报错



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 3, 2023 11:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apitable/apitable] bug: widget Chinese garbled characters (Issue#1011)




 
@Jack20152019 你好，问题已在上周修复。可以重新make up启动，或者根据自己的启动方式，主动拉取更新最新的 init-appdata 镜像后即可恢复。

**Comment by Jack20152019** [comment]
apitable/init-db和apitable/init-appdate都试过啦，报错，跑不起来



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 3, 2023 11:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apitable/apitable] bug: widget Chinese garbled characters (Issue#1011)




 
@Jack20152019 你好，问题已在上周修复。可以重新make up启动，或者根据自己的启动方式，主动拉取更新最新的 init-appdata 镜像后即可恢复。
