### ISSUE TITLE
移动端深色模式下，日期控件字体不显示

### ISSUE THREAD

**Issue by xiaogua00** [apitable/apitable#1015]
【操作步骤】
1. 移动端+暗黑模式
2. 打开日期控件，文字未显示
![WechatIMG358](https://github.com/apitable/apitable/assets/16549856/c8bbadd5-d53a-4a09-a588-7698e3697586)
【预期结果】
日期控件为黑色背景+白色文字

**Comment by LuJun-vika** [comment]
日期选择组件是用的 adm 组件，背景没有绑定变量，
选择器背景色改为 var(--bgCommonDefault)
<img width="1290" alt="image" src="https://github.com/apitable/apitable/assets/105473667/57509cb0-7705-40a4-821d-bd0c1ca485c8">

**Comment by wangkailang** [comment]
fixed
