### ISSUE TITLE
question: how to get viewId through API

### ISSUE THREAD

**Issue by yorke669** [apitable/apitable#1016]
## viewId 如何通过API获取

从文档看 viewId 是通过浏览器看的，但如何是系统间的集成，应该需要从API获取，如在自有平台集成 APItable

<img width="898" alt="image" src="https://github.com/apitable/apitable/assets/128157265/d0fee9f7-e816-4fb4-8065-7a97ecaf3310">

**Comment by ChambersChan** [comment]
@yorke669 API 支持获取指定表格的视图列表。[api docs](https://developers.apitable.com/api/get-views)
