### ISSUE TITLE
fix: can not load strings.und.json

### ISSUE THREAD

**Issue by wangjing3910** [apitable/apitable#1019]
**描述Bug**
创建新空间时，出现异常（异常情况见截图）

**重现步骤**
1，通过 install.sh 成功安装到本地
curl https://apitable.github.io/install.sh | bash
2，创建用户并进入系统
3，创建新的空间，触发异常（异常情况见截图）

**期望行为**
期望能够成功的创建空间，并继续进行下边的业务

**屏幕截图**
<img width="1791" alt="image" src="https://github.com/apitable/apitable/assets/12859418/29104c4b-b0df-4a1c-aa37-43e35ede672a">

**电脑版（请填写以下信息）：**
 - 版本号：[MacBook Pro 16-inch, 2019]
 - 操作系统：[macOS Ventura 13.1]
 - 浏览器：[Chrome 114.0.5735.198]

**Comment by ziqiangai** [comment]
Similar issue with #1021

**Comment by ziqiangai** [comment]
Hi @wangjing3910, Can you provide the version, enter the following code in the browser console:

```js
window.__initialization_data__.version
```

**Comment by ziqiangai** [comment]
We fixed this problem, pull the new code to try.
