### ISSUE TITLE
fix: client/info setCookie: lang=und then the page could not be opened

### ISSUE THREAD

**Issue by lllling** [apitable/apitable#1021]
When I start my local server, I get an error: ```Error: Language pack: und not found.```

I found out that the reason is the api client/info will sets cookie lang as und. So when I go to the page, it gets lang from cookie, which is und, and tries to get strings.und.json. This file can't be found. So it doesn't have any language packs and throws this error.

After I delete this cookie, I can successfully open the page.

I'm not sure if this is just a local environment issue.

<img width="1001" alt="image" src="https://github.com/apitable/apitable/assets/48577056/8a6b7acb-3cdf-4d20-9cc3-b9fc8c0710e7">
<img width="1077" alt="image" src="https://github.com/apitable/apitable/assets/48577056/4386a0d1-342e-441a-8592-13e1dd5be48e">

**Comment by ziqiangai** [comment]
Hi @lllling ，which case:
- After switching languages? 
- Open Application it for the first time?

**Comment by ziqiangai** [comment]
The string `und` comes from the result of the first server-side render, which has never been reproduced.
![企业微信截图_d1126d02-6898-496a-bcc7-f1aceb173d2f](https://github.com/apitable/apitable/assets/18455767/efcf42d7-35da-442c-8092-9c2faf080625)

**Comment by lllling** [comment]
Refresh after login.

**Comment by lllling** [comment]
https://github.com/apitable/apitable/assets/48577056/11e153c8-637e-4f49-912c-372e6234bccb

This is a video record.

**Comment by ziqiangai** [comment]
Thanks for your feedback, we will fix this issue.

> 2023-07-04.18.39.41.mov 
> This is a video record.

Thanks for your feedback, we will fix this issue.

**Comment by Exclamation-mark** [comment]
Similar issue with 1021

**Comment by ziqiangai** [comment]
We fixed this problem, pull the new code to try.
