### ISSUE TITLE
fix: 【接口404导致界面错误】页面刷新导致错误

### ISSUE THREAD

**Issue by liuJchun** [apitable/apitable#1026]
**描述Bug**
清晰简洁地描述Bug是什么。
http://localhost:3000/file/langs/strings.und.json
接口404导致界面错误，并且返回的 
Cache-Control: no-store, must-revalidate

**重现步骤**
重现行为的步骤：
1. 在开发环境中登录
2. 然后刷新界面就会看到错误

**期望行为**
页面正常，不报错

**屏幕截图**
![Snipaste_2023-07-05_09-56-30](https://github.com/apitable/apitable/assets/33089174/8859b8fa-3677-48da-91b3-20e304e6fbd6)

**电脑版（请填写以下信息）：**
 - 操作系统：macos
 - 浏览器：最新的 chrome

**其他上下文**
该接口是否应该使用协商缓存，不缓存的意义是？

**Comment by ziqiangai** [comment]
Similar issue with https://github.com/apitable/apitable/issues/1021 ，We fixed this problem, pull the new code to try.
