### ISSUE TITLE
question: apitable怎么发布自己的小程序

### ISSUE THREAD

**Issue by baiy513** [apitable/apitable#1035]
## 我用apitable上传小程序时报错，然后看到以下文档，要定义upload host，请问这个host是啥东西，该怎么配置。

![image](https://github.com/apitable/apitable/assets/111549256/9ecfc401-f6da-4e02-9550-7f7c5fb73024)

**Comment by ChambersChan** [comment]
@baiy513 默认情况下是你的apitable host，也是 widget-cli init 那一步的 -h 的host值

**Comment by ranglang** [comment]
If you are deploying apitable on your own server, you should use the server name as **uploadHost**.

**Comment by baiy513** [comment]
经过蓝工指导，已经解决，uploadHost是自己的IP地址或者域名，例如https://vika.cn ，http://112.214.26.106，域名IP后不能带/
