### ISSUE TITLE
ROOM_SERVER ClientProxy 一直报超时

### ISSUE THREAD

**Issue by pengxueshan** [apitable/apitable#1036]
运行make run 2后，一直报超时：
[ROOM_SERVER] Error	2023-07-06 18:52:36.514 [ClientProxy] ping room client :[169.254.239.102:3334] timeout, ping code:[ECONNABORTED] - {
  stack: [
    'Error: timeout of 1500ms exceeded\n' +
      '    at createError (/Users/xxx/apitable/node_modules/@nestjs/axios/node_modules/axios/lib/core/createError.js:16:15)\n' +
      '    at RedirectableRequest.handleRequestTimeout (/Users/xxx/apitable/node_modules/@nestjs/axios/node_modules/axios/lib/adapters/http.js:328:16)\n' +
      '    at RedirectableRequest.emit (node:events:513:28)\n' +
      '    at RedirectableRequest.emit (node:domain:489:12)\n' +
      '    at Timeout.<anonymous> (/Users/xxx/apitable/node_modules/follow-redirects/index.js:164:12)\n' +
      '    at listOnTimeout (node:internal/timers:569:17)\n' +
      '    at processTimers (node:internal/timers:512:7)'
  ]
}

截图如下：
<img width="716" alt="image" src="https://github.com/apitable/apitable/assets/9959433/51178263-0146-4ae7-99b0-162746cc7f81">

**Comment by ChambersChan** [comment]
Hello. Please update the latest code and try again.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).

**Comment by dainunu** [comment]
same,解决了吗
