### ISSUE TITLE
bug: 自己部署的apitable,给镜像添加小程序报错

### ISSUE THREAD

**Issue by baiy513** [apitable/apitable#1041]
**Describe the bug**

**To Reproduce**
1. 打开一个镜像
2. 点击添加小程序
3. 选择一个小程序，比如helloword
4. ![image](https://github.com/apitable/apitable/assets/111549256/b1732837-bb27-4d3f-b06c-4babd2bc9bc2)
附加这个小程序加到datasheet上没啥问题

**Comment by ranglang** [comment]
看起来是OT 命令解析错误，请问刷新后给镜像添加小程序正常么？ ps, 看截图小程序在镜像上已经添加了，刷新后应该正常，如果不正常，请告知下。

**Comment by baiy513** [comment]
经过蓝工指导，发现是自己库中，resource_meta表缺少数据造成的，已经解决
