### ISSUE TITLE
fix: Unable to start `init-db` and `init-appdata` containers in docker .

### ISSUE THREAD

**Issue by manly0305** [apitable/apitable#1047]
**Describe the bug**
Unable to start `init-db` and `init-appdata` containers in docker .

**To Reproduce**
1. Check out `develop` branch
2. Run `make dataenv` in terminal
3. Check Docker containers status by run `docker ps` in terminal
4. Unable to start `init-db` and `init-appdata` containers in docker .  See screenshot 

**Expected behavior**
Should able to start `init-db` and `init-appdata` containers in docker .

**Screenshots**
<img width="1560" alt="Screenshot 2023-07-07 at 18 26 10" src="https://github.com/apitable/apitable/assets/8382355/dbd6a978-88f5-449b-b810-d920f0b92081">

**Desktop (please complete the following information):**
 - MacBook Pro 16-inch,2021 M1 Max
 - Version Ventura 13.4.1
 - OS: macOs

**Comment by ranglang** [comment]
It's ok that initdb exit successfully.

**Comment by manly0305** [comment]
Ok . I was face other mac brew  dependency issue , spend a lot time on docker compose file before solve it.  
You should mention in the developer documents . Else it's very confuse for other people .

**Comment by miaomiao1992** [comment]
make dataenv一直失败，都没法pull，帖主是如何解决的？
