### ISSUE TITLE
master或dev分支感觉可以加一个lock建议文件，防止依赖版本冲突

### ISSUE THREAD

**Issue by aiqubits** [apitable/apitable#1049]
有一两个墙外的包无法直接下载，解析污染cdn地址有时候访问不了，加一个lock 文件方便固定版本手动下载

**Comment by ziqiangai** [comment]
Hi @aiqubits , We have uploaded [yarn.lock](https://github.com/apitable/apitable/blob/develop/yarn.lock) file.

**Comment by llkevin13579** [comment]
Are you using npm instead of yarn?
Seems that they have only ```yarn.lock```

**Comment by arucil** [comment]
There is already a `yarn.lock` file.

**Comment by mr-kelly** [comment]
Yes, we use yarn...

@llkevin13579 Do you have any error screenshots or?

**Comment by llkevin13579** [comment]
> Yes, we use yarn...
> 
> @llkevin13579 Do you have any error screenshots or?

Not yet.  Just discuss with @aiqubits . I guess he uses ```npm``` instead of ```yarn```
