### ISSUE TITLE
If `init-db` does not need to be `running`  in docker, better to specify in the documentation.

### ISSUE THREAD

**Issue by IceRabbit1999** [apitable/apitable#1051]
## What documentation do you want?
I followed the [Developer Quick Start](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A#h-linux) to start develop but got stuck on `make dataenv` as I thought there was an error #1047 since the documentation doesn't say anything about.

I personally took some extra time to confirm that my environment was correct, so perhaps some extra notes should be added to the documentation.

By the way, there is an error on heading level here. [Automation Quick Start](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/quick-start-sOIbWQJR6s)

**Comment by networkhermit** [comment]
Thank you very much. I think both of these suggestions have been updated accordingly.
