### ISSUE TITLE
fix: 用户注册功能bug

### ISSUE THREAD

**Issue by DOnlyone** [apitable/apitable#1052]
https://github.com/apitable/apitable/assets/29710687/19b3e436-2082-4c27-acc7-9fc2f7d2646b

**描述Bug**
当用户注册账号时两次密码不一致可以注册成功

**重现步骤**
重现行为的步骤：
1. 前往用户注册界面
2. 输入邮箱，注册时两次填写密码不一致即可
3. 点击注册，即可登录

**期望行为**
注册时两次密码应该为一致才允许用户注册。

**屏幕截图**
已经上传录屏。

**电脑版（请填写以下信息）：**
 - 版本号：
 - 分支为develop分支
https://github.com/apitable/apitable/tree/develop 

 - 操作系统：Mac OS Big Sur
 - 浏览器： Chrome 

**其他上下文**
无

**Comment by llkevin13579** [comment]
I fixed this issue and please help review it.
https://github.com/apitable/apitable/pull/1074
@mr-kelly @ChambersChan @DOnlyone @nagisakon @laboonly

**Comment by llkevin13579** [comment]
@DOnlyone  This issue has been solved (https://github.com/apitable/apitable/pull/1074)
