### ISSUE TITLE
question:  Usage of node.js built-in libraries in the script engine

### ISSUE THREAD

**Issue by schwartx** [apitable/apitable#1054]
I would like to confirm whether it is possible to node.js built-in libraries in the script engine. Specifically, I would like to use `net.isIPv4()` and `net.isIPv6()` functions to categorize IP addresses. I have tried to use regular expressions for this purpose, but they can't cover all the potential formats of IPv6 addresses. If it's possible to use the `net` library directly, that would simplify the task greatly.

Can someone please provide some guidance on this matter? Thank you.

**Comment by arucil** [comment]
Do you mean using `net` in frontend? I'm afraid you can't do it, but you can use a third-party package with browser support, like https://www.npmjs.com/package/is-ip
