### ISSUE TITLE
question: I don't have  admin account?

### ISSUE THREAD

**Issue by horrylala** [apitable/apitable#1057]
## Any questions?
I dont have admin account, it's strange?
I saw other issues, there got an [admin](https://github.com/apitable/apitable/issues/536) account.

What am i missing?

**Comment by ziqiangai** [comment]
Hi @horrylala ， You can register an account by yourself, and then log in.

**Comment by mr-kelly** [comment]
Thank you for reporting this issue. A filename containing multiple dots (like `1.1.2.jpg`) is completely valid, and the system should correctly parse the final string as the file extension. Rejecting the upload with an "invalid file extension" error is definitely a file-parsing bug. We have recorded it and our backend team will fix the regular expression or string-splitting logic used for file uploads.

---

感谢您报告此问题。包含多个点（如 `1.1.2.jpg`）的文件名是完全合法的，系统应该正确解析最后的字符串作为文件扩展名。以“无效的文件扩展名”错误拒绝上传绝对是一个文件解析 Bug。我们已经将其记录在案，我们的后端团队将修复用于文件上传的正则表达式或字符串拆分逻辑。
