### ISSUE TITLE
question: 请教社区版怎么开启https访问(Please tell me how to enable HTTPS access in the community edition.)

### ISSUE THREAD

**Issue by Green1ee** [apitable/apitable#1061]
## 如题(rt.)
我找到可以在apitable-gateway-1中修改/etc/nginx/conf.d/default.conf 来添加SSL配置，但这这样操作并不安全，也不知道如何使修改的配置生效，感谢帮助。
I found that I can add SSL configuration in apitable-gateway-1 by modifying /etc/nginx/conf.d/default.conf, but it's not safe to do so and I don't know how to make the modification take effect, thanks for the help.

**Comment by mr-kelly** [comment]
I would recommend setting up **a separate Nginx instance as a reverse proxy** and configuring SSL on that Nginx instance. 

This approach provides better security and separation of concerns.

Here are the general steps to follow:

1. Install Nginx on a separate server or virtual machine.
2. Obtain an SSL certificate from a trusted certificate authority (CA), such as Let's Encrypt.
3. Configure Nginx to use SSL by adding the SSL certificate and private key to the Nginx configuration file. You can use the `ssl_certificate` and `ssl_certificate_key` directives to specify the location of the certificate and key files.
4. Configure Nginx to act as a reverse proxy for your community edition application by adding a `location` block to the Nginx configuration file. The `proxy_pass` directive should point to the URL of your community edition application.
5. Test the SSL configuration by accessing your application via HTTPS.

Once you have confirmed that the SSL configuration is working correctly, you can update the DNS records for your domain to point to the new Nginx instance. 

This will ensure that all traffic to your application is encrypted using SSL.

**Comment by mr-kelly** [comment]
I would recommend setting up **a separate Nginx instance as a reverse proxy** and configuring SSL on that Nginx instance. 

This approach provides better security and separation of concerns.

Here are the general steps to follow:

1. Install Nginx on a separate server or virtual machine.
2. Obtain an SSL certificate from a trusted certificate authority (CA), such as Let's Encrypt.
3. Configure Nginx to use SSL by adding the SSL certificate and private key to the Nginx configuration file. You can use the `ssl_certificate` and `ssl_certificate_key` directives to specify the location of the certificate and key files.
4. Configure Nginx to act as a reverse proxy for your community edition application by adding a `location` block to the Nginx configuration file. The `proxy_pass` directive should point to the URL of your community edition application.
5. Test the SSL configuration by accessing your application via HTTPS.

Once you have confirmed that the SSL configuration is working correctly, you can update the DNS records for your domain to point to the new Nginx instance. 

This will ensure that all traffic to your application is encrypted using SSL.

**Comment by Green1ee** [comment]
这确实是一个办法，非常感谢@mr-kelly，但是APITABLE本来就有一个网关了，如果该网关直接实现了HTTPS不是更方便吗，还能减少故障点。
That is indeed a solution, thank you very much, but APITABLE already has a gateway, wouldn't it be more convenient if that gateway implemented HTTPS directly, and also reduce the points of failure.

**Comment by llkevin13579** [comment]
There is another method. If you host on the cloud such as AWS, you could integrate with their related service such as AWS EC2 Load balancers + AWS Certificate Manager(ACM). Set SSL cert to ACM and then config it to its load balancer. 

This method could decouple infra and application. If the SSL cert expires in the future, we only need manually update ACM config. If the application upgrades, we only need to upgrade the application via the apitable document and ignore the SSL cert config inside the application.

**Comment by Green1ee** [comment]
我配置好HTTPS之后，可以进入页面，但是wss无法连接，不知道怎么处理，能帮忙看看吗？谢谢！@mr-kelly
After I configured HTTPS, I can access the page, but wss can't connect, I don't know how to deal with it, can you help me out? Thanks!
![image](https://github.com/apitable/apitable/assets/9738666/762ed3ae-2236-47b1-a1af-98fedf0c71c5)

**Comment by Green1ee** [comment]
感谢 @mr-kelly ，我想我已经配置成功了，主要配置：
Thanks to @mr-kelly, I think I have successfully configured, the main configuration:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    ...
    location / {
        proxy_pass http://apitableservers;
        proxy_set_header Upgrade $http_upgrade;
        # 需要修改反向代理的头，如果前端是升级的连接，代理也需要升级，否则 wss:// 会被当成 http:// 处理
        # The header of the reverse proxy needs to be modified, if the frontend is an upgraded connection, the proxy also needs to be upgraded, otherwise the wss:// will be treated as an http://
        proxy_set_header Connection $connection_upgrade;
    }
}
```
