### ISSUE TITLE
require('@apitable/databus').DataBusModule , the DataBusModule is undefined 

### ISSUE THREAD

**Issue by roach01** [apitable/apitable#1064]
**Describe the bug**

branch: develop
run room-service with error
![bug01](https://github.com/apitable/apitable/assets/16829640/0e759e45-b0e1-44c2-a15f-82441f8fab9d)

**To Reproduce**
1. `make dataenv`
2. `make install-local`
3. `make run-local 2`

**Desktop:**
 - Version [e.g. v0.20]
 - OS: macOS Sonoma(beta3), Apple M2 Max

**Additional context**

![bug1](https://github.com/apitable/apitable/assets/16829640/f032b4b1-061d-4f43-b2a3-617dcac87105)

The required file is generated by the file `build.js`.
But the output here is `module.exports = {}`.
Which means  the constant here `require('@apitable/databus').DataBusModule` is undefined.

![3](https://github.com/apitable/apitable/assets/16829640/2461e805-34cd-4c44-8dbd-d01c73589001)

**Comment by arucil** [comment]
Remove `USE_NATIVE_MODULE=1`  in `.env` file.
