### ISSUE TITLE
fix: 附件上传之上传头像后提示上传成功，但是获取头像403

### ISSUE THREAD

**Issue by forxiucn** [apitable/apitable#1067]
**描述Bug**
附件上传之上传头像后提示上传成功，但是获取头像403。

**重现步骤**
重现行为的步骤：
0. 登陆成功
1. 前往“空间站管理-空间站驾驶舱”
2. 打开浏览器调试窗口，按键盘F12按钮
3. 点击“空间站的默认图标”
4. 选择符合上传格式的图片
5. 这个时候看到上传成功，并且上传API响应也是成功的
6. 点击图片截取编辑对话框的确认按钮后，看到页面提示“编辑空间信息成功”
7. 但是从调试窗口查看图片获取报错，错误码403，页面对应上传的空间站图标展示为白色。

**期望行为**
希望可以正常上传图片。

**屏幕截图**
上传成功截图：
![image](https://github.com/apitable/apitable/assets/11312508/0fbc5772-67cb-470b-ba31-1f7184abaeb6)
获取图片失败截图：
![image](https://github.com/apitable/apitable/assets/11312508/08c03748-58fd-49aa-8efd-7288d650a23a)
![image](https://github.com/apitable/apitable/assets/11312508/3df66005-0338-4060-b208-6fcda6e4414d)

**电脑版（请填写以下信息）：**
 - 版本号：**社区版-All-in-one**
 - 操作系统：CentOS
 - 浏览器：Chrome

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by forxiucn** [comment]
控制台报错信息截图：
![Snipaste_2023-07-12_10-07-37](https://github.com/apitable/apitable/assets/11312508/28a35913-0c07-493b-b2fb-8dce4103f8da)

**Comment by llkevin13579** [comment]
Have you added the rules to the security group?
Minio uses port 9000 and you need to add port 9000 to the security group because it's disabled as default.

**Comment by forxiucn** [comment]
> 

I am using the all in one Docker image, but it seems that this is not the reason

**Comment by shkero** [comment]
请求头像资源的路径好像有问题，http://minio:9000/assets/assets/public/2023/07/08/eeca8179dbde4 ，去掉一个assets就可以正常获得头像了。不知道改哪里才能修复

**Comment by forxiucn** [comment]
I just discovered it, but I just don't know where to fix it. I searched around for the configuration file but couldn't find it....
我刚也发现了，但是就是不知道改哪里才能修复。找了一圈配置文件也没找到。。。。

**Comment by forxiucn** [comment]
I have found the configuration file for Nginx in the Docker instance's/etc/nginx/conf. d/imageproxy. conf, but he did not provide a modification command. I am trying to map this file to the host computer and try it out.

我找到了Nginx的配置文件，在docker实例的/etc/nginx/conf.d/imageproxy.conf，但是他没有提供修改的命令，我正在尝试通过映射这个文件到宿主机上试一下。

**Comment by forxiucn** [comment]
我通过一下方式暂时解决了这个问题，希望官方修改一下Nginx配置文件后再更新一下。
```
docker exec -it apitable /bin/bash
cp imageproxy.conf imageproxy.conf.bak
echo -e '\nlocation /assets {\n  proxy_set_header Host 'minio:9000';\n  proxy_set_header X-Real-IP $remote_addr;\n  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n  proxy_set_header X-Forwarded-Proto $scheme;\n\n  proxy_connect_timeout 300;\n  proxy_http_version 1.1;\n  proxy_set_header Connection "";\n  chunked_transfer_encoding off;\n  proxy_pass   http://imageproxy/image;\n  if ( $args !~* ^imageView ){\n      proxy_pass   http://minio;\n  }\n\n  if ( $request_method = PUT ){\n      proxy_pass http://minio;\n  }\n\n}\n\nlocation =/assets {\n    return 403;\n}\n' imageproxy.conf
cd /usr/local/openresty/nginx
./sbin/nginx -s reload
```

**Comment by forxiucn** [comment]
I found that this still needs to be fixed in the code. I took a look at the default image resources in the previous system that failed to load. Here, I suggest that the official unify the historical data, Nginx configuration files, and the path where the program drops into the library after uploading the files

我发现这个还得修复代码才行了，我看了下之前系统默认已有的图片资源加载失败了，这里还建议官方把历史数据、Nginx配置文件、文件上传后程序落库的路径统一一下

**Comment by raining1123** [comment]
关注
