### ISSUE TITLE
When I delete the group in the Gantt view, the page crashes

### ISSUE THREAD

**Issue by 352718784** [apitable/apitable#1069]
**Describe the bug**
When I delete the group in the Gantt view, the page crashes
**To Reproduce**
1. create a new Gantt view
2. set startDate field and endDate field
3. add some task and groupInfo like this
4. ![image](https://github.com/apitable/apitable/assets/52225733/707a4ec4-3fbf-4de9-bca8-c7b41148d796)
5. delete the group, the page crashes
6. function  getTaskGroupHeaderStyle return undefind 
![image](https://github.com/apitable/apitable/assets/52225733/32bcc40a-ab89-4f76-9f81-ac544cab9ca1)

It seems that after I delete the group, the table still renders the content of the deleted group

**Comment by 352718784** [comment]
I reassigned the groupCount using the depth parameter, 
`groupCount = Math.max(depth + 1, groupCount)`
which temporarily solved the problem, but there should be a more thorough solution

**Comment by pengjin123** [comment]
@352718784 The issue has been resolved. Could you please update the latest code? Thank you
