### ISSUE TITLE
fix: room-server启动存在报错以及本地添加datasheets后出现server error

### ISSUE THREAD

**Issue by enolaved** [apitable/apitable#1070]
**描述Bug**
如题

**重现步骤**
重现行为的步骤：
1. 克隆最新仓库
2. 按照developer guide 启动项目
3. make run: 2
4. 就会出现这个报错

**期望行为**
终端不出现这个错误

**屏幕截图**
<img width="723" alt="image" src="https://github.com/apitable/apitable/assets/131639172/6b771c6d-2b34-4c24-bb40-bc72fa647ca6">

<img width="1440" alt="image" src="https://github.com/apitable/apitable/assets/131639172/1cbf61c1-6616-41d1-8b04-8463dbc0491b">

**电脑版（请填写以下信息）：**
 - 版本号：pc：13.2  browse：114.0.5735.198
 - 操作系统：iOS
 - 浏览器：Chrome

**智能手机（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 设备：[例如 iPhone6]
 - 操作系统：[例如 iOS8.1]
 - 浏览器：[例如内置浏览器，Safari]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by arucil** [comment]
Remove `USE_NATIVE_MODULE=1` in `.env` file.
