### ISSUE TITLE
无法导入 Excel 文件

### ISSUE THREAD

**Issue by luoxianglong233** [apitable/apitable#1080]
**描述Bug**
我尝试用 APITable 导入 Excel 文件，按照文档中的步骤进行操作，选择了正确的 Excel 文件，但在导入过程中遇到了错误。

**重现步骤**
重现行为的步骤：
1. 打开 APITable 网站
2. 登录并创建一个新的 API 表
3. 在 "Data" 选项卡中选择导入 Excel 文件
4. 选择正确的 Excel 文件并点击导入按钮
5. 预期结果应该是成功导入数据，但实际上我收到了一个错误消息:"无法读取文件。请确保文件格式正确并且文件没有被其他进程占用。"
**期望行为**
我期望能够成功导入 Excel 文件，并在 API 表中看到导入的数据。

**电脑版（请填写以下信息）：**
 - 版本号：21H2
 - 操作系统：Windows 11
 - 浏览器：Edge

**Comment by ChambersChan** [comment]
1. 按照提示，可以检查一下，上传的文件，是否处于被其他软件打开编辑中；
2. 需要提供下相关错误信息。操作步骤：上传前打开控制台，上传该文件，提供控制台和网络请求中上传API 响应信息。

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
