### ISSUE TITLE
fix: 安装apiable并启动后，ws失败

### ISSUE THREAD

**Issue by chenhaoxiang** [apitable/apitable#1083]
**描述Bug**
安装命令：
curl https://apitable.github.io/install.sh | bash

系统为纯净系统，安装好curl和docker，Docker version 24.0.4, build 3713ee1。

服务器：内存48G。Linux centos 7.6 

第一次安装并运行：
![image](https://github.com/apitable/apitable/assets/18033084/42163d8c-d3bf-4ba9-9f29-6288ad47395a)

第二次安装并运行： 
![image](https://github.com/apitable/apitable/assets/18033084/0aaffb61-8ab2-41b3-b494-f0f7bdf1d55b)

两次运行为一样的错误；
![image](https://github.com/apitable/apitable/assets/18033084/256959f4-2730-4022-970d-be17df70c802)

docker运行：
![image](https://github.com/apitable/apitable/assets/18033084/adbe33c2-7a95-40f3-b836-b7e51ecf2cfd) 

![image](https://github.com/apitable/apitable/assets/18033084/f613dae0-bf0c-4345-8cd0-8df3b3448d18)

**Comment by chenhaoxiang** [comment]
开始我是在乌班图系统运行，也是一样的问题。

**Comment by Kaiyuan** [comment]
我也是

**Comment by maltoze** [comment]
https://github.com/apitable/apitable/issues/1070#issuecomment-1632054240

> Remove USE_NATIVE_MODULE=1 in .env file.

试试这个

**Comment by chenhaoxiang** [comment]
> [第1070章（评论）](https://github.com/apitable/apitable/issues/1070#issuecomment-1632054240)
> 
> > 删除 .env 文件中的 USE_NATIVE_MODULE=1。
> 
> 试试这个

我和他的安装方式不同，我是Docker一键安装启动的。没有找到 .env 文件在哪里。 

请问克隆项目运行的步骤 方式是什么样的？
是下面的这个方式吗？
1、克隆最新仓库
2、运行：developer guide命令 启动项目
3、make run: 2
是这三个步骤吗？请问需要安装什么环境？

**Comment by maltoze** [comment]
docker 安装的方式也会有 `.env` 文件，试试这样：
```bash
cd {运行安装命令的目录}/apitable
vim .env
# Remove USE_NATIVE_MODULE=1 
docker compose up -d
```

**Comment by chenhaoxiang** [comment]
> docker 安装的方式也会有 `.env` 文件，试试这样：
> 
> ```shell
> cd {运行安装命令的目录}/apitable
> vim .env
> # Remove USE_NATIVE_MODULE=1 
> docker compose up -d
> ```

感谢，解决了
