### ISSUE TITLE
fix: BUG command make install error in jdk 20

### ISSUE THREAD

**Issue by lispking** [apitable/apitable#1084]
the make install bug for jdk 20 like to issue: https://github.com/apitable/apitable/issues/421#issue-1591580994

**Comment by mr-kelly** [comment]
We apologize for any inconvenience, but currently, we only support JDK 8. To manage parallel versions of multiple SDKs, we recommend using SDKMAN! which you can find at [https://sdkman.io/. ↗](https://sdkman.io/) Thank you for your understanding. @lispking

**Comment by mr-kelly** [comment]
We apologize for any inconvenience, but currently, we only support JDK 8. To manage parallel versions of multiple SDKs, we recommend using SDKMAN! which you can find at [https://sdkman.io/. ↗](https://sdkman.io/) Thank you for your understanding. @lispking

**Comment by lispking** [comment]
Jdk 8 has officially announced that it is no longer maintained, and it is recommended to upgrade to jdk 20. However, I am currently expanding the support for the branch
@mr-kelly
