### ISSUE TITLE
question: 注册为什么有跳过验证的逻辑

### ISSUE THREAD

**Issue by zhaoyunxing92** [apitable/apitable#1090]
## Any questions?
注册的时候为什么有跳过注册验证的逻辑 [AuthController#register](https://github.com/apitable/apitable/blob/959c48d86d6c6ec145268cf46e7e7d8d4174c7da/backend-server/application/src/main/java/com/apitable/auth/controller/AuthController.java#L103-L105)

**Comment by ziqiangai** [comment]
Hi @zhaoyunxing92 , we hope the users see results quickly on their own devices on the community edition.
