### ISSUE TITLE
fix: 介绍文档中有一些错误

### ISSUE THREAD

**Issue by fcxjluo** [apitable/apitable#1091]
**描述Bug**
介绍文档中有一些错误
https://apitable.getoutline.com/s/82e078fc-1a8d-4616-b69d-fcdbb18ef715/doc/architecture-of-apitable-CBYJsDTrkr

using `NextJS

room-serve

**屏幕截图**

<img width="828" alt="image" src="https://github.com/apitable/apitable/assets/11330107/8b0e0709-2317-4045-b5d1-d3bc7309c970">

**Comment by networkhermit** [comment]
Thank you very much. I have just corrected these typos.
