### ISSUE TITLE
fix: 社区版更新到v0.23.0-release_1468后room-server无法连接

### ISSUE THREAD

**Issue by Green1ee** [apitable/apitable#1100]
**描述Bug**
社区版docker compose更新到v0.23.0-latest后room-server无法连接。

**重现步骤**
重现行为的步骤：
1.执行以下命令进行升级
```bash
docker compose down -v --remove-orphans
docker ps

cp -pr .data .data.backup
cp docker-compose.yaml docker-compose.yaml.backup
cp .env .env.backup

curl -fLo docker-compose.tar.gz 'https://github.com/apitable/apitable.github.io/releases/latest/download/docker-compose.tar.gz'
tar -xvzf docker-compose.tar.gz

docker compose pull
docker compose up -d

# 运行以下命令可以查看到错误
docker logs apitable/room-server-1
```
2.登录系统验证可以登录，但是无法查看到表格内容

**期望行为**
可以正常使用。

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/9738666/3876bb33-d66e-4b6f-87d0-af68bab27a73)。

**电脑版（请填写以下信息）：**
 - 版本号：v0.23
 - 操作系统：Windows 11
 - 浏览器：Chrome

**Comment by huanghqdx** [comment]
我也一样，表打不开

**Comment by Green1ee** [comment]
> 我也一样，表打不开

还以为就我一个人是这样呢，都没看到其他人提ISSUE，0.23.0-beta.1 和 0.23.0-beta.2 都有这个问题，查看代码是因为从beta1开始，将 nativeapi 改成了 databus，但是有些地方没改到
![image](https://github.com/apitable/apitable/assets/9738666/5b5f66de-b5a2-4965-8cbd-c4a49fd83ce0)

**Comment by airsmon** [comment]
从0.21升级到0.23；room-server 容器反复重启
![image](https://github.com/apitable/apitable/assets/55136870/445a5bee-e561-400b-8b24-96a6c3c3fa99)

**Comment by Green1ee** [comment]
@airsmon 可以考虑先退回到 0.22.0-beta.1 docker 版本是：v0.22.0-beta.1_1431，等修复之后再升级到新版本。我现在不敢轻易升级版本了，国内hub.docker.com又上不去，想回退都找不到版本号

**Comment by networkhermit** [comment]
It seems to be the issue about outdated manifests in https://github.com/apitable/apitable.github.io/releases/latest/download/docker-compose.tar.gz.

I just updated the docker-compose.tar.gz and the problem should be fixed. Please try again if you want to upgrade.

As a bonus tip, you can always pin the image version to specific tag:

```text
IMAGE_PULL_POLICY=if_not_present
IMAGE_REGISTRY=docker.io

IMAGE_BACKEND_SERVER=apitable/backend-server:v0.23.0-beta.2_1502
IMAGE_GATEWAY=apitable/openresty:v0.23.0-beta.2_1502
IMAGE_INIT_DB=apitable/init-db:v0.23.0-beta.2_1502
IMAGE_ROOM_SERVER=apitable/room-server:v0.23.0-beta.2_1502
IMAGE_WEB_SERVER=apitable/web-server:v0.23.0-beta.2_1502
```

**Comment by Green1ee** [comment]
重新升级了，确实可以了，谢谢
Re-upgraded and it does work, thanks @networkhermit .
