### ISSUE TITLE
fix: Table Sharing Feature Not Working Properly

### ISSUE THREAD

**Issue by robocky** [apitable/apitable#1110]
**Describe the bug**
Currently, the table sharing feature only allows users to invite others to collaborate on a table, but it does not provide the option to share and publish the table for wider access. This limitation hinders the efficient dissemination of important information and restricts the collaborative potential of the software.

**To Reproduce**
1. Open the software and log in to your account.
2. Navigate to the table you wish to share.
3. Click on the share button.
4. In the popup sharing options, click on the publish button.
5. The page displays a blank screen without loading the shared content.

**Desktop (please complete the following information):**
 - Version [e.g. vv0.23.0-alpha+1507]
 - OS: [e.g. windows]
 - Browser [e.g. chrome]

**Comment by robocky** [comment]
![image](https://github.com/apitable/apitable/assets/135186247/2196a82e-0217-4209-8eef-d097c4bd9de9)
![image](https://github.com/apitable/apitable/assets/135186247/222e42c9-dab7-4a48-8ea2-11a564178dc8)

**Comment by nagisakon** [comment]
![img_v2_63473bd5-d674-4ba5-b898-d7b6dd1a2ecg](https://github.com/apitable/apitable/assets/49678762/62d227b2-6319-4dcc-ad56-5713d0058f0e)

**Comment by robocky** [comment]
请问这个问题什么时候能够修复？目前这个功能对使用影响比较大。或者是我哪里配置不对？

**Comment by robocky** [comment]
补充一下，实测分享是能够成功的，我在apitable_node_share_setting表中能够查到分享记录，使用share_id进行分享地址访问也能正常访问，只是页面上查看不到这个信息，而且也无法在页面上修改发布的分享设置。
希望下个版本升级时能够尽快fix这个问题，谢谢！
