### ISSUE TITLE
Robot在发送网络请求时如何将结果数据回传给APITable？

### ISSUE THREAD

**Issue by quppenge** [apitable/apitable#1116]
背景说明：
我试图在APITable上搭建一个AIGC的数据分析报告机制；具体表现为在APITable上输入数据集的名称与数据集的数据分析要求，然后通过机器人校验数据格式后发送网络请求给服务器，服务器返回一份数据分析报告的网络地址。

但是我在阅读Rebot教程的时候并没有看见列是否可以接收到请求返回的内容并回写到Table上

**Comment by yanming71107Zhang** [comment]
另外python的apitable api包中得安装pip  install Pydantic==1.7.1，版本高了会报错
mportError: cannot import name 'ForwardRef' from 'pydantic.typing'

**Comment by NeonBubbles** [comment]
> 另外python的apitable api包中得安装pip install Pydantic==1.7.1，版本高了会报错 mportError: cannot import name 'ForwardRef' from 'pydantic.typing'

就是，这个超级讨厌

**Comment by xukecheng** [comment]
> 另外python的apitable api包中得安装pip install Pydantic==1.7.1，版本高了会报错 mportError: cannot import name 'ForwardRef' from 'pydantic.typing'

Thank you for reporting the issue. I have created an issue on https://github.com/apitable/apitable-sdks/issues/116. We will confirm the problem as soon as possible. If you have any additional details, please add them to this issue.

**Comment by xukecheng** [comment]
> 背景说明： 我试图在APITable上搭建一个AIGC的数据分析报告机制；具体表现为在APITable上输入数据集的名称与数据集的数据分析要求，然后通过机器人校验数据格式后发送网络请求给服务器，服务器返回一份数据分析报告的网络地址。
> 
> 但是我在阅读Rebot教程的时候并没有看见列是否可以接收到请求返回的内容并回写到Table上

APITable temporarily does not support direct create or update records by robots, you can use Send Web Requests Action to call [APITable Fusion API](https://developers.apitable.com/api/introduction/).
And we are working on a significant update to the automation function of APITable, and the relevant capabilities will be supplemented and improved as soon as possible. Thank you for your suggestions 🙏.

**Comment by xukecheng** [comment]
> 另外python的apitable api包中得安装pip install Pydantic==1.7.1，版本高了会报错 mportError: cannot import name 'ForwardRef' from 'pydantic.typing'

I failed to reproduce this error: importError: cannot import name 'ForwardRef' from 'pydantic.typing', please add more information [here](https://github.com/apitable/apitable-sdks/issues/116), thanks 🙏

![CleanShot 2023-07-25 at 16 40 21](https://github.com/apitable/apitable/assets/29099863/0e32e826-1ff5-4d89-b340-9392754bbb55)

**Comment by NeonBubbles** [comment]
> > 另外python的apitable api包中得安装pip install Pydantic==1.7.1，版本高了会报错 mportError: cannot import name 'ForwardRef' from 'pydantic.typing'
> 
> 
> 
> I failed to reproduce this error: importError: cannot import name 'ForwardRef' from 'pydantic.typing', please add more information [here](https://github.com/apitable/apitable-sdks/issues/116), thanks 🙏
> 
> 
> 
> ![CleanShot 2023-07-25 at 16 40 21](https://github.com/apitable/apitable/assets/29099863/0e32e826-1ff5-4d89-b340-9392754bbb55)
> 
> 


我用的是anaconda也会报错，必须要按照低级版本才行

**Comment by xukecheng** [comment]
> > > 另外python的apitable api包中得安装pip install Pydantic==1.7.1，版本高了会报错 mportError: cannot import name 'ForwardRef' from 'pydantic.typing'
> > 
> > 
> > I failed to reproduce this error: importError: cannot import name 'ForwardRef' from 'pydantic.typing', please add more information [here](https://github.com/apitable/apitable-sdks/issues/116), thanks 🙏
> > ![CleanShot 2023-07-25 at 16 40 21](https://user-images.githubusercontent.com/29099863/255842793-0e32e826-1ff5-4d89-b340-9392754bbb55.png)
> 
> 我用的是anaconda也会报错，必须要按照低级版本才行

https://github.com/apitable/apitable-sdks/issues/116#issuecomment-1650900906
