### ISSUE TITLE
question: 这个有管理员账户码

### ISSUE THREAD

**Issue by a506488043** [apitable/apitable#1117]
## 希望有个关闭新用户注册的选项

**Comment by ChambersChan** [comment]
没有系统管理员。 

关闭注册可以修改环境变量 `SKIP_REGISTER_VALIDATE=false`，然后重启 backend-server 。

**Comment by a506488043** [comment]
我这是用docker部署的，在哪里修改环境变量？

**Comment by ChambersChan** [comment]
在 [.env](https://github.com/apitable/apitable/blob/develop/.env#L82) 文件修改该变量

**Comment by a506488043** [comment]
修改了.env和重启backend-server，并没有生效呀

**Comment by ChambersChan** [comment]
不是用 docker-compose 的配置吗？这里会涉及很多配置。
<img width="657" alt="image" src="https://github.com/apitable/apitable/assets/32906036/6f8606e7-0e92-40e1-b5ea-287d465292ec">

纯docker run ➕ 一个-e 参数， docker run ... -e  SKIP_REGISTER_VALIDATE=false

**Comment by a506488043** [comment]
.env 里的配置是安装部署前才生效的吧。

**Comment by ChambersChan** [comment]
是的，所以修改后需要重新部署一下 backend-server

**Comment by a506488043** [comment]
是重新部署，不是重启backend-server吧。

**Comment by ChambersChan** [comment]
当然可以直接全部重新部署，如果是单个启动也可以只重新部署 backend-server。
