### ISSUE TITLE
why uable to open apitable page(self-hosted) via clash proxy?

### ISSUE THREAD

**Issue by NeonBubbles** [apitable/apitable#1120]
I self-hosted APItable on a VPS, and I couldn't open the webpage before. 
https://github.com/apitable/apitable/issues/1111

 Later, I found out that as long as I turn off the system proxy function in Clash, I can open it. I've tried several different VPS and used different proxy servers, and they all produced the same result.

As long as the system proxy in Clash is on, even if I choose a direct connection, it won't work. But as long as Clash is turned off, I can open my webpage even if I manually turn on the system proxy in Windows 10.

Although I can now open the webpage, it's really troublesome to have to turn off the system proxy every time. I would like to know if this is a problem with Clash or APItable. Has anyone else encountered this kind of problem?

Here is the address: http://185.117.0.166/login

**Comment by NeonBubbles** [comment]
I didn't encounter this problem with Clash on Windows 11, but it occurs on Windows 10 (Clash for Windows), Mac (Clash for Windows), and iOS (Stash). Moreover, when I forcibly use TUN mode in iOS (Stash) or use  proxy via shadowsocket, I can also open the webpage. But activating TUN mode in Clash on Windows 10 doesn't work.

I'm wondering if this is due to incompatibility between Clash and API table?

**Comment by NeonBubbles** [comment]
@xukecheng  请问知道这是什么情况吗，我在几个vps和电脑上试过了，用clash就是连不上，唉...............

**Comment by networkhermit** [comment]
I don't think it's a bug of apitable. I tried to enable clashx on macos, accessing a testing instance via DIRECT mode and accessing your mentioned instance via proxy mode, both can be logged in.

**Comment by NeonBubbles** [comment]
> I don't think it's a bug of apitable. I tried to enable clashx on macos, accessing a testing instance via DIRECT mode and accessing your mentioned instance via proxy mode, both can be logged in.

Thanks, I tried connecting via Clashx on my Mac (big sur) tonight but still failed.
so weird.........

**Comment by qiaoqka** [comment]
> 

我也碰到了。。整了一天没搞明白。原来是这样。。
Mac系统，用的ClashX(1.117.1 Beta)，设置为系统代理后，就无法访问外网ip(vps)的apitable web。但如果在局域网里可以访问192.x.x.x的apitable web。关闭系统代理开关后，可以正常访问外网ip(vps)的apitable web

**Comment by qiaoqka** [comment]
> > I don't think it's a bug of apitable. I tried to enable clashx on macos, accessing a testing instance via DIRECT mode and accessing your mentioned instance via proxy mode, both can be logged in.
> 
> Thanks, I tried connecting via Clashx on my Mac (big sur) tonight but still failed. so weird.........

我也碰到了。。整了一天没搞明白。原来是这样。。
Mac系统，用的ClashX(1.117.1 Beta)，设置为系统代理后，就无法访问外网ip(vps)的apitable web。但如果在局域网里可以访问192.x.x.x的apitable web。关闭系统代理开关后，可以正常访问外网ip(vps)的apitable web

**Comment by NeonBubbles** [comment]
> > > I don't think it's a bug of apitable. I tried to enable clashx on macos, accessing a testing instance via DIRECT mode and accessing your mentioned instance via proxy mode, both can be logged in.
> > 
> > 
> > Thanks, I tried connecting via Clashx on my Mac (big sur) tonight but still failed. so weird.........
> 
> 我也碰到了。。整了一天没搞明白。原来是这样。。 Mac系统，用的ClashX(1.117.1 Beta)，设置为系统代理后，就无法访问外网ip(vps)的apitable web。但如果在局域网里可以访问192.x.x.x的apitable web。关闭系统代理开关后，可以正常访问外网ip(vps)的apitable web

昨天发现可以使用cloudflare的免费服务，让域名使用它们的nameserver实现代理转发，这样就能直接用clash了。
或者用firefox，设置中选择不使用系统代理。
