### ISSUE TITLE
question: 开源社区版本，单表限制的数据行数问题

### ISSUE THREAD

**Issue by lleytonyu** [apitable/apitable#1122]
<img width="1573" alt="image" src="https://github.com/apitable/apitable/assets/34887355/31542634-2cf3-40b0-ac19-8db99f593695">
这个限制，可以通过修改github下载的源码，来放开这个限制吗？

**Comment by ChambersChan** [comment]
可以，修改 [.env.defaults](https://github.com/apitable/apitable/blob/develop/packages/room-server/env/.env.defaults#L34C30-L34C30)  SERVER_MAX_RECORD_COUNT 数值

**Comment by lleytonyu** [comment]
> 可以，修改 [.env.defaults](https://github.com/apitable/apitable/blob/develop/packages/room-server/env/.env.defaults#L34C30-L34C30) SERVER_MAX_RECORD_COUNT 数值

收到，在确认下，开源社区版，通过修改这个值，会生效吗？因为文档中写的是开源社区版本，会有这个限制。 @ChambersChan

**Comment by lleytonyu** [comment]
另外，在请问下，我们可以基于开源的代码，去开发这个功能吗？就是字段权限的设置。
<img width="1529" alt="image" src="https://github.com/apitable/apitable/assets/34887355/59aac570-7ca2-4b67-849c-98b9d6b692e0">

**Comment by mr-kelly** [comment]
> 另外，在请问下，我们可以基于开源的代码，去开发这个功能吗？就是字段权限的设置。
> 
> <img width="1529" alt="image" src="https://github.com/apitable/apitable/assets/34887355/59aac570-7ca2-4b67-849c-98b9d6b692e0">
> 
> 

This feature for cloud edition vikadata.com or apitable.com

**Comment by lleytonyu** [comment]
> > 另外，在请问下，我们可以基于开源的代码，去开发这个功能吗？就是字段权限的设置。
> > <img alt="image" width="1529" src="https://user-images.githubusercontent.com/34887355/255775844-59aac570-7ca2-4b67-849c-98b9d6b692e0.png">
> 
> This feature for cloud edition vikadata.com or apitable.com

get it. thanks!

**Comment by Gavin-J** [comment]
> > 可以，修改 [.env.defaults](https://github.com/apitable/apitable/blob/develop/packages/room-server/env/.env.defaults#L34C30-L34C30) SERVER_MAX_RECORD_COUNT 数值
> 
> 收到，在确认下，开源社区版，通过修改这个值，会生效吗？因为文档中写的是开源社区版本，会有这个限制。 @ChambersChan

修改那个环境变量是没有用的，现在是在代码里写死的。需要修改代码，重新打包。
https://github.com/apitable/apitable/blob/develop/backend-server/application/src/main/java/com/apitable/interfaces/billing/model/DefaultSubscriptionFeature.java



    @Override
    public Seat getSeat() {
        return new Seat(2L);
    }

    @Override
    public TotalRows getTotalRows() {
        return new TotalRows(250L);
    }


    @Override
    public FileNodeNums getFileNodeNums() {
        return new FileNodeNums(5L);
    }

    @Override
    public RowsPerSheet getRowsPerSheet() {
        return new RowsPerSheet(100L);
    }
