### ISSUE TITLE
Can not set a reminder in the date cell(can not found the bell in the date cell)

### ISSUE THREAD

**Issue by woojunrt** [apitable/apitable#1132]
Can not found the bell when my mouse in the date cell.
cloud you please help to check or tell me how to do.

thanks always!!!

![issue_20230725](https://github.com/apitable/apitable/assets/134896929/53bb429f-ca52-4e1f-b782-5e72e32426d4)

**Comment by Alex-hufeng** [comment]
The feature is not currently available in Community version, we will consider improving this feature in the future.
you can use it in Cloud version now: https://apitable.com/

**Comment by woojunrt** [comment]
Thans for your reply.
I see.
it`s helpful to open this future and will promotion this project.
