### ISSUE TITLE
question: APITable 项目处在什么阶段？

### ISSUE THREAD

**Issue by QAQmmttyyy** [apitable/apitable#1138]
是已经成熟还是？

**Comment by QAQmmttyyy** [comment]
PS：初次接触多维表格是在使用feishu的时候，APITable 这个项目很 cool ！

**Comment by mr-kelly** [comment]
matur

**Comment by QAQmmttyyy** [comment]
> matur

Got it. Thx!

**Comment by Green1ee** [comment]
发布的版本号是 0.XY ，通常来讲应该是草稿阶段。用过一段时间，后台服务没有崩过，前端界面时不时会崩，需要刷新页面来恢复。
