### ISSUE TITLE
Support for deploying on Windows Server

### ISSUE THREAD

**Issue by steskalja** [apitable/apitable#114]
Your docker deploy script only takes in to account linux, where as windows server is still around 75% of the onprem market and about 50% of the cloud market. You need to create a powershell docker deploy script for your app.

**Comment by networkhermit** [comment]
hi, currently we do not have plan to support for deploying on windows server. We recommend using Linux vm like ubuntu as a workaround.

**Comment by wemod123** [comment]
Amazing project 🎉
If only about deploy, the matual way is build all-in-one docker image, looking forward the image release.
