### ISSUE TITLE
fix: Update 更新 好像会新建一行数据

### ISSUE THREAD

**Issue by starmisszhang** [apitable/apitable#1148]
API功能:recordId核对过,用自动生成的API示范数据也会新建一行,不会在原来基础上行更新,测试不同的表格结果一样,每次都会生成新的recordId

**Comment by starmisszhang** [comment]
不确定是不是我搞错了

**Comment by ChambersChan** [comment]
可以确认下请求方式，修改是用`PATCH`，若是 `POST` 会新增记录。

![image](https://github.com/apitable/apitable/assets/32906036/a2db8a2b-24aa-427e-88f0-6b31d4509d64)
![image](https://github.com/apitable/apitable/assets/32906036/b74d6746-693f-4bbe-95bb-a3e95a10c214)

**Comment by starmisszhang** [comment]
不好意思,技术太菜,看漏请求方式
