### ISSUE TITLE
question: Looks like the "Automation" Chapter  is Outdated

### ISSUE THREAD

**Issue by capraynor** [apitable/apitable#1155]
Greetings, APITable team: 

I'm a beginner user of APITable, and trying to add a customized Automation Action via coding. 

During my investigation, I've found [this chapter](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/quick-start-sOIbWQJR6s) describing the Automation Customization. A `AutomationAction` decorator should be used when defining an automation action. 

But during I'm trying to write an implementation, I've found no reference (built in automation actions like sms, webhook and send slack message) to `AutomationAction`, but I've found the following SQL Server tables are used for automation actions: 

`apitable_automation_action`

`apitable_automation_action_type`

**My question is**: Is my statement above correct? If so, I will try to submit something to modify the Cookbook, and begin my implementation work based on this investigation. 

Thousand thanks for your awesome project. 

Kindly Regards

Raynor

**Comment by ChambersChan** [comment]
Cookbook bootstrapping is correct.

The automation action type actually supports a combination of remote (db data) and decorator model (local code).
