### ISSUE TITLE
fix: Adding the Chart widget or Pivot table displays the error

### ISSUE THREAD

**Issue by nagisakon** [apitable/apitable#1162]
**Describe the bug**

**To Reproduce**
1. Add a new Chart widget or Pivot table
2. Display error message like “An unknown error has occurred, please refresh and retry”
![image](https://github.com/apitable/apitable/assets/49678762/375aba1a-dbb6-4643-a0ee-b60568e7d0de)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v0.20]

**Smartphone (please complete the following information):**
 - Version [e.g. v0.20]

**Additional context**

**Comment by wangkailang** [comment]
fixed
