### ISSUE TITLE
question: What computer should i have to do apitable development?

### ISSUE THREAD

**Issue by panjiangyi** [apitable/apitable#1174]
After i setup the environment, my little Macbook air was on fire.

**Comment by pengjin123** [comment]
@panjiangyi Please take a screenshot and take a look. Thank you

**Comment by panjiangyi** [comment]
> @panjiangyi Please take a screenshot and take a look. Thank you
> 
> 
> 
> 

I fired this issue just because I applied to your team’s job. Hope I can get an interview😃. Thanks!
