### ISSUE TITLE
question: How should I update all apitable programs and keep the data already entered?

### ISSUE THREAD

**Issue by telungit** [apitable/apitable#1177]
How should I update all apitable programs and keep the data already entered?

**Comment by lumos0** [comment]
fyi:

https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW#h-how-to-upgrade-to-the-newest-release-version

**Comment by lumos0** [comment]
ps: 
i tried but failed
see #1182
