### ISSUE TITLE
fix: Mirrors of views with group by on hidden column does not preserve groups

### ISSUE THREAD

**Issue by briankinney** [apitable/apitable#1194]
**Describe the bug**
A mirror of a group by view that has the grouped column hidden does not show the records in groups.

**To Reproduce**
1. Create a new datasheet with at least one column other than the display column
2. Create a view in the datasheet grouped by the column
3. Group by the non-display column
4. Hide the grouped column
5. Create a mirror of the view
6. Open the mirro in browser
7. The mirror does not show groups. Where the group label should appear there is the message "You have no access to the field"

**Expected behavior**
The groups should appear even though the grouped field is hidden from the grid part of the grid view

**Screenshots**
Screenshot showing buggy mirror view
![image](https://github.com/apitable/apitable/assets/6935747/587c8852-fd1d-4f35-8121-e261153c71d9)

Screenshot showing original view used to create the mirror
![image](https://github.com/apitable/apitable/assets/6935747/45396df4-7595-49ca-903c-e33b72fea20f)

**Desktop (please complete the following information):**
 - Version 0.23
 - OS: Ubuntu
 - Browser Chrom

**Additional context**
It seems that the viewable fields in mirrors should include all group by columns in addition to the columns displayed in the normal part of the grid. It is pretty common that I want to remove the group by columns from the grid part of the view because it is redundant information.

I can get the mirror to work the way I want if I select the option to make all columns available to mirror viewers, but this is not a perfect workaround.

**Comment by pengjin123** [comment]
@briankinney Modifying view configurations within the mirror only has temporary effects and won't be saved. To save the changes, you need to modify the view configurations in the source table

**Comment by briankinney** [comment]
This bug is not about modifying view configurations via a mirror though. I save changes to the view only through the original view, and then the mirror is not working.
