### ISSUE TITLE
急急急急急急，make install 报错，依赖装不下来

### ISSUE THREAD

**Issue by shitoushushu** [apitable/apitable#1199]
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zen-observable-ts@npm:1.2.2 can't be found in the cache and will be fetched from the remote regis
➤ YN0013: │ zen-observable@npm:0.8.15 can't be found in the cache and will be fetched from the remote registr
➤ YN0013: │ zip-stream@npm:3.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zwitch@npm:1.0.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 3m 47s
➤ YN0000: ┌ Link step
➤ YN0007: │ core-js@npm:2.6.10 must be built because it never has been before or the last one failed
➤ YN0007: │ highlight.js@npm:9.18.5 must be built because it never has been before or the last one failed
➤ YN0007: │ styled-components@npm:5.3.6 [35072] must be built because it never has been before or the last one failed
➤ YN0007: │ cypress@npm:8.3.0 must be built because it never has been before or the last one failed
➤ YN0007: │ canvas@npm:2.9.1 must be built because it never has been before or the last one failed
➤ YN0007: │ @nestjs/core@npm:7.6.18 [a1a68] must be built because it never has been before or the last one failed
➤ YN0007: │ protobufjs@npm:6.11.2 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.16.4 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.16.0 must be built because it never has been before or the last one failed
➤ YN0007: │ ejs@npm:2.7.4 must be built because it never has been before or the last one failed
➤ YN0007: │ protobufjs@npm:7.1.2 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
➤ YN0007: │ nice-napi@npm:1.0.2 must be built because it never has been before or the last one failed
➤ YN0007: │ @sentry/cli@npm:1.74.6 must be built because it never has been before or the last one failed
➤ YN0009: │ nice-napi@npm:1.0.2 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-fb08de92/build.log)

**Comment by mr-kelly** [comment]
Please follow the issue format

https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&projects=&template=bug_report_cn.md&title=fix%3A+%E7%AE%80%E7%9F%AD%E7%9A%84BUG%E6%8F%8F%E8%BF%B0
