### ISSUE TITLE
fix: Error in creating new form in working directory

### ISSUE THREAD

**Issue by pengjin123** [apitable/apitable#120]
**Describe the bug**
Error in creating new form in working directory

**To Reproduce**
1.Enter the apitable space station
2.Click the "+" button in the working directory
3. Click the new form button in the list
4.Error is reported on the console

**Expected behavior**
Click the new form button to pop up all the created tables in the space station

**Screenshots**
![image](https://user-images.githubusercontent.com/108248808/210139872-99412a26-c4f7-4821-a25a-2edc83ded7f0.png)

**Desktop (please complete the following information):**
 - OS:  windows 10
 - Browser : Chrome 108.0.5359.125

**Comment by Sky-FE** [comment]
No need to fix.
