### ISSUE TITLE
fix: no member named 'accessorsignature' in namespace 'v8'

### ISSUE THREAD

**Issue by HuangFJ** [apitable/apitable#1209]
**描述Bug**
源代码编译，执行`make install`的时候查看日志发现在安装`node-canvas`这个package的时候报错：no member named 'accessorsignature' in namespace 'v8'

![111](https://github.com/apitable/apitable/assets/106249/939223d3-eec6-4450-91a4-f045b94cd6fa)

**电脑版（请填写以下信息）：**
 - 版本号：branch: develop, commit-id: 3e86d53712bf2e50d244b7218e13c2d03eadce2e
 - 操作系统：macOS 13.4.1 M2

**Comment by mr-kelly** [comment]
Have you fixed?

**Comment by HuangFJ** [comment]
> 

Yes, due to the version conflicts I think. So I just add the following code in the section of resolutions in the package.json
```
"nan": "2.17.0",
"canvas": "2.11.2"
```
Ant it works.
