### ISSUE TITLE
question: 多人协同技术方案

### ISSUE THREAD

**Issue by lleytonyu** [apitable/apitable#1223]
## 请问apitable中多人协同的技术方案，是自建的多人协同还是基于开源框架，如果是基于开源框架，方便发一下使用的是哪些开源框架吗？

**Comment by ChambersChan** [comment]
OT algorithm implement function + socket.io.

**Comment by lleytonyu** [comment]
收到，请问OT算法是自研的，还是基于开源框架呢？如果是基于开源框架，方便发我下开源框架的名称吗？

**Comment by mr-kelly** [comment]
> 收到，请问OT算法是自研的，还是基于开源框架呢？如果是基于开源框架，方便发我下开源框架的名称吗？

No framework

**Comment by lleytonyu** [comment]
> > 收到，请问OT算法是自研的，还是基于开源框架呢？如果是基于开源框架，方便发我下开源框架的名称吗？
> 
> No framework

收到，谢谢。
