### ISSUE TITLE
fix: The network request robot does not support lookup fields

### ISSUE THREAD

**Issue by buckcao** [apitable/apitable#1228]
I have an idea for this project.

网络请求action 不支持引用表格里面的字段

![image](https://github.com/apitable/apitable/assets/2275784/bcf1ef30-add0-42d7-b221-740542fb31c5)

**Comment by ChambersChan** [comment]
Need enter the symbol "/" to activate the variables panel. 👉 [guide docs](https://help.apitable.com/docs/guide/manual-automation-robot/#how-to-use-variables-in-actions)
