### ISSUE TITLE
question: it has Chinese language version?

### ISSUE THREAD

**Issue by gitoftom** [apitable/apitable#123]
Is there a Chinese translation package?

**Comment by mr-kelly** [comment]
> Is there a Chinese translation package?

yes. working on

**Comment by pengjin123** [comment]
@gitoftom The login page currently does not support Chinese, but you can set the language after login (My Settings>Preferences)

**Comment by Green1ee** [comment]
> @gitoftom The login page currently does not support Chinese, but you can set the language after login (My Settings>Preferences)

No change after selecting Chinese

**Comment by eafun** [comment]
How to set the default language to Chinese?

**Comment by mr-kelly** [comment]
> How to set the default language to Chinese?

Language is automatically detected by your browser.
