### ISSUE TITLE
fix: Can not start room-server and web-server in local env

### ISSUE THREAD

**Issue by a523** [apitable/apitable#1234]
**Describe the bug**
I'm new to APITable and trying to set up the development environment locally. 
I encountered some issues towards the end when I was almost close to succeeding. 
The command "make run: 2" resulted in an error.
for room-server:
```shell
DeprecationWarning: 'getMutableClone' has been deprecated since v4.0.0. Use an appropriate `factory.update...` method instead, use `setCommentRange` or `setSourceMapRange`, and avoid setting `parent`.
DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.
src/automation/actions/decorators/automation.action.decorator.ts:19:42 - error TS2307: Cannot find module '@apitable/core' or its corresponding type declarations.
```

for web-server:
```shell
error - ./pages/_app.tsx:21:0
Module not found: Can't resolve '@apitable/core'
  19 | // import App from 'next/app'
  20 | import React, { useEffect, useLayoutEffect, useState } from 'react';
> 21 | import {
  22 |   Api,
  23 |   integrateCdnHost,
  24 |   Navigation,
```
Both of these issues seem to be related to the absence of the '@apitable/core' module.
How can I get the '@apitable/core'?

I've made sure to run 'nvm use', and I've also used 'git checkout v0.99.0-beta.1'.

**To Reproduce**
I followed this guide https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A to get started. What did I do wrong?

**Expected behavior**
run sucessful

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v0.99.0]
 - OS: [mac OS]

**Comment by a523** [comment]
I finally found the answer in another issue, https://github.com/apitable/apitable/issues/971. 
After I completed running `yarn build:dst:pre`, I reran `make run 2 or 3`, and now I can see the front-end page. 
I'm not a front-end expert, so I'm not exactly sure what this command does. However, it seems like it was forgotten to be added to the makefile.

**Comment by ChambersChan** [comment]
This command is actually executed in the `make install` step in the guide.
<img width="909" alt="image" src="https://github.com/apitable/apitable/assets/32906036/7e183828-8500-4bf0-85ce-82f719867b63">

**Comment by a523** [comment]
Oh, Really? I remember I have executed `make install` before this. @ChambersChan 
pls, check the makefile.

**Comment by a523** [comment]
Oh, Really? I remember I have executed `make install` before this

**Comment by ChambersChan** [comment]
Yes, make install already includes `yarn build:pre`, which is the same price as `build:dst:pre`.
<img width="588" alt="image" src="https://github.com/apitable/apitable/assets/32906036/10386526-219e-48a7-ab9b-878ae9a10826">
<img width="1441" alt="image" src="https://github.com/apitable/apitable/assets/32906036/ba7dc0dc-c85b-4af7-b872-f96322ef0128">
