### ISSUE TITLE
question: Have APITable think about Bazel?

### ISSUE THREAD

**Issue by zacker330** [apitable/apitable#1235]
## Any questions?
APITable's main codebase is a monorepo, which is using Make to build all different kind of language, setup local development environment, or other build stuff. 

I noticed that the build-test in CI pipeline cost in range of 14 to 24 minutes, whatever the change is on the codebase.

My question is have you think about using Bazel or other build tools suitable monorepo better? 

BTW, in my opinions, a build tool for monorepo must have these features:
1. multi-language friendly
2. build cache
3. increcement build
4. distribute build

ref: [When to use Bazel?](https://earthly.dev/blog/bazel-build/)

**Comment by cymqqqq** [comment]
AFAIK, bazel is used for building Rust && C++ projects now, but there is no code about Rust or C++ in the Apitable. And it's a little bit complex to set up the bazel build flow.

**Comment by pengjin123** [comment]
Thank you for your feedback ,we have assigned relevant colleagues to follow up this issue
@networkhermit @paylm Could you please help me take a look? Thank you

**Comment by networkhermit** [comment]
Sorry. Currently we don't have any plan to change the build tool, Bazel and the alternatives are impressive but indeed they are too complex to maintain correctly. Thanks for the suggestion.
