### ISSUE TITLE
feat: add formula support

### ISSUE THREAD

**Issue by devwlw** [apitable/apitable#1236]
I have an idea for this project.

## Why?
Inconvenient when statistics or calculations，no `sum`,`avg` and other functions provided

## What?
we can add formula entrance and provide some common functions like `sum`,`avg`,`count`, just like **microsoft office** did

## How?

base on cell type and position,it's easy to implement by **AST**

**Comment by pengjin123** [comment]
@devwlw Currently, formula support is available. You can create a formula field column and input the desired formula in the formula field column to perform calculations or statistics.
![image](https://github.com/apitable/apitable/assets/108248808/f16e4edf-56c2-4b88-bae9-fbf2bc6721a9)
![image](https://github.com/apitable/apitable/assets/108248808/e0499cce-364c-4ac7-ba53-6580d2a05c70)

**Comment by D1reW0lf** [comment]
Hi. 

As far as I can tell, “sum” (among others) only works with lines, not columns, so the initial request / idea is, in my opinion, still valid.
