### ISSUE TITLE
fix: open sorry,something went wrong and the page crashed. We will fix it soon.

### ISSUE THREAD

**Issue by forxiucn** [apitable/apitable#1245]
**描述Bug**
退出登录后，再进入到首页跳转到登录页面无法打开

**重现步骤**
重现行为的步骤：
1. 前往“登录页面”
2. 点击“Sign in”
3. 看到错误

**期望行为**
可正常登录使用

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/11312508/39fedca8-82ac-4ff3-9b88-68a601d754e8)
![image](https://github.com/apitable/apitable/assets/11312508/a8828dee-f746-44c4-a9e2-85a1adb40237)

**电脑版（请填写以下信息）：**
 - 版本号：docker all in one
 - 操作系统：Win10
 - 浏览器：Chrome

**Comment by pengjin123** [comment]
Thank you for your feedback ,we have assigned relevant colleagues to follow up this issue
@wangkailang Could you please help me take a look? Thank you

**Comment by forxiucn** [comment]
> Thank you for your feedback ,we have assigned relevant colleagues to follow up this issue @wangkailang Could you please help me take a look? Thank you

看来你这位同事有点忙哦。又有人提出了这个同样的bug[1411](https://github.com/apitable/apitable/issues/1411)

**Comment by forxiucn** [comment]
附控制台报错截图：
![image](https://github.com/apitable/apitable/assets/11312508/c853c3f6-704a-4d73-b05f-e6ea7dee8075)
![image](https://github.com/apitable/apitable/assets/11312508/34a36c44-8337-4cd1-8ad5-5444108fdd32)
![image](https://github.com/apitable/apitable/assets/11312508/0f32d2c6-cf36-440a-839b-3b7198e59a69)
![image](https://github.com/apitable/apitable/assets/11312508/695ab51d-d49d-40c4-9338-fd39057cb99d)
![image](https://github.com/apitable/apitable/assets/11312508/ef30b8a9-a65e-433e-8d1d-184ce3b5f47e)
![image](https://github.com/apitable/apitable/assets/11312508/6356dbd9-9de5-4241-af5a-21e9fb18d5a3)
