### ISSUE TITLE
fix: 无限重复“当前文件内容已更新，请刷新查看(3005)” Infinite repeat "The current file content has been updated, please refresh to view (3005)"

### ISSUE THREAD

**Issue by Green1ee** [apitable/apitable#1247]
**描述Bug**
如题。
rt.

**重现步骤**
重现行为的步骤：
1. 同一浏览器，在两个或以上标签页中打开同一个维格表
    Open the same vika table in two or more tabs in the same browser
2. 刷新任一维格表
    Refresh any vika table
3. 看到错误
    See the error
**期望行为**
No error

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/9738666/aff03f78-5c28-47f0-a1ee-8dd3028f882b)

**电脑版（请填写以下信息）：**
 - 版本号：v0.99.0-beta
 - 操作系统：Windows 11
 - 浏览器：Chrome

**其他上下文**
无其他上下文。

**Comment by pengjin123** [comment]
@Green1ee Please update to the latest code. This issue has been resolved in the latest version. Thank you.

**Comment by Green1ee** [comment]
Thank you so much! @pengjin123
