### ISSUE TITLE
issues about compelled to exit

### ISSUE THREAD

**Issue by XHYhappy** [apitable/apitable#1251]
The prolonged deployment time of the web-based platform for accessing Jupyter Notebook can lead to situations where users are compelled to exit. This can create a preference among users to utilize a local Integrated Development Environment (IDE). Would you have the plan to improve the performance of the online coding experience? Thanks.

**Comment by pengjin123** [comment]
@networkhermit @paylm Could you please help me take a look? Thank you

**Comment by networkhermit** [comment]
Hello, you can try to use [gitpod](https://gitpod.io/#https://github.com/apitable/apitable) (perhaps a paid plan), by the way if you have enough cpu/memory resource, the devenv is not that hard to setup.
