### ISSUE TITLE
fix: 录入数据时，如果网络异常，这时关闭页面，会丢失数据

### ISSUE THREAD

**Issue by baiy513** [apitable/apitable#1257]
**描述Bug**
fix: 录入数据时如果网络异常，这时关闭页面，会丢失数据，也没有提示
**重现步骤**
重现行为的步骤：
1. 新建一个表格
2. 录人数据
3. 断掉网络
4. 关闭表格

**期望行为**
希望下次打开页面时能提交未保存的数据，或者能给予提示。

**Comment by pengjin123** [comment]
@baiy513 When the network is abnormal, the network connection in the upper right corner should be displayed in red or yellow status
![image](https://github.com/apitable/apitable/assets/108248808/7c84946a-0519-4a55-bd33-b77847ac9063)

**Comment by baiy513** [comment]
PENGJIN123 你好，这个问题是这样的，提交数据需要一些时间，如果改的比较多，提交没有完成，这时关闭页面也会丢数据的

**Comment by ChambersChan** [comment]
技术手段上，未提交完成的数据，我们在浏览器会有缓存，下次进入表格会再次发送到服务端。
但这个也受到个人浏览器的策略或自定义设置影响，如用无痕模式打开或关闭页面退出自动清空缓存等等因素。

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
