### ISSUE TITLE
fix: 邮件robot发送失败页面没有报错(there is not any error msg in webpage while mail robot failed)

### ISSUE THREAD

**Issue by willcfyang** [apitable/apitable#1259]
**Describe the bug**
邮件robot发送失败页面没有报错(there is not any error msg in webpage while mail robot failed)

**To Reproduce**
1. go to gird view
2. create new email robot 
3. modify gird until reach the mail robot trigger condition
4. see log and web page changes

**Expected behavior**

**Screenshots**
![00ea29b3-3ed5-4ed5-a390-d3b8d40cc5bd](https://github.com/apitable/apitable/assets/117024441/02a2baeb-163d-46fa-a13e-79883c17d76b)

![73d0b21e-9451-476b-95eb-00ae16bab6a8](https://github.com/apitable/apitable/assets/117024441/c29bba5d-a3fb-446e-b402-7f5e0e48707b)

**Comment by ChambersChan** [comment]
Hello, you can first confirm whether the robot is enabled. Then you can enter the robot running history to view details.
<img width="354" alt="image" src="https://github.com/apitable/apitable/assets/32906036/ab937ddb-86a6-4767-ac26-fb13011dad95">

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
