### ISSUE TITLE
fix: row api update failed

### ISSUE THREAD

**Issue by oyb001** [apitable/apitable#1260]
**描述Bug**
清晰简洁地描述Bug是什么。
row api update failed
**重现步骤**
获取条目失败
```shell
MacBook-Pro-3:~ ouyangbin$ curl "http://localhost:3000/fusion/v1/datasheets/dstPX44fmTz6zzvoYa/records?viewId=viw9KK5do9DVc&fieldKey=id" \
>   -H "Authorization: Bearer uskhN73MPCbe0HUd0Zm0hmv"
Error occurred while trying to proxy: localhost:3000/fusion/v1/datasheets/dstPX44fmTz6zzvoYa/records?viewId=viw9KK5do9DVc&fieldKey=idMacBook-Pro-3:~ ouyangbin$ 
MacBook-Pro-3:~ ouyangbin$ 
```

**期望行为**
清晰简洁地描述您期望发生的情况。

**屏幕截图**
如果适用，添加屏幕截图以帮助说明您的问题。
errors.html#errors_common_system_errors)
[HPM] Error occurred while proxying request localhost:3000/fusion/v1/datasheets/dstPX44fmTz6zzvoYa/records?viewId=viw9KK5do9DVc&fieldKey=id to http://127.0.0.1/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)

**电脑版（请填写以下信息）：**
 - 版本号：[macOS Ventura 13.4]
 - 操作系统：[macOS]
 - 浏览器：[Chrome 116.0.5845.110（正式版本） (x86_64)]

**Comment by ChambersChan** [comment]
@oyb001 感谢你的反馈，该问题已在 develop 分支修复。非本地开发启动模式，将于下周v1.0.0版本的镜像中生效。
