### ISSUE TITLE
fix:中文目录下开发文档是英文

### ISSUE THREAD

**Issue by 1549742101** [apitable/apitable#1266]
**描述Bug**
清晰简洁地描述Bug是什么。

**重现步骤**
重现行为的步骤：
1. 前往“https://github.com/apitable/apitable/blob/develop/docs/readme/zh-CN/README.md”
2. 点击“...” 
![image](https://github.com/apitable/apitable/assets/49146003/e9791d40-88ce-472a-8b34-6fb4db44a2fe)

3. 滚动到“[...](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A)”
4. 看到错误
![image](https://github.com/apitable/apitable/assets/49146003/c0cbd2f2-89ef-4adc-94bf-650f462cb000)

**期望行为**
希望有中文的开发文档

**屏幕截图**
如果适用，添加屏幕截图以帮助说明您的问题。

**电脑版（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 操作系统：[例如 iOS]
 - 浏览器：[例如 Chrome，Safari]

**智能手机（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 设备：[例如 iPhone6]
 - 操作系统：[例如 iOS8.1]
 - 浏览器：[例如内置浏览器，Safari]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by pengjin123** [comment]
@1549742101 Currently, there are no Chinese development documents available
