### ISSUE TITLE
关于docker中apitable/all-in-one镜像的参数设置问题

### ISSUE THREAD

**Issue by Ternence-D** [apitable/apitable#1267]
在docker中部署apitable时，发现apitable/all-in-one镜像在运行时需要设置一些参数，跳过该参数的设置无法运行，没有找到相关的参数设置说明，版本号为：[v0.99.1-beta.1_1644](https://registry.hub.docker.com/layers/apitable/all-in-one/v0.99.1-beta.1_1644/images/sha256-ffac89a2234a16a4ecee7df074db6fde65cc7feae905fbb7b010d24df0f3707e?context=explore)，有谁知道在docker中部署时参数如何设置？
![bfc4892f25a0a2037edc26a90eb6aca](https://github.com/apitable/apitable/assets/57622183/89877f07-2684-4a41-8267-ea4f5bffdb94)
![a098be471e357948c74704eda657907](https://github.com/apitable/apitable/assets/57622183/663c62e2-2eba-4a10-88de-8f72d69ce4cb)

**Comment by pengjin123** [comment]
@networkhermit Could you please help me take a look? Thank you

**Comment by networkhermit** [comment]
看上去并不是docker的问题，是你使用的软件（或平台）并不允许设置空的环境变量，可以尝试删除这些变量看看
