### ISSUE TITLE
question: Is there any Databus documentation? 

### ISSUE THREAD

**Issue by cloud0072** [apitable/apitable#1271]
The make run command has 4) databus-server

When I start this service and open the swagger document, many interfaces cannot run successfully.

Is my usage wrong?

![apitable_issue2](https://github.com/apitable/apitable/assets/34976399/a51189fd-6d2f-497d-b019-22e2d60eaaeb)
![apitable_issue1](https://github.com/apitable/apitable/assets/34976399/a756c6f7-f45b-4b6d-8d18-9331800e79e4)

**Comment by ChambersChan** [comment]
At present, the service is still under development and not put into use, you can ignore it.

**Comment by cloud0072** [comment]
> At present, the service is still under development and not put into use, you can ignore it.

thanks
