### ISSUE TITLE
fix: package.json command `yarn sss` not exist

### ISSUE THREAD

**Issue by qiaoyupi** [apitable/apitable#128]
**Describe the bug**
运行 yarn sss
提示没有dev这个命令

因为 @apitable/components 这个项目的package.json 下，并没有注册这个命令

![D942D0DC-7569-4D41-BC8A-B7E15FB3F58D](https://user-images.githubusercontent.com/42425482/210323256-9f1d5c3a-5888-4801-b265-7a6380c588db.png)

![4378D7D9-609B-4A78-9F66-6A359C868E77](https://user-images.githubusercontent.com/42425482/210323335-f0a5973e-b0b5-4914-b5cf-80e679c3cb54.png)

**Comment by pengjin123** [comment]
@qiaoyupi Thank you! we will fix it ASAP
