### ISSUE TITLE
question: How do I incrementally update a dataset without using the API?

### ISSUE THREAD

**Issue by ethan-xiao** [apitable/apitable#1281]
How do I quickly update an imported csv dataset?
btw, where is the SQL-like query(https://github.com/apitable/apitable/tree/develop#sql-like-query)?

**Comment by pengjin123** [comment]
Thank you for your feedback ,we have assigned relevant colleagues to follow up this issue.
@ChambersChan Could you please help me reply? Thank you

**Comment by ChambersChan** [comment]
The data in the table can only be accessed through client communication or API now.

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
