### ISSUE TITLE
question: 单个表格的行数上限是 50000 条,有没有办法去除限制？

### ISSUE THREAD

**Issue by jhk5263** [apitable/apitable#1294]
单个表格的行数上限是 50000 条,有没有办法去除限制？

**Comment by cloud0072** [comment]
backend-server/application/src/main/resources/application.yml

limit:
  space-max-count: ${SPACE_MAX_COUNT:10}
  max-file-size: ${EXPORT_MAX_FILE_SIZE:20971520}
  max-column-count: ${MAX_COLUMN_COUNT:200}
  max-row-count: ${MAX_ROW_COUNT:50000}
  template-max-count: ${TEMPLATE_MAX_COUNT:20}
  dsb-widget-max-count: ${DSB_WIDGET_MAX_COUNT:30}
  dst-robot-max-count: ${DST_ROBOT_MAX_COUNT:10}

找配置文件，其实去掉性能也跟不上，没有分页。还是存在上限

**Comment by pengjin123** [comment]
@cloud0072 The current upper limit for the number of records in a single table is 50,000, and it cannot be changed. If you have a large amount of data, you can try creating multiple tables to address this.

**Comment by cloud0072** [comment]
@pengjin123 Thank you for your reply and wish apitable becomes better！
