### ISSUE TITLE
fix: The Trigger Configuration dropdown option cannot fully display the text.

### ISSUE THREAD

**Issue by Eished** [apitable/apitable#1297]
**Describe the bug**

The Trigger Configuration dropdown option cannot fully display the text.

**To Reproduce**
1. Select a robot
2. Click “Trigger”
3. Click "Trigger type" -> "Record matches conditions"
4. Click “New match condition”

**Expected behavior**

Fully display the text content of the dropdown options, or show the full content on mouse hover.

**Screenshots**
![image-20230910161639844](https://github.com/apitable/apitable/assets/12061600/e7dbaf3e-fcaf-47d0-a97f-378e1c9ea2af)

**Desktop (please complete the following information):**
 - Ubuntu-20.04
 - OS: Windows10 + WSL2
 - Browser： Chrome

**Comment by pengjin123** [comment]
@Eished This is a truncation based on character length, and we will optimize it for the robot later. Please continue to stay tuned.
