### ISSUE TITLE
feat(auth): SSO with OIDC / Oauth for authentication and security purposes

### ISSUE THREAD

**Issue by pharindoko** [apitable/apitable#13]
Hey, seen your product and would be quite happy to use it but I`ve seen following section in your readme:

https://github.com/apitable/apitable/blob/294130aa16747060ab0bfb467a748b003ffee34f/README.md?plain=1#L282

Can I self-host this solution using SSO with OIDC / Oauth for authentication and security purposes ?

br,

pharindoko

**Comment by mr-kelly** [comment]
> Hey, seen your product and would be quite happy to use it but I`ve seen following section in your readme:
> 
> https://github.com/apitable/apitable/blob/294130aa16747060ab0bfb467a748b003ffee34f/README.md?plain=1#L282
> 
> Can I self-host this solution using SSO with OIDC / Oauth for authentication and security purposes ?
> 
> br,
> 
> pharindoko

Thanks for your interest.

These features will be included in our hosted and Enterprise versions.

The hosted version will be published **in February 2023**.

At that time, we will offer the enterprise version(self-hosted) with advanced features.


@pharindoko we will notify you when the features are ready.

**Comment by pharindoko** [comment]
Sorry I did not asked correctly for what I wanted to know: 

Do I need to pay if I self-host this solution and want to use it with SSO with OIDC / Oauth for authentication and security purposes ?

**Comment by mr-kelly** [comment]
> Sorry I did not asked correctly for what I wanted to know:
> 
> Do I need to pay if I self-host this solution and want to use it with SSO with OIDC / Oauth for authentication and security purposes ?

@pharindoko 

Not sure about the pricing model yet...
It may be free to login to Google, Github, and Facebook for personal use.
For teams or enterprises, LDAP or SAML SSO may be charged.

**Comment by pharindoko** [comment]
OK I`m working in an enterprise and need to know this before I will spent any effort.

From a security and organizational perspective we need to use OIDC / SAML authentication.
From a cost and effort perspective I don`t want to run into a paywall before I can use it productively and spread the word.

I know that other "products" have the same strategy -> opensource + paywall and this goes into a bad direction.
We already have a product in place that had the same strategy and what should I say - we would have tried to avoid that we need to implement this after we set it up for production.

If I pay in anyway why should I use especially your product ?
I have no argument when other business people come up with some stupid tool mentioned in this fancy gardner magic quadrant ...

br,

@pharindoko

**Comment by mr-kelly** [comment]
> OK I`m working in an enterprise and need to know this before I will spent any effort.
> 
> From a security and organizational perspective we need to use OIDC / SAML authentication. From a cost and effort perspective I don`t want to run into a paywall before I can use it productively and spread the word.
> 
> I know that other "products" have the same strategy -> opensource + paywall and this goes into a bad direction. We already have a product in place that had the same strategy and what should I say - we would have tried to avoid that we need to implement this after we set it up for production.
> 
> If I pay in anyway why should I use especially your product ? I have no argument when other business people come up with some stupid tool mentioned in this fancy gardner magic quadrant ...
> 
> br,
> 
> @pharindoko

Thanks for your advice.
APITable was just open-sourced yesterday. 
In the next two months, we will be working hard on the hosted version. 
Could you possibly see some updated features in different "strategies" at that time?

**Comment by pharindoko** [comment]
I will wait for the hosted version and your pricing model. 
Thanks for the discussion.
