### ISSUE TITLE
question: Why Choose Rust for Refactoring

### ISSUE THREAD

**Issue by KKould** [apitable/apitable#1305]
## Any questions?
The project functions are already very complete or due to transformation？

Although Rust can bring many maintenance advantages, the process will consume a lot of manpower and reduce the need for business development. What kind of trade-offs led to this decision?

**Comment by pengjin123** [comment]
@Exclamation-mark @chalme Could you please help me answer this? Thank you.

**Comment by ziqiangai** [comment]
Rust is more convenient for front-end and back-end to share a set of data structures and the implementation of some functions. Some projects in the community do this, such as [Yjs](https://github.com/y-crdt/y-crdt).

While a refactoring project may be labor- and time-intensive, it may reduce the project's maintenance costs in the long run. Rust's strong type system and memory safety can help prevent many common bugs and vulnerabilities, reducing the need for future fixes and maintenance.
