### ISSUE TITLE
question: 行数据共享 ‘自增键’的数据

### ISSUE THREAD

**Issue by cloud0072** [apitable/apitable#1306]
apitable_datasheet_record 的 field_updated_info 中保存了和行相关的数据
其中 field_updated_info.fieldUpdatedMap 保存了每个字段的更新时间等信息和自增键的数值
例如
`
{
  "createdAt": 1678433107659,
  "createdBy": "aa8ad2e78a254eb5853a3a388a925faa",
  "fieldUpdatedMap": {
    "fld2GFXgPyCzp": {
      "at": 1678433107659,
      "autoNumber": 10,
      "by": "aa8ad2e78a254eb5853a3a388a925faa"
    },
  }
}
`

自增键变成了每个字段的属性，而不是该行数据的属性
建议改成
`
{
  "createdAt": 1678433107659,
  "createdBy": "aa8ad2e78a254eb5853a3a388a925faa",
  "autoNumber": 10,
  "fieldUpdatedMap": {
    "fld2GFXgPyCzp": {
      "at": 1678433107659,
      "by": "aa8ad2e78a254eb5853a3a388a925faa"
    },
  }
}
`
好处是可以
1 所有field公用同一个 autoNumber 更符合行本身的设计
2 在表比较大的时候可以清空 fieldUpdatedMap 以节省空间和减少加载时间

**Comment by pengjin123** [comment]
@cloud0072  Thank you for your feedback ,we have assigned relevant colleagues to follow up this issue
@ChambersChan Could you please help me answer this? Thank you.

**Comment by ChambersChan** [comment]
非常好的观点。
但实际上我们很难满足所有人的需要，一千个人眼里有一千个哈姆雷特。
也有人想要的效果是，创建自增字段（之前可能有人使用过）是重新开始排序，而不是从n 开始，我们最后选定的产品方案还是偏向于这个。

**Comment by cloud0072** [comment]
@ChambersChan 非常感谢
