### ISSUE TITLE
fix: make run 3 后报错

### ISSUE THREAD

**Issue by 851091009** [apitable/apitable#1308]
**描述Bug**
make run 3 后报错

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/8460036/c437f9f0-2c28-4efc-b5b8-31cbf3151bc1)

**电脑版（请填写以下信息）：**
 - 版本号：[v1.0]
 - 操作系统：[ubuntu22.04 wsl2 ]
 - 浏览器：[Chrome]

**Comment by ziqiangai** [comment]
run `make install` before `make run`

**Comment by 851091009** [comment]
> 运行之前`make install``make run`

是的，运行过了，报的这个错误

**Comment by 851091009** [comment]
访问 http://localhost:3000 就会退出
![image](https://github.com/apitable/apitable/assets/8460036/b1d6263a-28a9-49dc-863a-0e73392850ba)
