### ISSUE TITLE
question: 一直无法运行起来，请问大家都用的什么开发环境？

### ISSUE THREAD

**Issue by 851091009** [apitable/apitable#1309]
我用的 win10 系统，在 wsl2 中装的 ubuntu 22.04， 然后按照手册进行安装，尝试多次一直无法正常运行，最新错误提示是：
![image](https://github.com/apitable/apitable/assets/8460036/9716c2c7-bba6-40cd-b65c-5379b5b286e6)

**Comment by pengjin123** [comment]
Thank you for your feedback ,we have assigned relevant colleagues to follow up this issue
@networkhermit Could you please help me check? Thank you

**Comment by 851091009** [comment]
好的，谢谢

**Comment by networkhermit** [comment]
@851091009 看不出错误，麻烦检查下退出前后系统资源（cpu/内存）占用情况，一般需要16G或以上内存

**Comment by 851091009** [comment]
> @851091009 看不出错误，麻烦检查下退出前后系统资源（cpu/内存）占用情况，一般需要16G或以上内存

感谢回复，我刚才试了一下，还是出现同样的问题。下面是我的电脑配置信息和安装流程。

使用方式是：在win10 的 wsl2 安装了 ubuntu 22.04 ，在 ubuntu 安装 docker , yarn, node ,java 等手册上要求的软件运行环境。

1. 电脑信息


![微信截图_20230915104624](https://github.com/apitable/apitable/assets/8460036/9e670cf7-68bd-4f52-9413-408c8bf0ef9e)

![10](https://github.com/apitable/apitable/assets/8460036/6f3fd175-2d9a-46c0-a070-b4fb9dc58f72)


2. 软件运行环境

![1](https://github.com/apitable/apitable/assets/8460036/d19fadfd-cd17-4739-92e8-263e683773e7)

![2](https://github.com/apitable/apitable/assets/8460036/fb14526a-11b6-4734-bfe8-191d32c76f1e)

![3](https://github.com/apitable/apitable/assets/8460036/502f8e89-ccc5-4ecd-af39-fe15a837962c)

3. 安装过程

![4](https://github.com/apitable/apitable/assets/8460036/cde17d8a-85ca-4c16-91f0-94e2f4786c71)

![5](https://github.com/apitable/apitable/assets/8460036/65d30ce3-020a-4f11-a60e-9a9fd2d1279d)

![6](https://github.com/apitable/apitable/assets/8460036/ca1e4520-9561-42fc-b122-47d911cea940)

4. 运行

**4.1 make run 1**

![7](https://github.com/apitable/apitable/assets/8460036/ed7a37c2-137d-4d2e-abb4-7374d1e5b758)

**4.2 make run 2**

![8](https://github.com/apitable/apitable/assets/8460036/327e7165-eb0f-44c6-a3dc-1140a7c4120b)

**4.3 make run 3**
![9](https://github.com/apitable/apitable/assets/8460036/82ddac62-7b71-4513-87d0-1082eb83b3cc)



5. 打开 http://localhost:3000 报下面错误

![11](https://github.com/apitable/apitable/assets/8460036/2f9e3172-d34e-43a4-b496-8e40e524d427)

**Comment by networkhermit** [comment]
安装流程是正确的，WSL里执行`free -h`有多少内存呢，WSL类似虚拟机，默认似乎不能利用所有系统内存。可以搜一下.wslconfig里的内存参数重启wsl试试看，可能是这个问题。

**Comment by 851091009** [comment]
> 安装流程是正确的，WSL里执行`free -h`有多少内存呢，WSL类似虚拟机，默认似乎不能利用所有系统内存。可以搜一下.wslconfig里的内存参数重启wsl试试看，可能是这个问题。

非常感谢，确实是内存不够的问题，我分配到 20G 才能运行起来。
