### ISSUE TITLE
question: databus-server does not have a corresponding dockerfile. How to package the image locally?

### ISSUE THREAD

**Issue by ClearloveTwo** [apitable/apitable#1311]
## databus-server没有相应的dockerfile吗，本地该如何打包镜像呢

**Comment by nagisakon** [comment]
Thanks for your feedback.
@shawndenggh  @ChambersChan  Please help answer this question

**Comment by ChambersChan** [comment]
There is currently no open source plan for this project.
The open source version currently only provides a mirror version.

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
