### ISSUE TITLE
fix: docker all-in-one 版本 automation 页面无法创建新 automation 

### ISSUE THREAD

**Issue by suequn0702** [apitable/apitable#1312]
**描述Bug**
在 Automation 页面点击 『New Automation』，显示一片空白，无法创建任何新的 Automation

**重现步骤**
重现行为的步骤：
重现行为的步骤：

点击『Automation』
点击『New Automation』
空白页面，无法进行下一步。

**期望行为**
可以正常创建 Automation

**屏幕截图**
如果适用，添加屏幕截图以帮助说明您的问题。
![image](https://github.com/apitable/apitable/assets/116086920/ebc43a0b-e357-403e-ba11-a700547108e8)

**电脑版（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 操作系统：[例如 iOS]
 - 浏览器：[例如 Chrome，Safari]

**智能手机（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 设备：[例如 iPhone6]
 - 操作系统：[例如 iOS8.1]
 - 浏览器：[例如内置浏览器，Safari]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by dontriskit** [comment]
This bug is also present in install.sh / docker compose version

**Comment by nagisakon** [comment]
Please open the console to see if there is an error message.

**Comment by dontriskit** [comment]
![image](https://github.com/apitable/apitable/assets/34084110/c5aa2e0a-7061-43af-8de6-1d0e64587cc5)
after click 'new automation' there are no console logs.

**Comment by nagisakon** [comment]
> ![image](https://user-images.githubusercontent.com/34084110/268250690-c5aa2e0a-7061-43af-8de6-1d0e64587cc5.png) after click 'new automation' there are no console logs.

I see, our technicians will fix it ASAP.

**Comment by networkhermit** [comment]
I think this issue is resolved in newer version, I tried the following all-in-one version and the automation works:

```bash
sudo docker run -d -v ${PWD}/.data:/apitable -p 80:80 --name apitable apitable/all-in-one:v1.1.0-beta_1676
```
