### ISSUE TITLE
fix: make install failed

### ISSUE THREAD

**Issue by shke308** [apitable/apitable#1314]
**描述Bug**
执行make install是报错 Cannot find module  ‘worker_threads’

**重现步骤**
重现行为的步骤：
按着开发文档执行，执行到make install步骤

**期望行为**
make install success

**屏幕截图**
![301694745576_ pic](https://github.com/apitable/apitable/assets/89243625/04d3e9a8-3bed-4fb6-89ab-ec0be7296f34)

**电脑版（请填写以下信息）：**
 - 版本号：v1.0.0
 - 操作系统：ubuntu 20.04.6 LTS   + wsl2
 - 浏览器：Chrome

**Comment by nagisakon** [comment]
Thanks for your feedback.
@shawndenggh @ChambersChan Please help answer this question

**Comment by shke308** [comment]
补充几个组件版本
nodejs版本：
![321694765733_ pic](https://github.com/apitable/apitable/assets/89243625/56d5410f-aac5-4e4a-87fa-1e6430dc0453)

npm版本：
![341694765781_ pic](https://github.com/apitable/apitable/assets/89243625/16eb2630-6252-4657-9917-03cf33a80368)

yarn版本：
在项目目录内是3.4.1
![331694765759_ pic](https://github.com/apitable/apitable/assets/89243625/1507b776-4a03-4e1b-828c-d132a4b368b0)
项目目录外是1.22.19
![371694766945_ pic](https://github.com/apitable/apitable/assets/89243625/22228ec5-566d-4add-a059-f26fe020bd73)

Docker版本：
![351694765805_ pic](https://github.com/apitable/apitable/assets/89243625/8e284f74-dd28-4824-b6f7-4f98e9d440c1)

docker compose版本：
![361694766869_ pic](https://github.com/apitable/apitable/assets/89243625/7d15fe39-2ace-4968-b12c-3dfdf647691e)

**Comment by shke308** [comment]
问题已经解决了，是因为本地有两个nodejs，在执行yarn install命令时，nvm版本管理不生效导致的，nvm安装的nodejs的可执行文件没安装在/usr/bin目录下，在这个目录的是一个低版本的nodejs，然后nvm管理对xshell是生效的， 所以在本地执行node --version时，查看到的版本是16.15.0，但是yarn install 时，实际使用的nodejs是安装在/usr/bin目录下面的低版本的nodejs，所以运行的时候会报这个错。
解决方案：/usr/bin目录下的node执行文件，替换成nvm安装的nodejs的执行文件就可以了
