### ISSUE TITLE
question: Steps to configure the development environment on my m1 MacBook

### ISSUE THREAD

**Issue by JevonYu** [apitable/apitable#1317]
I followed the configuration instructions at https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A on my m1 MacBook and configured it. Despite the same procedure, I met some problems.

First of all, for some unknown reason I needed to install canvas and helmet manually: 
`npm install canvas`
`npm install helmet`

Then during the execution of `make install`, I met many `Object is of type 'unknown'` errors. 
To fix these problems, I made the following changes:

change `state` to `(state: any)`:
```
packages/widget-sdk/src/error_handler.tsx   line 28, 47, 60
packages/widget-sdk/src/hooks/private/use_views.ts   line 11
packages/widget-sdk/src/hooks/use_active_cell.ts   line 60
packages/widget-sdk/src/hooks/use_active_view_id.ts   line 45
packages/widget-sdk/src/hooks/use_cloud_storage.ts   line 62, 63
packages/widget-sdk/src/hooks/use_collaborators.ts   line 51
packages/widget-sdk/src/hooks/use_field.ts   line 82, 89
packages/widget-sdk/src/hooks/use_fields.ts   line 89, 90
packages/widget-sdk/src/hooks/use_meta.ts   line 57
packages/widget-sdk/src/hooks/use_primary_field.ts   line 59, 63, 67
packages/widget-sdk/src/hooks/use_record.ts   line 81
packages/widget-sdk/src/hooks/use_records.ts   line 97
packages/widget-sdk/src/hooks/use_records_all.ts   line 64
packages/widget-sdk/src/hooks/use_selection.ts   line 97
packages/widget-sdk/src/hooks/use_session.ts   line 55
packages/widget-sdk/src/ui/filter/filter.tsx   line 20
packages/widget-sdk/src/ui/filter/filter_base.tsx   line 120, 124
packages/widget-sdk/src/hooks/use_fields.ts   line 91
```

change `collaborator` to `(collaborator: any)`: 
```
packages/widget-sdk/src/hooks/use_collaborators.ts   line 55
```
This seems to be a problem with the type of some variables, but since I'm not familiar with TypeScript, I won't speculate too much here.

Finally, during `make dataenv`, the program seemed to configure a password for the redis docker image, which is not configured in the `springboot configuration`, and this would cause an error in the first option of `make run`. This issue is also mentioned in #982.

After the above configurations, the development environment did work normally, despite being weird, and I present issue here for other people to see, and hopefully the developers will be able to focus on these issues as well.

**Comment by pengjin123** [comment]
@networkhermit Help me check, thank you

**Comment by networkhermit** [comment]
As for mac m1, you can checkout https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A#h-macos.

> Then during the execution of make install, I met many Object is of type 'unknown' errors.

Generally you can ignore these typescript type errors/warnings.

> Finally, during make dataenv, the program seemed to configure a password for the redis docker image, which is not configured in the springboot configuration, and this would cause an error in the first option of make run. This issue is also mentioned in https://github.com/apitable/apitable/issues/982.

Can't be reproduced in a clean environment. Please see my comment in https://github.com/apitable/apitable/issues/982#issuecomment-1725231784.

**Comment by JevonYu** [comment]
> As for mac m1, you can checkout https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A#h-macos.
> 
> > Then during the execution of make install, I met many Object is of type 'unknown' errors.
> 
> Generally you can ignore these typescript type errors/warnings.
> 
> > Finally, during make dataenv, the program seemed to configure a password for the redis docker image, which is not configured in the springboot configuration, and this would cause an error in the first option of make run. This issue is also mentioned in #982.
> 
> Can't be reproduced in a clean environment. Please see my comment in [#982 (comment)](https://github.com/apitable/apitable/issues/982#issuecomment-1725231784).

You are right, this may have been related to the fact that I have multiple Redis instances in my local environment. 

Anyway, the problem has been solved, thanks for the answer, and good luck with everything you guys are doing.
