### ISSUE TITLE
为什么时区选择，这种选择框，总会弹出。

### ISSUE THREAD

**Issue by nevertoday** [apitable/apitable#1325]
能不能让我默认一个时区

**Comment by nagisakon** [comment]
请补充操作步骤和截图

**Comment by mr-kelly** [comment]
> 能不能让我默认一个时区

Would you please follow this format: https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&projects=&template=bug_report_cn.md&title=fix%3A+%E7%AE%80%E7%9F%AD%E7%9A%84BUG%E6%8F%8F%E8%BF%B0

Thanks

**Comment by nevertoday** [comment]
天天不同浏览器，更换不一样的时区

**Comment by nevertoday** [comment]
为什么就不能固定一个时区呢，让后2023-09-28 这种格式的日期， 并不会因为时区发生变化
