### ISSUE TITLE
fix: first trigger on the get-started button sends you to the bottom of page

### ISSUE THREAD

**Issue by YashasaveeKesarwani99** [apitable/apitable#133]
**Describe the bug**
When a user clicks on the `get started` button, they are sent to the bottom of the page, below the `get-saas-notice` id section. The purpose for sending user to subscribe section is lost. The screenshot attached below explains the issue better. Also this happens only on the initial trigger of the button

**To Reproduce**
1. Go to [homepage](https://apitable.com/)
2. Click on 'Get Started'

**Expected behavior**
Should land user at saas notice segment

**Screenshots**
User lands here.
![Screenshot from 2023-01-04 00-34-27](https://user-images.githubusercontent.com/56859852/210424328-e20d5d11-c8ef-481e-ae10-9380d98cfc80.png)

**Desktop :**
 - OS: Ubuntu 20.04 LTS
 - Browser: Chrome

**Comment by mr-kelly** [comment]
@YashasaveeKesarwani99 Thank you, we think it was a very unpleasant experience. We will optimize it.
