### ISSUE TITLE
question: 通过make install 构建环境时，运行 yarn build:pre 提示如下错误，请问怎么解决

### ISSUE THREAD

**Issue by wangcheng0825** [apitable/apitable#1334]
<img width="878" alt="image" src="https://github.com/apitable/apitable/assets/6059018/43f81f2f-faf0-4cbb-8242-6b882496b7a6">

**Comment by pengjin123** [comment]
thank you for your feedback ,we have assigned relevant colleagues to follow up this issue

**Comment by wangcheng0825** [comment]
这个问题已经解决，感谢项目组，分享一下过程。

今天更新代码后，运行 make install，明确提示需要node 16.15.0 和 pnpm 8以上版本，我之前是版本为node 20，pnpm 7.30，调整到对应版本后，一切安装顺利。完美解决
