### ISSUE TITLE
Problem when running make install

### ISSUE THREAD

**Issue by 15763336201** [apitable/apitable#1335]
<img width="828" alt="1695611238151" src="https://github.com/apitable/apitable/assets/145440992/8522f298-32c0-48f6-a232-27e29e32e770">
![image](https://github.com/apitable/apitable/assets/145440992/dc6f53c1-05c9-4025-b126-e3dc2fd3704f)

**Comment by 15763336201** [comment]
![1695612070704](https://github.com/apitable/apitable/assets/145440992/e0b8ed22-91a1-4886-b401-38e3ce298d6e)

**Comment by ChambersChan** [comment]
Hello. Please update the latest code and try again.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
