### ISSUE TITLE
fix: Click to create an automation and the page is blank

### ISSUE THREAD

**Issue by nagisakon** [apitable/apitable#1344]
**Describe the bug**

**To Reproduce**
1. Open the automation list, there is currently no automation in the list
2. Click to create an automation and the page is blank

**Expected behavior**

**Screenshots**
![企业微信截图_cbdd5c57-c2b7-4d90-b20c-ce1de1e0a7e7](https://github.com/apitable/apitable/assets/49678762/ec08f778-12d4-4031-a89e-9e6625f7413e)

**Desktop (please complete the following information):**
 - Version [e.g. v0.20] APItable CE v1.2.0-beta

**Smartphone (please complete the following information):**
 - Version [e.g. v0.20]

**Additional context**

**Comment by zoe-icu** [comment]
@nagisakon fix this already, please try again
