### ISSUE TITLE
SERVER_ERROR(4000)

### ISSUE THREAD

**Issue by WyInnovate** [apitable/apitable#1345]
**描述Bug**
在表格中进行任何操作，比如创建、删除、筛选均会报错提示SERVER_ERROR(4000)

**重现步骤**
重现行为的步骤：
1. cd /opt/apitable
2. sudo docker-compose up -d
3. 前往表格
4. 点击筛选
5. 点击增加筛选条件
6. 看到错误SERVER_ERROR(4000)

**期望行为**
希望能够尽快解决，目前任何操作都无法完成

**屏幕截图**
不方便提供截图

**电脑版（请填写以下信息）：**
 - 版本号：apitable最新版
 - 操作系统：centos7
 - 浏览器：edge

**其他上下文**
F12内容
```
Uncaught (in promise) Error: SERVER_ERROR
    at E.<anonymous> (_app-cc0e38bdb7a9ba1c.js:241:178943)
    at Generator.next (<anonymous>)
    at s (_app-cc0e38bdb7a9ba1c.js:241:168794)

Uncaught (in promise) Error: SERVER_ERROR
    at E.<anonymous> (_app-cc0e38bdb7a9ba1c.js:241:178943)
    at Generator.next (<anonymous>)
    at s (_app-cc0e38bdb7a9ba1c.js:241:168794)
```

**Comment by WyInnovate** [comment]
新增、删除等等操作均可以完成，但是每次操作完就是会弹窗提示，需要我提供什么信息？

**Comment by NN-Binary** [comment]
Same fatal bug, It works, but each time a field is edited, it shows a modal with SERVER_ERROR(4000) and force the reload, it however works and insert the data correctly. Since the last update, it does this for absolutely every data being edited.



```

_app-cc0e38bdb7a9ba1c.js:241 Uncaught (in promise) Error: SERVER_ERROR
    at E.<anonymous> (_app-cc0e38bdb7a9ba1c.js:241:178943)
    at Generator.next (<anonymous>)
    at s (_app-cc0e38bdb7a9ba1c.js:241:168794)
(anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
s @ _app-cc0e38bdb7a9ba1c.js:241
Promise.catch (async)
(anonymous) @ _app-cc0e38bdb7a9ba1c.js:243
(anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
(anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
o @ _app-cc0e38bdb7a9ba1c.js:241
(anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
Promise.catch (async)
E.sendUserChanges @ _app-cc0e38bdb7a9ba1c.js:241
(anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
g @ _app-cc0e38bdb7a9ba1c.js:52
_ @ _app-cc0e38bdb7a9ba1c.js:52
A @ _app-cc0e38bdb7a9ba1c.js:52
syncOperations @ _app-cc0e38bdb7a9ba1c.js:241
(anonymous) @ _app-cc0e38bdb7a9ba1c.js:243
operationExecuted @ _app-cc0e38bdb7a9ba1c.js:252
didExecutedHook @ _app-cc0e38bdb7a9ba1c.js:237
_executeActions @ _app-cc0e38bdb7a9ba1c.js:237
_execute @ _app-cc0e38bdb7a9ba1c.js:237
execute @ _app-cc0e38bdb7a9ba1c.js:237
(anonymous) @ _app-cc0e38bdb7a9ba1c.js:68
X @ _app-cc0e38bdb7a9ba1c.js:68
U @ _app-cc0e38bdb7a9ba1c.js:68
onEndEdit @ _app-cc0e38bdb7a9ba1c.js:68
(anonymous) @ _app-cc0e38bdb7a9ba1c.js:68
$ @ _app-cc0e38bdb7a9ba1c.js:68
onViewMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
onViewMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
(anonymous) @ _app-cc0e38bdb7a9ba1c.js:68
l @ _app-cc0e38bdb7a9ba1c.js:68
onMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
onMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
_fire @ _app-cc0e38bdb7a9ba1c.js:448
_pointerdown @ _app-cc0e38bdb7a9ba1c.js:448
content.addEventListener.passive @ _app-cc0e38bdb7a9ba1c.js:448
_app-cc0e38bdb7a9ba1c.js:241 Uncaught (in promise) Error: SERVER_ERROR
    at E.<anonymous> (_app-cc0e38bdb7a9ba1c.js:241:178943)
    at Generator.next (<anonymous>)
    at s (_app-cc0e38bdb7a9ba1c.js:241:168794)
```


With a temporary JS script injected with TamperMonkey:
```

   setInterval(function() {
        document.querySelectorAll(".ant-modal-root").forEach(el => el.remove());
    }, 1500);
```

It makes it usable again.

**Comment by WyInnovate** [comment]
> Same fatal bug, It works, but each time a field is edited, it shows a modal with SERVER_ERROR(4000) and force the reload, it however works and insert the data correctly. Since the last update, it does this for absolutely every data being edited.
> 
> ```
> 
> _app-cc0e38bdb7a9ba1c.js:241 Uncaught (in promise) Error: SERVER_ERROR
>     at E.<anonymous> (_app-cc0e38bdb7a9ba1c.js:241:178943)
>     at Generator.next (<anonymous>)
>     at s (_app-cc0e38bdb7a9ba1c.js:241:168794)
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
> s @ _app-cc0e38bdb7a9ba1c.js:241
> Promise.catch (async)
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:243
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
> o @ _app-cc0e38bdb7a9ba1c.js:241
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
> Promise.catch (async)
> E.sendUserChanges @ _app-cc0e38bdb7a9ba1c.js:241
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
> g @ _app-cc0e38bdb7a9ba1c.js:52
> _ @ _app-cc0e38bdb7a9ba1c.js:52
> A @ _app-cc0e38bdb7a9ba1c.js:52
> syncOperations @ _app-cc0e38bdb7a9ba1c.js:241
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:243
> operationExecuted @ _app-cc0e38bdb7a9ba1c.js:252
> didExecutedHook @ _app-cc0e38bdb7a9ba1c.js:237
> _executeActions @ _app-cc0e38bdb7a9ba1c.js:237
> _execute @ _app-cc0e38bdb7a9ba1c.js:237
> execute @ _app-cc0e38bdb7a9ba1c.js:237
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:68
> X @ _app-cc0e38bdb7a9ba1c.js:68
> U @ _app-cc0e38bdb7a9ba1c.js:68
> onEndEdit @ _app-cc0e38bdb7a9ba1c.js:68
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:68
> $ @ _app-cc0e38bdb7a9ba1c.js:68
> onViewMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
> onViewMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:68
> l @ _app-cc0e38bdb7a9ba1c.js:68
> onMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
> onMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
> _fire @ _app-cc0e38bdb7a9ba1c.js:448
> _pointerdown @ _app-cc0e38bdb7a9ba1c.js:448
> content.addEventListener.passive @ _app-cc0e38bdb7a9ba1c.js:448
> _app-cc0e38bdb7a9ba1c.js:241 Uncaught (in promise) Error: SERVER_ERROR
>     at E.<anonymous> (_app-cc0e38bdb7a9ba1c.js:241:178943)
>     at Generator.next (<anonymous>)
>     at s (_app-cc0e38bdb7a9ba1c.js:241:168794)
> ```
> 
> With a temporary JS script injected with TamperMonkey:
> 
> ```
> 
>    setInterval(function() {
>         document.querySelectorAll(".ant-modal-root").forEach(el => el.remove());
>     }, 1500);
> ```
> 
> It makes it usable again.

It's totally cool.

**Comment by WyInnovate** [comment]
> Same fatal bug, It works, but each time a field is edited, it shows a modal with SERVER_ERROR(4000) and force the reload, it however works and insert the data correctly. Since the last update, it does this for absolutely every data being edited.
> 
> ```
> 
> _app-cc0e38bdb7a9ba1c.js:241 Uncaught (in promise) Error: SERVER_ERROR
>     at E.<anonymous> (_app-cc0e38bdb7a9ba1c.js:241:178943)
>     at Generator.next (<anonymous>)
>     at s (_app-cc0e38bdb7a9ba1c.js:241:168794)
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
> s @ _app-cc0e38bdb7a9ba1c.js:241
> Promise.catch (async)
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:243
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
> o @ _app-cc0e38bdb7a9ba1c.js:241
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
> Promise.catch (async)
> E.sendUserChanges @ _app-cc0e38bdb7a9ba1c.js:241
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:241
> g @ _app-cc0e38bdb7a9ba1c.js:52
> _ @ _app-cc0e38bdb7a9ba1c.js:52
> A @ _app-cc0e38bdb7a9ba1c.js:52
> syncOperations @ _app-cc0e38bdb7a9ba1c.js:241
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:243
> operationExecuted @ _app-cc0e38bdb7a9ba1c.js:252
> didExecutedHook @ _app-cc0e38bdb7a9ba1c.js:237
> _executeActions @ _app-cc0e38bdb7a9ba1c.js:237
> _execute @ _app-cc0e38bdb7a9ba1c.js:237
> execute @ _app-cc0e38bdb7a9ba1c.js:237
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:68
> X @ _app-cc0e38bdb7a9ba1c.js:68
> U @ _app-cc0e38bdb7a9ba1c.js:68
> onEndEdit @ _app-cc0e38bdb7a9ba1c.js:68
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:68
> $ @ _app-cc0e38bdb7a9ba1c.js:68
> onViewMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
> onViewMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
> (anonymous) @ _app-cc0e38bdb7a9ba1c.js:68
> l @ _app-cc0e38bdb7a9ba1c.js:68
> onMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
> onMouseDown @ _app-cc0e38bdb7a9ba1c.js:68
> _fire @ _app-cc0e38bdb7a9ba1c.js:448
> _pointerdown @ _app-cc0e38bdb7a9ba1c.js:448
> content.addEventListener.passive @ _app-cc0e38bdb7a9ba1c.js:448
> _app-cc0e38bdb7a9ba1c.js:241 Uncaught (in promise) Error: SERVER_ERROR
>     at E.<anonymous> (_app-cc0e38bdb7a9ba1c.js:241:178943)
>     at Generator.next (<anonymous>)
>     at s (_app-cc0e38bdb7a9ba1c.js:241:168794)
> ```
> 
> With a temporary JS script injected with TamperMonkey:
> 
> ```
> 
>    setInterval(function() {
>         document.querySelectorAll(".ant-modal-root").forEach(el => el.remove());
>     }, 1500);
> ```
> 
> It makes it usable again.

I solved the problem after reloading, which is very annoying.
