### ISSUE TITLE
feat: Do you consider supporting offline applications, like PWA？

### ISSUE THREAD

**Issue by Highnesslin** [apitable/apitable#1351]
I have an idea for this project.

## Why? 
> Why we need this feature？
> What is the user story for this feature? 

Sometimes I may not have the internet on the plane and I want to continue working, but the webpage cannot be opened.

## What?
> Can you describe this feature in detail?
> Who can benefit from it? 

With the offline caching feature of PWA, some functions are still supported when there is no network. When I connect to the network, I will prompt the user to merge with the online content.
Some people who frequently travel by plane or have poor network signal may like this feature.

## How?

I am also new to this project and have not yet delved into many details.

But I have come up with a rough plan that may be feasible.

Technical selection: PWA

Step:

1. As long as the user has accessed it, some function will be cached and can still be accessed in offline scenarios, similar to Google Mail,

2. Provide basic table editing capabilities, and cache the edited content locally

3. When the user returns to a network environment, if no one has edited or modified the content during this period, let the user choose to keep those contents themselves (ideally, they can selectively merge)

**Comment by mr-kelly** [comment]
Thanks

> I have an idea for this project.
> 
> ## Why?
> > Why we need this feature？
> > What is the user story for this feature?
> 
> Sometimes I may not have the internet on the plane and I want to continue working, but the webpage cannot be opened.
> 
> ## What?
> > Can you describe this feature in detail?
> > Who can benefit from it?
> 
> With the offline caching feature of PWA, some functions are still supported when there is no network. When I connect to the network, I will prompt the user to merge with the online content. Some people who frequently travel by plane or have poor network signal may like this feature.
> 
> ## How?
> I am also new to this project and have not yet delved into many details.
> 
> But I have come up with a rough plan that may be feasible.
> 
> Technical selection: PWA
> 
> Step:
> 
> 1. As long as the user has accessed it, some function will be cached and can still be accessed in offline scenarios, similar to Google Mail,
> 2. Provide basic table editing capabilities, and cache the edited content locally
> 3. When the user returns to a network environment, if no one has edited or modified the content during this period, let the user choose to keep those contents themselves (ideally, they can selectively merge)



Thanks for sharing your idea! The functionality you're suggesting, offline caching for a Progressive Web Application (PWA), can indeed be a useful feature for users who frequently travel or have limited internet connectivity. Offline caching allows certain functions and content to be accessible even when there is no network connection, providing a seamless user experience.

However, it's important to note that the feasibility and implementation details of this feature will depend on the specific backend data engine and architecture of the project.  

Not only the frontend engineering technology choosing.

So the answer is: yes after we refactored the data engine. But not now.
