### ISSUE TITLE
docs: Supplementary make: *** [dataenv] Error documentation

### ISSUE THREAD

**Issue by czff** [apitable/apitable#1354]
## What documentation do you want?
make dataenv-up
mkdir -p $DATA_PATH/.data/mysql \
                $DATA_PATH/.data/minio/data \
                $DATA_PATH/.data/minio/config \
                $DATA_PATH/.data/redis \
                $DATA_PATH/.data/rabbitmq \

docker compose --env-file $ENV_FILE -p $DEVENV_PROJECT_NAME -f docker-compose.yaml -f docker-compose.dataenv.yaml up -d mysql minio redis rabbitmq init-db init-appdata
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
make[1]: *** [dataenv-up] Error 1
make: *** [dataenv] Error
执行make dataenv时docker未启动或安装和mysql未安装时会报上述的错误。可以补充一下这里的文档～

**Comment by networkhermit** [comment]
看上去是docker没有启动，请检查下docker服务或docker desktop
