### ISSUE TITLE
question: About `pnpm` usage

### ISSUE THREAD

**Issue by boxsnake** [apitable/apitable#1355]
In the dev guide, `pnpm` installation is stated after `nvm` and `sdkman` installation. However, the guide says we need a `yarn2`. I am wondering why we do not use `pnpm` as a uniform `node` dependency manager?

[dev-guide]: https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A

**Comment by mr-kelly** [comment]
> In the dev guide, `pnpm` installation is stated after `nvm` and `sdkman` installation. However, the guide says we need a `yarn2`. I am wondering why we do not use `pnpm` as a uniform `node` dependency manager?

Thanks for pointing out the confusion. You can indeed change to `pnpm` as a uniform node dependency manager. We apologize for the inconsistency in the guide. We will make the necessary corrections to reflect the option of using pnpm.
