### ISSUE TITLE
sentry auth token

### ISSUE THREAD

**Issue by mondaysunrise** [apitable/apitable#1357]
https://github.com/apitable/apitable/blob/feaf33f818ed3041c4dd81bdf99fa505922111b9/packages/datasheet/.env#L138C1-L138C1

should this auth token be accessible to the public?

If not, please remove, otherwise, please explicitly state this

related to: https://github.com/getsentry/sentry-react-native/issues/1096

**Comment by ChambersChan** [comment]
Thanks for your feedback, this default value is not real data, we will remove them in the next issue.
