### ISSUE TITLE
docs: How to run the development environment quickly on windows system

### ISSUE THREAD

**Issue by sword-zjp** [apitable/apitable#136]
How to run the development environment quickly on windows system？

**Comment by pengjin123** [comment]
@sword-zjp You can refer to the APITable quick start document for operation
https://github.com/apitable/apitable

**Comment by pengjin123** [comment]
@sword-zjp  You can refer to the APITable quick start document for operation
https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md

**Comment by pengjin123** [comment]
@sword-zjp You can refer to the Developer Guide document under APITable quick start
https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md
