### ISSUE TITLE
运行页面优化

### ISSUE THREAD

**Issue by ylqer** [apitable/apitable#1360]
script面板运行时有点太矮了，内容只能显示一点点，需要来回上下滑动
![optimize](https://github.com/apitable/apitable/assets/50039348/df2b2275-419a-44d3-8463-57a142c1b632)

**Comment by nagisakon** [comment]
![image](https://github.com/apitable/apitable/assets/49678762/01d223c3-d897-4a62-a422-291e3c38bcf6)
You can drag and drop the lower right corner to elongate the display panel.
