### ISSUE TITLE
fix: URL Change

### ISSUE THREAD

**Issue by vasnt** [apitable/apitable#1364]
URL changed to : https://aitable.ai/ from apitable? 

**Screenshots**
<img width="248" alt="image" src="https://github.com/apitable/apitable/assets/117589240/d618f341-6630-4265-a330-e1a3715432fd">

**Comment by pengjin123** [comment]
@vasnt Aitable.ai is an overseas saas version, while apitable is an open source version

**Comment by ovizii** [comment]
Interesting, I thought someone had pivoted their product :-)

**Comment by vasnt** [comment]
i guess, URL apitable.com doesnt exist as it routes to aitable.ai when clicked. @pengjin123, can someone rectify?

**Comment by ChambersChan** [comment]
Thanks for your feedback, the link has been updated.

**Comment by vasnt** [comment]
This image in readme needs to be updated? @ChambersChan 

<img width="684" alt="image" src="https://github.com/apitable/apitable/assets/117589240/0d02c22b-c5c7-4536-b201-7ecfb9585b62">

**Comment by ChambersChan** [comment]
@vasnt No. The open source project is not equal to the cloud version, it does not have AI attributes.
