### ISSUE TITLE
feat: Examples in development documents correspond to examples in the code library

### ISSUE THREAD

**Issue by qqqzhch** [apitable/apitable#1365]
I have an idea for this project.

## Why? 
Generally, open source components will have an example folder, which lists various modules that can be customized by users. Some examples explained in the document also come from this example folder, so that it will be smoother to learn software customization based on the document.

## What?
https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/quick-start-sOIbWQJR6s
Take automation documentation as an example. It is difficult to understand the documentation by comparing it with the developed modules of the code base. There is still a lack of use cases that fully explain the documentation.

## How?
Write some demos around documentation and use cases

**Comment by ChambersChan** [comment]
Sorry, as a complete project rather than a single component, we still have a long way to go in terms of code description.
