### ISSUE TITLE
web-server无法启动

### ISSUE THREAD

**Issue by rxy1212** [apitable/apitable#1375]
**描述Bug**
在本地启动开发环境时 web-server 报错，其余三个环境启动正常
```
error - ./pages/_app.tsx:73:0
Module not found: Can't resolve 'enterprise/style.less'
  71 | import 'react-grid-layout/css/styles.css';
  72 | import 'react-image-crop/dist/ReactCrop.css';
> 73 | import 'enterprise/style.less';
  74 | import 'pc/components/common/button_base/button.less';
  75 | import 'pc/components/common/button_plus/button_plus.less';
  76 | import 'pc/components/common/emoji/emoji.less';

https://nextjs.org/docs/messages/module-not-found
```

**重现步骤**
重现行为的步骤：
1. 前往“...”
2. 点击“...”
3. 滚动到“...”
4. 看到错误

**期望行为**
清晰简洁地描述您期望发生的情况。

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/14829556/e6b6cd87-985e-4e1f-b971-f34b8041efdf)

**电脑版（请填写以下信息）：**
 - 版本号：Ubuntu 22.04
 - 操作系统：Linux
 - 浏览器：[例如 Chrome，Safari]

**智能手机（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 设备：[例如 iPhone6]
 - 操作系统：[例如 iOS8.1]
 - 浏览器：[例如内置浏览器，Safari]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by nagisakon** [comment]
We have fixed the problem, please pull the latest code
I will close this issue and raise the issue again if there are more questions.
