### ISSUE TITLE
question: 按照安装说明启动服务后login页面出不来

### ISSUE THREAD

**Issue by flying-dolphin** [apitable/apitable#1376]
执行curl https://apitable.github.io/install.sh | bash
然后打开链接地址后一直卡在login页面

![截屏2023-10-10 下午3 41 48](https://github.com/apitable/apitable/assets/100764432/84b27652-7f2e-414d-937c-78c50a044b7e)

OS:Ubuntu Server 22.04 LTS 64bit
docker：Docker version 24.0.6, build ed223bc
docker compose: v2.21.0

**Comment by networkhermit** [comment]
hello, I tried `curl https://apitable.github.io/install.sh | bash` and it is working as expected.

**Comment by flying-dolphin** [comment]
How should I go about analyzing and troubleshooting this issue?

**Comment by networkhermit** [comment]
> How should I go about analyzing and troubleshooting this issue?

0. Try to use another browser, or using private mode/clear all the cache
1. If you use VPN or network proxy, try to disable them and access the site again
2. Enable DevTool in Chrome and check if there are error in the Network tab
3. Use mobile traffic or another network, could be firewall policies in you company
4. Try to use other computer/tablet/phone to access the service
5. Use ssh to port-forward your remote service to local port

BTW, I can access you public service using firefox/chrome from my computer.

**Comment by flying-dolphin** [comment]
> > How should I go about analyzing and troubleshooting this issue?
> 
> 0. Try to use another browser, or using private mode/clear all the cache
> 1. If you use VPN or network proxy, try to disable them and access the site again
> 2. Enable DevTool in Chrome and check if there are error in the Network tab
> 3. Use mobile traffic or another network, could be firewall policies in you company
> 4. Try to use other computer/tablet/phone to access the service
> 5. Use ssh to port-forward your remote service to local port
> 
> BTW, I can access you public service using firefox/chrome from my computer.

I've identified the issue, it was caused by my VPN. When I turned it off, everything worked fine. I'll implement service access restrictions. Thanks for the reminder
