### ISSUE TITLE
Question on windows WSL when build dev env on branch develop 

### ISSUE THREAD

**Issue by photosssa** [apitable/apitable#1377]
+ docker compose failed when trigger in target make
Makefile in root path, commands bellow
```
_DATAENV := docker compose --env-file $$ENV_FILE -p $$DEVENV_PROJECT_NAME -f docker-compose.yaml -f docker-compose.dataenv.yaml
_DEVENV := docker compose --env-file $$ENV_FILE -p $$DEVENV_PROJECT_NAME -f docker-compose.devenv.yaml
```
will got error like: 
```
unknown flag: --env-file
See 'docker --help'.
```
I think export env varibles may differs on WSL, but i've tried change varible to its value, but nothing changed.  But i copy command lines run in bash directly, it works.
I have no idea, may be tab or space encode differs on Makefile  in windows FS, similiar as CRLF got error in gradlew scripts

+ rabbitmq container not running
```
0.44.0> Application rabbitmq_prelaunch exited with reason: {{shutdown,{failed_to_start_child,prelaunch,{badmatch,{error,{{shutdown,{failed_to_start_child,auth,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_no_setcookie,0,[{file,"auth.erl"},{line,313}]},{auth,init,1,[{file,"auth.erl"},{line,165}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,851}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}},{child,undefined,net_sup_dynamic,{erl_distribution,start_link,[#{clean_halt => false,name => rabbit_prelaunch_21@localhost,name_domain => shortnames,net_tickintensity => 4,net_ticktime => 60,supervisor => net_sup_dynamic}]},permanent,false,1000,supervisor,[erl_distribution]}}}}}},{rabbit_prelaunch_app,start,[normal,[]]}}
```
rabbitmq container remains resmuming state, a crash log found in docker container, suggestion on google is 
[https://github.com/docker-library/rabbitmq/issues/171#issuecomment-316302131](url)
i change 
```
volumes:
      - ${DATA_PATH}/.data/rabbitmq:/var/lib/rabbitmq
```
to 
```
volumes:
      - ${DATA_PATH}/.data/rabbitmq:/var/lib/rabbitmq/mnesia
```
in docker-compose.yaml:198, and restart container, it works

**Comment by networkhermit** [comment]
> unknown flag: --env-file
> See 'docker --help'.

Please check your docker/docker compose version and update them accordingly.

> change ${DATA_PATH}/.data/rabbitmq:/var/lib/rabbitmq to ${DATA_PATH}/.data/rabbitmq:/var/lib/rabbitmq/mnesia works

I think it is an environment specific issue. We are using mac/linux/wsl-ubuntu setup and none of them have this problem. And the issue you mentioned https://github.com/docker-library/rabbitmq/issues/171#issuecomment-316302131 is not newly reported.

BTW, what linux distro are you using in your wsl? Do you use some CIFS/NFS or windows drive?

**Comment by photosssa** [comment]
```
tsukasa@DESKTOP-2J0TFE0:/mnt/c/WINDOWS/system32$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
tsukasa@DESKTOP-2J0TFE0:/mnt/c/WINDOWS/system32$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
Yes, i use windows filesystem in WSL, path like /mnt/f/apitable, some problems maybe brougt in for it. Docker compose version is OK, because i can run that command directly in bash command without env varialbes, but when triggered in makefile it failed.
