### ISSUE TITLE
bug: Running in docker-compose stops 48 hours later

### ISSUE THREAD

**Issue by galexbh** [apitable/apitable#1380]
**Describe the bug**

I create an instance of the following image:

But when just 48 hours have passed, the application stops working.

What I have done to make it work is change the name of the volume and it works again.

-----

I don't know if it is preferable to use minikube and execute it in a kubernetes.

In the end I just require that it stay local.

The strange thing is that I have the configuration that when something happens it restarts but the application is technically 'up' at all times and stops working.

**To Reproduce**
1. Go to 'https://gist.github.com/galexbh/baf349cb8b25eebefb5815b1192bf22f'
2. Run docker-compose up -d
3. After 48 hours it stops working

**Expected behavior**

**Screenshots**
Running the command:

```docker container logs``` 
![image](https://github.com/apitable/apitable/assets/37647434/eacf023d-06e1-4676-8c90-c3a1cc3d9ac8)

**Desktop:**
 - Version 6.5.6-arch2-1
 - OS: Arch Linux x86_64
 - Browser Brave

**Server:**
 - Version 5.15.0-86-generic
 - OS: Ubuntu 22.04.3 LTS

**Additional context**

**Comment by networkhermit** [comment]
> But when just 48 hours have passed, the application stops working.

What do you mean "the application stops working"? Can you curl the service on the server?

> Go to 'https://gist.github.com/galexbh/baf349cb8b25eebefb5815b1192bf22f'

Please note that it is not recommended to use all-in-one in docker compose:

> We also provide an all-in-one image based on [pm2](https://pm2.keymetrics.io/) for demo or testing purpose (not recommended for enterprise or production usage)

We recommend use the official docker-compose.yaml.

Edited:

Running all-in-one image alone for more than 2 days, it is still accessible.
