### ISSUE TITLE
feat: upgrade multi-language function and expand the Chinese market

### ISSUE THREAD

**Issue by tugers** [apitable/apitable#1382]
I have an idea for this project.

Currently, apitable does not support Chinese, even though discord supports Chinese.  I wonder if there are plans for multi-language support.  I hope apitable can provide product localization support and modifications for Chinese-speaking regions to expand the Chinese-speaking market, especially the mainland market!

**Comment by ChambersChan** [comment]
Hello, we now support l10n including Chinese.
This can be achieved by setting the DEFAULT_LOCALE=zh-CN parameter in the .env and restart server.
