### ISSUE TITLE
fix: all in one 无法访问，backend-server异常

### ISSUE THREAD

**Issue by polaurs** [apitable/apitable#1387]
我注意到fix:#520 issue，我遇到的错误与其表现相同。
运行于MacOs 14.0 m2 CPU。

**重现步骤**
1:sudo docker run -d -v ${PWD}/.data:/apitable -p 80:80 --name apitable apitable/all-in-one:latest;
2:pm2 restart backend-server && pm2 log backend-server;
此时print类似java编译启动的log，等待buile success & done;
3:访问http://localhost:80,查看docker log：
http://backend-server:8081/api/v1/client/info?spaceId=
该链接访问报错；
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect'

**Comment by polaurs** [comment]
查看env，MAIL_TYPE已为smtp

**Comment by networkhermit** [comment]
Quoted from README:

> Depending on your environment, you may need to wait several minutes for all the services to start. This image is amd64 (x86_64) only, you may encounter pretty bad performance on arm64 or apple silicon.

It seems the initialization is not finished yet. I deployed all-in-one using the following command and it works:

```bash
sudo docker image pull apitable/all-in-one:latest
sudo docker run -d -v ${PWD}/.data:/apitable -p 80:80 --name apitable apitable/all-in-one:latest
# wait several minutes for all the services to start
```
