### ISSUE TITLE
fix: Cannot receive the confirmation email after I signed up

### ISSUE THREAD

**Issue by yanrchen** [apitable/apitable#1394]
**Describe the bug**
I signed up successfully, but I couldn't receive the confirmation email. I didn't find it even if I resend it.

**To Reproduce**
1. Go to the signup page.
2. fill out the information and submit the form.
3. it shows "Please confirm your email", but I cannot find it from my email account.
4. Click the "Resend email" button, still cannot receive the email.

**Expected behavior**
I should receive the confirmation email after I signed up.

**Screenshots**
![cannot receive confirmation email](https://github.com/apitable/apitable/assets/59917908/60beef56-a0ce-42d9-a936-133ddea3a6d1)

**Additional context**
my email is 163 and a VPN in my computer is running.

**Comment by pengjin123** [comment]
@yanrchen  May I ask if you are using aitable.ai or apitalbe? Can you provide your access link address and email address

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue.
