### ISSUE TITLE
How to set up a domain for a server? Can you provide a detailed guide?

### ISSUE THREAD

**Issue by hardyleung** [apitable/apitable#1397]
I used a server deployed with a docker-compose.yaml file and .env file.

When I reverse proxy to the server's exposed port through Nginx, I can access the website normally. However, there is always a "Network Disconnected" message in the upper right corner. I tried setting "SERVER_DOMAIN=http://mydomain/" in the gateway section of the docker-compose.yaml file, but it didn't work.

Could you please provide a detailed guide on how to configure a domain for my server?

**Comment by networkhermit** [comment]
hello, "Network Disconnected" means websocket hasn't been properly proxied. You can add the following snippet in your nginx configuration:

```conf
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''  close;
}

server {
    charset utf-8;

    location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Nginx-Proxy true;
        proxy_set_header Host $http_host;
        proxy_set_header X-Original-URI $request_uri;
        proxy_http_version 1.1;
        proxy_pass  http://APITable_IP_ADDRESS:PORT;
    }
}
```

**Comment by mr-v-v-v** [comment]
Hi @networkhermit , is it possible to add nginx conf (with SSL) for everyone, so it's easy to setup domain for app?
I also have issues with domain settings.

**Comment by networkhermit** [comment]
> Hi @networkhermit , is it possible to add nginx conf (with SSL) for everyone, so it's easy to setup domain for app? I also have issues with domain settings.

Hello, while it is possible to add generic nginx ssl conf in the built-in nginx, it is still not easy to renew the certs, we recommend to use a seperate nginx/traefik so it is not intrusive. Anyway, thanks for the suggestion.

**Comment by Cazus777** [comment]
Same problem, I tried a lot of options, but I couldn't configure either Apache or Litespeed...(((

**Comment by itangqiao** [comment]
请问在Nginx Proxy Manager该怎么配置，我试过好几次都没弄成功~~

**Comment by networkhermit** [comment]
@itangqiao hello, we have not used Nginx Proxy Manager so we can't provide the specific detail.

**Comment by itangqiao** [comment]
有朋友可以帮帮忙吗？我的系统是群晖DSM7.2，使用的是Nginx Proxy Manager设置的反向代理让外网访问，但是这个实在不知道怎么设置。

**Comment by ningcol** [comment]
我也搞了半天，反代就代理了80端口，但是websocket一直不行，不知道是哪个端口

**Comment by itangqiao** [comment]
> 我也搞了半天，反代就代理了80端口，但是websocket一直不行，不知道是哪个端口

我的问题解决了，Nginx Proxy Manager 有个开关需要打开，如果你也用这个的话可以试试。
<img width="598" alt="image" src="https://github.com/apitable/apitable/assets/44393379/972a34a8-6c8b-4251-ab4d-855a93f4b23b">

**Comment by ningcol** [comment]
> > 我也搞了半天，反代就代理了80端口，但是websocket一直不行，不知道是哪个端口
> 
> 我的问题解决了，Nginx Proxy Manager 有个开关需要打开，如果你也用这个的话可以试试。 <img alt="image" width="598" src="https://user-images.githubusercontent.com/44393379/280334426-972a34a8-6c8b-4251-ab4d-855a93f4b23b.png">

这个是在第三方的群晖套件中心下载的？

**Comment by itangqiao** [comment]
> > > 我也搞了半天，反代就代理了80端口，但是websocket一直不行，不知道是哪个端口
> > 
> > 
> > 我的问题解决了，Nginx Proxy Manager 有个开关需要打开，如果你也用这个的话可以试试。 <img alt="image" width="598" src="https://user-images.githubusercontent.com/44393379/280334426-972a34a8-6c8b-4251-ab4d-855a93f4b23b.png">
> 
> 这个是在第三方的群晖套件中心下载的？

是的，不过也可以自己用docker构建一个~

**Comment by networkhermit** [comment]
Document is updated in [APITable Cookbook - Troubleshooting], any contribution of document improvement is welcomed:

https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW#h-how-to-set-up-tls-support

https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW
