### ISSUE TITLE
fix: docker创建的服务显示自动化已达上限

### ISSUE THREAD

**Issue by shkero** [apitable/apitable#1398]
**描述Bug**
使用 v1.3.0-beta.1 部署的 docker-compose 服务，自动化显示“本表的自动化数量已达上限”。已经开启过自动化的显示也是空白。
`/api/v1/automation/robots` 响应的是“The field `props` in the JSON string is not defined in the `AutomationRobotIntroductionPO` properties”。

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/20251994/95af13cb-cc7c-4110-b987-a7c323250469)

**Comment by nagisakon** [comment]
Thanks for your feedback, we have fixed this problem in v1.3.0-beta.2. 
Please pull the latest code to verify the problem.
