### ISSUE TITLE
在 Linux 系统上本地部署 APITable 项目 ，room-server 不能正常启动?

### ISSUE THREAD

**Issue by xiaokangcoding** [apitable/apitable#1404]
## 在 Linux 系统上本地部署 APITable 项目 ，room-server 不能正常启动?

![image](https://github.com/apitable/apitable/assets/54012783/582ff010-7611-4c7b-a92b-24fed771e4f8)

报大量的如下错误，截图如下：

![image](https://github.com/apitable/apitable/assets/54012783/1bbeb843-b2a8-4e82-89f2-15d3483d3831)

 @apitable/core 库是安装的，截图如下：

![image](https://github.com/apitable/apitable/assets/54012783/29dde793-1385-43ef-8cc5-ce8695e6377f)

系统环境: 
Linux k8s-node2 5.15.0-87-generic #97~20.04.1-Ubuntu SMP Thu Oct 5 08:25:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

解决方法：

rm -rf node_modules
rm pnpm-lock.yaml 
make install
还是不行。

**Comment by ChambersChan** [comment]
执行`pnpm install && pnpm build:dst:pre`(make install 一部分)，试试是否发生中断错误。

**Comment by ChambersChan** [comment]
Hello. Please update the latest code and try again.
If you still have this problem, you can reopen this issue.
