### ISSUE TITLE
fix: 断网情况下无法登录

### ISSUE THREAD

**Issue by uusdnfdsfhnttyh** [apitable/apitable#1411]
**描述Bug**
清晰简洁地描述Bug是什么。

**重现步骤**
重现行为的步骤：
1. 断网情况下进登录页面登录

**期望行为**
登录成功

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/142380608/5037d7ce-7c72-4642-96a7-6b6ae86888f6)

**电脑版（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 操作系统：[例如 iOS]
 - 浏览器：[例如 Chrome，Safari]

**智能手机（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 设备：[例如 iPhone6]
 - 操作系统：[例如 iOS8.1]
 - 浏览器：[例如内置浏览器，Safari]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by z1592252807** [comment]
the same problem~
版本号：v1.3.0-beta.2
操作系统：windows10
浏览器：chrome, Edge

**Comment by forxiucn** [comment]
我之前也遇到了，我以为all in one才会出现这种情况，今天试了一下最新版本的all in one docker镜像也是这样的错误。唉，我之前提过这个bug[1245](https://github.com/apitable/apitable/issues/1245)，都已经一个多月了。

**Comment by gogogogoChen** [comment]
同样的问题，断网情况无法进入到登录界面，报错

**Comment by uusdnfdsfhnttyh** [comment]
等nocodb下版本更新就换了
