### ISSUE TITLE
dependency failed to start: container for service "mysql" is unhealthyfix: 简短的BUG描述

### ISSUE THREAD

**Issue by itangqiao** [apitable/apitable#1413]
<img width="1017" alt="image" src="https://github.com/apitable/apitable/assets/44393379/e176c8a7-ea7e-49b2-821d-6ddf9ce7c271">
试过很多次了，始终无法避免该错误。
系统：群晖7.2，docker-compose up -d 启动就会出现，初次部署。

**Comment by networkhermit** [comment]
mysql的错误日志是什么呢

如果是第一次部署可以重置重新启动试试：

```bash
docker-compose down -v
rm -fr .data
docker-compose up -d
```

**Comment by itangqiao** [comment]
反复重复了好几次，可以了❤
