### ISSUE TITLE
在本地部署后无法正常使用add automation

### ISSUE THREAD

**Issue by pengshy** [apitable/apitable#1417]
**描述Bug**
完成本地部署后，通过Chrome浏览器进入localhost:3000，完成注册，点击add automation，报错

**重现步骤**
重现行为的步骤：
1. 完成本地部署后，通过Chrome浏览器进入localhost:3000
2. 新注册账号或者使用已注册账号
3. 点击add automation
4. 看到错误

**期望行为**
能够进行下一步操作或有其他提示

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/25749889/becf6045-6138-4534-a822-f2e91ca08dc1)

**终端截图**
![image](https://github.com/apitable/apitable/assets/25749889/19aaa9c0-11a0-45dc-82ee-421508dca4a8)

**电脑版（请填写以下信息）：**
 - 版本号：1.2.0
 - 操作系统：Windows 11
 - 浏览器：Chrome，Edge

**Comment by nagisakon** [comment]
We have fixed this issue, please pull the latest version of the code
