### ISSUE TITLE
fix: 本地开发环境部署，web-server启动失败

### ISSUE THREAD

**Issue by FOR0x00** [apitable/apitable#1418]
**描述Bug**
本地开发环境部署，web-server启动失败

**重现步骤**
重现行为的步骤：
1. make run
2. 3

**期望行为**
能够启动web-server

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/74942131/996c78f0-7cff-4969-9d12-6f5de3941e9c)

![image](https://github.com/apitable/apitable/assets/74942131/ab02a44f-d322-432f-8930-616220c1605f)

![image](https://github.com/apitable/apitable/assets/74942131/3d0a245e-f3ff-4e50-84c3-3606871d7ce9)

**电脑版（请填写以下信息）：**
 - 版本号：最新develop分支
 - 操作系统：Ubuntu
 - 浏览器：Chrome

**Comment by pengjin123** [comment]
Thank you for your feedback ,we have assigned relevant colleagues to follow up this issue
@wangkailang Could you please help me take a look? Thank you

**Comment by wangkailang** [comment]
fixed
