### ISSUE TITLE
automation: 发送邮件的输入框没有对应的校验

### ISSUE THREAD

**Issue by jiangui001** [apitable/apitable#1420]
输入框没有做邮箱格式校验；
最后一个发送内容的输入框对敏感词没有对应的提示和处理；
<img width="1773" alt="2023-10-27 16 40 56" src="https://github.com/apitable/apitable/assets/146874653/a092c897-122a-4725-ad04-aca5828a9ae9">

**Comment by ChambersChan** [comment]
这里使用通用的JSONSchema UI，并无过多校验。
