### ISSUE TITLE
question: 生产环境中room-server参数设置多少比较合适

### ISSUE THREAD

**Issue by smartTeaCup** [apitable/apitable#1421]
## 关于room-server中INSTANCE_MAX_MEMORY和INSTANCE_COUNT参数设置的问题
我对nodejs了解的不是太深入，有几个关于参数设置方面的问题想请教下
1. 生产环境部署项目的话，单表数据如果达到3万，关联两个数量1万左右的表，单个room-server实例INSTANCE_MAX_MEMORY设置多少内存比较合适，设置的太小的话会出现什么问题吗？
2. 如果设置多个room-server实例，在更新数据的时候，它们之间的通信是异步的吗？对性能有没有损耗？
3. 项目部署到生产服务器上的话，room-server需要做其他编译或者说是打包之类的能提升性能的行为吗？

**Comment by ChambersChan** [comment]
1. INSTANCE_MAX_MEMORY 的设置取决于多个因素，如可用内存、预计的数据量和查询负载等。
建议开始适当增加 INSTANCE_MAX_MEMORY 的值（如2g、3g），以便为查询和数据操作提供足够的内存空间，
后续进行监测，观察内存使用情况。根据实际测试结果进行调整，以平衡内存消耗和性能需求。

如果将 INSTANCE_MAX_MEMORY 设置得过小，可能会导致内存不足的错误（如 JavaScript heap out of memory）。这可能会导致应用程序崩溃或执行缓慢，特别是在处理大量数据时。

2. 多个 room-server 实例时，在更新数据时它们之间的通信通常是异步的。每个实例独立处理自己的请求和更新操作。这可以提高并发性能和可扩展性。
异步通信可能会引入一些延迟和性能开销，但这通常可以通过水平扩展和负载均衡来解决。通过在多个实例之间分配负载，可以提高整体的处理能力和性能。

3. 不需要做其他步骤，通常也无法提升到性能方面。通常可以采取以下行动来提升性能：数据库优化、水平扩展实例数与对应负载均衡。

**Comment by smartTeaCup** [comment]
谢谢老师
