### ISSUE TITLE
fix: 当datasheet有链接到其他datasheet时，Chart Widget选择fields时会奔溃报错，selfhost和cloud版都有这个bug

### ISSUE THREAD

**Issue by michaellw** [apitable/apitable#1423]
**描述Bug**
当datasheet有链接到其他datasheet时，Chart Widget选择fields时会奔溃报错。

**重现步骤**
重现行为的步骤：
1. 新建chart widget，选择一个带有链接到其他datasheet的datasheet，单项或双向都可以
2. 前往widget设置
3. 点击“Select X axis”或者“Group by”，或者其他选择field的选项
4. 崩溃，报错：An unknown error has occurred, please refresh and retry
5. 具体请看下面视频

**期望行为**
正确显示field选项，没有奔溃，没有报错。

**屏幕截屏**
视频怎么也传不上，只能放几张截图了
![image](https://github.com/apitable/apitable/assets/276357/daa80650-2fa2-41ba-a715-a09be640eed8)

![image](https://github.com/apitable/apitable/assets/276357/cf2fa5d8-56ce-4565-bbe7-80d4b857c14c)

**电脑版（请填写以下信息）：**
 - 版本号：v1.3.0-beta.3，以及当前cloud版
 - 操作系统：win10 64位
 - 浏览器：Edge

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by ranglang** [comment]
thank you for contribution.

**Comment by nagisakon** [comment]
已修复该问题
