### ISSUE TITLE
export/import of spaces, folders and tables

### ISSUE THREAD

**Issue by dariusdarwish** [apitable/apitable#1424]
I think it's one of the most essential feature that a knowledge management system should have. thank you so much for making this brilliant product.

**Comment by nagisakon** [comment]
Please fill in the issue in the correct format to help us better understand your needs.
https://github.com/apitable/apitable/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=feat%3A+A+brief+description+of+your+requested+feature
