### ISSUE TITLE
使用外网访问时，显示网络异常，只能查看 无法编辑 

### ISSUE THREAD

**Issue by itangqiao** [apitable/apitable#1425]
<img width="982" alt="image" src="https://github.com/apitable/apitable/assets/44393379/1da98468-f04b-45b4-846c-a5f6fd57d63d">

**Comment by networkhermit** [comment]
Seems duplicate as https://github.com/apitable/apitable/issues/1397#issuecomment-1769825690

**Comment by itangqiao** [comment]
已解决。
如果有用 Nginx Proxy Manager 反向代理的同学，记得打开这个开关哦！
<img width="598" alt="image" src="https://github.com/apitable/apitable/assets/44393379/2171cc2d-4ab1-4499-bcd9-f1b2e7961234">
