### ISSUE TITLE
fix: 自动化的执行历史为空

### ISSUE THREAD

**Issue by fungxu** [apitable/apitable#1432]
**描述Bug**
自动化的执行历史为空， run-history的方法返回的 data字段是空数组

**重现步骤**
重现行为的步骤：
使用 1.4.0 和 1.3.0 都有这个问题。
1. 设置好机器人
2. 触发机器人，确认已经运行了一次
3. 点击查看机器人

**期望行为**
能查到对应的执行日志

目前使用的 databus-server是

![image](https://github.com/apitable/apitable/assets/4064396/30524845-43f6-4e09-a7cf-86f5da03c37e)

后台日志是: 

java.lang.IllegalArgumentException: The field `errorMessages` in the JSON string is not defined in the `AutomationRunHistoryPO` properties. JSON: {"taskId":"4909612358960864","robotId":"arbgECvApQtypSko4H","status":1,"createdAt":"2023-11-01T05:55:25","actionIds":"[\"aacYnhYbBwSUaRAxmW\", \"atrYCVWHXotnVjPSil\"]","actionTypeIds":"[\"aatSSHdFkR7B7197Is\", \"att3AB2qZ47Qldul5K\"]","errorMessages":null}
        at com.apitable.databusclient.model.AutomationRunHistoryPO.validateJsonElement(AutomationRunHistoryPO.java:336)
AutomationRunHistoryPO 只有 errorStacks 字段，没有 errorMessages 字段，是否 databus的docker 镜像不是最新版？

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/4064396/726987ec-ffa6-4738-a78c-11a9828be572)

**Comment by nagisakon** [comment]
Thanks for your feedback, we will fix it ASAP.

**Comment by nagisakon** [comment]
The issue has been fixed in the latest version
