### ISSUE TITLE
question: do we have any migration plan for main trend database except csv import ?

### ISSUE THREAD

**Issue by WARJY** [apitable/apitable#1433]
do we have any migration plan for main trend database except csv import ?

**Comment by ChambersChan** [comment]
There are currently no plans for this feature.
For more methods now, please refer to [this](https://github.com/apitable/apitable/issues/415#issuecomment-1436200679).

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue.
