### ISSUE TITLE
fix: 为什么我在macos跑make dataenv式 makefile中docker compose  --env-file报错

### ISSUE THREAD

**Issue by calvinxie668** [apitable/apitable#1435]
**描述Bug**
我在启动开发环境时 执行make dataenv 时会执行makefile中_DATAENV := docker-compose --env-file $$ENV_FILE -p $$DEVENV_PROJECT_NAME -f docker-compose.yaml -f docker-compose.dataenv.yaml 但报 **unknown flag --env-file**

**重现步骤**
重现行为的步骤：
1.配好环境后，初次直接执行make dataenv
**期望行为**
通过编译，而不是报错

**屏幕截图**
如果适用，添加屏幕截图以帮助说明您的问题。

**电脑版（请填写以下信息）：**
 - 版本号：[12.1]
 - 操作系统：[macOS Monterey]
 - 浏览器：Chrome
 - docker 24.0.6 
 - docker compose  v2.23.0
 

**其他上下文**
但是我将docker compose改为docker-compose貌似解决了
<img width="1437" alt="image" src="https://github.com/apitable/apitable/assets/17590085/cb6ac8dc-4fc6-4bcf-b6b6-137fdd1f24ff">

**Comment by networkhermit** [comment]
你好，docker compose无法使用说明没有成功安装docker compose v2，docker-compose只是淘汰的v1兼容模式，详情请参考官网 https://docs.docker.com/compose/ ， https://docs.docker.com/compose/migrate/ 。你本地可以换成docker-compose使用，但是不推荐。
