### ISSUE TITLE
make run 选择 1）backend-server 退出后重新执行，报端口被占用

### ISSUE THREAD

**Issue by mx777-swing** [apitable/apitable#1444]
**描述Bug**
make run 选择 1）backend-server 退出后重新执行，报端口被占用

**重现步骤**
重现行为的步骤：
1. make dataenv
2. make install
3. make run -> 1
4. 退出:ctrl+z
5. make run -> 1

**期望行为**
不应该发生上面问题

**屏幕截图**
![Screenshot 2023-11-08 091724](https://github.com/apitable/apitable/assets/64941456/e566b147-3be7-4a59-ac4f-d473420c7df8)

**电脑版（请填写以下信息）：**
 - 操作系统：[虚拟机 Ubuntu]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by nagisakon** [comment]
kill掉即可
