### ISSUE TITLE
apitable_backend-server errors

### ISSUE THREAD

**Issue by davidloman** [apitable/apitable#1447]
**Describe the bug**
keep on getting apitable_backend-server BusinessException error

**To Reproduce**
1. go to logs - docker compose logs -f
2. you will see the error

**Expected behavior**
no exception error

**Screenshots**
apitable_backend-server     | 2023-11-08 11:32:23.038 ERROR [service-api,31887f26903390ed682cc564206b754d,199a1a274c6233bc] 1 --- [nio-8081-exec-7] c.a.s.interceptor.ResourceInterceptor    : Request path [/datasheet/field/permission] is not exist
apitable_backend-server     | 2023-11-08 11:32:23.041 ERROR [service-api,31887f26903390ed682cc564206b754d,199a1a274c6233bc] 1 --- [nio-8081-exec-7] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/api/v1] threw exception [Request processing failed; nested exception is com.apitable.core.exception.BusinessException: resource does not exist] with root cause
apitable_backend-server     |
apitable_backend-server     | com.apitable.core.exception.BusinessException: resource does not exist
apitable_backend-server     | 	at com.apitable.shared.interceptor.ResourceInterceptor.preHandle(ResourceInterceptor.java:85)
apitable_backend-server     | 	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148)

**Desktop (please complete the following information):**
 - Version: 1.4 beta 2
 - OS: Linux
 - Browser: Chrome

**Comment by nagisakon** [comment]
Thanks for the feedback, this error will not affect normal use.

**Comment by ChambersChan** [comment]
The reason is because of [him](https://github.com/apitable/apitable/issues/1443), the community version should not trigger this API.
