### ISSUE TITLE
fix: 同步个chrome的更新，allow-insecure-localhost已经移除

### ISSUE THREAD

**Issue by Magi-Wang** [apitable/apitable#1449]
https://support.google.com/chrome/thread/241869686/allow-insecure-localhost-has-been-removed-as-of-chrome-119?hl=en

allow-insecure-localhost has been removed as of Chrome 119 

这个开关移除之后，会影响小组件的开发流程。

**Comment by xukecheng** [comment]
We have noticed the issue and there is an [updated technical document](https://developers.aitable.ai/widget/quick-start/#step-5-previewing-the-widget) available for your reference:

**Comment by magic-cd** [comment]
感谢~
