### ISSUE TITLE
Case-sensitive IDs vs. case-insensitive DB collation

### ISSUE THREAD

**Issue by allenhsu** [apitable/apitable#1450]
**Describe the bug**
It's not causing bug yet, but I noticed that case sensitivity of IDs is inconsistent. ID generator (`IdUtil`) is generating case sensitive IDs, while DB collation is set to `utf8mb4_unicode_ci` which is case insensitive. So technically, `dstabc` and `dstABC` are the same and cannot be inserted into the database, and using `dstabc` can find the `dstABC` record.

It's not causing any problems, but making including uppercase letters in the `IdUtil` a bit meaningless.

**To Reproduce**
[DB collation](https://github.com/apitable/apitable/blob/develop/init-db/src/main/resources/db/changelog/0.2/create_datasheet_table.xml#L30)
[Charset in IdUtil](https://github.com/apitable/apitable/blob/develop/backend-server/application/src/main/java/com/apitable/shared/util/RandomExtendUtil.java#L32)

**Expected behavior**
Either exclude uppercase letters in `IdUtil`, or change DB collation to a case-sensitive one.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Version [e.g. v0.20] develop branch
 - OS: [e.g. iOS] Irrelevant
 - Browser [e.g. chrome, safari] Irrelevant

**Smartphone (please complete the following information):**
 - Version [e.g. v0.20] Irrelevant
 - Device: [e.g. iPhone6] Irrelevant
 - OS: [e.g. iOS8.1] Irrelevant
 - Browser [e.g. stock browser, safari] Irrelevant

**Additional context**
N/A

**Comment by pengjin123** [comment]
Thank you for your feedback ,we have assigned relevant colleagues to follow up this issue

**Comment by ChambersChan** [comment]
Good idea. Feedback has been given to superiors.
