### ISSUE TITLE
feat: how about create a docker image for developing

### ISSUE THREAD

**Issue by neverlee** [apitable/apitable#1451]
May this idea have done? if not, it doesn't hurt to try.

## Why? 
> Even though every developer in China should be able to fininsh the development  environment through VPN, there are still a few hiccups.

## What?
> So how about create a docker image in dockerhub that contains all the necessary tools for new developer?

**Comment by networkhermit** [comment]
hello, currently we don't have any plan to support dev container, if you want to contribute, one example is https://github.com/apitable/apitable/tree/develop/packaging/all-in-one .
