### ISSUE TITLE
Installation issue for local development environment

### ISSUE THREAD

**Issue by wdywjm** [apitable/apitable#1465]
Because it is my first attempt to run the AITable development environment locally, and I have not used AITable before, the installation process went smoothly. However, I have already started a Redis Docker container on my local machine, which occupies port 6379. Therefore, when I run the "make" command, it will throw an error. The same issue may occur with other component containers. The solution is simple: I just need to temporarily stop the conflicting components that were previously started or edit the docker-compose file to resolve the port conflict issue. It would be helpful if this information could also be mentioned in the documentation.

**Comment by networkhermit** [comment]
hello, you can run `docker ps` to find the other redis container and `docker stop $container_name` to stop it.
