### ISSUE TITLE
Question: How does Apitable solve the problem of multiple people editing the same row of data?

### ISSUE THREAD

**Issue by theCodedMike** [apitable/apitable#1466]
## Any questions?
我们知道在数据库中，更新同一行记录，先来的那个线程是要获得排他锁的，然后再更新数据，其他线程只能读而不能写。
即使在Git中，我们知道如果2人编辑到同一份文件，会有很大的概率有冲突，然后需要一个人等另一个人更新后再解决冲突。
那么这个问题Apitable同样会面对，你们是如何解决的呢？

**Comment by mr-kelly** [comment]
Operational transformation
