### ISSUE TITLE
The installation script seems to have some optimizations that could be done

### ISSUE THREAD

**Issue by monettoCoffee** [apitable/apitable#1467]
## Any questions?
In fact, I executed the installation script twice.
curl https://apitable.github.io/install.sh
The first time an error occurred, but no clear error message was given to me, I checked the Terminal.
I thought about it, maybe there is a conflict between the Redis service port and my local machine.
So I killed the Redis process and the installation was successful.
Finally I checked the installation script and I found some areas that could be optimized.
For example, pre-installation inspections.
If Docker is not running, it can be frustrating to not be able to install it after downloading it.
Therefore, you can consider adding such a detection script.

```
if docker info >/dev/null 2>&1
then
     echo "Docker daemon is not running ... please check"
fi
```

Secondly, there doesn't seem to be a reasonable check for port conflicts, so adding a port check would seem to be better.

Some personal suggestions, I hope your products will get better and better  :)

**Comment by networkhermit** [comment]
Thanks for the suggestion. Do you have a redis instance listening on all the interfaces?

**Comment by monettoCoffee** [comment]
> Thanks for the suggestion. Do you have a redis instance listening on all the interfaces?

I has started a redis service in docker on my localhost, then i stop the redis service by brew, install script success(the docker redis instance started failed, and localhost:80 not can be access, i install success after stop my own redis docker instance)

**Comment by networkhermit** [comment]
I think we can add some port conflict tips in the installation script, reliably and compatibly checking conflict like *:6379 is not easy in shell.

**Comment by Green1ee** [comment]
以下是一个简单的Shell脚本，用于检查指定端口是否被占用：

```bash
#!/bin/bash

PORT=$1

# 检查端口是否被占用
netstat -tuln | grep $PORT > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo "端口 $PORT 已被占用"
else
    echo "端口 $PORT 未被占用"
fi
```
在脚本中，我们使用$1来接收命令行参数中的端口号。然后，我们使用netstat命令来获取当前系统中的端口列表，并通过grep命令过滤出与指定端口相关的行。如果grep命令返回成功（即退出状态码为0），则表示该端口已被占用；否则，表示该端口未被占用。最后，我们使用echo命令输出相应的结果信息。

**Comment by networkhermit** [comment]
@Green1ee 

Thanks. I understand the shell logic. But the snippet you provided has several flaws in it:

1. You are making the assumption that the correct version of `netstat` and `grep` are installed on the target machine (wsl, macos, linux).  AFAIC, `netstat` is not installed on all linux distros, for example, archlinux.
2. `grep $PORT` would give false conclusion if you have local process listening on `*:16379` or `*:33306`
3. Having local process listening on `127.0.0.1:6379` or `192.168.1.20:6379` won't cause port confict but the script can't detect the usecase.
