### ISSUE TITLE
fix: ineffective git hooks

### ISSUE THREAD

**Issue by micl2e2** [apitable/apitable#1493]
**Describe the bug**
Currently git hooks exist in source but not being used effectively, and addtionally, some of hook scripts are broken.

**To Reproduce**
1. Run `make install`

**Expected behavior**
No errors.  Git hooks are run effectively.

**Screenshots**
Outputs of `make install`:
```
#...
$ . postinstall$ cd .. && husky install apitable/.husky
│ fatal: not a git repository (or any of the parent directories): .git
│ husky - git command not found, skipping install
└─ Done in 65ms
# ...
```

**Desktop (please complete the following information):**
```
$ uname -a
Linux debian 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux

$ pnpm --version
8.11.0

$ node --version
v16.15.0

$ sdk current java
Using java version 8.0.362-amzn

```

**Smartphone (please complete the following information):**
 -

**Additional context**
-

**Comment by onlyone-hyphen** [comment]
Why was this closed as completed?

The issue still exists in the latest release and in develop
