### ISSUE TITLE
新建出现错误提示 file nums over limit

### ISSUE THREAD

**Issue by itangqiao** [apitable/apitable#1495]
<img width="543" alt="image" src="https://github.com/apitable/apitable/assets/44393379/0f46efc8-f288-424a-9f43-95e571e3996c">

文件数量超出限制？
可我也没也没几个表呀，一个文件夹不超过5个，总共才4个文件夹

**Comment by nagisakon** [comment]
开源版限制总文件数为5个，有更多用量需求可以使用cloud版本 https://aitable.ai/
