### ISSUE TITLE
有没有数据库迁移到阿里云RDS的方案

### ISSUE THREAD

**Issue by YTU94** [apitable/apitable#1510]
## mysql 迁移到阿里云的RDS
修改了env的配置信息，但是RDS没有root账号，所以在docker-compse.yaml中 吧 mysql的健康校验都去掉了，
但是最后打包结果发现 init-appdata的容器启动不了

重新构建了以下镜像：
room-server
backend-server
init-db

最后 docker-compose up -d 可以跑起来，可以登录，但是其他接口基本都报错

这是 backend-server 容器的logs 有报错信息：
```
 Caused by: java.sql.SQLSyntaxErrorException: Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'apitable.leaf.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```
room-server容器的logs 就是一直报错： undefined

期待回复！！！

**Comment by ChambersChan** [comment]
需要修改下数据库配置。
SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';
SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';

**Comment by YTU94** [comment]
> 需要修改下数据库配置。 SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION'; SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';

是需要修改 云数据库的配置是吗？还是修改apitable的配置信息

**Comment by YTU94** [comment]
@ChambersChan 
看了下我RDS的参数配置，已经添加了NO_ENGINE_SUBSTITUTION
<img width="1207" alt="image" src="https://github.com/apitable/apitable/assets/19224071/9ede20b3-f4ec-44d0-bbba-c24967e7f7d8">

**Comment by ChambersChan** [comment]
> @ChambersChan 看了下我RDS的参数配置，已经添加了NO_ENGINE_SUBSTITUTION <img alt="image" width="1207" src="https://private-user-images.githubusercontent.com/19224071/288756456-9ede20b3-f4ec-44d0-bbba-c24967e7f7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDIwODMsIm5iZiI6MTcwMjAwMTc4MywicGF0aCI6Ii8xOTIyNDA3MS8yODg3NTY0NTYtOWVkZTIwYjMtZjRlYy00NGQwLWJiYmEtYzI0OTY3ZTdmN2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3Zjc1ZDE3Zjg4NTg2ZDNlYWExYTdkZWQxMzM5ZDA5M2E2NzcxMGZjMGUyYTg4NThhMjU2ZDNhMjFkZDBkNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DiHUjIkFm-XoABsdZxa5GjN5voUmIHZWGkWsSk88vGI">

需要只保留NO_ENGINE_SUBSTITUTION

**Comment by YTU94** [comment]
> > @ChambersChan 看了下我RDS的参数配置，已经添加了NO_ENGINE_SUBSTITUTION <img alt="image" width="1207" src="https://private-user-images.githubusercontent.com/19224071/288756456-9ede20b3-f4ec-44d0-bbba-c24967e7f7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDIwODMsIm5iZiI6MTcwMjAwMTc4MywicGF0aCI6Ii8xOTIyNDA3MS8yODg3NTY0NTYtOWVkZTIwYjMtZjRlYy00NGQwLWJiYmEtYzI0OTY3ZTdmN2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3Zjc1ZDE3Zjg4NTg2ZDNlYWExYTdkZWQxMzM5ZDA5M2E2NzcxMGZjMGUyYTg4NThhMjU2ZDNhMjFkZDBkNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DiHUjIkFm-XoABsdZxa5GjN5voUmIHZWGkWsSk88vGI">
> 
> 需要只保留NO_ENGINE_SUBSTITUTION

好的 我试下

**Comment by YTU94** [comment]
> > @ChambersChan 看了下我RDS的参数配置，已经添加了NO_ENGINE_SUBSTITUTION <img alt="image" width="1207" src="https://private-user-images.githubusercontent.com/19224071/288756456-9ede20b3-f4ec-44d0-bbba-c24967e7f7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDIwODMsIm5iZiI6MTcwMjAwMTc4MywicGF0aCI6Ii8xOTIyNDA3MS8yODg3NTY0NTYtOWVkZTIwYjMtZjRlYy00NGQwLWJiYmEtYzI0OTY3ZTdmN2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3Zjc1ZDE3Zjg4NTg2ZDNlYWExYTdkZWQxMzM5ZDA5M2E2NzcxMGZjMGUyYTg4NThhMjU2ZDNhMjFkZDBkNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DiHUjIkFm-XoABsdZxa5GjN5voUmIHZWGkWsSk88vGI">
> 
> 需要只保留NO_ENGINE_SUBSTITUTION

解决了 非常感谢🙏
