### ISSUE TITLE
question: mino为外部地址时,gateway报错.

### ISSUE THREAD

**Issue by starmisszhang** [apitable/apitable#1514]
2023/12/07 08:55:28 [emerg] 1#1: host not found in upstream "minio:9000" in /etc/nginx/conf.d/upstream/ups-minio.conf:2
nginx: [emerg] host not found in upstream "minio:9000" in /etc/nginx/conf.d/upstream/ups-minio.conf:2

env里面已经把mino改为其它局域网IP,为什么这个服务还是访问minio:9000,不是设置的IP地址*.*.*.*:9000吗?导致整个服务不能启动

**Comment by networkhermit** [comment]
gateway 容器里的nginx配置也需要改，不支持环境变量

详情参考https://github.com/apitable/apitable/tree/develop/gateway/conf.d 和 https://github.com/apitable/apitable/blob/8db5b3c6ff4548776ed92a528ac49a8cad1cb176/packaging/Dockerfile.openresty#L6

**Comment by starmisszhang** [comment]
[gateway/conf.d/upstream/ups-minio.conf](https://github.com/apitable/apitable/blob/develop/gateway/conf.d/upstream/ups-minio.conf)
本来是
upstream minio {
   server minio:9000;
}

改成
upstream minio {
   server 192.168.1.2:9000;
}

这样修改之后gateway能启动了,也能正常查看之前传的图片,但是上传不了图片。
https://github.com/apitable/apitable/blob/develop/gateway/conf.d/server/minio.conf 
这个文件的proxy_pass   http://minio; 需要修改成proxy_pass   http://192.168.1.2; 这样吗
@networkhermit
