### ISSUE TITLE
question: How to ensure that the post-event will be triggered?

### ISSUE THREAD

**Issue by funny823** [apitable/apitable#1516]
比如新增一条数据，会触发自动化。假设在这两者之间，系统重启或者宕机，怎么能保证后置自动化一定会被触发

**Comment by ChambersChan** [comment]
For stand-alone service, this extreme situation cannot be guaranteed to be triggered;

Introduce other service measures, such as triggering calls to cloud functions and referencing MQ.

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue.
