### ISSUE TITLE
fix: doker all in one 版本无法启动

### ISSUE THREAD

**Issue by nagisakon** [apitable/apitable#1517]
doker all in one 版本无法启动
version:v1.6.0
<img width="579" alt="image" src="https://github.com/apitable/apitable/assets/49678762/e595ccc3-36e6-4c08-a565-8a2f0493c3eb">

**Comment by networkhermit** [comment]
可以使用 `apitable/all-in-one:v1.5.0-beta.2_1856` 或更早的版本，1.6 由于切换到 jdk 17，all-in-one还未完成java 组件适配

**Comment by networkhermit** [comment]
fixed in apitable/all-in-one:v1.6.0-beta.1_1886 and apitable/all-in-one:latest
