### ISSUE TITLE
通过 Installation 脚本一键安装 APITable，localhost:80 无法正常打开（三到五分钟后恢复正常）

### ISSUE THREAD

**Issue by amching** [apitable/apitable#1518]
## Env

- 操作系统：MacOS 14.1.1
- CPU：Intel Core i5
- Memory：8GB
- docker version：24.0.7
- docker compose：v2.23.3-desktop.2

## 问题描述

通过 READEME 文档 `curl https://apitable.github.io/install.sh | bash` 执行后，容器启动完成，但是 http://localhost:80 却无法立即打开，需要等待三到五分钟后方可打开

## Screenshot

![image](https://github.com/apitable/apitable/assets/103871930/2614479b-ef7a-4764-81c3-d12ba6201514)

**Comment by networkhermit** [comment]
猜测和内存资源紧张有关系

**Comment by tenclr** [comment]
我直接就是Unable to connect to the database无限崩溃
