### ISSUE TITLE
无法新增表格、表格数据，历史数据能修改。

### ISSUE THREAD

**Issue by lpqoang** [apitable/apitable#1525]
[apitable-backend-server-1] 容器报错如下：
ERROR 1 --- [nio-8081-exec-5] c.a.s.interceptor.ResourceInterceptor    : Request path [/datasheet/field/permission] is not exist

**Comment by pengjin123** [comment]
看这个报错信息是请求地址权限丢失
能麻烦把具体的报错信息截个图吗，方便进一步排查，谢谢

**Comment by lpqoang** [comment]
> 看这个报错信息是请求地址权限丢失 能麻烦把具体的报错信息截个图吗，方便进一步排查，谢谢

![image](https://github.com/apitable/apitable/assets/33981754/23ad4bf1-bc2d-4308-886b-09d52c93216c)
应该是我之前修改目录权限的时候没注意加了 -R，把apitable目录下的权限也改了。
