### ISSUE TITLE
fix:无法本地进行make bulid-docker

### ISSUE THREAD

**Issue by oneWujr** [apitable/apitable#1527]
**描述Bug**
make bulid 没有问题的，但make bulid-docker就报错了

**重现步骤**
重现行为的步骤：
1. 本地编译
2. 本地编译docker

**期望行为**
可以本地编译docker,允许离网运行

**屏幕截图**
编译成功
![MVIMG_20231218_095859](https://github.com/apitable/apitable/assets/136409375/db4e4c27-09d9-4511-8a44-e2d27146cb6f)

![wx_camera_1702737367307](https://github.com/apitable/apitable/assets/136409375/86416239-1fd4-4072-99a3-c20e33171b76)

**电脑版（请填写以下信息）：**
 - 版本号：ubuntu 桌面版 22.4
 - 操作系统：ubuntu
 - 浏览器:Chrome

**Comment by networkhermit** [comment]
Try the following buildx command to see if it works:

```bash
docker buildx bake --set '*.platform=linux/amd64' --load
docker buildx bake --set '*.platform=linux/amd64' backend-server --load
```

[docker buildx bake docs](https://docs.docker.com/build/bake/configuring-build/)
