### ISSUE TITLE
question: init db script missing

### ISSUE THREAD

**Issue by Jixiangup** [apitable/apitable#153]
**Describe the bug**
Hello APITable team, thank you for open-sourcing such a good product, I am very interested in this project, and I am going to study it. If possible, I hope to participate in open-source work with APITable, because I also love open-source, but now I'm having a problem with not being able to initialize the database, I looked at the current project version up to `0.17.0`, but I noticed that our init-db doesn't have a `db script` for `0.17.0`, is this a problem please? thank you for your reply!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shawndenggh** [comment]
@bnyte hello, 0.17.0 version does not necessarily have database changes, no script is normal

**Comment by Jixiangup** [comment]
> @bnyte hello, 0.17.0 version does not necessarily have database changes, no script is normal

@shawndenggh Thank you for your reply, but I think this design is unreasonable. My personal opinion is to add `init.sql script` to quickly build a database for first-time users

**Comment by mr-kelly** [comment]
> 

Hi, @bnyte 

In my opinion, our *init.sql script* is equivalent to the commands `make db-plan` and `make db-apply`.

You can have a try.

We use Liquibase to initialize our database schema. And we build it into a Docker image called `init-db`.
In fact, it is just a Liquibase Java project.
So you can check out more details in the  [Makefile](https://github.com/apitable/apitable/blob/develop/Makefile)

**Comment by Jixiangup** [comment]
> 



> > 
> 
> Hi, @bnyte
> 
> In my opinion, our _init.sql script_ is equivalent to the commands `make db-plan` and `make db-apply`.
> 
> You can have a try.
> 
> We use Liquibase to initialize our database schema. And we build it into a Docker image called `init-db`. In fact, it is just a Liquibase Java project. So you can check out more details in the [Makefile](https://github.com/apitable/apitable/blob/develop/Makefile)

okey! Thank you @mr-kelly  for your reply, In my previous experience, it is different from this way. I will read him after get off work. Thank you again for your answer. I will close this issue

I have another suggestion. Currently, `apitable` has no question issue template. If you expect to use discussions, please open it and start using it, because I know this is not a BUG, but I can't find a way to give feedback or ask a question~

**Comment by mr-kelly** [comment]
> > 
> 
> > > 
> > 
> > 
> > Hi, @bnyte
> > In my opinion, our _init.sql script_ is equivalent to the commands `make db-plan` and `make db-apply`.
> > You can have a try.
> > We use Liquibase to initialize our database schema. And we build it into a Docker image called `init-db`. In fact, it is just a Liquibase Java project. So you can check out more details in the [Makefile](https://github.com/apitable/apitable/blob/develop/Makefile)
> 
> okey! Thank you @mr-kelly for your reply, In my previous experience, it is different from this way. I will read him after get off work. Thank you again for your answer. I will close this issue
> 
> I have another suggestion. Currently, `apitable` has no question issue template. If you expect to use discussions, please open it and start using it, because I know this is not a BUG, but I can't find a way to give feedback or ask a question~

This is a good advice of creating a question issue. I will do it now!

If you don't like this way, tell us and we'll do our best to improve your experience.
