### ISSUE TITLE
自动化功能无法正常使用

### ISSUE THREAD

**Issue by hzk19951103** [apitable/apitable#1533]
**描述Bug**
清晰简洁地描述Bug是什么。
新建自动化无法进行编辑
**重现步骤**
重现行为的步骤：
1. 前往“自动化”
2. 点击“新建的自动化”
3、无任何反应
![微信图片_20231220112953](https://github.com/apitable/apitable/assets/88029119/e999bbd7-0b00-4f0f-a2a9-12d1680aca46)

**Comment by pengjin123** [comment]
麻烦打开下控制台看下日志信息，方便更快定位问题，谢谢
