### ISSUE TITLE
更新最新版的apitable docker镜像后无法提交神奇表单

### ISSUE THREAD

**Issue by fangjiyuan** [apitable/apitable#1534]
**描述Bug**
更新最新版的apitable docker镜像后无法提交神奇表单

**重现步骤**
重现行为的步骤：
1. 前往“神奇表单”
2. 点击“提交”
3. 提示网络失败无法提交

**期望行为**
正常提交

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/36502693/cd81dbf5-b1f6-4816-8256-fd4f0315d9e2)
![image](https://github.com/apitable/apitable/assets/36502693/7d389cb5-741f-43aa-a9e1-6ccc4807d1e1)

**电脑版（请填写以下信息）：**
 - 版本号：[2023年12月20日docker镜像]
 - 操作系统：[win11]
 - 浏览器：[edge]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by fangjiyuan** [comment]
其他功能是正常可以访问的。

**Comment by fangjiyuan** [comment]
[_apitable_logs (7).txt](https://github.com/apitable/apitable/files/13724779/_apitable_logs.7.txt)
这是一部分日志文件，希望对debug有帮助。

**Comment by pengjin123** [comment]
1.请问你表单对应的源表有删除过么,看日志信息显示对应表不存在
![image](https://github.com/apitable/apitable/assets/108248808/59eebd61-8803-46fe-aa55-cf6265d6be3e)
2. 麻烦打开下控制台看下network下面的addrecord接口报什么错误呢

**Comment by fangjiyuan** [comment]
code: 309
message: "{\"key\":\"max_rows_in_space\",\"specification\":250,\"usage\":2360}"
success: false

**Comment by fangjiyuan** [comment]
我似乎找到了问题所在，我发现空间战的文件数有默认值了。这个是有bug吗？
![image](https://github.com/apitable/apitable/assets/36502693/e404342b-b3b3-4ce5-b1cb-af0092366d1b)

**Comment by fangjiyuan** [comment]
我尝试在docker运行的时侯添加这个参数解决了问题    -e SKIP_USAGE_VERIFICATION="true"
应该是新的docker镜像设置了这个参数默认为false，请确认后的话在下个版本修正。

**Comment by curtishall** [comment]
I have this same problem when trying to publish a form using the later docker compose builds

![image](https://github.com/apitable/apitable/assets/331478/0cccce94-1b4b-4dbe-a302-9bb0bdb08211)

**Comment by fangjiyuan** [comment]
> I have this same problem when trying to publish a form using the later docker compose builds
> 
> ![image](https://private-user-images.githubusercontent.com/331478/292017502-0cccce94-1b4b-4dbe-a302-9bb0bdb08211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTgyODQsIm5iZiI6MTcwMzExNzk4NCwicGF0aCI6Ii8zMzE0NzgvMjkyMDE3NTAyLTBjY2NjZTk0LTFiNGItNGRiZS1hMzAyLTliYjBiZGIwODIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwMDE5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2JkNjE2OTQ4MDM5NmM3N2E2NjU2ZTg2NmYyMGQyMGM5YjUzMTk2MzRjYjhjN2IwN2I3YWI2YTQyMmI4Mzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CNx9OcqaPfM-J4eA6bwmt4lfD3zYiohTMEAnUUbHKU0)


我已经解决了这个问题，你可以在docker run的时侯添加 -e SKIP_USAGE_VERIFICATION="true" 参数
I have resolved this issue, you can add   a parameter    -e SKIP_USAGE_VERIFICATION="true"      when Docker runs。
for example：sudo docker run -d -v ${PWD}/.data:/apitable  -e SKIP_USAGE_VERIFICATION="true"  -p 80:80 --name apitable apitable/all-in-one:latest

**Comment by ChambersChan** [comment]
This should be because the space station has exceeded the limit, and the prompt is wrong.

**Comment by curtishall** [comment]
That is the problem.  The self hosted version I was using had 0 limits, the new self hosted docker has 250 limits?  When did this change?

**Comment by ChambersChan** [comment]
Adjusted this month, older versions can use v1.5.0-beta or previous images.
