### ISSUE TITLE
question: What is the purpose of init-appdata

### ISSUE THREAD

**Issue by thend03** [apitable/apitable#1549]
## purpose of init-appdata
The init-appdata initializes which data? I am deploying locally and would like to understand the purpose of init-appdata to determine its impact.

any docs of init-appdata? I only found a script which is packaging/all-in-one/all-in-one/script/init-appdata.sh

**Comment by ChambersChan** [comment]
It includes template center, official applet, automation robot data and product attachments (cover images, illustrations, etc.).
