### ISSUE TITLE
question: A question about room-server client address

### ISSUE THREAD

**Issue by BurgerTown** [apitable/apitable#1550]
## Any questions?

I encounter this problem when running development environment

![image](https://github.com/apitable/apitable/assets/19660419/b603eb71-77fa-460f-a316-6186929e577f)

I found that `ping room client` is trying to `HTTP GET` a `gRPC` service which hosted by room-server `initRoomGrpc`

Is there any problem with my env?

**Comment by ChambersChan** [comment]
This is no problem. It's just that when it first started, grpc initialization was a little slower than the health check.
