### ISSUE TITLE
question: 自己部署的系统，系统语言问题

### ISSUE THREAD

**Issue by chaoaiai** [apitable/apitable#1567]
## Any questions?
使用的官网推荐的docker-compose部署的程序，但是语言选择里没有其它语言选项，是部署的时候需要额外设定什么参数么？
![image](https://github.com/apitable/apitable/assets/69340547/71ae4db8-46bd-4847-b295-efc2df35cd13)

**Comment by lanco531** [comment]
我们在做技术选型，也遇到这个问题，现在是什么情况呀？是开源版本不支持么？@nagisakon

**Comment by networkhermit** [comment]
Other languages are not supported in the open source version.
