### ISSUE TITLE
question:更新列类型时大事务问题

### ISSUE THREAD

**Issue by thend03** [apitable/apitable#1575]
## 问题?
更新列类型的时候，如果表格行比较多(目前表格超过2万行的话)，会造成事务超时(超时时间是30s)，超时可能会回滚，导致修改失败

## 目的
修改列类型的时候，如何避免大事务的超时以及回滚问题，或者有没有什么方案可以实现最终一致性，绕过大事务问题

**Comment by nagisakon** [comment]
很抱歉暂时没有解决的办法，您可以尝试修改数据库事务时间设置，或者对数据分批操作（例如新创一列，然后从这列分批粘贴数据到新列）
