### ISSUE TITLE
question: About how to use database data

### ISSUE THREAD

**Issue by Nonomi514** [apitable/apitable#1576]
question:
- How is record stored in the database?
- Is JSONObject used to process data?

The above two questions can be used to explain whether the data stored in MySqL is JSON String?

@spantaleev @mr-kelly @zhou-yg @almosnow @BensonCheung

**Comment by shawndenggh** [comment]
what is recode? @Nonomi514

**Comment by Nonomi514** [comment]
> what is recode? @Nonomi514

Sorry,it should is record

**Comment by ChambersChan** [comment]
Record data is stored in the database apitable_datasheet_record, and the data format is json.

**Comment by RedCrazyGhost** [comment]
[DatasheetRecordVo.java](https://github.com/apitable/apitable/blob/54ae71107446c1235df47ac4337578787e5d0595/backend-server/application/src/main/java/com/apitable/workspace/vo/DatasheetRecordVo.java#L42) The data type is JSONObject, and the underlying implementation is Map<String,Object>
```Java
@Schema(description = "Data recorded in one row (corresponding to each field)")
private JSONObject data;
```

[JsonHandler.java](https://github.com/apitable/apitable/blob/54ae71107446c1235df47ac4337578787e5d0595/backend-server/application/src/main/java/com/apitable/shared/util/ibatis/JsonHandler.java#L27) Write about the mapping processing of JSONObject
```Java
@MappedTypes(JSONObject.class)
@MappedJdbcTypes(JdbcType.VARCHAR)
public class JsonHandler extends BaseTypeHandler<JSONObject> 
```

[DatasheetRecordMapper.xml](https://github.com/apitable/apitable/blob/54ae71107446c1235df47ac4337578787e5d0595/backend-server/application/src/main/resources/mapper/workspace/DatasheetRecordMapper.xml#L51) There was a mention of data
```XML
<sql id="RecordVo_Column_List">
        record_id, `data` as data, revision_history, revision, field_updated_info as recordMeta
    </sql>

<select id="selectListByDstId" resultMap="datasheetRecordVo">
    select  <include refid="RecordVo_Column_List"/> from ${tablePrefix}datasheet_record
    where dst_id = #{dstId} and is_deleted = 0
</select>
```

[datasheet-record-data.sql](https://github.com/apitable/apitable/blob/54ae71107446c1235df47ac4337578787e5d0595/backend-server/application/src/test/resources/sql/datasheet-record-data.sql#L4) json is embodied in sql statements
```Java
INSERT INTO `datasheet_record` 
(`id`, `record_id`, `dst_id`, `data`,
`revision_history`, `revision`,
`field_updated_info`, `is_deleted`)
VALUES 
(0, 'rec5TDJ5dfewH', 'dst0ZDEBxQPJxoaQ1h', '{}', 
'13', 13,
'{\"createdAt\": 1595922741000}', 0);
```

**Comment by Nonomi514** [comment]
Thanks to both of you, I know the answer to this question

**Comment by nnurmano** [comment]
What happens when a user adds a field? Does it update all rows to add a new field?
