### ISSUE TITLE
question: When the amount of data is too large, it leads to unsuccessful modification of column types

### ISSUE THREAD

**Issue by weidao123** [apitable/apitable#1577]
## When a column exceeds 20000 pieces of data, modifying the column type or inserting a column will cause the database transaction to automatically roll back after timeout, resulting in unsuccessful modification of the column type

* Local service built by Opportunity Docker Compose

**Comment by nagisakon** [comment]
Please refer to this issue
https://github.com/apitable/apitable/issues/1575
