### ISSUE TITLE
question: 位操作权限处理实际上带来了哪些优点?

### ISSUE THREAD

**Issue by LeonChen1024** [apitable/apitable#1596]
想了解下为什么使用位操作来处理权限,实际使用后有什么优缺点吗? 我一般是在操作系统或者 Android 移动端里有看到使用这个,在平台上使用不太清楚实际带来的收益有多大.

**Comment by ChambersChan** [comment]
预估权限限制操作较多，位运算接近底层语言，加快运算速度。
