### ISSUE TITLE
调用API获取表格数据问题

### ISSUE THREAD

**Issue by hzk19951103** [apitable/apitable#1601]
调用apitable多维表格的api接口，以get的方式获取数据，但是每次最多只能获取1000条，表格数据大于1000条，且使用maxRecords参数无效。麻烦大佬指导一下。

**Comment by nagisakon** [comment]
我们一次最多只支持获取1000条数据，详情可看帮助文档 https://developers.aitable.ai/api/reference#tag/Record/operation/get-records
