### ISSUE TITLE
feat: 表格操作按钮能否提示快捷键

### ISSUE THREAD

**Issue by lzy2014love** [apitable/apitable#1603]
I have an idea for this project.

## Why? 
> 快捷键能能提升工作效率
> 能让用户快速记住快捷键

## What?
> 鼠标hover显示对应快捷键
> 或者通过鼠标点击操作的同时屏幕显示对应快捷键， 跟ide插件类似表现方式

**Comment by nagisakon** [comment]
表格内部分功能支持鼠标hover显示对应快捷键，如撤销、展开记录等。请问你还希望增加哪些操作的快捷键提示？

**Comment by lzy2014love** [comment]
例如： 全选操作 插入操作 显示隐藏操作 挺多都没有的。 个人意见而已

**Comment by nagisakon** [comment]
> 例如： 全选操作 插入操作 显示隐藏操作 挺多都没有的。 个人意见而已

感谢你的提议，这边会反馈给相关同事 😊
