### ISSUE TITLE
fix: using API to write date values should be converted using the user-specified time zone

### ISSUE THREAD

**Issue by kwp-lab** [apitable/apitable#1610]
**Describe the bug**
When I use the API to create records, and input values into the date field in the form of a date string, the datetime displayed in the cell is inconsistent with my column configuration. I suspect that the conversion of the date string incorrectly uses UTC+0 instead of the user's local timezone.

**To Reproduce**

1. Set the Time zone to UTC+1 in Preferences;
2. Create a new datasheet, which includes a date field, and specify the timezone as `UTC+2 (Africa/Blantyre)`;
3. Use the create record API to create a new record, where the input value for the date field is in string form, for example, `"2024/01/02 10:00"`;
4. After the API call is successful, a new record appears in the table, but the value of the date field is `"2024/01/02 12:00 (CAT)"`

**Expected behavior**
The value of the date field should be "2024/01/02 11:00 (CAT)"

**Screenshots**
![chrome_XN27BZdh8w](https://github.com/apitable/apitable/assets/35914355/0d391347-65e1-46a0-b2e9-0fcad50acc01)
![chrome_kRvArXp5be](https://github.com/apitable/apitable/assets/35914355/86b348eb-54ba-48a5-9a18-141739c5fa5a)
![ShareX_KPHFz78JkQ](https://github.com/apitable/apitable/assets/35914355/37f06d09-198f-4c3f-a135-6504f4fdf0c5)
![chrome_rERYGtQO9u](https://github.com/apitable/apitable/assets/35914355/f8a7d497-b5cc-48cc-9543-ca56ff47fcf0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Environment: aitable.ai

**Comment by wmEvie** [comment]
This issue has been resolved. When using API to update the DateTime field, please make sure the string format matches the ISO 8601 standards, for example: {fieldName}: "2024-01-03T12:00:00+03:00".

For more explanation, please refer to this document: https://en.wikipedia.org/wiki/ISO_8601
