### ISSUE TITLE
java 17.0.9-amzn not work

### ISSUE THREAD

**Issue by tnyi** [apitable/apitable#1611]
input "make run", select 1, I get the below error msg

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/apitable/Application has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

**Comment by ChambersChan** [comment]
You can use the `java -version` command to check whether the java version matches.

**Comment by tnyi** [comment]
After switching to Java 21, I solved the problem. The main issue was that the development guide misled me, as it was written that Java 17 should be used for deployment. I hope the development guide can be updated to prevent others from encountering this problem in the future.

**Comment by ChambersChan** [comment]
It may be that the .jar has been packaged and compiled before switching the Java version, and it does not match the version after switching.

After switching the Java version number, you can manually delete the .jar and repackage it, or execute the following command:
`cd backend-server`
`./gradlew clean build -x test`
