### ISSUE TITLE
feat: 是否考虑在社区版中提供轻文档能力？

### ISSUE THREAD

**Issue by yangzhongru** [apitable/apitable#1631]
# 1. Executive Summary
表格中提供的轻文档能力，能够极大的扩大使用场景，请问社区是否考虑同步此能力？

# 2. Business Analysis
和云上的轻文档能力相同。
![image](https://github.com/apitable/apitable/assets/38790038/cb77314f-0b8b-4b40-acc4-5450374bd566)

**Comment by nagisakon** [comment]
目前轻文档功能暂时没有在社区版开放的规划，你可以在云版本使用该功能哦～
