### ISSUE TITLE
fix: Some issues to be fixed on UI

### ISSUE THREAD

**Issue by XsChen524** [apitable/apitable#1641]
1. 'Rows' is using a serif font. Consider to make it consistent.
2. 'Free' is not hidden. Suppose to be hidden on 'Bronze' context.

![308536125-8e911639-1526-45e3-9bba-607b78c4de1a](https://github.com/apitable/apitable/assets/43726972/ff373ec4-0fd1-4b1e-8da8-d23be4244d95)
![308536133-85595d92-914d-4e52-b82b-22e89bd960de](https://github.com/apitable/apitable/assets/43726972/bf35c943-8ba3-456b-af63-a4689c40f64e)

**Desktop (please complete the following information):**
 - Version: v1.9.0_beta.1
 - OS: Ubuntu 22.04 LTS
 - Browser: Chrome

**Comment by nagisakon** [comment]
The first issue may be due to the font package not being loaded successfully. You can try refreshing the page. 
I will forward the second issue to the designer and thank you for your suggestion.😊
