### ISSUE TITLE
feat: Can we have history feature to view edited history of datasheet or single cell?

### ISSUE THREAD

**Issue by siam-ese** [apitable/apitable#1677]
As title.

## Why? 
> Why we need this feature？
> What is the user story for this feature? 

## What?
> Can you describe this feature in detail?
> Who can benefit from it?

**Comment by nagisakon** [comment]
If you want to view the edit history of a single cell, you can expand the single record and the history will be displayed on the right side of the page.
If you are axing to view the edit history of the entire table, you can use the Time Machine.
