### ISSUE TITLE
无法批量选择行列,多行选择不方便

### ISSUE THREAD

**Issue by mx369** [apitable/apitable#1681]
从外部导入的表格可能有比较多的空白行或列,
发现列只能单个删除,无法多选.
行虽然可以多选,但是只能点选,无法拖拽鼠标完成多选
### 提议的功能：
允许用户通过鼠标拖拽或键盘快捷键等方式，
选择表格中的任意连续或不连续的多行或多列。

**Comment by nagisakon** [comment]
点击选择一行，然后按下shift键，再选择另外一行，中间的行即可全部选中
或者你可以按照条件筛选出空行，全选删除

**Comment by mx369** [comment]
> 点击选择一行，然后按下shift键，再选择另外一行，中间的行即可全部选中 或者你可以按照条件筛选出空行，全选删除

为啥 不是cmd ,我试了cmd,点选, 或者 cmd shift都支持
