### ISSUE TITLE
feat: Provide selectable backend server development languages, such as: GO, Python, Rust, etc.

### ISSUE THREAD

**Issue by clkz** [apitable/apitable#1691]
I have an idea for this project.
I hope backend-server operation is not limited to the Java platform or development language, and I wish to provide more options, such as: .Net, Go, Python, Rust, etc.
## Why? 
> Why we need this feature？

- For the convenience and quick setup of APITable
- Many developers using MacBook with Apple Mx CPU find it slightly inconvenient to install Java development environmen
- Reduce the barrier for developers。

> What is the user story for this feature? 

- Reduce developer learning costs, e.g., as a Python developer, I have a need to customize APITable. Using my familiar programming language will inevitably minimize integration risks.

## What?
> Can you describe this feature in detail?
- We need a scaffold.
- Choose the appropriate language platform according to developer preferences.
- Create code repositories as needed.
- Other Done.

> Who can benefit from it? 
- APITable Developer
- The developer's workplace
- Perhaps the own

## How?
- Scaffold: Develop on a platform using scaffolding, keeping it as simple and lightweight as possible.
- Language Support: Provide repositories or mirrors for supported languages (developer's choice).
- Attempt to run

**Comment by mr-kelly** [comment]
We are using Node JS TypeScript lang
