### ISSUE TITLE
Module not found: Can't resolve '@apitable/widget-sdk'

### ISSUE THREAD

**Issue by godIsAProgrammer** [apitable/apitable#1700]
**描述Bug**
根据本地开发指南，按照操作步骤操作，当执行到 make run 3 时出现 Module not found: Can't resolve '@apitable/widget-sdk' 报错。

**重现步骤**
重现行为的步骤：
1、brew install git make gcc
2、brew install --cask docker
3、brew install python3
4、curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
5、curl -s "https://get.sdkman.io" | bash
6、curl -fsSL https://get.pnpm.io/install.sh | sh -
7、make dataenv 
8、make install 
9、make run      # enter 1  
10、make run # enter 2
11、make run # enter 3
12、make run # enter 4

**期望行为**
编译成功，不会报  Module not found: Can't resolve '@apitable/widget-sdk' 错误。

**屏幕截图**
![image](https://github.com/apitable/apitable/assets/11454918/97cae334-3ef6-4ec5-8030-ddc8e6db0ae2)

**电脑版（请填写以下信息）：**
 - 版本号：[venturn 13.6.6 (22G630)]
 - 操作系统：[macOs ]
 - 浏览器：[Chrome]

**其他上下文**
apitable 版本 v1.10.0-beta，develop 分支。

**Comment by mobei12** [comment]
改一下datasheet的packege.json依赖，@apitable/widget-sdk：“*”改为@apitable/widget-sdk：“workerspace:*”

**Comment by ranglang** [comment]
Thank you for reporting this issue. You can try to fix it by the temporary solution above. It seems that the monorepo is not working well.

**Comment by nagisakon** [comment]
Thank you for the feedback. 
We have fixed it in v1.10.0-beta. Please update to the latest code.
