### ISSUE TITLE
fix: make run 3  npm run start:datasheet Module not found: Can't resolve '@apitable/widget-sdk'

### ISSUE THREAD

**Issue by HiGreenMF** [apitable/apitable#1706]
**描述Bug**
make run 【3】
error - ./src/pc/common/store_subscribe/dashboard_map.ts:21:0 Module not found: Can't resolve '@apitable/widget-sdk'

**重现步骤**
重现行为的步骤：
1.分支develop
2.前往“apitable 项目根路径”
3. > make run  选择3
4.Module not found: Can't resolve '@apitable/widget-sdk'

**修复**
cd apitable/packages/datasheet/
vim package.json
将 "@apitable/widget-sdk" : " * " 修改为 "@apitable/widget-sdk" : " workspace:* " 
重新下载该包
make run 【3】

**系统版本**
MacOS 13.4

**Comment by networkhermit** [comment]
Please check the error messages of the `make install` step, or make a clean install.

**Comment by nagisakon** [comment]
Thank you for the feedback. 
We have fixed it in v1.10.0-beta. Please update to the latest code.
