### ISSUE TITLE
question: Alternative tool for minio

### ISSUE THREAD

**Issue by nelajc** [apitable/apitable#1730]
is there any tool or service we can use to replace minio for this apitable stack?

**Comment by ChambersChan** [comment]
Services compatible with S3 SDK can modify the [environment variable](https://github.com/apitable/apitable/blob/develop/.env#L107)(L107 - L110) value accordingly.

**Comment by nelajc** [comment]
thanks. but how can i tell if s3 is connected properly to apitable stack? 

also. should i stop/remove the minio container right?

**Comment by nelajc** [comment]
> Services compatible with S3 SDK can modify the [environment variable](https://github.com/apitable/apitable/blob/develop/.env#L107)(L107 - L110) value accordingly.

seems this one not working.. upstream and imageproxy configs of gateway container is searching for minio..

**Comment by ChambersChan** [comment]
> > Services compatible with S3 SDK can modify the [environment variable](https://github.com/apitable/apitable/blob/develop/.env#L107)(L107 - L110) value accordingly.
> 
> seems this one not working.. upstream and imageproxy configs of gateway container is searching for minio..

Sorry. I missed the env configuration inside the service (ASSETS_URL、OSS_HOST and QNY1).
They can be assigned to s3 or cdn addresses, for example, using local minio to assign 'http://127.0.0.1:9000/'.
