### ISSUE TITLE
[Building] Cannot find Pingplusplus dependency

### ISSUE THREAD

**Issue by han-steve** [apitable/apitable#1768]
When trying to build the backend java application, I'm running into this error: 
```
FAILURE: Build failed with an exception.
 * What went wrong:
 Execution failed for task ':application:extractIncludeProto'.
 > Could not resolve all files for configuration ':application:compileProtoPath'.
    > Could not find Pingplusplus:pingpp-java:2.3.14.
      Required by:
          project :application
```
It seems like the repository
```
        maven { url = uri("https://jcenter.bintray.com") }
```
no longer has this file. I was able to get around the issue by download the jar directly from their [repo](https://github.com/PingPlusPlus/pingpp-java) and using it directly. 

## General question about the project
Btw, before I dive too deep into this codebase, what is the current status of this open source project? I haven't seen any commits in the past few months, and I'm wondering if it's being put on hold. For example, https://github.com/apitable/apitable/issues/1438 is still blocking me from using this.

**Comment by youngmilker** [comment]
try this

**Comment by youngmilker** [comment]
try this

allprojects {
    group = "com.apitable"

    repositories {
        mavenCentral()
        maven { url = uri("https://jcenter.bintray.com") }
        // other maven repositories
        maven {url 'https://maven.aliyun.com/repository/public/'}
        maven {url 'https://maven.aliyun.com/repository/spring/'}
        maven {url 'https://maven.aliyun.com/repository/spring-plugin/'}
        maven {url 'https://maven.aliyun.com/repository/gradle-plugin/'}
    }
}

**Comment by han-steve** [comment]
Thanks! That works. 

If I may ask, do you know what’s the plan for open source for this project? There hasn’t been commits for months, and I’m worried about learning this codebase just for it to be abandoned. There are still many bugs in the open source version that prevents me from using it for personal management.

**Comment by scorpion-orion** [comment]
The guys behind APITable should definitely raise money to bring this to the mass. This is simply the best out there.

**Comment by han-steve** [comment]
Agreed. I get it if they have to focus on commercial version to make money, but I do hope that they can communicate more clearly about the open source plan. It's a very powerful piece of software that just needs some more polish to be able to replace nearly all CRUD apps.
