### ISSUE TITLE
fix: Cannot invite user

### ISSUE THREAD

**Issue by vinyll** [apitable/apitable#195]
A blank content appears when inviting a future member by link.
A 403 "not allowed" error comes along with the following response: `requested URL is not allowed`.

**To Reproduce**
1. Connect as an admin
2. Go to the users > invite > invite via link. Copy the URL (ex: "http://apitable.local/invite/link?token=1721726062f24c4fb0ad09c57104f15e From APITable: admin invited you to join "Cool workspace" Space. Open it via a computer browser for a better experience.")
3. Paste that link in another browser or in private mode
4. click "confirm to join"

**Expected behavior**
A window should confirm the account creation with an email and password creation

**Screenshots**

<img width="1342" alt="Screenshot 2023-01-14 at 12 34 52" src="https://user-images.githubusercontent.com/145172/212470082-d850f01a-6a9e-4e47-ab7f-d3e7ad01c217.png">

That occurs on Firefox and Chromium with a remote server (HTTP no SSL).

**Comment by kwp-lab** [comment]
hi, @vinyll 
This is known issue. Due to the absence of the registration page, the user cannot complete the password entry. We are speeding up the processing of this issue. After the registration page is completed, team collaboration will be possible.

**Comment by kwp-lab** [comment]
Based on version v0.18.0-rc.1, the features of registering, inviting users, and changing passwords are ready.
