### ISSUE TITLE
question: How to change the admin user password?

### ISSUE THREAD

**Issue by vinyll** [apitable/apitable#198]
By default the admin account is `admin@apitable.com` and `Apitable2022`.
If publishing the app we need to customize the password for obvious reasons.

Where to do that?

**Comment by mr-kelly** [comment]
> By default the admin account is `admin@apitable.com` and `Apitable2022`. If publishing the app we need to customize the password for obvious reasons.
> 
> Where to do that?

Hi, @vinyll 
In user profile setting page, there's "Change Password" setting.

**Comment by vinyll** [comment]
Thanks for your reply.
My first shot was to get there, so it would make total sense to me too.
However I see this page with no password editing.
Am I missing something obvious here? 🧐 

<img width="809" alt="Screenshot 2023-01-16 at 10 59 33" src="https://user-images.githubusercontent.com/145172/212650840-91bc3e41-f9cd-4f75-b3e7-a93e3747238b.png">

**Comment by vinyll** [comment]
Same for the space admin members, not there neither. 🤷‍♂️ 
<img width="993" alt="Screenshot 2023-01-16 at 11 40 37" src="https://user-images.githubusercontent.com/145172/212659177-64a001d7-cd33-4ce3-8b4b-cf732c4a0a8f.png">

**Comment by fabioqcorreia** [comment]
@vinyll I know that's not the best way, but I did manage to do a workaround.

1. Got inside mysql container and login;
2. Looked into mysql apitable database and table `apitable_user`;
3. Figured out that password hash is bcrypt, so generated from a self created password a new hash;
4. Updated using `INSERT`;
5. It worked fine.

I would recommend APITable team to make username and password an external configuration from `.env` file.

Another option would be generating it when you startup and show it from logs like backend service.

**Comment by fabioqcorreia** [comment]
And this issue seems to be more an UI bug than lack of documentation IMO.

**Comment by vinyll** [comment]
Note that cloning the repo and running the latest _develop_ branch locally has the same issue.

<img width="937" alt="Screenshot 2023-01-18 at 06 27 12" src="https://user-images.githubusercontent.com/145172/213091630-71e16864-2d5c-40e5-810a-af442936cc63.png">

**Comment by vinyll** [comment]
Indeed it's not just a documentation issue but a bug: a `ACCOUNT_RESET_PASSWORD_VISIBLE` flag is set to false by default, meaning we cannot update a password.

However switching to true does not solve and shows the following blank screen:

<img width="726" alt="Screenshot 2023-01-18 at 10 58 51" src="https://user-images.githubusercontent.com/145172/214267381-feb76b8e-64c6-4382-b3c6-78597e489fa3.png">

Furthermore the default behavior requires a SMS code that is not provided in developer mode.

@mr-kelly what workaround can we put in place to easily offer a user to change his password?

**Comment by mr-kelly** [comment]
> Furthermore the default behavior requires a SMS code that is not provided in developer mode.

Yes.
Due to security and SMS fee problems, we do not provide SMS authentication in the community version.
That's why we provide a default username and password.
We will fix this change password issue in next sprints ASAP.

**Comment by hmmhmmhm** [comment]
I leave a password change guide in case someone comes here.

1. Go to https://bcrypt.online/, convert the desired password to a bcrypt hash string, and copy it.
2. In the Docker Desktop, find **"apitable-mysql-*"** and click "Open in terminal"
![w1](https://user-images.githubusercontent.com/38493722/219969556-daf1c344-2d02-4356-be40-c27fa5eda86f.png)
4. In your terminal, type the following commands one by one, you can remove the $ in front of them.
``` bash
$ mysql -u root -p
$ apitable@com
$ USE apitable;
$ SELECT * FROM apitable_user;
$ UPDATE apitable_user SET password='YOUR_NEW_BCRYPT_HASH' WHERE email='admin@apitable.com';
```

**Comment by hmmhmmhm** [comment]
This issue seems to be for all widgets. The moment I add a widget in Workbench, all pages are paralyzed,
The only way I was able to get out of it was to delete all cookies and re-login, but never hit the widget tab.

**Comment by vinyll** [comment]
Not having SMS for community edition sounds very fair.
However it is still required for editing the password for community, which therefore makes no sense.

Thanks @hmmhmmhm for the workaround, I had the same idea in mind but didn't move forward to make it happen.
You saved me an hour! 💯 

BTW ApiTable looks **very** promissing, it went crazily fast to 7k⭐️ while we were just a very few a couple of weeks ago.
You guys are doing an amazing job!

**Comment by hmmhmmhm** [comment]
And just to clarify, here's how to add a Space Member account:
After connecting to the terminal as shown above, log in to mysql and enter the SQL command below.
```sql
INSERT INTO apitable_user (uuid, nick_name, code, mobile_phone, email, password, created_at, updated_at)
VALUES (
    UUID(),
    'YOU_WANT_NICKNAME',
    NULL,
    NULL,
    'YOU_WANT_EMAIL',
    'YOU_WANT_PASSWORD_BCRYPT',
    NOW(),
    NOW()
);
```

Even though you've entered the above command, it's not fully added yet, you'll need to do the following additional tasks as an administrator.

Settings -> Organization -> Members & Team -> Click Invite Button -> Invite via email -> (Enter the email address you just added)

![114](https://user-images.githubusercontent.com/38493722/219976646-ad45ea7a-81c2-4b95-bc50-bc498d2af25f.png)
If you've completed the above, users from that account will now be able to access the invited space.

**Comment by mr-kelly** [comment]
Thanks for your patience... We are working on this fix soon.

**Comment by Liamzai** [comment]
Based on version v0.18.0-rc.1, the features of registering, inviting users, and changing passwords are ready.
