### ISSUE TITLE
docs: system architecture diagram

### ISSUE THREAD

**Issue by Magi-Wang** [apitable/apitable#200]
## What documentation do you want?

Hi, can you provide a system architecture diagram? Help read the project source code, thank you.

**Comment by mr-kelly** [comment]
> ## What documentation do you want?
> Hi, can you provide a system architecture diagram? Help read the project source code, thank you.

Room Server Architecture: https://github.com/apitable/apitable/tree/develop/packages/room-server

Can it help?
