### ISSUE TITLE
Cannot find module canvas.node

### ISSUE THREAD

**Issue by vinyll** [apitable/apitable#212]
Installing the project in local for contributing base on [the developer guide](https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md).
the `make run # -> 4` runs the web-server on port 3000.

When starting the web page in my browser the following error occurs:

```
Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /Users/vinyll/Projects/apitable/node_modules/canvas/lib/bindings.js
- /Users/vinyll/Projects/apitable/node_modules/canvas/lib/canvas.js
- /Users/vinyll/Projects/apitable/node_modules/canvas/index.js
- /Users/vinyll/Projects/apitable/node_modules/konva/cmj/index-node.js
- /Users/vinyll/Projects/apitable/packages/datasheet/web_build/server/pages/_app.js
- /Users/vinyll/Projects/apitable/node_modules/next/dist/server/require.js
- /Users/vinyll/Projects/apitable/node_modules/next/dist/server/next-server.js
- /Users/vinyll/Projects/apitable/node_modules/next/dist/server/next.js
- /Users/vinyll/Projects/apitable/packages/datasheet/server.js
```

**Comment by vinyll** [comment]
ensuring to switch to node 16 `nvm use 16` and install packages by hand `yarn` did the trick.

**Comment by Oh-suki** [comment]
i have the same problem. I used your solution. It doesn't work.

**Comment by arucil** [comment]
> i have the same problem. I used your solution. It doesn't work.

Please create a new issue about what you've attempted and the errors you've encountered, or you can just ask questions on our [Discord channel](https://discord.com/channels/1016320471010115666/1016320471769296937).

**Comment by meimosor** [comment]
First download the canvas-v2.9.1-node-v93-win32-unknown-x64.tar package, and after decompression, manually copy the Build directory to the Build directory of the canvas directory under node_modules.
