### ISSUE TITLE
feat: all-in-one Docker image - like Budibase

### ISSUE THREAD

**Issue by dominik-mukrecki** [apitable/apitable#230]
Greetings,

I tested your software and I am very impressed! Hope this project will develop further.

Let me show you, how Budibase solved problems of maintaining applications dependent on different services. They prepared an all-in-one docker image, which works well with a few lines of docker-compose.yml. A lot of businesses use containers on their VMs: smaller ones simple Docker ones, eventually in Swarm mode, and bigger Kubernetes-like solutions. Just check their DockerHub:

hub.docker.com/r/budibase/budibase

In their case, CouchDB, Redis, MinIO, and Budibase core services are packed into one container, configured with a few environmental variables.

As a business founder and IT passionate I clearly understand your idea, but to make it accessible, you have to prepare the simplest possible method to prepare a self-hosted instance of your app. An All-in-one Docker image seems to fit into this very well.

Regards,
Dominik

**Comment by networkhermit** [comment]
Thanks for the suggestion. We are already working on it.

**Comment by networkhermit** [comment]
For anyone interested in the all-in-one image, you can test the versioned image now:

```bash
sudo docker run -d -v ${PWD}/.data:/apitable -p 80:80 --name apitable apitable/all-in-one:v0.18.0-alpha_873
```

The stateful mysql/redis/minio/rabbitmq data are all stored inside /apitable.

Depending on your environment, you will need to wait several minutes for all the services and initialization to complete.

The all-in-one image is only for demo/testing purpose, we don't recommend it for enterprise usage.

P.S. This image is amd64 (x86_64) only, you may encounter pretty bad performance on arm64 or apple silicon.
