### ISSUE TITLE
feat: dependencies in gantt diagram

### ISSUE THREAD

**Issue by iEgit** [apitable/apitable#231]
I have an idea for this project.

## Why? 
basic feature for gantt diagrams

## What?
set dependencies between tasks so as we could move them around and see their connections. If we move the dependency, the dependent tasks should also move if their start date is not valid after the change.

Do you have plans on implementing this feature?

**Comment by xukecheng** [comment]
@iEgit Hello iEgit, it's great to see you bringing up this topic. At APITable, we already have the capability to build Gantt charts using task dependencies. To do this, you simply need to create a dependency in the view's settings. The process is easy and straightforward

First, create a 'Magic link' field that links to the current datasheet. 
![CleanShot 2023-01-29 at 11 25 36@2x](https://user-images.githubusercontent.com/29099863/215303368-f5a70d05-3f02-4881-a8e7-215fd4eaea41.png)

With this set up, you can add dependencies to your Gantt view by connecting two tasks by dragging an arrow line between them.
![CleanShot 2023-01-29 at 11 38 39@2x](https://user-images.githubusercontent.com/29099863/215303412-8b13eb20-57cb-45b9-b593-dcf6706ce280.png)

We also support the FS task dependency model, where a "predecessor" task must be completed before the "successor" task can begin. This is a common concept used in project management to ensure that tasks are completed in the proper order and that dependencies between tasks are clearly defined. This helps to keep your project on schedule and ensure that tasks are completed on time.

**Comment by iEgit** [comment]
Hello, thank you so much for your thorough response! Looks like I missed this setup. The feature works great
