### ISSUE TITLE
fix: Cannot reset password

### ISSUE THREAD

**Issue by wmEvie** [apitable/apitable#238]
**Describe the bug**
There is no entrance for resetting the account password in the product, cannot reset the account password.

**Expected behavior**
Can reset the account password in the product.

**Comment by networkhermit** [comment]
Related question:

https://github.com/apitable/apitable/issues/198

**Comment by vinyll** [comment]
It is also related to https://github.com/apitable/apitable/pull/222

**Comment by wmEvie** [comment]
This is fixed now, please pull the latest code, and follow the steps below to complete the configuration for sending the verification code, which is used to reset the password:
1. Open the .env file from the root directory.
2. Configure the following keys:
  - MAIL_ENABLED=false
  - MAIL_TYPE=smtp
  - MAIL_SSL_ENABLE=true
  - MAIL_HOST=_your_email_host_
  - MAIL_USERNAME=_your_email_username_
  - MAIL_PASSWORD=_your_email_password_
  - MAIL_PORT=_email_port_

Then restart APITable, here are the steps to reset the password:
- Click on the avatar in the lower left corner, open "My Settings"
- Click on the "Change Password"
- Click on "Send" to send the code to your email, check out your inbox for the code, and fill in to reset the password.
![image](https://user-images.githubusercontent.com/37546178/220116760-51606e36-d416-4c64-ba6e-e553fa0e275f.png)
![image](https://user-images.githubusercontent.com/37546178/220116825-05007d61-785a-4e1f-8e28-a260f426010b.png)

**Comment by vinyll** [comment]
the form does appear, however the verification field by SMS is required for saving despite the fact that it is said not to be enabled in the community version.
The "save" button is disabled until a verification code is inserted.

<img width="434" alt="Screenshot 2023-02-20 at 19 06 33" src="https://user-images.githubusercontent.com/145172/220175484-eb16c636-d3d1-4383-92d5-2507e8fe1e69.png">

**Comment by wmEvie** [comment]
> the form does appear, however the verification field by SMS is required for saving despite the fact that it is said not to be enabled in the community version. The "save" button is disabled until a verification code is inserted.
> 

Please change the account email to your own email first (Using SQL), 
and follow the above guide to configure the .env file.

Then click on the "Send" button to send the verification code to your email, 
check your inbox for the code, 
and fill out the code to enable the "Save" button.
