### ISSUE TITLE
perf: apply concurrency to improve throughput of fusion api getRecords

### ISSUE THREAD

**Issue by arucil** [apitable/apitable#248]

**Comment by yort-feng** [comment]
Is the issue to serialize an object with Rust?

**Comment by arucil** [comment]
> Is the issue to serialize an object with Rust?

Either applying worker threads in Node.js or multi-thread in Rust is acceptable.

**Comment by yort-feng** [comment]
> > Is the issue to serialize an object with Rust?
> 
> Either applying worker threads in Node.js or multi-thread in Rust is acceptable.

How is the progress? Seems you should list all tasks or split them into multiple issues.
