### ISSUE TITLE
fix: Unable to invite google email or outlook email

### ISSUE THREAD

**Issue by nagisakon** [apitable/apitable#253]
**Describe the bug**

**To Reproduce**
1.click to「contacts」-「invite」-「invite via email」
2.input google email or outlook email and click 「send invitation」
3.send failed

[image](https://user-images.githubusercontent.com/49678762/215433717-4cdafb87-bf8e-4fed-aaab-ccf8b01996f2.png)

**Expected behavior**
send successful

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ChambersChan** [comment]
Artificially delete accounts in the background of Auth0, causing data problems.
