### ISSUE TITLE
fix: ESLint scanning issue

### ISSUE THREAD

**Issue by yort-feng** [apitable/apitable#259]
**Describe the bug**
Would report the below error message while executing the `Run ESLint scanning` job(GitHub workflow):

> The prop value with an expression type of ChainExpression could not be resolved. Please file an issue to get this fixed immediately.

**To Reproduce**
ESLint scanning issue while executing GitHub workflow job

**Expected behavior**
run `yarn lint` successfully and report errors

**Screenshots**
![GTlYqBIYSD](https://user-images.githubusercontent.com/7292727/215650096-34c70c6f-362f-454d-bd92-351ec003e53f.jpg)

**Additional context**
none

**Comment by Jactif93** [comment]
- [ ] [](url)

**Comment by yort-feng** [comment]
> * [ ]

? @Jactif93 it seems like you pasted the wrong URL.
