### ISSUE TITLE
fix: docker image missing .proto files

### ISSUE THREAD

**Issue by yort-feng** [apitable/apitable#261]
**Describe the bug**
The docker image lost `.proto` files once in a while, the reason might be a typescript compiler issue

**To Reproduce**
Building a docker image and  it was accidental

**Expected behavior**
Never lose static files while building docker image

**Screenshots**
![9xtfxk3nos](https://user-images.githubusercontent.com/7292727/215658259-27ae0f75-e893-4a18-93c4-1af8ede3a84c.jpg)

**Additional context**
none

**Comment by Julian-Hackenberg** [comment]
Hey, experiencing the same problem at the moment. @yort-feng have you found a quick fix by any chance?

**Comment by dominik-mukrecki** [comment]
Greetings,

same here - pulling latest room-server image from DockerHub reproduces this issue.

Also, I tried to rebuild the room-server locally (cloned repository and used `apitable/packaging/Dockerfile.room-server` file) and this issue appears:

`Cannot read properties of undefined (reading 'url')`

Only those layers were build up:

`1	124.1 MB	
ADD file:abc6873c98339a3c496cb75ec2528e65ebe1f20d2cea777033f86dcd55d73da5 in /`
`2	0 B	
CMD ["bash"]`
`3	10.7 MB	
RUN set -eux; apt-get update; apt-get install -y --no-install-recommends ca-certificates curl netbase wget ; rm -rf... `
`4	19 MB	
RUN set -ex; if ! command -v gpg > /dev/null; then apt-get update; apt-get install -y --no-install-recommends gnupg ... `
`5	152 MB	
RUN apt-get update && apt-get install -y --no-install-recommends git mercurial openssh-client subversion procps &&... `
`6	529 MB	
RUN set -ex; apt-get update; apt-get install -y --no-install-recommends autoconf automake bzip2 dpkg-dev file g++... `
`7	332.1 kB	
RUN RUN groupadd --gid 1000 node && useradd --uid 1000 --gid node --shell /bin/bash --create-home node # buildkit`
`8	0 B	
ENV ALINODE_VERSION=7.6.0`
`9	0 B	
ENV ENABLE_NODE_LOG=YES`
`10	0 B	
ENV NODE_LOG_DIR=/tmp`
`11	0 B	
ENV HOME=/root`
`12	138 MB	
RUN RUN apt-get update && apt-get -y --force-yes install build-essential libcairo2-dev libpango1.0-dev ... `
`13	749 B	
COPY ./default.config.js /root # buildkit`
`14	178 B	
COPY ./start-agenthub.sh / # buildkit`
`15	0 B	
RUN RUN chmod u+x /start-agenthub.sh # buildkit`
`16	0 B	
ENV YARN_VERSION=1.22.15`
`17	5.3 MB	
RUN RUN set -ex && for key in 6A010C5166006599AA17F08146C2130DFD2497F5 ; do gpg --batch --keyserver hkps://keys.ope... `
`18	0 B	
ENTRYPOINT ["/start-agenthub.sh"]`
`19	0 B	
WORKDIR /app`
`20	2.3 MB	
COPY dir:654cca24821ab920d41e2e6d50c78fcc864d0cae06497150d501b8345873bfe7 in ./.yarn`
`21	1.7 MB	
COPY multi:8bcad939617871b1f207e807f10e6ba0d4cdbb267206a9f3127f92a1046ff111 in ./`
`22	535 B	
COPY file:f2638797ab137cd9bfe29eeb0a2464edc79e4f5d82bc8582c7c6d4dd2e238bb6 in ./packages/i18n-lang/`
`23	2.5 kB	
COPY file:b6486255ff886b4ba6fc8e83e55ada5ccd977aa8ef301097ae54eda3c61e5283 in ./packages/core/`
`24	4.9 kB	
COPY file:5a406838a8b21304bb3548291863f80fca6db0035253ffbe5a6675d993556b55 in ./packages/room-server/`

Regards :)

**Comment by yort-feng** [comment]
@Julian-Hackenberg @Julian-Hackenberg The latest image already fixed it by rebuilding. It was accidental and might be a typescript compiler issue and we're trying to find a solution to solve it absolutely.

**Comment by yort-feng** [comment]
According to `nest-cli` issues: https://github.com/nestjs/nest-cli/issues/320, https://github.com/nestjs/nest-cli/issues/1117, https://github.com/nestjs/nest-cli/pull/1264, and https://github.com/4s1-org/snow-white-api/issues/150.

There are two solutions: 
- [x] upgrade dependency @nestjs/cli to v8.1.4
- [x] writing a script to copy assets
