### ISSUE TITLE
question: How to install from npm

### ISSUE THREAD

**Issue by linonetwo** [apitable/apitable#272]
I'd like to explore the possibility of empower tiddlywiki using apitable's dynamic table/form UI, so instead of setup a website, I may need to programmatically use it as a npm package that provides some table/form components.

Is this possible or on the roadmap?

**Comment by mr-kelly** [comment]
> I'd like to explore the possibility of empower tiddlywiki using apitable's dynamic table/form UI, so instead of setup a website, I may need to programmatically use it as a npm package that provides some table/form components.
> 
> Is this possible or on the roadmap?

Hi @linonetwo,

It is impossible to use APITable's table/form UI components through **npm package**.

But you can use our `embed` feature, which can embed APITable via `<iframe>` into your application.

You can contact us at **dev@apitable.com** for more information.

**Comment by linonetwo** [comment]
Get it, that will requires starting another web server to use it, which won't work on mobile platform ( tiddlywiki.com/ is a single HTML wiki that can add many plugins like tldraw , as long as they can be embedded via npm).

And it may make it harder to access data in the app memory (have to access data via web API).

Anyway, thanks for opensource this, I may try it later!

**Comment by linonetwo** [comment]
By the way, as a professional developer in the table field, can you recommend a best dynamic table package that is accessible from npm?
