### ISSUE TITLE
question:  where can I find the source code for com.apitable.appdata.AppDataApplication

### ISSUE THREAD

**Issue by Magi-Wang** [apitable/apitable#289]
## Any questions?

Thank you very much to the apitable team. I have a question when I read the code, where can I find the source code for com.apitable.appdata.AppDataApplication?

**Comment by ChambersChan** [comment]
Sorry. The source code is not yet planned to be made public.

This server is used to initialize incremental application content, such as Template Center.

**Comment by magic-cd** [comment]
Is the program "AppDataApplication" necessary for APITable?

**Comment by ChambersChan** [comment]
> Is the program "AppDataApplication" necessary for APITable?

This is not required if accept some content is empty.
