### ISSUE TITLE
question: Q&A...install with bug 【Error: unknown flag: --remove-orphans】

### ISSUE THREAD

**Issue by absir1949** [apitable/apitable#291]
## Any questions?
>#docker --version
> Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman version 3.2.3

>#curl https://apitable.github.io/install.sh | bash

>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4569  100  4569    0     0   1300      0  0:00:03  0:00:03 --:--:--  1300
gateway/
gateway/conf.d/
gateway/conf.d/server/
gateway/conf.d/server/backend-server.conf
gateway/conf.d/server/room.conf
gateway/conf.d/server/minio.conf
gateway/conf.d/server/default.conf
gateway/conf.d/server/web-server.conf
gateway/conf.d/server/socket-server.conf
gateway/conf.d/server/imageproxy.conf
gateway/conf.d/nginx.conf
gateway/conf.d/upstream/
gateway/conf.d/upstream/ups-socket-server.conf
gateway/conf.d/upstream/ups-imageproxy.conf
gateway/conf.d/upstream/ups-minio.conf
gateway/conf.d/upstream/ups-room.conf
gateway/conf.d/upstream/ups-backend-server.conf
gateway/conf.d/upstream/ups-web-server.conf
.env
docker-compose.yaml
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: unrecognized command `podman compose`
Try 'podman --help' for more information.
======== WARM TIPS ========
Before you submit any github issue, please do the following check:
* make sure the docker daemon is running
* make sure you use docker compose v2: recommend 2.x.x, got not install
* check your internet connection if timeout happens
===========================

**Comment by JhonXucf** [comment]
**same question**
system: Centos mini 7 64bit
docker: Docker version 20.10.15, build fd82621

[root@localhost ~]# curl https://apitable.github.io/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   868  100   868    0     0   2393      0 --:--:-- --:--:-- --:--:--  2391
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4569  100  4569    0     0   4129      0  0:00:01  0:00:01 --:--:-- 21152
gateway/
gateway/conf.d/
gateway/conf.d/server/
gateway/conf.d/server/backend-server.conf
gateway/conf.d/server/room.conf
gateway/conf.d/server/minio.conf
gateway/conf.d/server/default.conf
gateway/conf.d/server/web-server.conf
gateway/conf.d/server/socket-server.conf
gateway/conf.d/server/imageproxy.conf
gateway/conf.d/nginx.conf
gateway/conf.d/upstream/
gateway/conf.d/upstream/ups-socket-server.conf
gateway/conf.d/upstream/ups-imageproxy.conf
gateway/conf.d/upstream/ups-minio.conf
gateway/conf.d/upstream/ups-room.conf
gateway/conf.d/upstream/ups-backend-server.conf
gateway/conf.d/upstream/ups-web-server.conf
.env
docker-compose.yaml
unknown flag: --remove-orphans
See 'docker --help'.

======== WARM TIPS ========
Before you submit any github issue, please do the following check:
* make sure the docker daemon is running
* make sure you use docker compose v2: recommend 2.x.x, got not install
* check your internet connection if timeout happens
===========================

**Comment by welsondou** [comment]
modify the install.sh, replace "docker compose" with "docker-compose"

**Comment by absir1949** [comment]
@welsondou when i replace it ,it is still wrong

**Comment by networkhermit** [comment]
> ## Any questions?
> 
> > #docker --version
> > Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
> > podman version 3.2.3
> 
> > #curl https://apitable.github.io/install.sh | bash
> 
> > % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > Dload  Upload   Total   Spent    Left  Speed
> > 100  4569  100  4569    0     0   1300      0  0:00:03  0:00:03 --:--:--  1300
> > gateway/
> > gateway/conf.d/
> > gateway/conf.d/server/
> > gateway/conf.d/server/backend-server.conf
> > gateway/conf.d/server/room.conf
> > gateway/conf.d/server/minio.conf
> > gateway/conf.d/server/default.conf
> > gateway/conf.d/server/web-server.conf
> > gateway/conf.d/server/socket-server.conf
> > gateway/conf.d/server/imageproxy.conf
> > gateway/conf.d/nginx.conf
> > gateway/conf.d/upstream/
> > gateway/conf.d/upstream/ups-socket-server.conf
> > gateway/conf.d/upstream/ups-imageproxy.conf
> > gateway/conf.d/upstream/ups-minio.conf
> > gateway/conf.d/upstream/ups-room.conf
> > gateway/conf.d/upstream/ups-backend-server.conf
> > gateway/conf.d/upstream/ups-web-server.conf
> > .env
> > docker-compose.yaml
> > Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
> > Error: unrecognized command `podman compose`
> > Try 'podman --help' for more information.
> > ======== WARM TIPS ========
> > Before you submit any github issue, please do the following check:
> 
>     * make sure the docker daemon is running
> 
>     * make sure you use docker compose v2: recommend 2.x.x, got not install
> 
>     * check your internet connection if timeout happens
>       ===========================

I notice that you use podman as a docker alias. We haven't tested the installation script on a podman environment.  It seems podman doesn't support `podman compose` directly. You can remove the alias and use the official docker/docker-compose v2 described in https://github.com/apitable/apitable#installation, or you will need to tweak the start up command youself. :-)

**Comment by networkhermit** [comment]
> modify the install.sh, replace "docker compose" with "docker-compose"

You need to install docker-compose v2 described in https://github.com/apitable/apitable#installation.

For more information, consult https://github.com/docker/compose#about-update-and-backward-compatibility.

**Comment by absir1949** [comment]
@networkhermit 
 i has installed the `docker-compose`，but still has the problem
> docker-compose -v
Docker Compose version v2.12.2

**Comment by networkhermit** [comment]
> @networkhermit i has installed the `docker-compose`，but still has the problem
> 
> > docker-compose -v
> > Docker Compose version v2.12.2

Could you show me the output of `docker compose version`? The installation script uses `docker compose`, not `docker-compose`, to avoid confusion.

**Comment by absir1949** [comment]
@networkhermit  thx，i fix it by your method~~
