### ISSUE TITLE
question: Is it possible to build this project without docker?

### ISSUE THREAD

**Issue by ddannyc** [apitable/apitable#293]

**Comment by tennc** [comment]
一样不能 一键部署
错误提示：一直循环
service "pre-init-db" didn't completed successfully: exit 1

**Comment by ChambersChan** [comment]
I think it's ok if it's acceptable that something is missing.

Step:
1. Install basic services(mysql minio redis rabbitmq) or using their cloud platform production;
2. Replace env variable;
3. Execute init-db;
4. Execute `make run` start service.

**Comment by ddannyc** [comment]
> 

Thanks

**Comment by goby1220** [comment]
> 一样不能 一键部署 错误提示：一直循环 service "pre-init-db" didn't completed successfully: exit 1

docker 安装报错你解决了吗

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you encounter any problems, could feel free to contact us through github or [discord](https://discord.gg/5WrDWxkXE9).

**Comment by noahlam** [comment]
> 一样不能 一键部署 错误提示：一直循环 service "pre-init-db" didn't completed successfully: exit 1

@ChambersChan I also got this error when I running `make dataenv`

Below is my machine information:
![image](https://github.com/apitable/apitable/assets/22094266/8206d28e-2732-4437-a59d-c99b3e6d1bb8)

![image](https://github.com/apitable/apitable/assets/22094266/241e8b26-bf92-4f85-b087-06c3150a2293)


And I have tried different docker version(4.15.0 / 4.19.0), it still does not work.

here is my docker info

![image](https://github.com/apitable/apitable/assets/22094266/c69d6774-f6f0-4cfd-893d-2c7664434a10)
