### ISSUE TITLE
feat: Provide versioning via tags for images at DockerHub

### ISSUE THREAD

**Issue by dominik-mukrecki** [apitable/apitable#295]
Please provide versioning for images at DockerHub.

https://hub.docker.com/u/apitable

## Why? 

After the last update room server image crashes again due to a missing `.proto` file (#261).

## What?

Each image at DockerHub should have its own tag because using `latest` for every new one overwrites the old version and makes rollback impossible in case of any issue.

## How?

Just name tags your own way, for example with timestamps like Minio.

**Comment by mr-kelly** [comment]
related https://github.com/apitable/apitable/issues/22
