### ISSUE TITLE
perf: Fusion API pagination cache

### ISSUE THREAD

**Issue by arucil** [apitable/apitable#301]
APITable SDKs typically fetch all records of a datasheet by reading records page by page and then combining them, adding a pagination cache will make this process faster.

## First step

Coarse grained cache invalidation: record revisions of all datasheets that are linking with this datasheet and may affect cell values of this datasheet, if any revision is changed, the cache is invalidated.

**Comment by vedantiitkgp** [comment]
@arucil assign it to me I want to work on this

**Comment by arucil** [comment]
> @arucil assign it to me I want to work on this

Great! if you encounter any problems during your development, feel free to ask questions on our [Discord channel](https://discord.com/channels/1016320471010115666/1016320471769296937).

**Comment by vedantiitkgp** [comment]
Sure @arucil
