### ISSUE TITLE
M2 电脑死活牵不下来，奇怪，apitable！

### ISSUE THREAD

**Issue by nevertoday** [apitable/apitable#307]
尝试多台电脑了，intel 电脑可以，但是m1 m2系列芯片，总卡在这个步骤； 大神，可以帮忙排查下么？ 
![chen2023-02-06_09-47-12](https://user-images.githubusercontent.com/166048/216893856-07637c15-3bf0-4199-951e-6e75a2ab0622.jpg)
Container apitabLe-init-db-1 这个步骤， 就是卡不过去，如何突破？ 

Thanks! hope ~

**Comment by networkhermit** [comment]
Related: https://github.com/apitable/apitable/issues/66, https://github.com/apitable/apitable/issues/67

The root cause is currently we don't have arm64 native docker images, and the amd64 emulation on m1 docker is terrible.

**Comment by yanmw** [comment]
不止是你，centenOS7也一样，妈的，这项目简直服了。领导还一直让搞这个

**Comment by nevertoday** [comment]
用intel 的机器可用是可用哈， 问题是我不太可能开着笔记本在局域网，每天共享~ 
我还是觉得官方大佬， 能不能出来fix 下这个问题....

**Comment by Rel1cx** [comment]
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/24217275/217433672-97096c40-f5d9-4b55-a9b2-801b32104fc3.png">
M2 实测会在这一步卡住

**Comment by Rel1cx** [comment]
<img width="1692" alt="image" src="https://user-images.githubusercontent.com/24217275/217434228-f7f7e5d2-7339-4193-acae-528020d62d88.png">

**Comment by nevertoday** [comment]
俺也一样， 很急很憔悴，求大神降临人间，光芒万丈般完成优化！

**Comment by networkhermit** [comment]
> Related: #66, #67
> 
> The root cause is currently we don't have arm64 native docker images, and the amd64 emulation on m1 docker is terrible.

@nevertoday @Nicify 

Let's track this issue in https://github.com/apitable/apitable/issues/66.

**Comment by nevertoday** [comment]
这个问题不再是问题了么？
