### ISSUE TITLE
question: What is the difference in positioning between "nest/v1" and "/fusion/v1" in the room-server?

### ISSUE THREAD

**Issue by Magi-Wang** [apitable/apitable#308]
## Any questions?

What is the difference in positioning between "nest/v1" and "/fusion/v1" in the room-server?

**Comment by magic-cd** [comment]
FROM Chambers — Today at 5:11 PM
The overall design is based on microservices. Later, for the convenience of developers, they were merged into one repository to reduce the number of startup services.
