### ISSUE TITLE
question: Q&A...This generated password is for development use only. Your security configuration must be updated before running your application in production.

### ISSUE THREAD

**Issue by evelyn361745** [apitable/apitable#310]
## Any questions?
This generated password is for development use only. Your security configuration must be updated before running your application in production.

**Comment by vinyll** [comment]
Hey @evelyn361745, I'm not sure I understand your question.
Can you clarify what this message is and what is your need?

**Comment by ziqiangai** [comment]
What he said should be the statement that `SpringSecurity` prints on the console when the backend-server starts. Ignore this, and you can log in normally with account number: `admin@apitable.com` password: `Apitable2022`.

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
