### ISSUE TITLE
question: Unable to open the magic form share link on the mobile terminal

### ISSUE THREAD

**Issue by huashaoxu** [apitable/apitable#313]
神奇表单分享链接后，为什么在手机端无法打开，PC端可以

**Comment by ChambersChan** [comment]
Which way to deploy the service? Is it on the PC side?

**Comment by huashaoxu** [comment]
平台用docker部署在Linux服务器（pc），生成神奇表单后，分享链接，复制地址后在手机浏览器中无法显示，PC浏览器正常可用。

**Comment by ChambersChan** [comment]
Can you take a look at the share link address? It may not be a public network.

**Comment by huashaoxu** [comment]
是内部局域网搭建，私有化部署的，网段应该是一样的，同网段其他应用都可以在手机端（本地wifi）打开。

**Comment by ChambersChan** [comment]
Can other APItable connections be opened normally?

**Comment by huashaoxu** [comment]
也不行，如果APITable没有针对手机浏览器的限制，我再排查一下网络问题，感谢支持

**Comment by ChambersChan** [comment]
It is no limited.

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you encounter any problems, could feel free to contact us through github or [discord](https://discord.gg/AV3VvkED).
