### ISSUE TITLE
docs: The front-end start steps

### ISSUE THREAD

**Issue by meimosor** [apitable/apitable#320]
How the front end works, the installation dependencies keep failing, and I want to know what the solution is and what the boot instructions correspond to?
![image](https://user-images.githubusercontent.com/31975932/217397610-f99980ae-c0d1-42e7-8ca1-321079516d57.png)

**Comment by ChambersChan** [comment]
Could be try run `npm install canvas@2.9.1`.

**Comment by meimosor** [comment]
> npm install canvas@2.9.1

Still have a problem:
![image](https://user-images.githubusercontent.com/31975932/217485895-c9d1bd5a-cb86-45ad-84ca-7cb42c4718a8.png)

**Comment by ziqiangai** [comment]
> > npm install canvas@2.9.1
> 
> Still have a problem: ![image](https://user-images.githubusercontent.com/31975932/217485895-c9d1bd5a-cb86-45ad-84ca-7cb42c4718a8.png)

Maybe [this blog](https://juejin.cn/post/6953830179105931300) is helpful.
