### ISSUE TITLE
feat:space supports inviting user

### ISSUE THREAD

**Issue by zhouyi-up** [apitable/apitable#321]
目前无法邀请用户

**Comment by Alex-hufeng** [comment]
Thank you for your feedback. We are solving this problem

**Comment by ChambersChan** [comment]
Members can now be invited after configuring smtp.
The configuration method can view [the document](https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md#how-to-configure-the-smtp-server)
