### ISSUE TITLE
question: Cannot find module '@apitable/core' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Yqccc** [apitable/apitable#322]
make run
select 2 to start room-server
Cannot find module '@apitable/core' or its corresponding type declarations.
help~thanks

![errorimg](https://user-images.githubusercontent.com/54765789/217420601-517ed05f-9381-4ede-b16b-5d7729d4e843.png)

**Comment by arucil** [comment]
Did you run `make install` before running room-server?

**Comment by Yqccc** [comment]
> Did you run `make install` before running room-server?

Yes, I have started `docker` and run `make dataenv`  and run  `make install`.

**Comment by arucil** [comment]
Did you start web-server before room-server? Currently starting web-server will recompile `@apitable/core` and thus room-server detects file changes and recompile, however `@apitable/core` is being recompiled by web-server, so room-server reports these errors. We will fix this problem ASAP. For now, you can start web-server before room-server to bypass this problem.

**Comment by Yqccc** [comment]
> Did you start web-server before room-server? Currently starting web-server will recompile `@apitable/core` and thus room-server detects file changes and recompile, however `@apitable/core` is being recompiled by web-server, so room-server reports these errors. We will fix this problem ASAP. For now, you can start web-server before room-server to bypass this problem.

thanks, I can run the project now!
