### ISSUE TITLE
perf: reduce memory consumption of web-server in dev mode

### ISSUE THREAD

**Issue by arucil** [apitable/apitable#323]
Running web-server by `make run` consumes ~8GB RAM on my Manjaro Linux computer, this makes it unfriendly for developers who want to contribute to this project.

Related issue: https://github.com/vercel/next.js/issues/42514

**Comment by BodhiHu** [comment]
try disable `dev` mode

**Comment by ab70** [comment]
> try disable `dev` mode

if  disable dev, how can developer will see the changes!
