### ISSUE TITLE
docs: DOCS... High-Level architecture for this production

### ISSUE THREAD

**Issue by xckai** [apitable/apitable#337]
## What documentation do you want?
Thanks for open source this wonderful production， I'm trying to add some code into it, but I found I have a little bit  confused of each service's responsible and how they are working together overrall. So could you provide a high-level architecture that briefly describe each serice's  responsible?

**Comment by yort-feng** [comment]
Excellent! Please read [Understand APITable - Architecture Overview](../blob/develop/docs/contribute/architecute-overview.md) and feel free to contact us if you have any problems.
