### ISSUE TITLE
以本地模式启动web服务卡死，报错

### ISSUE THREAD

**Issue by wtl-tianliang** [apitable/apitable#338]
服务启动顺序：
`backend`-`socket`-`room`-`web`

启动命令： `make run-local`

启动到web服务时整个wsl卡死，无法开启新的终端会话。大约20分钟后web服务报错。wsl恢复。

![image](https://user-images.githubusercontent.com/15212547/217738705-c17cd77f-19bf-4924-aac2-d355edd615ad.png)

![image](https://user-images.githubusercontent.com/15212547/217738876-3811e0b3-93f6-4a36-89ac-fdb938a10586.png)

![image](https://user-images.githubusercontent.com/15212547/217738897-0f3753ea-b7fd-4c9c-9eaa-897639cdb999.png)

![image](https://user-images.githubusercontent.com/15212547/217738930-53c395c9-1360-4cfd-83a6-774d03b57faf.png)

系统配置：
![image](https://user-images.githubusercontent.com/15212547/217738662-07f12b85-c5a7-46d2-bf6f-8fec54607af9.png)

**Comment by yort-feng** [comment]
We found out that running the web server could consume over ~8GB of RAM. It should be a NextJS issue: [Bug: extremely high memory usage with next dev #42514](https://github.com/vercel/next.js/issues/42514)

Let's track this issue here: #323
