### ISSUE TITLE
feat: editable view using shareable link with a mirror view

### ISSUE THREAD

**Issue by okvdhhc** [apitable/apitable#344]
I have an idea for this project.

## Why? 
I want to be able to send out editable views of spreadsheets (in my case only one field would be editable) with certain fields hidden completely from the people I share to.  

## What?
 I want to basically accomplish this:
1. I have a grid view with multiple fields.
2. I want to be able to send out that view to other people but do not want them to see certain fields (this works using the mirror feature which also doesn't show hidden fields once you expand details of a single record)
3. I want the people that I sent out the view to be able to edit that view (you can't share an editable view using the mirror feature) but at the same time to hide certain fields completely.
Is there any workaround to accomplish this

## How?
 I wish I could help. You can technically do this on Airtable using their Interface feature.

**Comment by Alex-hufeng** [comment]
I will follow up on this requirement.He will be split into two tasks.
1. Hidden fields can't be view in mirrows.(Almost complete)
2. Mirror can be sharing.

**Comment by Alex-hufeng** [comment]
this work is done~ 
You can experience it online.
