### ISSUE TITLE
docs: add section about upgrade instructions

### ISSUE THREAD

**Issue by networkhermit** [apitable/apitable#347]
I propose the following draft document regarding apitable-ce upgrade instructions (WIP), any feedback is appreciated:

## stop the running instance

* docker compose
```bash
cd apitable # or any installation directory containing the docker-compose.yaml/.env and .data
sudo docker compose down -v --remove-orphans
sudo docker ps # check the target instance is actually stopped
```
* all-in-one
```bash
sudo docker stop apitable
sudo docker rm apitable
sudo docker ps # check the target instance is actually stopped
```

## backup the data directory and deployment manifest
* docker compose
```bash
cd apitable # or any installation directory containing the docker-compose.yaml/.env and .data
sudo cp -pr .data .data.backup
sudo cp docker-compose.yaml docker-compose.yaml.backup
sudo cp .env .env.backup
```
* all-in-one
```bash
cd apitable # or any installation directory containing the .data
sudo cp -pr .data .data.backup
```

## update your local deployment manifest and start the new instance
* docker compose
```bash
cd apitable # or any installation directory containing the docker-compose.yaml/.env and .data
curl -fLo docker-compose.tar.gz 'https://github.com/apitable/apitable.github.io/releases/latest/download/docker-compose.tar.gz'
tar -xvzf docker-compose.tar.gz
# update the .env docker-compose.yaml if you make any customization
sudo docker compose pull # pull the image if you use the latest build
sudo docker compose up -d
```
* all-in-one
```
sudo docker pull apitable/apitable:latest # pull the latest image if you want to use the latest build
sudo docker run -d -v ${PWD}/.data:/apitable -p 80:80 --name apitable apitable/all-in-one:latest # you can replace the latest image tag with the one found in dockerhub
```

**Comment by networkhermit** [comment]
https://github.com/apitable/apitable/issues/414#issue-1590570317

**Comment by networkhermit** [comment]
https://github.com/apitable/apitable/issues/446

**Comment by waterxman** [comment]
“sudo docker-compose down -v --remove-orphans” ,Command execution error. Using root to execute Docker Compose can succeed

**Comment by peterng1618** [comment]
Hi @networkhermit, how do I update the local docker deployment after customizing some variables in `\packages\datasheet\.env`? Thanks!

**Comment by networkhermit** [comment]
@peterng1618 hi, if you modified the source code, I suggest you rebulid the image using `docker buildx bake web-server` and uncomment `IMAGE_PULL_POLICY=always` in .env.

**Comment by networkhermit** [comment]
Migrated to https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW#h-how-to-upgrade-to-the-newest-release-version

**Comment by lumos0** [comment]
> Migrated to https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW#h-how-to-upgrade-to-the-newest-release-version

![image](https://github.com/apitable/apitable/assets/30490759/e2bab10a-e57b-49a3-9edd-dfcd735e25e5)

**Comment by lumos0** [comment]
ps:
i tried but failed
see https://github.com/apitable/apitable/issues/1182
