### ISSUE TITLE
fix: 启动datasheet报错

### ISSUE THREAD

**Issue by meimosor** [apitable/apitable#351]
**Describe the bug**
其它服务都启动正常（包括后端服务），但是启动datasheet就报错，一直找不到components服务
启动命令是按照这个脚本执行的
![image](https://user-images.githubusercontent.com/31975932/218063119-7e123835-6617-4a54-9a54-525e19c502da.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/31975932/218062772-eab6404b-94c9-4506-8bea-bf8a24c97b95.png)

**Desktop (please complete the following information):**
 - OS: wsl ubuntu20.04
 - Browser chrome
 - Version v18.0.0-beta

**Comment by meimosor** [comment]
localhost:3000报错信息：
![image](https://user-images.githubusercontent.com/31975932/218063646-e3c132eb-618e-45fe-9f76-a7ceeaf41302.png)

**Comment by ChambersChan** [comment]
You may have missed installing a dependency. 
It is necessary to execute `make install` before start server.

Could be refer to the document. https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md

**Comment by meimosor** [comment]
> You may have missed installing a dependency. It is necessary to execute `make install` before start server.
> 
> Could be refer to the document. https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md

我在win10上用17.0.0 rc2 可以启动，但是18.0.0不行
