### ISSUE TITLE
fix: BUG...机器人配置后，无请求发送

### ISSUE THREAD

**Issue by masterkkkkkong** [apitable/apitable#352]
这是一个伟大的项目！感谢您对这个项目作出的杰出贡献！
机器人用于新增记录后，给钉钉发送消息提醒。
配置好机器人后，点击新增记录，F12查看网络请求，发现无任何请求发送，钉钉也未收到信息。
麻烦请排查是否是软件本身bug。
![image](https://user-images.githubusercontent.com/55868627/218064661-e9ad2f1e-3d3d-4fb7-95f3-c70e532b231b.png)

**Comment by pengjin123** [comment]
@masterkkkkkong 
1. Can see your send web request configuration information
2.Please open the robot operation history page to see the operation record

**Comment by Itou-Ng** [comment]
@masterkkkkkong It's successful to call lark robot webhook. You can check your dingtalk robot configuration.

**Comment by cchh2277** [comment]
@masterkkkkkong  大佬 钉钉消息通知成功了吗？
