### ISSUE TITLE
feat: Looking forward to open user system

### ISSUE THREAD

**Issue by sepbin** [apitable/apitable#363]
## Any questions?
目前用户注册、新增、修改密码等功能是没有开放的。我们的6人团队已经将正式数据应用于贵团队的产品，现在没法协作。想问一下多久能开放这些功能？？？我们是坚定的支持者~

**Comment by mr-kelly** [comment]
> ## Any questions?
> 目前用户注册、新增、修改密码等功能是没有开放的。我们的6人团队已经将正式数据应用于贵团队的产品，现在没法协作。想问一下多久能开放这些功能？？？我们是坚定的支持者~

Hi, we are going to fix this in the next sprint... 
Works to do.

**Comment by sepbin** [comment]
@mr-kelly thank you . my dearest

**Comment by lx233** [comment]
不是可以邀请加入吗？本地搭建也不能注册新用户么，我们也在调研这个

**Comment by TOT-JIN** [comment]
我本地部署过了不行，还没有注册页面，等正式版本发布吧，看他们的回复：
https://github.com/apitable/apitable/issues/195

**Comment by TOT-JIN** [comment]
> 不是可以邀请加入吗？本地搭建也不能注册新用户么，我们也在调研这个

我本地部署过了，不行，还没有注册页面，看他们的回复：
https://github.com/apitable/apitable/issues/195

另外，你们调研这个是因为飞书要收费了吗？

**Comment by lx233** [comment]
> > 不是可以邀请加入吗？本地搭建也不能注册新用户么，我们也在调研这个
> 
> 我本地部署过了，不行，还没有注册页面，看他们的回复： #195
> 
> 另外，你们调研这个是因为飞书要收费了吗？

嗯，确实没有注册页，不过手动在数据库里加一条用户数据的话可行吗？=v=
不全是因为飞书，主要是需要一些可扩展和自定义的功能

**Comment by nevertoday** [comment]
特意买了m2 芯片的电脑， 跑过来，居然不支持这个型号，厕所哭晕躺尸中！

**Comment by tw20510946** [comment]
邀请功能也行不通。

**Comment by TOT-JIN** [comment]
> > > 不是可以邀请加入吗？本地搭建也不能注册新用户么，我们也在调研这个
> > 
> > 
> > 我本地部署过了，不行，还没有注册页面，看他们的回复： #195
> > 另外，你们调研这个是因为飞书要收费了吗？
> 
> 嗯，确实没有注册页，不过手动在数据库里加一条用户数据的话可行吗？=v= 不全是因为飞书，主要是需要一些可扩展和自定义的功能

在数据库里加数据应该可行，毕竟admin用户也不是注册进去的，建议看看初始脚本吧，也许可以把一整个团队输进去。我还在等第一个正式版本，之前Readme.md里提到2月下旬会发布，但又被删除了，不知道会不会跳票。

**Comment by wq57wq57** [comment]
> 是需要一些可

数据库里面加记录，不知道密码是如何加密的

**Comment by arucil** [comment]
> > 是需要一些可
> 
> 数据库里面加记录，不知道密码是如何加密的

We use bcrypt to encrypt user passwords.

**Comment by lx233** [comment]
数据库里强行插入了几条看起来是登陆可以了，不过登陆成功后一直redirect到login页面，报找不到space 404。。
猜想是否 用户名校验能过，但是每个用户自己的数据空间啥的生成不了？

**Comment by lx233** [comment]
> > > > 不是可以邀请加入吗？本地搭建也不能注册新用户么，我们也在调研这个
> > > 
> > > 
> > > 我本地部署过了，不行，还没有注册页面，看他们的回复： #195
> > > 另外，你们调研这个是因为飞书要收费了吗？
> > 
> > 
> > 嗯，确实没有注册页，不过手动在数据库里加一条用户数据的话可行吗？=v= 不全是因为飞书，主要是需要一些可扩展和自定义的功能
> 
> 在数据库里加数据应该可行，毕竟admin用户也不是注册进去的，建议看看初始脚本吧，也许可以把一整个团队输进去。我还在等第一个正式版本，之前Readme.md里提到2月下旬会发布，但又被删除了，不知道会不会跳票。

我往数据库里强行插入了几条看起来是登陆可以了，不过登陆成功后一直redirect到login页面，报找不到space 404。。
猜想是否 用户名校验能过，但是每个用户自己的数据空间啥的生成不了？

**Comment by TOT-JIN** [comment]
> 

研究一下部署阶段的初始化操作，比如 https://github.com/apitable/apitable/tree/develop/init-db

**Comment by TOT-JIN** [comment]
> > > > > 不是可以邀请加入吗？本地搭建也不能注册新用户么，我们也在调研这个
> > > > 
> > > > 
> > > > 我本地部署过了，不行，还没有注册页面，看他们的回复： #195
> > > > 另外，你们调研这个是因为飞书要收费了吗？
> > > 
> > > 
> > > 嗯，确实没有注册页，不过手动在数据库里加一条用户数据的话可行吗？=v= 不全是因为飞书，主要是需要一些可扩展和自定义的功能
> > 
> > 
> > 在数据库里加数据应该可行，毕竟admin用户也不是注册进去的，建议看看初始脚本吧，也许可以把一整个团队输进去。我还在等第一个正式版本，之前Readme.md里提到2月下旬会发布，但又被删除了，不知道会不会跳票。
> 
> 我往数据库里强行插入了几条看起来是登陆可以了，不过登陆成功后一直redirect到login页面，报找不到space 404。。 猜想是否 用户名校验能过，但是每个用户自己的数据空间啥的生成不了？

研究一下部署阶段的初始化操作，比如 https://github.com/apitable/apitable/tree/develop/init-db

**Comment by frogsinging** [comment]
同样问题，期待第一个正式版

**Comment by wq57wq57** [comment]
> eadme.md里提

数据库里密码没办法加

**Comment by ChambersChan** [comment]
Hello. The user system has been release in [the latest version](https://github.com/apitable/apitable/releases/tag/v0.18.0-rc.1). 
I close this issue first.
If you encounter any problems, could feel free to contact us through github or [discord](https://discord.gg/5WrDWxkXE9).

**Comment by nevertoday** [comment]
原谅我， 没有看懂英语， 是不是版本可以了？
