### ISSUE TITLE
文件上传提示:Failed to load response data: No data found for resource with given identifier

### ISSUE THREAD

**Issue by baby1000001000** [apitable/apitable#366]
你好~我私有化部署后文件上传提示:Failed to load response data: No data found for resource with given identifier
执行私有化部署的脚本是:curl https://apitable.github.io/install.sh | bash

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/49216870/218423492-380d7c71-5991-407a-b888-770a8f870a9f.png">

问题已解决:  IP方式文件上传可能会有问题,换成域名后恢复正常.其有websocket,如果用nginx转发的,需要配置好

**Comment by ChambersChan** [comment]
Could I have a look at the full connection request?

**Comment by baby1000001000** [comment]
> 

很不好意思,我用ip体验的,上了域名之后文件上传及查看都OK的

**Comment by ChambersChan** [comment]
ok. I close this issue first.
If you encounter any problems, could feel free to contact us through github or [discord](https://discord.com/channels/1016320471010115666/1016320471769296937).
