### ISSUE TITLE
fix: Error querying database during login.

### ISSUE THREAD

**Issue by Yqccc** [apitable/apitable#376]
**Describe the bug**
Error querying database during login.

**To Reproduce**
1. sudo make dataenv
2. make install
3. make run -> 1
4. At the new terminal，make run -> 2
5. At the new terminal，make run -> 3
6. Open the login page, and then enter the account and password. Click Enter.

**Expected behavior**
Login succeeded.

**Screenshots**
<img width="957" alt="企业微信截图_1676432603560" src="https://user-images.githubusercontent.com/54765789/218923566-4b7b843b-6e87-4034-a400-d994c6acc1c9.png">

**Desktop**
 - OS: Windows10 Professional  -> virtual machine WSL2 -> Ubuntu 18.04.6 LTS
 - Browser: Chrome

**Comment by Yqccc** [comment]
I used username admin@apitable.com and password Apitable2022.

**Comment by Yqccc** [comment]
I used username admin@apitable.com and password Apitable2022.

**Comment by ChambersChan** [comment]
This may be that init-db failed to run when execute `make dataenv`.

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
