### ISSUE TITLE
question: Can you provide source code for JS files on your minio file server?

### ISSUE THREAD

**Issue by meimosor** [apitable/apitable#381]
## Any questions?
Can you provide source code for JS files on your minio file server?like these:
![image](https://user-images.githubusercontent.com/31975932/218989427-71d55088-df69-4c82-b513-af3c12eac02b.png)
Where can I see the source code of this JS? I don't want to use compressed JS
![image](https://user-images.githubusercontent.com/31975932/218990045-cde73393-6e76-42a8-8c6c-b51cbb43ee91.png)

**Comment by ChambersChan** [comment]
You probably want to know the source code about the widget.
There can be found in [apitable repository](https://github.com/orgs/apitable/repositories).

**Comment by meimosor** [comment]
> You probably want to know the source code about the widget. There can be found in [apitable repository](https://github.com/orgs/apitable/repositories).

oh yeah, very ths!
