### ISSUE TITLE
question: Question about maximum records per datasheet

### ISSUE THREAD

**Issue by VXenomac** [apitable/apitable#383]
Description:

Hi there,

I was looking at the [documentation](https://apitable.com/pricing/) for your product and noticed that the maximum number of records per datasheet is currently set to 50,000. I was wondering what the reason is for this limit and if there are any plans to support more records in the future?

Thank you!

**Comment by Alex-hufeng** [comment]
hello~ "50 000 rows max" is our suggestion to ensure smooth operation.You can modify the code to remove the restrictions.

By the way, We continue to improve our performance, and this limit will be gradually increased in the future.
