### ISSUE TITLE
feat: support for changing passwords and a sign-up page

### ISSUE THREAD

**Issue by Liamzai** [apitable/apitable#398]
## What?

Email registration, password changes, password resets, email invitations to join the space, and invitation links are all options available to users.

## How?

- Support registration by email
- Support to change password
- Support reset password
- Support to invite others to join the Space by email
- Support inviting others to join the Space by invitation link

**Comment by vinyll** [comment]
password relates to #238 #385 #222 -> fixed
Inviting users relates to #195

**Comment by Liamzai** [comment]
Based on version v0.18.0-rc.1, the features of registering, inviting users, and changing passwords are ready.
