### ISSUE TITLE
fix: all-in-one version, after click the dashboard, it crash.

### ISSUE THREAD

**Issue by zhangfugui727** [apitable/apitable#405]
**Describe the bug**
使用官方推荐的命令进行all-in-one安装，安装完成后，选择模板应用，点击仪表盘系统报错

**Desktop (please complete the following information):**

**To Reproduce**
1. 使用推荐命令安装，安装前已删除apitable目录和所有数据（包含镜像），
`curl https://apitable.github.io/install.sh | bash`
3. 登录并创建空间
4. 选择任意模板应用
5. 点击仪表盘，即可重现错误，但是重现刷新页面，路由能重现正常，但无数据
![image](https://user-images.githubusercontent.com/30425581/219556282-5905f802-3da2-4d3f-b542-29fbea73b7ca.png)
![image](https://user-images.githubusercontent.com/30425581/219556368-fa1ee688-0cb2-442d-bf1c-3b0fcb7ee9b0.png)
![image](https://user-images.githubusercontent.com/30425581/219556414-5cc1867d-5b38-47a0-a496-be6442b99f6f.png)
在无数据页面点击其他table，页面直接会报错，重新刷新，路由正常
![image](https://user-images.githubusercontent.com/30425581/219556486-03f6cb41-5449-4ecd-935f-a08bdc49f606.png)
![image](https://user-images.githubusercontent.com/30425581/219556616-46d986e8-da25-4bd4-b6f3-98d8280120ad.png)

**Expected behavior**
页面能正常打开

**Comment by sepbin** [comment]
> **Describe the bug** 使用官方推荐的命令进行all-in-one安装，安装完成后，选择模板应用，点击仪表盘系统报错
> 
> **Desktop (please complete the following information):**
> 
> **To Reproduce**
> 
> 1. 使用推荐命令安装，安装前已删除apitable目录和所有数据（包含镜像），
>    `curl https://apitable.github.io/install.sh | bash`
> 2. 登录并创建空间
> 3. 选择任意模板应用
> 4. 点击仪表盘，即可重现错误，但是重现刷新页面，路由能重现正常，但无数据
>    ![image](https://user-images.githubusercontent.com/30425581/219556282-5905f802-3da2-4d3f-b542-29fbea73b7ca.png)
>    ![image](https://user-images.githubusercontent.com/30425581/219556368-fa1ee688-0cb2-442d-bf1c-3b0fcb7ee9b0.png)
>    ![image](https://user-images.githubusercontent.com/30425581/219556414-5cc1867d-5b38-47a0-a496-be6442b99f6f.png)
>    在无数据页面点击其他table，页面直接会报错，重新刷新，路由正常
>    ![image](https://user-images.githubusercontent.com/30425581/219556486-03f6cb41-5449-4ecd-935f-a08bdc49f606.png)
>    ![image](https://user-images.githubusercontent.com/30425581/219556616-46d986e8-da25-4bd4-b6f3-98d8280120ad.png)
> 
> **Expected behavior** 页面能正常打开

不要用localhost，用ip或域名，就行了

**Comment by sepbin** [comment]
不要用localhost，用ip或域名，就行了

**Comment by zhangfugui727** [comment]
> 不要用localhost，用ip或域名，就行了

也不行，依然有问题，重新安装的

https://user-images.githubusercontent.com/30425581/219620441-228f8614-653f-4925-a490-a5fcb15c23c1.mp4

**Comment by networkhermit** [comment]
`curl https://apitable.github.io/install.sh | bash` is for docker-compose, not the all-in-one method. BTW, do you have both the docker-compose version and all-in-one version? Does this bug only exist in all-in-one?

**Comment by zhangfugui727** [comment]
> `curl https://apitable.github.io/install.sh | bash` is for docker-compose, not the all-in-one method. BTW, do you have both the docker-compose version and all-in-one version? Does this bug only exist in all-in-one?

Docker compose mode

**Comment by zhangfugui727** [comment]
@networkhermit 
This version does not have this error
```
IMAGE_PULL_POLICY=always
IMAGE_REGISTRY=docker.io

IMAGE_BACKEND_SERVER=apitable/backend-server:v0.18.0-alpha_873
IMAGE_GATEWAY=apitable/openresty:v0.18.0-alpha_873
IMAGE_INIT_DB=apitable/init-db:v0.18.0-alpha_873
IMAGE_ROOM_SERVER=apitable/room-server:v0.18.0-alpha_873
IMAGE_WEB_SERVER=apitable/web-server:v0.18.0-alpha_873

IMAGE_IMAGEPROXY_SERVER=apitable/imageproxy-server:latest
IMAGE_INIT_APPDATA=apitable/init-appdata:v0.18.0-alpha_build51

IMAGE_MINIO=minio/minio:RELEASE.2023-01-25T00-19-54Z
IMAGE_MYSQL=mysql:8.0.32
IMAGE_RABBITMQ=rabbitmq:3.11.7-management
IMAGE_REDIS=redis:7.0.8
```

**Comment by networkhermit** [comment]
@zhangfugui727 Do you mean v0.18.0-alpha_873 is ok but some newer version crashed? If the newer version still have the bug you described, please tell us the specific version. If you are using Chrome/Firefox, you can get the full semver info from the first few lines of Console output.

**Comment by JaneSu** [comment]
@zhangfugui727 We are currently working on this issue and will provide updates as soon as possible. Thank you for your patience and stay tuned!

**Comment by zhangfugui727** [comment]
> @zhangfugui727 Do you mean v0.18.0-alpha_873 is ok but some newer version crashed? If the newer version still have the bug you described, please tell us the specific version. If you are using Chrome/Firefox, you can get the full semver info from the first few lines of Console output.

Chrome version： 110.0.5481.104（正式版本） （64 位）
Docker images：No tag, it should be the latest version（I just pulled everything）
```
apitable/backend-server v0.18.0-alpha_912
apitable/web-server v0.18.0-alpha_912
```
Here are the image pull time and system time
![image](https://user-images.githubusercontent.com/30425581/220087902-09f9e3c1-7bcc-4999-b38a-9da4c049f9a7.png)

BUG log：
![image](https://user-images.githubusercontent.com/30425581/220089473-7d7d5479-9fee-40ed-a249-cf78f574b22f.png)
![image](https://user-images.githubusercontent.com/30425581/220089584-29ee3514-0d45-4a0d-a00b-4d80aa80c5d7.png)
![image](https://user-images.githubusercontent.com/30425581/220089675-22bf9e1c-44be-4d26-97b9-bb2c965bab98.png)
![image](https://user-images.githubusercontent.com/30425581/220089745-d6e27bbb-4949-4a47-aa38-4e57eea91671.png)

thanks！

**Comment by zhangfugui727** [comment]
> 

That's OK. Thank you very much!

**Comment by zhangfugui727** [comment]
> @zhangfugui727 We are currently working on this issue and will provide updates as soon as possible. Thank you for your patience and stay tuned!

That's OK. Thank you very much!

**Comment by JaneSu** [comment]
This issue has been resolved, please update your code.
