### ISSUE TITLE
question: Q&A... Change Primary/Unique Field

### ISSUE THREAD

**Issue by o-data** [apitable/apitable#406]
## Any questions?
API Table automatic choose my "Unique"/Primary field. How do I change to a different one field to be the unique one.

Can't hide or move these field because it is Unique. Currently it seem to be on the 1st column/Column A by default?

Thank you.
![image](https://user-images.githubusercontent.com/67723461/219590516-05382b81-9777-417f-b208-0bb68b2aee07.png)

**Comment by mr-kelly** [comment]
> ## Any questions?
> API Table automatic choose my "Unique"/Primary field. How do I change to a different one field to be the unique one.
> 
> Can't hide or move these field because it is Unique. Currently it seem to be on the 1st column/Column A by default?
> 
> Thank you. ![image](https://user-images.githubusercontent.com/67723461/219590516-05382b81-9777-417f-b208-0bb68b2aee07.png)

Yes it is. Primary key is the first column.
You can change this column's type but you cannot switch it.

**Comment by o-data** [comment]
So I have to export data, re-arrange the first column offline and import it again to have new Primary Field?

Thank you.

**Comment by mr-kelly** [comment]
> So I have to export data, re-arrange the first column offline and import it again to have new Primary Field?
> 
> Thank you.

![20230220-141703](https://user-images.githubusercontent.com/520852/220026032-b496f7ee-39a3-4a87-885c-79a74080567e.gif)

See the GIF above. @o-data 

You can:
1. Copy & paste the whole column
2. Change the Primary Field's  type

**Comment by o-data** [comment]
Thank you! Never consider we can just copy/paste over it.
