### ISSUE TITLE
question: How to upgrade to a new version of apitable

### ISSUE THREAD

**Issue by VXenomac** [apitable/apitable#414]
Hi there,

I noticed that a new version of apitable is going to be released soon. I have already deployed an older version of apitable and would like to know how I can upgrade to the new version? Will the upgrade process have any impact on the current data that I have stored in my apitable instance?

Thanks!

**Comment by arucil** [comment]
We've add a section about this problem in [Troubleshooting](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW#h-how-to-upgrade-to-the-newest-release-version).
