### ISSUE TITLE
question: What do you mean by "As an IdP provider" in the roadmap?

### ISSUE THREAD

**Issue by HamedMP** [apitable/apitable#423]
Hi,

Thanks for the great library, you are up to great stuff.

Quick question on what does it mean for APITable to be an identity provider as it's mentioned in the Readme? 

> # Future Features
> ...
> As an IdP
> ...

**Comment by mr-kelly** [comment]
> Hi,
> 
> Thanks for the great library, you are up to great stuff.
> 
> Quick question on what does it mean for APITable to be an identity provider as it's mentioned in the Readme?
> 
> > # Future Features
> > ...
> > As an IdP
> > ...

@HamedMP We use APITable as our team roster and connect HRM / LDAP with this roster data. 

Since our widget system is not ready yet, work on this feature's transition would not be urgent.

We are going to publish the updated product roadmap soon.

**Comment by HamedMP** [comment]
Amazing, thanks for the clear explanation.
