### ISSUE TITLE
fix: ERROR [TypeOrmModule] Unable to connect to the database

### ISSUE THREAD

**Issue by ziqiangai** [apitable/apitable#424]
**Describe the bug**
When I started room-server in the local development environment（not in docker）, the following error was reported.
```shell
[Nest] 17720  - 2023/02/21 05:18:03   ERROR [TypeOrmModule] Unable to connect to the database. Message: Access denied for user 'apitable'@'172.18.0.1' (using password: YES). Retrying (1)...
Error: Access denied for user 'apitable'@'172.18.0.1' (using password: YES)
    at Packet.asError (C:\code\github\apitable\node_modules\mysql2\lib\packets\packet.js:728:17)
    at ClientHandshake.execute (C:\code\github\apitable\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\code\github\apitable\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (C:\code\github\apitable\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (C:\code\github\apitable\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\code\github\apitable\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead [as _originalOnread] (node:internal/stream_base_commons:190:23)
    at TCP.<anonymous> (C:\code\github\apitable\node_modules\async-listener\glue.js:188:31)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)

```
Of course, we want to know how the IP address `172.18.0.1` came from？

if we run the command `docker network ls`
```shell
C:\Users\lenovo>docker network ls
NETWORK ID     NAME                       DRIVER    SCOPE
fae02bbabc48   apitable-devenv_apitable   bridge    local
1a9f876a55a3   bridge                     bridge    local
5d77b6f11ed2   host                       host      local
11fcb207835e   none                       null      local
```

then, I run the command `docker network inspect fae02bbabc48`, the result is:
```json
[
    {
        "Name": "apitable-devenv_apitable",
        "Id": "fae02bbabc481257fe574cbe9ad5218981d0e8af75e2810efedc91689afb14e4",
        "Created": "2023-02-20T10:17:17.013198412Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "087d6cd4c6d7b07317768191f0aa0e6db48e5aeecbf67e32b9de52dd4cf8afe0": {
                "Name": "apitable-devenv-rabbitmq-1",
                "EndpointID": "e4f839b3a276cbda1415e3de323ff613c7f01ecd8cd3429be52824aed5902451",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "435cf2ebd633fcc6418befb3145b8fd8f5031f86cf3fad8a2cbe3aa3f01f406e": {
                "Name": "apitable-devenv-minio-1",
                "EndpointID": "16b1800ae00af335fcfff20af67fd994d9875d0a184d7e32c866adbcf6f8b383",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "cb47b8e5d41a96c2905f0801e08aea42433bb4d31f301410d194e8fb57601a81": {
                "Name": "apitable-devenv-mysql-1",
                "EndpointID": "297ef236df87827605fdca7c5e2b4292b62c9f36f3708e5f888fc3d8089f05b6",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "f3dce517112c3e2e14a9e610d1261b14aafbfd6a277d7f83053710572ba8339e": {
                "Name": "apitable-devenv-redis-1",
                "EndpointID": "f7c8864d1f1a001d501349972803f74d434385ebbb74b852674109c1d5dbbc08",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "apitable",
            "com.docker.compose.project": "apitable-devenv",
            "com.docker.compose.version": "2.15.1"
        }
    }
]
```
we can see the `Gateway` field is the ip.

**This is the case of the `apitable-devenv` container in docker-desktop are running.**
 
If I stop the `apitable-devenv` container. The Command `docker network inspect fae02bbabc48` will display the json:

```json
[
    {
        "Name": "apitable-devenv_apitable",
        "Id": "fae02bbabc481257fe574cbe9ad5218981d0e8af75e2810efedc91689afb14e4",
        "Created": "2023-02-20T10:17:17.013198412Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "apitable",
            "com.docker.compose.project": "apitable-devenv",
            "com.docker.compose.version": "2.15.1"
        }
    }
]
```

And If I restart the `room-server`, the result will be:

```shell
[Nest] 10796  - 2023/02/21 05:38:37   ERROR [TypeOrmModule] Unable to connect to the database. Message: connect ECONNREFUSED 127.0.0.1:3306. Retrying (2)...
Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)

```

Now the `TypeOrmModule`'s host param is what we expected.

I don't know  why that will happen.I have take 5 hours to find the reason.

I haven't seen any code with such logic.

And in the windows dev envirment, run the `docker-compose.devenv.yaml`  in docker  extremely slow.

**To Reproduce**
1. run git clone command in windows
2. flow the development guide
3. file `.env.defaults` add config `MYSQL_USERNAME=root`
4. file `redis.config.service.ts`  line 26 add default redis password like `password: process.env.REDIS_PASSWORD || 'apitable@com',`
5. run command `yarn run start:room-server`

**Expected behavior**
successfully start

**Desktop:**
 - OS: win11
 - Version 0.18

**Comment by ziqiangai** [comment]
Connect mysql twice，Please teach me.

**Comment by yort-feng** [comment]
Sorry for confusing you, the reason is the default `MYSQL_USERNAME` is incorrect in the default settings, it should be `root` and we'll correct it soon.

We recommend you create a `.env.devlopment.local`  file under the `/room-server/env` folder to fix it as a temporary solution.

```.yaml
# MySQL configuration
MYSQL_USERNAME=root

# Redis configuration
REDIS_PASSWORD=apitable@com
```

**Comment by ziqiangai** [comment]
I have changed the relevant configurations. The key is that I don't understand why mysql2 is connected mysql://172.18.0.1.


The IP address&nbsp; 172.18.0.1 has not appeared in the configuration file. It is the address of the docker container.




---Original---
From: ***@***.***&gt;
Date: Tue, Feb 21, 2023 11:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apitable/apitable] fix: ERROR [TypeOrmModule] Unable to connectto the database (Issue #424)




 
Sorry for confusing you, the reason is the default MYSQL_USERNAME is incorrect for the default settings, it should be root and we'll correct it soon.
 
We recommend you create a .env.devlopment.local  file under the /room-server/env folder to fix it as a temporary solution.
 # MySQL configuration MYSQL_USERNAME=root # Redis configuration ***@***.***

**Comment by yort-feng** [comment]
> I have changed the relevant configurations. The key is that I don't understand why mysql2 is connected mysql://172.18.0.1. The IP address&nbsp; 172.18.0.1 has not appeared in the configuration file. It is the address of the docker container.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, Feb 21, 2023 11:57 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [apitable/apitable] fix: ERROR [TypeOrmModule] Unable to connectto the database (Issue #424) Sorry for confusing you, the reason is the default MYSQL_USERNAME is incorrect for the default settings, it should be root and we'll correct it soon. We recommend you create a .env.devlopment.local file under the /room-server/env folder to fix it as a temporary solution. # MySQL configuration MYSQL_USERNAME=root # Redis configuration ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Yes, it is. You could get more information from [Docker Container Networking](https://docs.docker.com/config/containers/container-networking/).

BTW, does it work after changing the configurations?

**Comment by ziqiangai** [comment]
It's interesting. I'll try it again.&nbsp;


About the configuration problem, can I sort out and submit pr




---Original---
From: ***@***.***&gt;
Date: Tue, Feb 21, 2023 14:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apitable/apitable] fix: ERROR [TypeOrmModule] Unable to connectto the database (Issue #424)




  
I have changed the relevant configurations. The key is that I don't understand why mysql2 is connected mysql://172.18.0.1. The IP address&nbsp; 172.18.0.1 has not appeared in the configuration file. It is the address of the docker container.
 …
 ---Original--- From: @.&gt; Date: Tue, Feb 21, 2023 11:57 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [apitable/apitable] fix: ERROR [TypeOrmModule] Unable to connectto the database (Issue #424) Sorry for confusing you, the reason is the default MYSQL_USERNAME is incorrect for the default settings, it should be root and we'll correct it soon. We recommend you create a .env.devlopment.local file under the /room-server/env folder to fix it as a temporary solution. # MySQL configuration MYSQL_USERNAME=root # Redis configuration @.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Yes, it is. You could get more information from Docker Container Networking.
 
BTW, does it work after changing the configurations?

**Comment by yort-feng** [comment]
Sure! But maybe next time, there is a PR about fixing this issue already.

**Comment by ziqiangai** [comment]
![image](https://user-images.githubusercontent.com/18455767/220326380-91853aab-c2d5-4cbb-91e9-c74746450b7d.png)
I intentionally connected to the database with the wrong username on the database client and got the prompt statement in the program. It was really the database connection problem. This ip `172.18.0.1` misled me.

**Comment by ziqiangai** [comment]
About, I found that there are two main problems
1. The default configuration parameters loaded and filled during system startup are inconsistent with the parameters defined in the `.env` file during system initialization.
2. Some mysql database names are written as database for unit test
