### ISSUE TITLE
fix: BUG：点击小程序按钮卡死。

### ISSUE THREAD

**Issue by fangjiyuan** [apitable/apitable#425]
当我创建一个表格后，点击小程序，程序会直接卡死。

**Comment by ziqiangai** [comment]
> 当我创建一个表格后，点击小程序，程序会直接卡死。

我测试了一下，点击小程序会弹出这个界面，到这里是没有卡死的
![image](https://user-images.githubusercontent.com/18455767/220630762-b74e71e9-eb05-4be4-9b01-2fce53e67bcd.png)
但是点击添加小程序会报错
![image](https://user-images.githubusercontent.com/18455767/220630334-4dc6d446-2d55-4264-9481-12420b105f8b.png)
应该是有些依赖没有build导致加载小程序插件出现了错误

===========
你和我的复现结果一样吗？

**Comment by sepbin** [comment]
退回 0.18-alpha。。。新发布的这个版本全是崩溃

**Comment by fangjiyuan** [comment]
> > 当我创建一个表格后，点击小程序，程序会直接卡死。
> 
> 我测试了一下，点击小程序会弹出这个界面，到这里是没有卡死的 ![image](https://user-images.githubusercontent.com/18455767/220630762-b74e71e9-eb05-4be4-9b01-2fce53e67bcd.png) 但是点击添加小程序会报错 ![image](https://user-images.githubusercontent.com/18455767/220630334-4dc6d446-2d55-4264-9481-12420b105f8b.png) 应该是有些依赖没有build导致加载小程序插件出现了错误
> 
> =========== 你和我的复现结果一样吗？

我是一点就死机，还没有到第二步。

**Comment by mr-kelly** [comment]
Hi. @fangjiyuan 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

1. Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...), better to take a screenshot or write more detail.
2. Describe your problem in English (Translation is OK).


Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
