### ISSUE TITLE
question: How to start web socket / Can not edit value row

### ISSUE THREAD

**Issue by khaphanspace** [apitable/apitable#430]
Hi there,

I install apitable using docker compose on Ubuntu server with the command below

```
curl https://apitable.github.io/install.sh | bash
```

Docker Container

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/16458012/220425943-6d16c7f0-5b6f-4f24-b290-9951a41451cf.png">

APITable can not edit row with error about WebSocket

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/16458012/220426715-9387a4e2-7546-4a7e-a26f-be030a93cd87.png">

Please help me, how to start web socket or I miss somethings?
Thanks!

**Comment by networkhermit** [comment]
@nhatkha1407 hi, thanks for the issue report. It is a comfirmed bug we'are currently working on.

**Comment by Pengap** [comment]
Try using our latest version and see if you still have problems?

Try again directly with `curl https://apitable.github.io/install.sh | bash`

Please clean up your local environment first if you can

**Comment by khaphanspace** [comment]
@Pengap Thank you for your response. I clean up all data & install it again but stills have problems.

**Comment by khaphanspace** [comment]
@networkhermit @Pengap Sorry for any inconvenience, can I ask this issue can be fix in next week?

**Comment by networkhermit** [comment]
@nhatkha1407 Sorry I made a mistake. It is not a comfirmed bug as I previously answered. Did you access the url behind a proxy or something? We can't reproduce the issue using `curl https://apitable.github.io/install.sh | bash`.
