### ISSUE TITLE
Unknown column 'time_zone' in 'field list'

### ISSUE THREAD

**Issue by vinyll** [apitable/apitable#431]
When installing a new instance on a new server using `docker compose up`, then attempting to log in with the default account, the following error occurs:
```
apitable-backend-server-1     | org.springframework.jdbc.BadSqlGrammarException: 
apitable-backend-server-1     | ### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'time_zone' in 'field list'
apitable-backend-server-1     | ### The error may exist in com/apitable/user/mapper/UserMapper.java (best guess)
apitable-backend-server-1     | ### The error may involve defaultParameterMap
apitable-backend-server-1     | ### The error occurred while setting parameters
apitable-backend-server-1     | ### SQL: SELECT id,uuid,nick_name,code,mobile_phone,email,password,avatar,color,time_zone,gender,remark,locale,ding_open_id,ding_union_id,last_login_time,is_social_name_modified,is_paused,is_deleted,created_at,updated_at FROM apitable_user WHERE id=?  AND is_deleted=0
apitable-backend-server-1     | ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'time_zone' in 'field list'
apitable-backend-server-1     | ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'time_zone' in 'field list'
apitable-backend-server-1     |         at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
apitable-backend-server-1     |         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
apitable-backend-server-1     |         at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
apitable-backend-server-1     |         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
apitable-backend-server-1     |         at com.sun.proxy.$Proxy169.selectOne(Unknown Source)
apitable-backend-server-1     |         at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160)
apitable-backend-server-1     |         at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
apitable-backend-server-1     |         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
apitable-backend-server-1     |         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
apitable-backend-server-1     |         at com.sun.proxy.$Proxy174.selectById(Unknown Source)
apitable-backend-server-1     |         at com.apitable.shared.cache.service.impl.LoginUserCacheInRedisServiceImpl.getLoginUser(LoginUserCacheInRedisServiceImpl.java:77)
apitable-backend-server-1     |         at com.apitable.shared.context.LoginContext.getLoginUser(LoginContext.java:78)
apitable-backend-server-1     |         at com.apitable.user.service.impl.UserServiceImpl.getCurrentUserInfo(UserServiceImpl.java:724)
apitable-backend-server-1     |         at com.apitable.user.service.impl.UserServiceImpl$$FastClassBySpringCGLIB$$99a4b7ab.invoke(<generated>)
```

**Comment by ChambersChan** [comment]
This may be that init-db failed to run.

**Comment by ziqiangai** [comment]
> When installing a new instance on a new server using `docker compose up`, then attempting to log in with the default account, the following error occurs:
> 
> ```
> apitable-backend-server-1     | org.springframework.jdbc.BadSqlGrammarException: 
> apitable-backend-server-1     | ### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'time_zone' in 'field list'
> apitable-backend-server-1     | ### The error may exist in com/apitable/user/mapper/UserMapper.java (best guess)
> apitable-backend-server-1     | ### The error may involve defaultParameterMap
> apitable-backend-server-1     | ### The error occurred while setting parameters
> apitable-backend-server-1     | ### SQL: SELECT id,uuid,nick_name,code,mobile_phone,email,password,avatar,color,time_zone,gender,remark,locale,ding_open_id,ding_union_id,last_login_time,is_social_name_modified,is_paused,is_deleted,created_at,updated_at FROM apitable_user WHERE id=?  AND is_deleted=0
> apitable-backend-server-1     | ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'time_zone' in 'field list'
> apitable-backend-server-1     | ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'time_zone' in 'field list'
> apitable-backend-server-1     |         at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
> apitable-backend-server-1     |         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
> apitable-backend-server-1     |         at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
> apitable-backend-server-1     |         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
> apitable-backend-server-1     |         at com.sun.proxy.$Proxy169.selectOne(Unknown Source)
> apitable-backend-server-1     |         at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160)
> apitable-backend-server-1     |         at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
> apitable-backend-server-1     |         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
> apitable-backend-server-1     |         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
> apitable-backend-server-1     |         at com.sun.proxy.$Proxy174.selectById(Unknown Source)
> apitable-backend-server-1     |         at com.apitable.shared.cache.service.impl.LoginUserCacheInRedisServiceImpl.getLoginUser(LoginUserCacheInRedisServiceImpl.java:77)
> apitable-backend-server-1     |         at com.apitable.shared.context.LoginContext.getLoginUser(LoginContext.java:78)
> apitable-backend-server-1     |         at com.apitable.user.service.impl.UserServiceImpl.getCurrentUserInfo(UserServiceImpl.java:724)
> apitable-backend-server-1     |         at com.apitable.user.service.impl.UserServiceImpl$$FastClassBySpringCGLIB$$99a4b7ab.invoke(<generated>)
> ```

This field was added at `2020-02-14` and the code in the https://github.com/apitable/apitable/blob/c95f6daae6eb69a962a3a66359026f963425a859/init-db/src/main/resources/db/changelog/0.18/20230210_changeset.xml#L28-L29

If your db init time before than 2020-02-14, This problem may happen, I suggest you try to reinitialize the database.

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still encounter it, u could reopen this issue.
