### ISSUE TITLE
密码问题还是没有解决

### ISSUE THREAD

**Issue by wq57wq57** [apitable/apitable#437]
I have an idea for this project.

**Comment by wq57wq57** [comment]
登录账号admin 需要验证码才能更改密码

**Comment by ziqiangai** [comment]
> 登录账号admin 需要验证码才能更改密码

开发者环境还是gitpod的环境，经过我的测试，使用readme中的写的账号密码可以登录：

账号：admin@apitable.com
密码：Apitable2022

**Comment by mr-kelly** [comment]
Hi. @wq57wq57 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

1. Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
2. Describe your problem in English (Translation is OK).

Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
