### ISSUE TITLE
question: Q&A...

### ISSUE THREAD

**Issue by wzzzzzz1111** [apitable/apitable#442]
## Any questions?图片上传不上去  是什么问题呢  空间站1.9gb就无法上传了
![5F532C85-B2AE-413C-8FB5-7953889286F4](https://user-images.githubusercontent.com/125652293/220647871-22b965c8-48e3-4446-b587-760e474961f3.png)

**Comment by wzzzzzz1111** [comment]
上传一会就提示网络状态异常

**Comment by ziqiangai** [comment]
空间用完了，不知道你用的什么环境的系统竟然送了你 0.9 g的空间。
你可以把已经用的资源给他刷掉。

先执行sql:
```sql
update apitable_asset set file_size = 0 where 1=1;
```
然后清掉redis的缓存。缓存的key是`statics:space:capacity:spaceId`

为什么会提示网络状态异常呢？应该是前端统一的处理，代码位于：
https://github.com/apitable/apitable/blob/c95f6daae6eb69a962a3a66359026f963425a859/packages/datasheet/src/pc/hooks/use_network.ts#L70-L74
上传文件时需要先申请一块oss对象空间，然后上传文件，文件上传完成后再把文件和表格嵌入到一起。
这一块儿的逻辑可能触发了上面的代码。

**Comment by ziqiangai** [comment]
> 空间用完了，不知道你用的什么环境的系统竟然送了你 0.9 g的空间。 你可以把已经用的资源给他刷掉。
> 
> 先执行sql:
> 
> ```sql
> update apitable_asset set file_size = 0 where 1=1;
> ```
> 
> 然后清掉redis的缓存。缓存的key是`statics:space:capacity:spaceId`
> 
> 为什么会提示网络状态异常呢？应该是前端统一的处理，代码位于：
> 
> https://github.com/apitable/apitable/blob/c95f6daae6eb69a962a3a66359026f963425a859/packages/datasheet/src/pc/hooks/use_network.ts#L70-L74
> 
> 
> 上传文件时需要先申请一块oss对象空间，然后上传文件，文件上传完成后再把文件和表格嵌入到一起。
> 这一块儿的逻辑可能触发了上面的代码。

好像没有使用本地开发版本，所以刷不了sql，所以这个地方应该作为一个优化项目提示用户扩容。

**Comment by mr-kelly** [comment]
Hi. @wzzzzzz1111 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

1. Write a title.
2. Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...), better to take a screenshot or write more detail.
3. Describe your problem in English (Translation is OK).


Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
