### ISSUE TITLE
question: edit same table cell by multi persons at the same time

### ISSUE THREAD

**Issue by 1330101170** [apitable/apitable#480]
时间一，两个人同时修改一个单元格
时间二，A提交修改，单元格内容  这是1
时间三，B提交修改，单元格内容  这是 2
A发现自己提交的内容被替换成 这是2，自己输入的不见了

**Comment by ziqiangai** [comment]
应该是A提交的内容被B提交的内容覆盖掉了，右击单元格，点击 `Expand record`

![image](https://user-images.githubusercontent.com/18455767/221808697-8151f8ef-8c01-41df-b356-96074361421d.png)

然后在弹窗里，点击这个上面的图标，可以看到单元格内容的变更记录:

![image](https://user-images.githubusercontent.com/18455767/221808278-034d39a9-4212-4750-8184-83a45afc55c8.png)

应该能找到A提交的内容吧。

**Comment by 1330101170** [comment]
> 应该是A提交的内容被B提交的内容覆盖掉了，右击单元格，点击 `Expand record`
> 
> ![image](https://user-images.githubusercontent.com/18455767/221808697-8151f8ef-8c01-41df-b356-96074361421d.png)
> 
> 然后在弹窗里，点击这个上面的图标，可以看到单元格内容的变更记录:
> 
> ![image](https://user-images.githubusercontent.com/18455767/221808278-034d39a9-4212-4750-8184-83a45afc55c8.png)
> 
> 应该能找到A提交的内容吧。

嗯嗯，他不能多人实时编辑一个单元格，他这个只是一个update操作
![image](https://user-images.githubusercontent.com/75105643/221810206-7e3e5e2c-e14c-41f5-925b-4e6ed1397eff.png)

**Comment by ziqiangai** [comment]
您期望的是，把两个人输入到单元格的内容做简单的合并，然后同步给他们吗？

这样会让内容更加凌乱。

**Comment by 1330101170** [comment]
> 

不是，如果一个dataSheet可以多人同时编辑多个单元格不冲突；也可以同时编辑一个单元格不冲突，
比如 abcdefg，A用户 在 a和b中间插入1，B用户在e和f中间插入2，最终结果是a1bcde2fg。
大部分的在线文档多人编辑在使用ot算法，可以实现这样的功能

**Comment by ziqiangai** [comment]
您说的这种处理，在协同文档类的产品中有较多实践，可能会有多个人给一个文章段落润色的场景，但是对于一个只能输入文字且没有复杂样式的狭小的单元格来说，在产品上会有这种场景吗？

好像APITable 的OT算法是他们自己实现的，据我观察，当一个单元格从编辑状态变为非编辑状态的时候，才会将单元格的新内容发送给其他协作者，要实现您描述的场景，要么将其改为在单元格内容变动时就发送协作指令，要么写一个diff算法在单元格完成编辑时计算diff结果然后进行合并（我能想到的两个处理方法，说不定还有其他方案）。不管哪种方案，都要花费较大时间成本，但是这样我感觉没有什么收益。

我不是 API Table 团队内的人员，只是看到了随便讨论一下。

**Comment by 1330101170** [comment]
> 

好的，了解了，感谢
