### ISSUE TITLE
question: Q&A...我想为开发出力，于是在本地搭建了开发环境，不过上来就出现了意外,make命令遇到了一些情况

### ISSUE THREAD

**Issue by itknight** [apitable/apitable#482]
## Any questions?
我发现一个问题，就是自己发布的表单，发出去以后，主题颜色是dark。我想把这个改成白色。
于是我在win10 22H2的环境上，安装了docker 拉下来了 ubuntu 镜像并创建容器。
安装好了`git` 及`make` 环境。
我将 `git clone` 得到的代码，挂到了 `ubuntu`容器中的 `/data/ ` 目录

```bash
docker run -it -d --name apitable_dev -v /f/data/docker/apitable:/data ubuntu:22.10 /bin/bash
```
目录结构如下图：
![image](https://user-images.githubusercontent.com/7972442/222076574-ee815116-56cc-4076-8230-6e1d9874e948.png)
make工具如文档中说，给出了输出。
![image](https://user-images.githubusercontent.com/7972442/222076748-dc3a8a25-af1a-436a-bc00-dfe1ff91dd60.png)

只不过在按照提示执行命令式发生了错误，详情如下：

![image](https://user-images.githubusercontent.com/7972442/222076931-224b5df2-7703-46cb-8add-e2913a0b043b.png)
这是什么情况，该如何去解，盼复。

**Comment by ChambersChan** [comment]
As the tip said, 'yarn: command not found'. You can try it after installing yarn.

**Comment by beelzebub2006** [comment]
16g的电脑跑起来吃力！本地调试麻烦！

**Comment by itknight** [comment]
> 16g的电脑跑起来吃力！本地调试麻烦！

我现在用着i5 12代 , 32G内存，还没跑起来，我试下看效果

**Comment by yort-feng** [comment]
> 16g的电脑跑起来吃力！本地调试麻烦！

@beelzebub2006 we're working on fixing the memory consumption issue, please follow this issue: [perf: reduce the memory consumption of web-server in dev mode #323](https://github.com/apitable/apitable/issues/323)

**Comment by itknight** [comment]
> As the tip said, 'yarn: command not found'. You can try it after installing yarn.

非常感谢你的提示，我以为前面的是mac系统才需要的没装，按照步骤搭建后一切正常！
