### ISSUE TITLE
fix: BUG 500 Revision History of Records

### ISSUE THREAD

**Issue by ratnikov-in** [apitable/apitable#484]
**500 Error Loading failed, please refresh and try again**

**To Reproduce**
1. Go to 'Datasheet'
2. Click on 'record with comments'
3. Loading failed, please refresh and try again

**Expected behavior**
See comments

**Screenshots**
<img width="1452" alt="Снимок экрана 2023-03-01 в 14 29 59" src="https://user-images.githubusercontent.com/37483261/222127275-e3cb85eb-5ee9-4794-a964-cbcbeca7d55c.png">

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Google Chome]

**Additional context**

**Comment by yort-feng** [comment]
Could you please provide the response message of the failed request? Which release do you use?

**Comment by ratnikov-in** [comment]
![Снимок экрана 2023-03-03 в 10 57 49](https://user-images.githubusercontent.com/37483261/222664017-8c7bbfdc-a15b-4408-a76f-0513b64e3d4b.png)
Response:
{"success":false,"code":500,"message":"Unknown column 'vum.unit_type' in 'where clause'"}

I`m install APITable curl https://apitable.github.io/install.sh | bash

**Comment by pengjin123** [comment]
This problem has been fixed in the latest version, please update the latest version
