### ISSUE TITLE
fix: collided src file

### ISSUE THREAD

**Issue by jinbo-yu** [apitable/apitable#488]
**Describe the bug**

Cloning into 'apitable'...
remote: Enumerating objects: 33083, done.
remote: Counting objects: 100% (3756/3756), done.
remote: Compressing objects: 100% (1955/1955), done.
remote: Total 33083 (delta 1720), reused 3463 (delta 1671), pack-reused 29327
Receiving objects: 100% (33083/33083), 91.28 MiB | 577.00 KiB/s, done.
Resolving deltas: 100% (18300/18300), done.
Updating files: 100% (7608/7608), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'packages/icons/src/components/Pause_filled.tsx'
  'packages/icons/src/components/pause_filled.tsx'

**To Reproduce**
1. git clone git@github.com:apitable/apitable.git

**Comment by pengjin123** [comment]
@networkhermit Please check it, thanks

**Comment by networkhermit** [comment]
@jinbo-yu 

```text
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

'packages/icons/src/components/Pause_filled.tsx'
'packages/icons/src/components/pause_filled.tsx'
```

Please remove 'packages/icons/src/components/Pause_filled.tsx' and try git clone again.
