### ISSUE TITLE
fix: authentication problem in API call

### ISSUE THREAD

**Issue by Luochenliang** [apitable/apitable#489]
你好，请问我使用官网文档上的API接口样例，使用了自己的api token ，但是返回身份认证失败，请问是为什么呢？
![image](https://user-images.githubusercontent.com/43427657/222390070-901094d8-438b-4303-b742-36fa605c8487.png)
![image](https://user-images.githubusercontent.com/43427657/222390143-6d186c02-5ef9-4486-8993-993721b8f341.png)

**Comment by mr-kelly** [comment]
@Luochenliang Are you using https://apitable.com ?

**Comment by Luochenliang** [comment]
![image](https://user-images.githubusercontent.com/43427657/222395503-948a8bb5-c2a1-48ec-a46c-d2a0ce3dba4c.png)

我使用的就是 https://apitable.com/ 文档的参考示例代码，只是替换了自己的api token，为什么会报错呢

**Comment by mr-kelly** [comment]
@mr-kelly Are you using https://apitable.com/ ? or https://vikadata.com

**Comment by xukecheng** [comment]
> ![image](https://user-images.githubusercontent.com/43427657/222395503-948a8bb5-c2a1-48ec-a46c-d2a0ce3dba4c.png)
> 
> 我使用的就是 https://apitable.com/ 文档的参考示例代码，只是替换了自己的api token，为什么会报错呢

If you are using APITable, are you using APITable Cloud or a Self-Hosted service? If you are using a Self-Hosted service, you need to code like this:
```python
from apitable import Apitable

apitable = Apitable("your_token", api_base="your_self_hosted_domain")
spaces = apitable.spaces.all()
for space in spaces:
    print(space.json())
```

For more details, please refer to https://github.com/apitable/apitable-sdks/tree/develop/apitable.py

**Comment by Luochenliang** [comment]
明白了，我是自己搭的服务器，没加api_base。现在可以了，谢谢

**Comment by mr-kelly** [comment]
> 明白了，我是自己搭的服务器，没加api_base。现在可以了，谢谢

Thank you!
