### ISSUE TITLE
fix: BUG...还有一点点问题了，图表X轴只要选神奇关联的字段，数据则显示为空

### ISSUE THREAD

**Issue by sepbin** [apitable/apitable#490]
**To Reproduce**
1，建立小程序
2，X轴字段选择神奇关联类型的字段
3，所有数据为空

**Comment by mr-kelly** [comment]
Hi. @sepbin 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

1. Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
2. Describe your problem in English (Translation is OK).

**Comment by sepbin** [comment]
> Hi. @sepbin
> 
> Consider the reading experience of others in the community. Please follow these instructions to submit your issues:
> 
> 1. Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
> 2. Describe your problem in English (Translation is OK).

嗨。。我这是提交bug，似乎只需要开发同学能看懂就行了吧？也确实有这样的BUG。为什么其他人不使用汉语照顾我的感受？他们也能翻译，既然是社区，那即是人人平等，语言平等。
Hi. . I am submitting a bug. It seems that only the developers can understand it, right? There is indeed such a BUG. Why don't other people take care of my feelings in Chinese? They can also translate. Since it is a community, everyone is equal and language is equal.
