### ISSUE TITLE
question: Where is the full SQL database schema script?

### ISSUE THREAD

**Issue by wasd345** [apitable/apitable#493]
![image](https://user-images.githubusercontent.com/5779660/222428346-297ee9b6-5232-4fba-8e3c-0d16d98a63c2.png)
这里面哪个是sql脚本？

**Comment by wasd345** [comment]
你好，请把最后完整的sql脚本发出来吧

**Comment by mr-kelly** [comment]
We use Liquibase to migrate our database SQL structure: https://www.liquibase.org/
