### ISSUE TITLE
question: How to run develop environment in IntellijIDEA / WebStorm / VSCode on Windows 11?

### ISSUE THREAD

**Issue by wasd345** [apitable/apitable#494]
请问win11系统上，怎么在idea或者webstom或者vsc中分别运行起来前后端代码？能不能出个完整的和具体的文档

**Comment by mr-kelly** [comment]
Check out the developer guide:
https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md

**Comment by wasd345** [comment]
> Check out the developer guide: https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md

大佬你好，你这个指南根本就不详细，表示看的一头雾水

**Comment by wasd345** [comment]
不想在win11上安装linux系统，不用linux系统就跑不起来源码？

**Comment by ziqiangai** [comment]
在 git base 命令行中执行相关的 make 命令即可，wsl 和 docker for desktop 还是要装的，很新的技术。

**Comment by weihomechen** [comment]
> 在 git base 命令行中执行相关的 make 命令即可

大佬，我想在本地运行，请教下需要执行哪些make命令

**Comment by ziqiangai** [comment]
> https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md



> > 在 git base 命令行中执行相关的 make 命令即可
> 
> 大佬，我想在本地运行，请教下需要执行哪些make命令

In the APITable directory, open the three command lines of git base,first run `make dataenv` and `make install` to install the environment, after ensuring that these two commands are running normally, execute `make run` in the three command lines in turn, select 1, 2, 3.

More information can be found here: [developer-guide](https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md)

**Comment by weihomechen** [comment]
> > https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md
> 
> > > 在 git base 命令行中执行相关的 make 命令即可
> > 
> > 
> > 大佬，我想在本地运行，请教下需要执行哪些make命令
> 
> In the APITable directory, open the three command lines of git base,first run `make dataenv` and `make install` to install the environment, after ensuring that these two commands are running normally, execute `make run` in the three command lines in turn, select 1, 2, 3.
> 
> More information can be found here: [developer-guide](https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md)

make run 时必须按照1、2、3的顺序来么，可以只启动3么大佬

**Comment by 15763336201** [comment]
大佬，我在本地win11环境装了docker desktop \ ubuntu 22 \ wsl2, 但是执行make命令的时候在报错，或者单独yarn install的时候也是出现很多异常信息
