### ISSUE TITLE
question: Do not want to install Linux on WIN11, can not run the source code without Linux?

### ISSUE THREAD

**Issue by wasd345** [apitable/apitable#495]
不想在win11上安装linux系统，不用linux系统就跑不起来源码？我在window系统上已经安装了make、gradel、react

**Comment by mr-kelly** [comment]
Officially, we do not provide non-Unix development environments.

Welcome to fork, modify, and commit the developer guide:
https://github.com/apitable/apitable/fork

**Comment by wasd345** [comment]
> Officially, we do not provide non-Unix development environments.
> 
> Welcome to fork, modify, and commit the developer guide: https://github.com/apitable/apitable/fork

必须安装带界面的Unix操作系统才可以，不带界面的unix不行？
