### ISSUE TITLE
reset the default password or create now account

### ISSUE THREAD

**Issue by Eucalyeupt** [apitable/apitable#497]
## Any questions?
started by docker-compose

### 1、reset the default password or disable the default account
it needs send code to the default email,  but i can‘t get it
or just disable it but i have no idea of entry (had searched all "settings"

maybe it can be configure by .env file soon?

### 2、create now account
it tells "Validate failure"

how to resolve this

**Comment by ratnikov-in** [comment]
https://github.com/apitable/apitable/issues/198#issuecomment-1436068234

**Comment by Eucalyeupt** [comment]
> [#198 (comment)](https://github.com/apitable/apitable/issues/198#issuecomment-1436068234)

get it .thx
