### ISSUE TITLE
如何对首页访问端口80进行修改

### ISSUE THREAD

**Issue by juran12138** [apitable/apitable#502]
## Any questions?

**Comment by mr-kelly** [comment]
Hi. @juran12138 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

1. Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=question&template=question.md&title=question%3A+Q%26A...).
2. Describe your problem in English (Translation is OK).


Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
