### ISSUE TITLE
apitable中 小程序插件不能用

### ISSUE THREAD

**Issue by Williem24** [apitable/apitable#503]
apitable中 小程序插件不能用，表格中添加小程序导致页面奔溃

**Comment by mr-kelly** [comment]
Hi. @Williem24 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

1. Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=question&template=question.md&title=question%3A+Q%26A...).
2. Describe your problem in English (Translation is OK).


Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
