### ISSUE TITLE
这个怎么在docker desktop下部署呢？用的Windows10

### ISSUE THREAD

**Issue by miudove** [apitable/apitable#505]
## Any questions?
RT

**Comment by mr-kelly** [comment]
Hi. @miudove 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

1. Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=question&template=question.md&title=question%3A+Q%26A...).
2. Describe your problem in English (Translation is OK).

Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).

**Comment by miaomiao1992** [comment]
欲哭无泪啊，单位电脑内存4G，win7，天知道运行wsl+docker后还剩几个多少内存
