### ISSUE TITLE
question: Create Datasheet & Field

### ISSUE THREAD

**Issue by Luochenliang** [apitable/apitable#506]
1、请问使用API创建表格时，创建完都会自动创建3行，导致我后续插入数据的时候，前面都有3个空行，请问这个怎么解决，如何在创建表时不插入这3行？
![image](https://user-images.githubusercontent.com/43427657/223013367-79f54bc6-36f7-4a23-957f-ec1b4e3e1d63.png)
2、根据官方文档的API接口，创建表格时只能直接创建在工作目录下，是否可以通过API创建表时，放在自己创建的目录下？
如下图，想要通过API创建表格，放在“工时统计”的目录下，改如何操作？
![image](https://user-images.githubusercontent.com/43427657/223013724-bcf860f7-9957-460a-a7c1-9b97c002a5fe.png)
3、官方文档上的字段类型，只看到了 SingleText 请问还支持其它哪些类型？比如数值，json等，对应到API里应该如何填写？
![image](https://user-images.githubusercontent.com/43427657/223013907-d9aea912-8d03-4042-bcaf-b31c9a08e88a.png)

**Comment by ChambersChan** [comment]
1. Creating table in the interface can't remove the default three record. You could create through Fusion API.

2. API support specified directory by using `folderId` param. [dosc](https://developers.apitable.com/api/reference#tag/Datasheet/operation/create-datasheets)

3. API support to create all filed type. You could get data struct after select filed type. [dosc](https://developers.apitable.com/api/reference/#tag/Field/operation/create-fields)
![image](https://user-images.githubusercontent.com/32906036/223035794-806c1fa0-00eb-479c-bd7c-d61dd3c0f16a.png)

**Comment by Luochenliang** [comment]
Thank you for solving my problem perfectly

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you encounter any problems, could feel free to contact us through github or [discord](https://discord.gg/5WrDWxkXE9).
