### ISSUE TITLE
fix: BUG...duplicate record function is faild

### ISSUE THREAD

**Issue by masterkkkkkong** [apitable/apitable#510]
Version: v0.18.0-rc
After I deployed a set of apitable locally, I found that the function of this copy line was invalid. After clicking, I just added a blank line without copying the original information. I'm not sure if this is a bug, so I will give feedback.
![image](https://user-images.githubusercontent.com/55868627/223074009-9535e9c6-b81e-4785-a144-5477f247c99c.png)
![image](https://user-images.githubusercontent.com/55868627/223074074-cc4e0a07-e6fc-4539-a63b-c31cd69b2cce.png)

**Comment by mr-kelly** [comment]
Hi. @masterkkkkkong 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

1. Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
2. Describe your problem in English (Translation is OK).
