### ISSUE TITLE
fix: MySQL service has always been unhealthy

### ISSUE THREAD

**Issue by Niko030303** [apitable/apitable#512]
**Describe the bug**
![image](https://user-images.githubusercontent.com/82041918/223089339-543e55ad-f6fa-46e6-ac85-b79b48f497ff.png)

I checked the image of the docker
![image](https://user-images.githubusercontent.com/82041918/223089377-6823a32d-0075-467f-8eab-0c091541bb3e.png)

**Comment by networkhermit** [comment]
To use devenv in gitpod, it is recommended to stop the apitable started by docker compose first (by running `make down`), otherwise the cpu/memory load maybe too high.

**Comment by mr-kelly** [comment]
> To use devenv in gitpod, it is recommended to stop the apitable started by docker compose first (by running `make down`), otherwise the cpu/memory load maybe too high.

You mean `make down` and then `make up`?

**Comment by networkhermit** [comment]
> > To use devenv in gitpod, it is recommended to stop the apitable started by docker compose first (by running `make down`), otherwise the cpu/memory load maybe too high.
> 
> You mean `make down` and then `make up`?

No. `make down` and `make dataenv`/`make run`, otherwise there are two conflict running instances using the same data volume.
