### ISSUE TITLE
fix: BUG...duplicate record function is faild

### ISSUE THREAD

**Issue by masterkkkkkong** [apitable/apitable#513]
**Describe the bug**
After I deployed a set of apitable locally, I found that the function of this copy line was invalid. After clicking, I just added a blank line without copying the original information. I'm not sure if this is a bug, so I will give feedback.

**To Reproduce**
1. Go to 'any line'
2. Click on 'duplicate record'

**Expected behavior**
Add a new line identical to the current line

**Screenshots**
![image](https://user-images.githubusercontent.com/55868627/223088970-031a0b39-ed47-407f-bc51-c8c378eaf0f6.png)
![image](https://user-images.githubusercontent.com/55868627/223089043-91fd60e0-e14f-41b2-ab2b-a0d19d1c8037.png)

**Desktop (please complete the following information):**
 - Version [v0.18.0-rc]

**Comment by pengjin123** [comment]
@Sky-FE  Please check this question, thanks
