### ISSUE TITLE
question: When Make Install, Cypress@NPM compilation failed, how to deal with it?

### ISSUE THREAD

**Issue by Niko030303** [apitable/apitable#514]
## Any questions?

When Make Install, Cypress@NPM compilation failed, how to deal with it?

This file contains the result of Yarn building a package (cypress@npm:8.7.0)
Script name: postinstall
Installing Cypress (version: 8.7.0)

[STARTED] Task without title.
[FAILED] The Cypress App could not be downloaded.
[FAILED]
[FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: [https://on.cypress.io/proxy-configuration](https://gitee.com/link?target=https%3A%2F%2Fon.cypress.io%2Fproxy-configuration)
[FAILED]
[FAILED] Otherwise, please check network connectivity and try again:
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] URL: [https://download.cypress.io/desktop/8.7.0?platform=darwin&arch=x64](https://gitee.com/link?target=https%3A%2F%2Fdownload.cypress.io%2Fdesktop%2F8.7.0%3Fplatform%3Ddarwin%26arch%3Dx64)
[FAILED] Error: read ECONNRESET
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Platform: darwin (21.6.0)
[FAILED] Cypress Version: 8.7.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: [https://on.cypress.io/proxy-configuration](https://gitee.com/link?target=https%3A%2F%2Fon.cypress.io%2Fproxy-configuration)

Otherwise, please check network connectivity and try again:

URL: [https://download.cypress.io/desktop/8.7.0?platform=darwin&arch=x64](https://gitee.com/link?target=https%3A%2F%2Fdownload.cypress.io%2Fdesktop%2F8.7.0%3Fplatform%3Ddarwin%26arch%3Dx64)
Error: read ECONNRESET

Platform: darwin (21.6.0)
Cypress Version: 8.7.0

**Comment by networkhermit** [comment]
```text
[FAILED] The Cypress App could not be downloaded.
[FAILED]
[FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: [https://on.cypress.io/proxy-configuration](https://gitee.com/link?target=https%3A%2F%2Fon.cypress.io%2Fproxy-configuration)
[FAILED]
[FAILED] Otherwise, please check network connectivity and try again:
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] URL: [https://download.cypress.io/desktop/8.7.0?platform=darwin&arch=x64](https://gitee.com/link?target=https%3A%2F%2Fdownload.cypress.io%2Fdesktop%2F8.7.0%3Fplatform%3Ddarwin%26arch%3Dx64)
[FAILED] Error: read ECONNRESET
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Platform: darwin (21.6.0)
[FAILED] Cypress Version: 8.7.0
```

Check your internet connection as suggested by the error message.
