### ISSUE TITLE
fix: Docker installation error

### ISSUE THREAD

**Issue by Niko030303** [apitable/apitable#515]
PS C:\Users\Administrator> curl [https://apitable.github.io/install.sh](https://gitee.com/link?target=https%3A%2F%2Fapitable.github.io%2Finstall.sh) | bash -bash: line 1: ′\r′:commandnotfound−bash:line2:
'\r': command not found
-bash: line 3: StatusCode: command not found
-bash: line 4: StatusDescription: command not found
-bash: line 5: Content: command not found
-bash: line 6: RawContent: command not found
-bash: line 7: Connection:: command not found
-bash: line 8: syntax error near unexpected token (' 'bash: line 8: permissions-policy: interest-cohort=()

**Comment by pengjin123** [comment]
@networkhermit Please check

**Comment by networkhermit** [comment]
> PS C:\Users\Administrator> curl [https://apitable.github.io/install.sh](https://gitee.com/link?target=https%3A%2F%2Fapitable.github.io%2Finstall.sh) | bash -bash: line 1: ′\r′:commandnotfound−bash:line2: '\r': command not found -bash: line 3: StatusCode: command not found -bash: line 4: StatusDescription: command not found -bash: line 5: Content: command not found -bash: line 6: RawContent: command not found -bash: line 7: Connection:: command not found -bash: line 8: syntax error near unexpected token (' 'bash: line 8: permissions-policy: interest-cohort=()

The url `https://gitee.com/link?target=https%3A%2F%2Fapitable.github.io%2Finstall.sh` is wrong and we don't support install apitable directly from Windows powershell.

Please consult https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md#windows if you want to setup apitable in windows wsl.
