### ISSUE TITLE
fix: the widget‘s background is white

### ISSUE THREAD

**Issue by nagisakon** [apitable/apitable#517]
**Describe the bug**

**To Reproduce**
![8VoiD1IOZN](https://user-images.githubusercontent.com/49678762/223100592-59007e4d-d957-46c6-9ea2-805cdb349416.jpg)

**Expected behavior**
black

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ziqiangai** [comment]
Is it still the case after refreshing the interface?
