### ISSUE TITLE
fix: BUG...一个神奇的BUG

### ISSUE THREAD

**Issue by sepbin** [apitable/apitable#518]
**Describe the bug**

1，设置小程序
2，统计指定字段，选择一般，正常出数据
![image](https://user-images.githubusercontent.com/3182421/223159111-c8f593be-6c27-48bf-8a2a-f00b5e8e0b7e.png)
3，改变为神奇关联的数字字段，空白
![image](https://user-images.githubusercontent.com/3182421/223161573-8a558fe8-e7d2-451b-a42f-1e4616fe6c42.png)
4，神奇的是，我再加个神奇引用
![image](https://user-images.githubusercontent.com/3182421/223161896-3257b4c9-2c06-4db8-beee-6099b4fe71be.png)
![image](https://user-images.githubusercontent.com/3182421/223162084-348fe1d0-b1b9-4456-b6c5-fbb14dbe25ca.png)
5，即使统计表不选我神奇应用的字段，它也好了。。
![image](https://user-images.githubusercontent.com/3182421/223162223-b18e3d9a-f7d4-4471-93c0-a66022a542b4.png)

真的很神奇的BUG

**Comment by mr-kelly** [comment]
Hi. @sepbin 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

- Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
- Describe your problem in English (Translation is OK).
- Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
