### ISSUE TITLE
fix: The width of the first column influences the display of group label

### ISSUE THREAD

**Issue by chxp** [apitable/apitable#525]
**Describe the bug**
The width of the first column influences the display of the group label. Too short the first column will display part of group label.

**To Reproduce**
- Wide first column

![2023-03-08 15-50-21 的屏幕截图](https://user-images.githubusercontent.com/14882692/223653318-c5933d80-ebc4-48c2-a7d0-a32a7513d240.png)

- Decrease the width of the first column

![2023-03-08 15-50-35 的屏幕截图](https://user-images.githubusercontent.com/14882692/223653336-abb25141-e40e-4a46-8e19-f3b57256e10a.png)

**Expected behavior**
Display complete group label ignoring the width of the first column.

**Desktop (please complete the following information):**
 - Browser [Firefox]
 - Version [v0.18.0-rc.1]

**Comment by nagisakon** [comment]
The width of the statistics column influences the display of the first columna, it's not a bug but I will feed back to our colleagues. Please pay attention to the follow-up improvement~
