### ISSUE TITLE
How to create a folder using the api？

### ISSUE THREAD

**Issue by Luochenliang** [apitable/apitable#527]
![image](https://user-images.githubusercontent.com/43427657/223677160-fafccc1a-8c59-490e-a0b1-1349fc5d884b.png)

How do I create a folder through python's api?

For example, in the figure above, I want to create a "二级目录" under the "一级目录" file. How should I use the python api?

I don't seem to find this case in the official document

**Comment by ChambersChan** [comment]
Unfortunately. Open API does not support creating folder now.

**Comment by Alex-hufeng** [comment]
> document

Can you describe in which scenarios you will use this API?
