### ISSUE TITLE
Default admin account can't be changed

### ISSUE THREAD

**Issue by RuralDependencies** [apitable/apitable#536]
**Describe the bug**
I've seen previous issues regarding it (https://github.com/apitable/apitable/issues/198), apparently fixed in the latest version, but as of now, there is still no way without going to MySQL manually to modify the password or change the default email 

**To Reproduce**
Go to My Settings , Change password, here there is a verification code that can't be obtained

**Expected behavior**
A way to change the default admin login/password

**Screenshots**
![APITABLE_ISSUE_PASSWORD](https://user-images.githubusercontent.com/55824167/223968547-5697ae70-4b76-4088-9f07-62df1db4d8d9.png)

**Additional context**
Thank you guys! Awesome product.

**Comment by NN-Binary** [comment]
I also face the same issue, for now my company does not want to use the self-hosted because of the "immediate" risk of hack the moment we deploy online because of scrappers. 

I hope there is a fix coming-up

**Comment by networkhermit** [comment]
Thanks for the feedback. We are considering removing the default user in future version and will provide some workaround to disable/remove the default user for old deployments.

**Comment by RuralDependencies** [comment]
Thank you, is there any way of changing the login/password of the admin from the interface?

**Comment by networkhermit** [comment]
Nope. You can try to set an empty password from mysql cli.

**Comment by zlxmygit** [comment]
I have the same problem, is it possible to replace the email and password of the admin account? Thank you very much!
