### ISSUE TITLE
How to set the default to Chinese language?

### ISSUE THREAD

**Issue by waterxman** [apitable/apitable#540]
I have set a Chinese theme, but English pages often appear,why?

**Comment by pengjin123** [comment]
@waterxman Please enter the personalized settings page language settings in personal settings

**Comment by waterxman** [comment]
Add parameters to the . env file：
`SYSTEM_CONFIGURATION_DEFAULT_LANGUAGE = zh_CN`
and then restart the service.

**Comment by waterxman** [comment]
Add parameters to the. env file：SYSTEM_CONFIGURATION_DEFAULT_LANGUAGE = zh_CN,and then restart the service.
