### ISSUE TITLE
question: The function of table permission setting is not found

### ISSUE THREAD

**Issue by masterkkkkkong** [apitable/apitable#541]
## Any questions?
I see that the official document has the function of table permission setting, but I found that this function is not available on the localized deployment service. What is the reason?

My version is: v0.18.0-rc

![image](https://user-images.githubusercontent.com/55868627/224235360-02dd3c6a-1fcd-4c10-9f93-bc8297c72734.png)
![image](https://user-images.githubusercontent.com/55868627/224235749-4bbdeced-4f70-43cf-8e9d-de34b1bcfe2d.png)

**Comment by ChambersChan** [comment]
The community version does not support this feature. For more description, please go to [official website](https://apitable.com/pricing/) to view.
![image](https://user-images.githubusercontent.com/32906036/224266140-6c239c88-f33c-472d-a0fb-c63a9fe5b6be.png)
