### ISSUE TITLE
Local development make install throw a error. 

### ISSUE THREAD

**Issue by eric183** [apitable/apitable#543]
I tried to run the dev env locally, but encountered obstacles during the 'make install' process.

1. open Developer Guide
2. make dataenv 
3. make install
4. `BOOM`

![image](https://user-images.githubusercontent.com/10773980/224264120-54243852-2d2b-4eaa-9221-fa0f529b67d9.png)

platform: window -  wsl2
Node:  16.15.0
rustc:  1.68.0

**Comment by arucil** [comment]
A `nightly` version of Rust is required to build APITable. Run `rustup default nightly` to switch to Rust nightly before running `make install`.
