### ISSUE TITLE
Windwos development environment of room-native-api

### ISSUE THREAD

**Issue by ziqiangai** [apitable/apitable#548]
For the configuration of the `room-native-api` development environment, it seems that only `macOs` users need to execute the following script: 

https://github.com/apitable/apitable/blob/de61e24b49648d4ced73dff2990e75f01c457a79/packages/room-native-api/README.md#L10-L29

It seems that a programming language called `zig` is also installed in the above script as a linker.

But for `windows` users, just follow [here](https://www.rust-lang.org/tools/install) to install the **Rust SDK**. Then follow this [guide](https://rust-lang.github.io/rustup/concepts/toolchains.html) to **set up the toolchain**.

Then run the `yarn build` command again. The corresponding files will be generated.

I'm wondering if it's necessary to state this in the **README.md**.

**Comment by arucil** [comment]
That is a note for cross compilation to `arm64` library on `amd64` platform. Cross compilation is only performed on CI/CD, for local development, these dependencies are not required.
