### ISSUE TITLE
docs: Missing license credits

### ISSUE THREAD

**Issue by jakob1379** [apitable/apitable#555]
## What documentation do you want?

A comprehensive section with the missing credits of multiple services you are using. Most of them seem to be packed away in your images that you host on your own repo which obfuscates it.

**Comment by mr-kelly** [comment]
What's the meaning of credit of service? What are they exactly?

@jakob1379

**Comment by jakob1379** [comment]
Giving credit to a service means acknowledging and attributing the work of its creators. In the case of the Apache2 License, which several services used in the project are licensed under, it requires users to give proper credit where it is due. This credit can take various forms, such as a mention in the project's documentation, a notice in the project's UI, or a link to the service's website. Properly crediting the services used not only fulfills legal requirements but also shows respect for the creators and their work which is a pretty nice touch for such a great tool as APITable. This would indeed empowering open source projects!

**Comment by mr-kelly** [comment]
> Giving credit to a service means acknowledging and attributing the work of its creators. In the case of the Apache2 License, which several services used in the project are licensed under, it requires users to give proper credit where it is due. This credit can take various forms, such as a mention in the project's documentation, a notice in the project's UI, or a link to the service's website. Properly crediting the services used not only fulfills legal requirements but also shows respect for the creators and their work which is a pretty nice touch for such a great tool as APITable. This would indeed empowering open source projects!

That's great. 

Thanks for reminding. 

We will work on it.

**Comment by mr-kelly** [comment]
> Giving credit to a service means acknowledging and attributing the work of its creators. In the case of the Apache2 License, which several services used in the project are licensed under, it requires users to give proper credit where it is due. This credit can take various forms, such as a mention in the project's documentation, a notice in the project's UI, or a link to the service's website. Properly crediting the services used not only fulfills legal requirements but also shows respect for the creators and their work which is a pretty nice touch for such a great tool as APITable. This would indeed empowering open source projects!

Normally, license credits are for cases where code is embedded in software engineering. 

However, all of our current dependencies are installed as packages and are not in the main code.

May I ask which services and licenses you think should be added to the documentation? @jakob1379
