### ISSUE TITLE
question: Why does the room-native-api use Rust instead of Java for implementation

### ISSUE THREAD

**Issue by Magi-Wang** [apitable/apitable#568]
## Any questions?
Hi，apitable team:
Why does the room-native-api use Rust instead of Java for implementation? Currently, there are two options for backend languages, can the advantages of using Rust outweigh the disadvantages of using Java, such as project complexity and the barrier to contributing code to open source communities?

**Comment by yort-feng** [comment]
Actually, we use Rust instead of Javascript, there're multiple reasons why we choose Rust rather than Java
1. Rust delivers faster startup times and a smaller memory footprint on top of it
2. Java uses Garbage Collection for memory management, which decreases performance
3. Rust is best for Web Assembly. We'd like to keep the ability to calculate cell values in both the back-end and front-end with Web Assembly

**Comment by arucil** [comment]
@yort-feng has summarized the reasons quite well, I will add some additional information here.

The purpose of introducing another programming language to room-server is to improve the throughput of REST APIs provided by APITable, so some criterions are used for choosing the language:
1. Low call overhead.  The data transferred between room-server and room-native-api may be quite large, in our testing, 20MB+ of data transfer is common. Nodejs provides N-API for native inter-language communication, and Rust has a binding for it. However Nodejs is not able to call Java using N-API directly, a bridge between Java and Nodejs is required, for example, named pipes, sockets, etc. This means an indirection is required in the communication of Nodejs and Java: JS values are serialized into binary data, and then transferred through named pipes, and then deserialized into Java values. The serialization/deserialization overhead is relatively high compared to N-API.
2. Runtime size. JVM is considerably larger than compiled Rust library (< 10MB). Running a JVM alongside a Nodejs instance will lead to a higher memory footprint for the container.

**Comment by doucheng** [comment]
Good idea  (*^▽^*)
