### ISSUE TITLE
feat: Fusion API support for search nodes by conditions

### ISSUE THREAD

**Issue by xukecheng** [apitable/apitable#570]
I have an idea for this project: https://apitable.getoutline.com/s/ee373d9a-9316-4098-aa8a-4e9933c06e99

## Why? 

Currently, we can only get all types of nodes by calling the API.

## What?

I want to do different operations depending on the type of node.

## How?

Add an optional parameter `type`, which can accept one or more types as values, such as `type=datasheet, mirror`.
In the returned result, only nodes that meet the conditions are included. If no type is specified, all nodes are returned.
- [x] support search node type as a query parameter 
- [x] #688

**Comment by Itou-Ng** [comment]
接口文档：[outline node list](https://apitable.getoutline.com/doc/node-list-UnucbnlJdy/edit)
