### ISSUE TITLE
Consider adding apitable to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [apitable/apitable#575]
Hey @mr-kelly, Thanks for adopting SeaORM! 
It's our pleasure to see more inspirational projects were built on top of SeaORM :) 

Let us know if you have any [feature recommendation](https://github.com/SeaQL/sea-orm/issues/new/choose) or [feedback](https://github.com/SeaQL/sea-orm/discussions/new). Your contribution is what drive us forward! 

Some learning resources for you: [Documentation](https://www.sea-ql.org/SeaORM/), [Tutorial](https://www.sea-ql.org/sea-orm-tutorial/), [Cookbook](https://www.sea-ql.org/sea-orm-cookbook/), [Q&A](https://github.com/SeaQL/sea-orm/discussions), [Blog](https://www.sea-ql.org/blog/) 
Join our [Discord server](https://discord.com/invite/uCPdDXzbdv) to chat with others in the SeaQL community! 

Feel free to submit a PR to showcase your project, https://github.com/SeaQL/sea-orm/issues/403.

**Comment by arucil** [comment]
Cool! SeaORM is a promising project and we are willing to make it better!

**Comment by billy1624** [comment]
Thanks for the love and support!! @arucil
