### ISSUE TITLE
question: Event Listener on Table

### ISSUE THREAD

**Issue by RuralDependencies** [apitable/apitable#579]
I don't really understand how I can achieve what I'm trying to do, I just want a simple eventListener for some specific rows (or ANY rows) in the DevTools (by using the console) but it's all in Canvas and it's really messy.

How can I achieve a simple listener that it's on click on a row and get its ID?

**Comment by arucil** [comment]
Do you indend to get the ID of a specific record? I don't think there is an easy way to do this.

There is a more complex way to do it, tho. In the devtools console, there is a global variable `VkResourceService` that contains nearly all internal states of the front end. You can inspect the state of the datasheet, including all records, in this variable. `VkResourceService.store.getState()` returns the internal redux state.
Say you are visiting a datasheet whose ID is `dstXYZ` (you can find the datasheet ID in the link of the page you are visiting), `state.datasheetMap["dstXYZ"].datasheet.snapshot.recordMap` contains all the records of the datasheet, you can find the record ID by inspecting its record data.
