### ISSUE TITLE
question: admin@apitable.com 密码怎么修改？

### ISSUE THREAD

**Issue by a506488043** [apitable/apitable#580]
## Any questions?

admin@apitable.com 密码怎么修改？注册账户怎么关闭？
这2个问题都不敢公开到公网。

**Comment by mr-kelly** [comment]
Hi. @a506488043 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

- Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
- Describe your problem in English (Translate by software is OK).
- Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
