### ISSUE TITLE
question: Q&A...怎么在linux环境下用命令升级到最新版本，求告知

### ISSUE THREAD

**Issue by wzzzzzz1111** [apitable/apitable#581]
## Any questions?怎么在linux环境下用命令升级到最新版本，求告知

**Comment by songbing97** [comment]
直接pull一下？提问感觉去discord更好一点

**Comment by mr-kelly** [comment]
Hi. @wzzzzzz1111 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

- Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
- Describe your problem in English (Translate by software is OK).
- Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
