### ISSUE TITLE
请开放用户管理 空间管理后台界面，便于管理

### ISSUE THREAD

**Issue by lucktoo** [apitable/apitable#582]
请开放用户管理 空间管理后台界面，便于管理

**Comment by mr-kelly** [comment]
Hi. @lucktoo 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

- Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
- Describe your problem in English (Translation is OK).
- Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
