### ISSUE TITLE
fix: "Delete space" button is missing

### ISSUE THREAD

**Issue by peterng1618** [apitable/apitable#583]
**Describe the bug**
A gear icon to delete space is not showing up under Space setting -> Overview as described in [the help article](https://help.apitable.com/docs/guide/faq-export-import#operation-steps)

**To Reproduce**
1. Go to 'Space settings'
2. Click on 'Overview'
3. The gear icon does not appear on the top right of the Overview box

**Expected behavior**
A clickable gear icon to delete the space

**Screenshots**
![image](https://user-images.githubusercontent.com/111590292/226171839-3be203de-37f8-45f2-b1a7-f4ee8a414be5.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 111.0.1661.44 (Official build) (64-bit)

**Comment by songbing97** [comment]
I'm not sure if this is a bug.
Try to set  'DELETE_SPACE_VISIBLE=true' in packages/datasheet/.env.
It works for me.

**Comment by peterng1618** [comment]
I have yet to look into that. Thanks for the tip!

Perhaps it should be made more obvious what features are available but disabled by default in the self-hosted version?
