### ISSUE TITLE
question: Q&A...What to do in this situation, thank you all

### ISSUE THREAD

**Issue by wzzzzzz1111** [apitable/apitable#587]
## Any questions?
![image](https://user-images.githubusercontent.com/125652293/226228000-ad3fe210-757f-4808-a0c7-21f3b9f53892.png)
What to do in this situation, thank you all

**Comment by yort-feng** [comment]
Could you show us the error message in the backend server container?

**Comment by wzzzzzz1111** [comment]
I don't know much about the code, I can't say the specifics, sorry, but that's how it was installed

**Comment by wzzzzzz1111** [comment]
I don't know much about the code, I can't say the specifics, sorry, but that's how it was installed

**Comment by ChambersChan** [comment]
Could you tell me your steps about start server?

In addition, you can view the log by entering `docker logs --tail=300 backend-server`.

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem after upgrading the latest version, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
