### ISSUE TITLE
feat(mirror): creat a editable public link of mirror

### ISSUE THREAD

**Issue by Alex-hufeng** [apitable/apitable#588]
# what?
User can creat a editable public link of mirror,then off-site users can edit data when view the share page

# why?
1. Because mirrors support filtering part of the data, it is common to share mirrors with off-site users to edit.
2. At present, there is user feedback that the mirrors I share does not support editing, which makes it impossible for off-site members to cooperate, so they can only be invited to the space , which increases the management cost.

# how?
When I creat a public link of mirror,I can choose "can edit" in the dropdown.

![Image](https://user-images.githubusercontent.com/54580109/226274743-edbe8038-0a77-49dd-af64-ac88f7144afc.png)

**Comment by Alex-hufeng** [comment]
需要一个后端中间层优化支持~

![Image](https://user-images.githubusercontent.com/54580109/230309015-290bb10a-8b0a-4c60-9528-a0a2a69c738e.png)

**Comment by Itou-Ng** [comment]
test环境可以达到预期

**Comment by wangkailang** [comment]
fixed
