### ISSUE TITLE
fix: Some parts of the English UI are in Chinese

### ISSUE THREAD

**Issue by peterng1618** [apitable/apitable#595]
**Describe the bug**
Some parts of the English UI are in Chinese. Additionally, there are some minor formatting issues, like extra white spaces before & after the closing/opening double quotes.

**Expected behavior**
All parts of the English UI should be in English. 

**Screenshots**
![image](https://user-images.githubusercontent.com/111590292/226343545-9c46860c-00b2-47c0-95aa-7612f649dac2.png)

**Additional context**
I want to contribute to completing/cleaning up the English translation. How do I do this? (The CrowdIn project doesn't list English because it's supposed to be the source language)

**Comment by pengjin123** [comment]
@peterng1618 thank you for your feedback, we have assigned relevant colleaagues to follow up this issue

**Comment by pengjin123** [comment]
@JaneSu Please check this issue，thanks

**Comment by pengjin123** [comment]
@peterng1618 Thank you for you  feedback,Notify you as soon as the problem is fixed
