### ISSUE TITLE
fix: Cover images in Gallery view become heavily pixelated at certain browser window sizes/ratios

### ISSUE THREAD

**Issue by peterng1618** [apitable/apitable#596]
**Describe the bug**
Cover images in Gallery view become heavily pixelated/have bad artifacts at certain browser window sizes/ratios

**To Reproduce**
1. Create a Gallery view & set an attachment field to be the cover image
2. Change the "Layout" setting to high records per row and/or resize the browser window to be smaller past a certain size
3. On a 1080p monitor with the browser set to full screen, this happens at 5 records/row or higher. But it can also happen at Auto/any number of records per row if the browser window is resized to be smaller past a certain size
4. If there are fewer records per row - i.e. the records are bigger on screen - the cover images get rendered fine

**Expected behavior**
Cover images should be rendered correctly without pixelations/artifacts regardless of the browser window's size, unless the original image's resolution is lower than the cover's current dimensions.

**Screenshots**
![image](https://user-images.githubusercontent.com/111590292/226350068-e1aa12b6-feeb-42cf-a21f-3b819f51203c.png)
![image](https://user-images.githubusercontent.com/111590292/226354355-46446d3e-7031-46a2-b8a4-19038d1e52fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: Chrome
 - Version: 111.0.5563.65 (Official Build) (64-bit)

**Comment by wangkailang** [comment]
Gallery view has compressed images by OSS with suffix like `?imageView2/0/w/198/h/198`. so image blurring may occur in some scenes. This is an optimization strategy, and of course you can adjust this configuration yourself at [the code](https://github.com/apitable/apitable/blob/develop/packages/datasheet/src/pc/components/display_file/display_file.tsx#L84).
