### ISSUE TITLE
question: how is communication with object storage backend implemented?

### ISSUE THREAD

**Issue by grigorev-lm** [apitable/apitable#600]
Hello team,
I have questions related to `gateway` container in [docker-compose.yaml](https://github.com/apitable/apitable/blob/develop/docker-compose.yaml) file. I see that inside of this image there is nginx with a hardcoded config related to `minio` upstream in [imageproxy.conf](https://github.com/apitable/apitable/blob/develop/gateway/conf.d/server/imageproxy.conf) and [minio.conf](https://github.com/apitable/apitable/blob/develop/gateway/conf.d/server/minio.conf). So my questions are: 
1. How is communication with other (not minio) object storages implemented?
2. Should I reconfigure nginx config files and rebuild this `gateway` container if I'm planning to use aws s3 as my object storage backend and how is issue with s3 bucket authentication should be solved?
3. This question is not related to my problem but anyway: Is it possible to implement all this `gateway` container nginx configuration as ingress configuration if I'm planning to deploy Apitable to k8s cluster with nginx ingress controller?

**Comment by networkhermit** [comment]
@grigorev-lm
Sorry. Currently we don't recommend external s3 storage, tweaking nginx config in the gateway container is possible but it require you to configure bucket policy and CORS configuration and also allow public-readable bucket access. Replace the `gateway` functionality with nginx ingress controller is possible but we haven't tried that.
