### ISSUE TITLE
fix: BUG widget load error on develop branch

### ISSUE THREAD

**Issue by Magi-Wang** [apitable/apitable#602]
**Describe the bug**
widget load error

**Screenshots**
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/5676888/226605313-703a606a-00c1-4063-9590-b7b9fadc2b75.png">
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/5676888/226605781-3867c4ff-ca31-440a-bae1-c582d9d559f3.png">
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/5676888/226605938-df1a85be-a2a9-4c5d-bfb4-a0b4097e35ba.png">

**Desktop (please complete the following information):**
 - OS: [mac]
 - Browser [chrome]

**Comment by pengjin123** [comment]
@doucheng Excuse me, you are the latest version, and this issue has been fixed in the latest version

**Comment by elonglau** [comment]
The latest docker images still not working yet. @pengjin123

**Comment by magic-cd** [comment]
@pengjin123  hi, which pull request fixed this issue?

**Comment by ratnikov-in** [comment]
Dont work
last docker version

**Comment by magic-cd** [comment]
this issue has been fixed in the latest version
