### ISSUE TITLE
feat: Any chance for postgres support? 

### ISSUE THREAD

**Issue by Charuru** [apitable/apitable#604]
I have an idea for this project.

## Why? 
All my other data and apps are in postgres

## What?
Support postgres as the data store for this project.

**Comment by arucil** [comment]
Good idea! We will consider supporting pg and maybe even more databases.

**Comment by rickylabs** [comment]
Any news on PG support ?

**Comment by mmospanenko** [comment]
will be great

**Comment by traderpedroso** [comment]
any update for PG?

**Comment by mr-kelly** [comment]
> any update for PG?

No plan for this
