### ISSUE TITLE
fix: BUG  search feature There are two entries, and  image load error at the latest version

### ISSUE THREAD

**Issue by Magi-Wang** [apitable/apitable#607]
**Describe the bug**
search feature There are two entries, and  image load error

**Screenshots**
<img width="694" alt="image" src="https://user-images.githubusercontent.com/5676888/226816484-4617c3d6-6e12-4819-beb6-df7b868aae89.png">
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/5676888/226816557-08b683d0-0a95-4ac2-aec8-412801c27a01.png">

**Desktop (please complete the following information):**
 - OS: [MAC]
 - Browser [edge]

**Comment by pengjin123** [comment]
@doucheng Thank you for your feedback. Please let me know when the problem is fixed
