### ISSUE TITLE
question: macOS install failure

### ISSUE THREAD

**Issue by shinnqy** [apitable/apitable#612]
## Any questions?

macOS arm64, failed when run `make install`. Would anyone help me resolve this?

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/15121888/226857804-68ba0853-d229-4212-b10d-5d719db5e3a1.png">

**Comment by pengjin123** [comment]
@yort-feng Please help me check, thank you

**Comment by zoe-icu** [comment]
@shinnqy This appears to be caused by the plugin not being downloaded correctly. Please try this command ` cd backend-server && ./gradlew clean build --no-build-cache -x test --stacktrace `

**Comment by shinnqy** [comment]
Hi all. Follow up: I resolved this by using `Rosetta`
