### ISSUE TITLE
feat: 机器人的触发条件需要扩充

### ISSUE THREAD

**Issue by cloud0072** [apitable/apitable#614]
I have an idea for this project.

## Why? 
许多功能需要在更多条件下触发

## What?
新增机器人触发条件
例如 数据删除时触发，数据新增前触发

**Comment by ChambersChan** [comment]
Hi. @cloud0072 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

- Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
- Describe your problem in English (Translate by software is OK).
- Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
