### ISSUE TITLE
feat: 自动生成ID的逻辑可以自定义，或提供更多的预设项

### ISSUE THREAD

**Issue by cloud0072** [apitable/apitable#615]
I have an idea for this project.

## Why? 
自动添加行时需要一个ID，或者一个流水号，或者允许调整 recordId 的生成逻辑
英文的uuid并不能满足许多场景的需要

## What?
希望可以通过api接口获取id，或者提供公式，生成id
也可以考虑提供更多的预设 例如雪花id 流水号，自增id

## How?

**Comment by ChambersChan** [comment]
Hi. @cloud0072 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

- Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
- Describe your problem in English (Translate by software is OK).
- Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
