### ISSUE TITLE
feat: 用户管理相关功能

### ISSUE THREAD

**Issue by china-powers** [apitable/apitable#617]
1. 用户维护功能，增删改查。
2. 可否禁止注册
3. 可否能够去除修改密码验证邮箱验证码

## Why? 

1. 需要管理网站注册用户
2. 不开发注册功能，管理员后台添加
3. 纯离线环境使用，无法发送验证码

**Comment by ziqiangai** [comment]
This is a good question. For the self-host edition, we may not want their server resources to be borrowed, commonly known as "薅羊毛".

**Comment by china-powers** [comment]
> 

离线环境去除一些在线功能也是需要的，纯内网环境无法使用互联网功能。用户一般也是人工管理。邮件验证功能无法使用

**Comment by ChambersChan** [comment]
Hi. @MX8CLUB 

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

- Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
- Describe your problem in English (Translate by software is OK).
- Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
