### ISSUE TITLE
fix: attachments not stored on ubuntu server

### ISSUE THREAD

**Issue by iovinoludovico** [apitable/apitable#627]
**Describe the bug**
Using the described installation script on ubuntu server apiTable is installed but attachments and images cannot be stored.

**To Reproduce**
Install using the script curl https://apitable.github.io/install.sh | bash
try to upload an attachment in a datasheet

**Expected behavior**
The attachment should be stored and attached to the cell of the datasheet

**Desktop (please complete the following information):**
 - OS: ubuntu server 22.04
 - Browser  chrome

**Additional context**
By using this script : sudo docker run -d -v ${PWD}/.data:/apitable -p 80:80 --name apitable apitable/all-in-one:latest

the attachments work but some features are not available.

**Comment by pengjin123** [comment]
@iovinoludovico Thank you for your feedback,we have assisgned relevant colleagues to follow up this issue

**Comment by pengjin123** [comment]
@networkhermit Could you please help me check? Thank you

**Comment by networkhermit** [comment]
@iovinoludovico

Make sure you have the following environment variables in .env, add them and run `docker compose up -d` if they are missing:
```text
ASSETS_LTD_BUCKET=assets
ASSETS_LTD_URL=assets
```
