### ISSUE TITLE
question: Fail to access '/' while not error logging in terminal

### ISSUE THREAD

**Issue by shinnqy** [apitable/apitable#628]
## Any questions?

When I run `next.js` app (aka `make run 3`), not error found in terminal.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/15121888/227304025-dc8f697f-4bba-4202-8d2e-2cc4c278b9f1.png">

However, when I open the url `localhost:3000` printed in terminal, it show 500. Does anyone know what's going on?
![image](https://user-images.githubusercontent.com/15121888/227303947-b0586d61-b492-4426-bda3-fe1f1160e83b.png)

**Comment by nagisakon** [comment]
Please check whether the Java project has been started.

**Comment by shinnqy** [comment]
This issue occurs in my maoOS arm64. In my windows laptop, even if I only start `next.js`, it still have no error and can access the landing page.
