### ISSUE TITLE
fix: api request post method doesn't support create new option of single select

### ISSUE THREAD

**Issue by Niko030303** [apitable/apitable#630]
**Describe the bug**
API request post method doesn't support creating the new options of single select

**To Reproduce**
1. Use postman to create a request to create a record containing a single select field
2. create a new option for single select 

**Expected behavior**
support creating a new option of single select

**Screenshots**
![image](https://user-images.githubusercontent.com/82041918/227462176-02c37a62-59b5-4e43-b980-17dc53f5c2a0.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yort-feng** [comment]
already fixed by [bug: Fusion新增记录接口响应添加数据失败#4140](https://github.com/vikadata/vikadata/issues/4140)

![Image](https://user-images.githubusercontent.com/7292727/231104220-305fff57-1946-42f1-8a4d-a7122970dfdc.jpg)

**Comment by sqkkyzx** [comment]
![1605f412271149dbec899732e5e8bef](https://github.com/apitable/apitable/assets/77138105/74fad7d5-a01d-48c6-a103-2106db1aef83)

@yort-feng

**Comment by arucil** [comment]
@sqkkyzx Sorry, I couldn't reproduce this error. What's the structure of your table?

**Comment by sqkkyzx** [comment]
> @sqkkyzx Sorry, I couldn't reproduce this error. What's the structure of your table?
#### 复现方式：
1、新建表，添加一个新的单选字段，单选字段中不设置任何可选值。
2、使用API创建一行数据，会返回此错误。

#### 具体表现：
经长期观察，此 BUG 不定期会重现。大部分时间通过API创建行时，会自动创建选项。但最近几天时常观察到日志中出现此错误，导致数据未能及时创建。

#### 期望：
关于单选和多选，当提交值不在选项列表时，如何处理提交的数据（究竟是返回错误，还是会自动新增选项），有一个明确的说明。目前似乎隔几天能够自动新增，再隔几天会返回错误。

- 如果能够自动更新选项，请保持该API能够持续稳定的运行。
- 如果该API定义为不能自动更新选项，请提供新增选项的API。

开放API是贵司宣传的主要优势，希望在此功能上，能够保持稳定，而非在一个功能上摇摆不定，导致用户需要频繁更改表字段类型，频繁更改业务代码。

**Comment by arucil** [comment]
@sqkkyzx Fixed in v0.23.0-alpha
