### ISSUE TITLE
feat: new record trigger (polling on records)

### ISSUE THREAD

**Issue by abuaboud** [apitable/apitable#635]
I would like to express my appreciation for this wonderful project. I am currently working on creating a connector to apitable in [activepieces](https://github.com/activepieces/activepieces), an automation software.

As I am looking to build a trigger for new records, I went with the polling option. In order to achieve this, I need one of the following options:

1- Get records listed in descending order by either "createdAt" or "updatedAt".
2- Get records that have been updated after a certain timestamp.

After reviewing the documentation, I was unable to locate either of the options mentioned. I attempted to use the sort field "{"order": "desc", "field": "createdAt"}", but it did not work.
https://developers.apitable.com/api/reference/#tag/Record/operation/get-records

Thank you for your time and assistance.

**Comment by xukecheng** [comment]
Hello, you should add a "CreateBy" field to the APITable. If the field name is "create_by". You can use the following code: "{"order": "desc", "field": "create_by"}".
