### ISSUE TITLE
问题：问答...

### ISSUE THREAD

**Issue by syon2019** [apitable/apitable#636]
## 有问题吗？
请问apitable支持一次开发，H5、钉钉、企微多端应用吗？

**Comment by nagisakon** [comment]
hi, @syon2019 
Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

- Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
- Describe your problem in English (Translation is OK).
- Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
