### ISSUE TITLE
question: Cannot sign in with default email and password

### ISSUE THREAD

**Issue by balthild** [apitable/apitable#655]
The `README.md` says:

> Then open [http://localhost:80](http://localhost/) in your browser to visit it. (default username `admin@apitable.com` and password `Apitable2022`)

However, the server says it's wrong:

![image](https://user-images.githubusercontent.com/2662758/228363879-1f1475f1-6e85-49b1-aae9-04b35d12b9d5.png)

I have tried `rm -rf ./.data` and let the server to re-initialize, but it does not work.

**Comment by ChambersChan** [comment]
Sorry. We removed the default account in the new version, because registration is now supported.

The description in the readme is wrong, we will arrange to fix it immediately.

**Comment by balthild** [comment]
Oh, I see. Thank you!

**Comment by NN-Binary** [comment]
How to block signups from random users? 2 people registered on our server with the signup working
