### ISSUE TITLE
feat: build a language model application with LangChain

### ISSUE THREAD

**Issue by yort-feng** [apitable/apitable#666]
I have an idea for this project.

## Why? 

LangChain provides developers with the ability to create chains that integrate with external data sources for generation purposes. This feature enables the generation of text based on specific data rather than the generic data used for training language models .

There are six main areas that LangChain is designed to help with. These are, in increasing order of complexity

1. LLMs and Prompts
2. chains
3. Data Augmented Generation
4. Agents
5. Memory
6. Evaluation

## What?

build a language model application with LangChain

## How?

- [x] Learn how LangChain works and it's use cases
- [x] build an llms app demo with `openapi-agent-toolkit` @xukecheng ——[Experience of OpenAPI](https://vikadata.feishu.cn/docx/UTgoduNwkoWxqrxwlVxc8WCinrc)
- [x] build an APITable Agent Toolkit of getting spaces/nodes/fields/records @xukecheng —— [APITable Agent Toolkit](https://github.com/xukecheng/apitable_agent_toolkit)
- [x] optimizing the prompt and accurate generation of creating a new datasheet @yort-feng 
- [ ] convert text to generate a CRM system with the APITable agent toolkit and template @xukecheng 
- [x] convert text to generate a CRM system with NLA(openapi and template) @yort-feng 
- [ ] combine agents and vectorstores @yort-feng 
- [ ] fine-tune the APITable model @xukecheng 
- [ ] docs: AI creation of datasheets/system technical solutions @yort-feng 
- [ ] feed OpenAI with the existing 200+ templates as training data with embeddings @yort-feng 
- [ ] docs: statistical analysis requirements for data @xukecheng

**Comment by xukecheng** [comment]
There is currently a new way to build an llms app demo without openapi-agent, demo repo: https://github.com/xukecheng/apitable_agent_toolkit.
