### ISSUE TITLE
fix: docker is not stable for running backend server on M1 chip MacBook

### ISSUE THREAD

**Issue by ozkalai** [apitable/apitable#67]
**Describe the bug**

I am attempting to set up the **API Table** project on my local development environment and have followed the developer guide to ensure that all dependencies are properly installed. However, when running `docker compose up -d`, in the terminal, the containers for  `apitable-backend-server-1 ` and `apitable-init-db-1` are stuck in a waiting state and take an excessively long time to start up. I am seeking assistance in resolving this issue as I am unable to properly run the project.

**To Reproduce**
1.  clone the project to your local `git clone https://github.com/apitable/apitable.git`
2. go to project folder : `cd apitable` 
3. run command on your termianl: `docker compose up -d`

**Expected behavior**
The expected behavior of the **API Table** project is to start up the backend server without any issues. However, the current behavior is that the containers for apitable-backend-server-1 and apitable-init-db-1 are taking an excessively long time to start up and are stuck in a waiting state. This prevents the project from running as intended and requires resolution in order to proceed.

**Screenshots**

![Screen Shot 2022-12-28 at 19 02 23](https://user-images.githubusercontent.com/75166276/209839906-12b8c2dc-4e59-4da9-9a58-aaf336382040.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey Version 12.4 

**Additional context**
I am using a MacBook Pro with an M1 chip and a total of 16GB of memory. The M1 chip has a total of 8 cores

**Comment by mr-kelly** [comment]
Roger that. We will fix it ASAP.
As a measure to strengthen the stability of the system, we are planning to build a dual image (ARM64 + AMD64).

FYI. @networkhermit

**Comment by vinyll** [comment]
A workaround for me is to use [Multipass](https://multipass.run/) and run ApiTable in it.

**Comment by nevertoday** [comment]
求m1 m2 方案！

**Comment by networkhermit** [comment]
Let's track this issue in https://github.com/apitable/apitable/issues/66.
