### ISSUE TITLE
question: Could I upload custom widgets on open-source apitable?

### ISSUE THREAD

**Issue by SuLingGG** [apitable/apitable#672]
## Any questions?

I found this widget is suite for me:

https://github.com/kwp-lab/vikadata-widget-docx-generator

Add I notice that the apitable documentation allows developers to upload widgets.

But when I run apitable locally by docker-composed and try to add a custom widget, I can't see the custom widget tab, and I can't find instructions in the documentation on how to display the hidden tab.

I'm pretty sure my current user is the master administrator, and when I tried to invite another member into my space and login his account, I couldn't find a button in the form to create a widget, too.

Is this feature available on the self-built version of apitable?
I've been trying to find instructions that enable the custom widgets on documentation for half an hour but I still can't find it...

**Comment by ChambersChan** [comment]
Please wait. We are opening up this part of the function.

**Comment by SuLingGG** [comment]
Thanks for the reply! 
Looking forward to the widget feature opening to everyone~

**Comment by zhuatuyu** [comment]
Same question, is there a specific timetable?
