### ISSUE TITLE
question: Whether there are plans to add management functions in the future?

### ISSUE THREAD

**Issue by CheeseBottle** [apitable/apitable#673]
## Any questions?

Are there any plans to add administrator functions later? For example, it is possible to prohibit users from registering, only administrators can add accounts, and retrieve accounts of people who have left the company. If there is no such plan, how can I disable user registration at this stage?

**Comment by ChambersChan** [comment]
There are currently no plans for this.

To prohibit user registration, you can set SKIP_REGISTER_VALIDATE in the environment variable to false, and then restart the `backend-server`.
