### ISSUE TITLE
question: How do we raise the limit for the API?

### ISSUE THREAD

**Issue by RuralDependencies** [apitable/apitable#675]
With the API (self-hosted), sometimes I'm getting some errors that too many operations are going-on, how do I raise this limit? It seems hardcoded somewhere

**Comment by grigorev-lm** [comment]
Have you tried changing env `API_MAX_MODIFY_RECORD_COUNTS` in the `room-server` container?

**Comment by seo888** [comment]
> Have you tried changing env `API_MAX_MODIFY_RECORD_COUNTS` in the `room-server` container?

I can't find confi file from room-server , please tell how to change api limit. thank you~

**Comment by yort-feng** [comment]
@seo888 it's in the `.env.default` file of `room-server,` read the [developer guide](https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md#can-i-increase-request-rate-limit-of-the-api-5-by-default) doc.

**Comment by RuralDependencies** [comment]
> @seo888 it's in the `.env.default` file of `room-server,` read the [developer guide](https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md#can-i-increase-request-rate-limit-of-the-api-5-by-default) doc.

Where is the file `.env.default`? I can only see `.env`
