### ISSUE TITLE
fix: Upload attachment does not work at all

### ISSUE THREAD

**Issue by NN-Binary** [apitable/apitable#676]
**Describe the bug**
Attachments either are stopping in the middle, either stuck at zero, but they never upload, regardless of their filesize, tried 0.01MB files, 10MB files or 1GB Files.

**To Reproduce**
Create an attachment field, and upload any sort of file.

**Expected behavior**
Upload attachment working

**Screenshots**
![image](https://user-images.githubusercontent.com/47809005/229785942-02b59ebd-0c23-4fc6-bb7e-510c2d366723.png)

**Desktop (please complete the following information):**
Tried basically Firefox, Chromium, Brave, none works.

**Comment by nagisakon** [comment]
Please provide a screenshot of the network and console

**Comment by NN-Binary** [comment]
The screenshot is not needed as it happens in any self-hosted version, 3 different servers, same thing, another user seems to have declared this issue already.

Summary: On self-hosted, uploading does not work at all.

**Comment by RuralDependencies** [comment]
> The screenshot is not needed as it happens in any self-hosted version, 3 different servers, same thing, another user seems to have declared this issue already.
> 
> Summary: On self-hosted, uploading does not work at all.

This has been already fixed in the recent versions of APITable, I can say because we have installed recently the new one and it works

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
