### ISSUE TITLE
feat: expose components metrics in Prometheus format

### ISSUE THREAD

**Issue by grigorev-lm** [apitable/apitable#677]
Hello Team!
Currently I'm deploying Apitable in k8s cluster, it would be nice to get inner metrics of every component of Apitable.
Do you have any plans about metrics exposure in Prometheus format?

## Why? 
With inner metrics exposed it will be much easier to troubleshoot Apitable problems.

## What?
Inner metrics of components exposed via http in Prometheus format

**Comment by yort-feng** [comment]
Sorry, we don't have that plan recently.

**Comment by zacker330** [comment]
For backend server, I implemented the feature request at https://github.com/apitable/apitable/pull/1233
