### ISSUE TITLE
question: How to issue SSL certificate with Docker version

### ISSUE THREAD

**Issue by Shahin-rmz** [apitable/apitable#679]
Hello,
Thanks for developing/open sourcing and maintaining API table.
I am new to it and want to play around with it.
Just installed the docker version with that `curl` command and now want to use it.
I can open the `ip address` but want to have it with `SSL certificate`. in Cloudflare pointed to the IP address, but get `Error 521`.
Where is the documentation for SSL cert?
Thanks

**Comment by Shahin-rmz** [comment]
The only way to access the APItable is to paste the IP of the server in the browser.
in `.env` file I have updated the `PUBLIC_URL=http://mydomain.com`.
In cloudflare it is also pointing to the ip of the server.
still no success!

**Comment by Shahin-rmz** [comment]
just a quick question, can I use nginx proxy manager as separate and normal docker to configure ssl ?
I will deploy a nginx proxy manager, but I am not sure if it has any conflicts with APItable docker files.

**Comment by networkhermit** [comment]
@Shahin-rmz If you want to use https, you can create custom nginx block in /etc/nginx/conf.d/ and mount your certs in the gateway container. As another option, you can also try to use a https-enabled proxy server like nginx in front of apitable.

P.S. PUBLIC_URL=http://mydomain.com is invalid as that env is not for your specific purpose, setting PUBLIC_URL alone will break the application. You should leave it as empty.
