### ISSUE TITLE
How to migration space?

### ISSUE THREAD

**Issue by Luochenliang** [apitable/apitable#680]
Can Apitable migrate a space from one server to another?

The statistical function on the page can only import data, but the table format and formulas cannot be fully imported. What should I do?

**Comment by pengjin123** [comment]
@Luochenliang Currently, importing to Capitable through Excel is a text type. You can change the data type after importing, or directly create the desired type field on Capitalbe

**Comment by Luochenliang** [comment]
What I want is to import data from one server's apitable to another set of servers in a space. Is this supported? Importing a single table is too cumbersome and cannot preserve formatting

**Comment by ChambersChan** [comment]
Can see if this helps you.
https://github.com/apitable/apitable/issues/415#issuecomment-1439398882

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
