### ISSUE TITLE
feat: docker image apitable/init-appdata contains many useless file

### ISSUE THREAD

**Issue by cloud0072** [apitable/apitable#686]
docker image apitable/init-appdata contains many unreachable file

For example
space\\2022\\04\\14\\aff988f37b6849b1bf438a73d8721ae2
space\\2022\\09\\01\\6b3ede98de284077ba86cea1def717a3
space\\2021\\08\\25\\a298e18d9ac04b7ea5fd9ae5260948cf
space\\2021\\05\\26\\4db26d43c2494bc09f10afe7e71b701c

They don't have an extension but I'm guessing they're video files
But there are also files that are neither pictures nor videos
For example
space\\2023\\02\\08\\5518a8809cfb4ed996ed1bc6b7472f5e

These files are very large and not referenced in the project, add a link from project or remove them
and I found some life photos that are not related to the program either. remove them please

**Comment by ChambersChan** [comment]
Thank you for your feedback, we are optimizing him.

**Comment by ChambersChan** [comment]
This problem has been optimized in the new version, but there are still some redundant files for the environment that has been deployed earlier.
If you don’t use many attachment in the deployed environment, you may consider clearing the minio data and redeploying the latest appdata.
