### ISSUE TITLE
v0.19.0-rc 版本遇到一个问题，就是 “视图被镜像后，再分享，此时打开镜像的分享链接，跳转的竟然是原始视图页面，而且还报错”

### ISSUE THREAD

**Issue by darcy168** [apitable/apitable#687]
**Describe the bug**
v0.19.0-rc 版本遇到一个问题，就是 “视图被镜像后，再分享，此时打开镜像的分享链接，跳转的竟然是原始视图页面，而且还报错”。

**To Reproduce**
1. 对某个视图创建镜像；
2. 对这个镜像创建分享链接；
3. 浏览器中打开分享链接；

**Expected behavior**
正确打开镜像页面的分享链接；
**Screenshots**
![image_2023_04_09T02_31_15_113Z](https://user-images.githubusercontent.com/76679710/230751652-49a70779-e825-4292-be6c-cd1da01ac923.png)

**Comment by ChambersChan** [comment]
Hi. @darcy168 . Thank you for your feedback, we are repairing him.

Consider the reading experience of others in the community.
Please follow these instructions to submit your issues:

- Follow the issue [template](https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&template=bug_report.md&title=fix%3A+BUG...).
- Describe your problem in English (Translate by software is OK).
- Also you can go into our [Discord zh-CN channel](https://discord.com/channels/1016320471010115666/1057150454993272832).
