### ISSUE TITLE
fix: cascader missing text

### ISSUE THREAD

**Issue by nagisakon** [apitable/apitable#692]
**Describe the bug**

**To Reproduce**
Version:0.20.0
cascader missing text.

![image](https://user-images.githubusercontent.com/49678762/230876331-e5a310dc-ca82-4343-86d7-9b47a689fe9e.png)
![OWnZV1pf0X](https://user-images.githubusercontent.com/49678762/230876262-d463a237-04f5-4ce5-b6f0-14d663cc3dff.jpg)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wangkailang** [comment]
fixed
