### ISSUE TITLE
could not compile room-api

### ISSUE THREAD

**Issue by Superman-wc** [apitable/apitable#699]
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:2:1
  |
2 | #![feature(async_closure)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated associated function `sea_orm::sea_query::Expr::asterisk`: Please use the [`Asterisk`]
  --> src/datasheet/services/record_comment.rs:13:22
   |
13 |     .column_as(Expr::asterisk().count(), "count")
   |                      ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

For more information about this error, try `rustc --explain E0554`.
warning: `room-api` (lib) generated 1 warning
error: could not compile `room-api` due to previous error; 1 warning emitted

**Comment by arucil** [comment]
room-native-api requires nightly version of Rust to compile. Please run `rustup default nightly` to swtich to nightly Rust before compiling the project.

**Comment by fEyebrow** [comment]
run ”rustup default nightly“, it still goes wrong:
![image](https://github.com/apitable/apitable/assets/18180417/5bcd11e6-4da2-41ee-a6d5-746acec889fb)

@arucil

**Comment by arucil** [comment]
@fEyebrow That's weird, the errors indicate that you were still using stable Rust. Try running `cargo clean` in `packages/room-native-api` and then rerun `make install`?

**Comment by fEyebrow** [comment]
I changed the version of rustc-nightly. it worked.
but When I ran "make run" and selected 2. I got this error:
![image](https://github.com/apitable/apitable/assets/18180417/c335ede9-aa49-4865-9197-40b4924311ae)
How to deal with it? my mac is m1. @arucil

**Comment by fEyebrow** [comment]
I found the cause of the error:
![image](https://github.com/apitable/apitable/assets/18180417/d00cdd9e-779e-4e85-b089-ac6343f6d18c)

I reinstalled node: nvm install v16.15.0 --arch=arm64, and rerun "make install"
but, I got new error when run "make run room-serve":
![image](https://github.com/apitable/apitable/assets/18180417/8493d6cf-289d-48e5-8009-dd843d5b7854)

There is a question about it: https://stackoverflow.com/questions/70425521/what-does-symbol-not-found-in-flat-namespace-cairo-fill-mean

Looks like I need to switch rustc to the x64 version
