### ISSUE TITLE
feat: Support custom widget in APITable CE

### ISSUE THREAD

**Issue by xukecheng** [apitable/apitable#706]
I have an idea for this project.

## Why? 

Currently, APITable Cloud is already supported, but APITable Community Edition is not yet supported. Therefore, this requirement needs to be addressed.

## What?

APITable Community Edition supports custom widgets.

**Comment by ChambersChan** [comment]
- [x] widget-cli upload domain replace + content-length issue
- [x] datasheet/.env CUSTOM_WIDGET_VISIBLE=true
- [x] web-server copywriting @wmEvie 
![284087cd-9d8a-488c-a98a-7ae6fd39992d](https://user-images.githubusercontent.com/32906036/231995352-fe149ed1-333c-4a20-8541-c0fa700eb96b.jpeg)
![image](https://user-images.githubusercontent.com/32906036/231994878-cb3add0d-7f2d-460e-b7a7-611ad54f84a8.png)

**Comment by zsnmwy** [comment]
Is the custom widget include the script widget?

**Comment by wmEvie** [comment]
> Is the custom widget includes the script widget?

@zsnmwy 

No, the custom widget does not include the script widget.

The custom widget allows developers to fully use SDK capabilities to develop more apps that match business scenes and personal needs.([learn more](https://developers.apitable.com/widget/introduction))

And the Script widget will be released on the widget center next Monday.

If you want to use it now, you can try it on our [Cloud version](https://apitable.com)

To learn more about the script widget, you can check out this project: https://github.com/apitable/widget-script
