### ISSUE TITLE
fix: The icon of the widget is not displayed

### ISSUE THREAD

**Issue by xukecheng** [apitable/apitable#720]
**Describe the bug**
The icon of the widget is not displayed

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/29099863/232807780-b2a66471-f51c-4b6b-bc2e-7b99131ddf9b.png">

![CleanShot 2023-04-18 at 22 23 07@2x](https://user-images.githubusercontent.com/29099863/232807402-195e3ab2-a3ed-41dd-a194-ce0e03f2d554.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Edge
 - Version: develop branch

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ChambersChan** [comment]
fixed.
