### ISSUE TITLE
fix: BUG Widgets dont display

### ISSUE THREAD

**Issue by ratnikov-in** [apitable/apitable#721]
**Describe the bug**
In new release 0.20.0 Error occurred when running the widget
**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1306" alt="Снимок экрана 2023-04-18 в 19 58 56" src="https://user-images.githubusercontent.com/37483261/232850348-b64c4c63-1cb2-472a-bd06-5588e442a17f.png">

In env file:
```
VK_ASSETS_LTD_BUCKET=assets
VK_ASSETS_LTD_URL=assets


ASSETS_LTD_BUCKET=assets
ASSETS_LTD_URL=assets
OSS_BUCKET_NAME=assets

DATA_PATH=.
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ratnikov-in** [comment]
<img width="548" alt="Снимок экрана 2023-04-18 в 20 15 53" src="https://user-images.githubusercontent.com/37483261/232854288-7c681694-b3c9-49c4-bbae-abcbac403b0f.png">

**Comment by ChambersChan** [comment]
This appears to be the domain name now, which cannot be forwarded to the oss service via the `/assets` route.
You can try to modify the nginx configuration,
or modify the value of `ASSETS_LTD_URL` if the oss service is configured with a CDN domain.

**Comment by ratnikov-in** [comment]
@ChambersChan can you please tell me what exactly needs to be changed in the env parameters in order for it to work?  Is there a more detailed description of the variables?

**Comment by ratnikov-in** [comment]
@ChambersChan can you please tell me what exactly needs to be changed in the env parameters in order for it to work?  Is there a more detailed description of the variables?

**Comment by ChambersChan** [comment]
@ratnikov-in Refer to my previous reply, because after you configure the service domain name, the resource file link cannot access your oss service. You need to modify your routing rules, or directly configure a dedicated domain name for the storage service

**Comment by ratnikov-in** [comment]
@ChambersChan if directly configure a dedicated domain name for the storage service modify OSS_HOST or ASSETS_LTD_URL?

**Comment by ratnikov-in** [comment]
And please tell me how corrcet connect SSL to APITable?

**Comment by ChambersChan** [comment]
> @ChambersChan if directly configure a dedicated domain name for the storage service modify OSS_HOST or ASSETS_LTD_URL? Because if I modify ASSETS_LTD_URL dont work

@ratnikov-in Yes. This requires restarting `room-server` and `backend-server` after modify OSS_HOST or ASSETS_LTD_URL.

**Comment by ChambersChan** [comment]
> And please tell me how corrcet connect SSL to APITable?

Sorry. I don't know much about this.

**Comment by ratnikov-in** [comment]
> > @ChambersChan if directly configure a dedicated domain name for the storage service modify OSS_HOST or ASSETS_LTD_URL? Because if I modify ASSETS_LTD_URL dont work
> 
> @ratnikov-in Yes. This requires restarting `room-server` and `backend-server` after modify OSS_HOST or ASSETS_LTD_URL.
If I modify ASSETS_LTD_URL after restart i see
<img width="548" alt="Снимок экрана 2023-04-19 в 09 42 51" src="https://user-images.githubusercontent.com/37483261/232988676-0349d034-234c-4a83-bc89-61ea66138a18.png">

**Comment by ChambersChan** [comment]
> > > @ChambersChan if directly configure a dedicated domain name for the storage service modify OSS_HOST or ASSETS_LTD_URL? Because if I modify ASSETS_LTD_URL dont work
> > 
> > 
> > @ratnikov-in Yes. This requires restarting `room-server` and `backend-server` after modify OSS_HOST or ASSETS_LTD_URL.
> 
> If I modify ASSETS_LTD_URL after restart i see <img alt="Снимок экрана 2023-04-19 в 09 42 51" width="548" src="https://user-images.githubusercontent.com/37483261/232988676-0349d034-234c-4a83-bc89-61ea66138a18.png">

This does not seem to have anything to do with resource file loading.

**Comment by ratnikov-in** [comment]
My root problem is widgets not working

**Comment by ratnikov-in** [comment]
@yort-feng Maybe you can help?

**Comment by ChambersChan** [comment]
Sorry. I mistook it as .js resource loading 500. The problem has reappeared, it is a problem with the latest .js of the widget.

**Comment by ratnikov-in** [comment]
@ChambersChan thanks, friend tell me how fix this problem?

**Comment by ChambersChan** [comment]
@ratnikov-in This problem has been fixed, just restart the latest appdata service.

**Comment by ratnikov-in** [comment]
> @ratnikov-in This problem has been fixed, just restart the latest appdata service.

Dont work

**Comment by deadnessking** [comment]
Same problem，restart the latest appdata service dont work

**Comment by sergeypugachov** [comment]
Same problem. Checked with v0.22.0-beta images

Looks, like instead of JS html of SPA is returning when loading widget
