### ISSUE TITLE
fix: On the "Create widget" dialog box, the button is disabled

### ISSUE THREAD

**Issue by vibl** [apitable/apitable#723]
**Describe the bug**
On the "Create widget" dialog box (the one with the list of templates: Hello World, TodoMVC, etc.), the button "Create widget" is disabled, even after selecting a template.

**Screenshots**
![Screenshot_20230420_174332](https://user-images.githubusercontent.com/628818/233418349-e7854a02-4c62-4a59-a2ad-fdacf31cca1d.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser: Chrome 112
 - Version: 22

**Additional context**
I use the docker compose version and I have just updated the images and re-created the containers (`git pull && docker-compose pull && docker-compose up -d --remove-orphans`). So I suppose I have the latest version of APITable.

**Comment by Sky-FE** [comment]
@vibl You need to fill in the name of the widget to create a custom widget.
