### ISSUE TITLE
question: Q&A...

### ISSUE THREAD

**Issue by baiy513** [apitable/apitable#727]
有人碰到这个问题吗，webserver开发环境起来占6g的内存，启动非常慢，第一次访问页面也非常慢，改点代码就要重启，动不动就挂掉。

**Comment by arucil** [comment]
This is a known issue https://github.com/apitable/apitable/issues/323, unfortunately we don't have enough energy to address this problem recently. I can only give you some suggestions:

1. When running apitable, close applications that consume memory, for example VSCode, instead use a lightweight text editor to modify code.
2. If you rely on an IDE to modify code, don't run web-server and the IDE at the same time. If you want to modify the code, stop web-server first, then start your IDE, modify code, then close the IDE, then restart web-server.

It's indeed a PITA, I'm sorry.😨

**Comment by yort-feng** [comment]
please follow this issue: https://github.com/apitable/apitable/issues/323
