### ISSUE TITLE
question: [all-in-one] Unable to connect to the database

### ISSUE THREAD

**Issue by lumos0** [apitable/apitable#733]
## Any questions?

首次体验all-in-one关闭后，再次启动container时faild to start 

docker log shows：

Unable to connect to the database

open docker terminal

all-in-one use pm2 to manage processes, so 
```
pm2 monit
```

定位到原因

```
4-24T10:17:09.944678Z 0 [ERROR] [MY-010259] [Server] Another process with pid 137 is using unix socket    │
Unable to setup unix socket lock file.               │
mysql > 2023-04-24T10:17:09.944692Z 0 [ERROR] [MY-010119] [Server] Aborting
```

# solution：
remove mysql socket lock file:   /var/run/mysqld/mysqld.sock.lock 
( lock file directory configured in  /etc/my.cnf file)

restart mysql:
`pm2 restart mysql`

**Comment by arucil** [comment]
Thanks, your solution will benefit future visitors with similar problems.
