### ISSUE TITLE
fix: socket service isn't started

### ISSUE THREAD

**Issue by zsp419** [apitable/apitable#746]
The roomserver failed to start with the error message "socket service isn't started", which causes the inability to edit tables. How should I handle this?
![image](https://user-images.githubusercontent.com/27196467/235034041-f79e67ff-fe1a-429d-912e-4689954fb609.png)

**Comment by mr-kelly** [comment]
@zsp419 Could you provide more detailed logs of your program during the boot stage?

**Comment by zsp419** [comment]
[roomserverlog.txt](https://github.com/apitable/apitable/files/11350626/roomserverlog.txt)
This is the complete room-server startup log, please help to check it

**Comment by zsp419** [comment]
![image](https://user-images.githubusercontent.com/27196467/235074272-26c0edc1-3559-4aa2-ac8a-af56969336a6.png)
This is a port occupancy situation and does not appear to be a port conflict

**Comment by ziqiangai** [comment]
Is your redis service working? `room-server` will register its own IP information in redis when it starts.
<img width="438" alt="image" src="https://user-images.githubusercontent.com/18455767/235084504-0e8b2149-5079-4e8e-9661-63e6f23eed12.png">

**Comment by zsp419** [comment]
Yes, redis is working, otherwise backend-server would not start, but it can start
![image](https://user-images.githubusercontent.com/27196467/235097643-ff698b0b-1a13-4b18-a8e0-424d60f91a98.png)

**Comment by ziqiangai** [comment]
> [roomserverlog.txt](https://github.com/apitable/apitable/files/11350626/roomserverlog.txt) This is the complete room-server startup log, please help to check it


I see warning messages in the logs, This warn message is thrown in the following code: 


https://github.com/apitable/apitable/blob/de73edad094601bf820a06a24493008471dccac5/packages/room-server/src/grpc/services/grpc.socket.service.ts#L293-L300

But it will not block the program from starting. Could it be other problems that make the program unable to start? Is there any omission in the log? Because normally, we can see such a log generate from [here](https://github.com/apitable/apitable/blob/de73edad094601bf820a06a24493008471dccac5/packages/room-server/src/socket/grpc/client/grpc.client.proxy.ts#L51-L79):
```text
...
[ROOM_SERVER] Info      2023-05-03 22:42:06.816 [ClientProxy] Subscription to [apitable:room_pool:local] successful - { channel: 'apitable:room_pool:local', count: 1 }
...
```

**Comment by yort-feng** [comment]
@zsp419  Which script did you use to start the `room-server`? Please ensure the variable `ENABLE_SOCKET` value is `true`. BTW, `socket-server` would use the `3007` port.

**Comment by zsp419** [comment]
![image](https://user-images.githubusercontent.com/27196467/236083185-7c5b9755-58f9-4412-bf79-35f86116b32f.png)
我就直接按照咱们的文档运行的，用的什么脚本是什么意思呢

> @zsp419 Which script did you use to start the `room-server`? Please ensure the variable `ENABLE_SOCKET` value is `true`. BTW, `socket-server` would use the `3007` port.

**Comment by zsp419** [comment]
> > [roomserverlog.txt](https://github.com/apitable/apitable/files/11350626/roomserverlog.txt) This is the complete room-server startup log, please help to check it
> 
> I see warning messages in the logs, This warn message is thrown in the following code:
> 
> https://github.com/apitable/apitable/blob/de73edad094601bf820a06a24493008471dccac5/packages/room-server/src/grpc/services/grpc.socket.service.ts#L293-L300
> 
> But it will not block the program from starting. Could it be other problems that make the program unable to start? Is there any omission in the log? Because normally, we can see such a log generate from [here](https://github.com/apitable/apitable/blob/de73edad094601bf820a06a24493008471dccac5/packages/room-server/src/socket/grpc/client/grpc.client.proxy.ts#L51-L79):
> 
> ```
> ...
> [ROOM_SERVER] Info      2023-05-03 22:42:06.816 [ClientProxy] Subscription to [apitable:room_pool:local] successful - { channel: 'apitable:room_pool:local', count: 1 }
> ...
> ```

![apitable](https://user-images.githubusercontent.com/27196467/236084062-a310d1ee-c38c-4149-81ae-9f60cdf1ae23.gif)
I recorded a screen. Look at that. The whole boot process

**Comment by ziqiangai** [comment]
Hi @zsp419 , I think there is no problem. You can open two more terminals, run the `make run` command, and select 1 and 3 respectively. After the two programs start, visit [http://localhost:3000](http://localhost:3000) and have a try?

**Comment by zsp419** [comment]
> Hi @zsp419 , I think there is no problem. You can open two more terminals, run the `make run` command, and select 1 and 3 respectively. After the two programs start, visit http://localhost:3000 and have a try?

可以启动起来，也可以访问到页面，但是因为socket没有启动，导致不能正常编辑表格，问题在这里

**Comment by ziqiangai** [comment]
https://github.com/apitable/apitable/blob/de73edad094601bf820a06a24493008471dccac5/packages/room-server/package.json#L11

If the environment variable here is `false`, a screenshot like yours will appear. Did you modify the value here?

**Comment by zsp419** [comment]
@Exclamation-mark No, after git clone, I just followed the instructions without changing the configuration

**Comment by zsp419** [comment]
Re-cloned a code, according to the document operation again, has been normal,thanks

**Comment by ziqiangai** [comment]
Is the re-cloned code still cloned in the `ubuntu on wsl2` environment?

**Comment by zsp419** [comment]
@Exclamation-mark yes
