### ISSUE TITLE
fix: Error creating table datapack interface

### ISSUE THREAD

**Issue by pengjin123** [apitable/apitable#747]
**Describe the bug**
Error creating table datapack interface

**To Reproduce**
1.Log in to APITable
2.create Table

**Expected behavior**
Can create tables normally

**Screenshots**
![image](https://user-images.githubusercontent.com/108248808/235045507-03c347ba-8dfb-4f52-8619-60ee9496f8ee.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser : chrome
 - Version:  108

**Comment by yaoyi2008** [comment]
我也是，哎，期待作者或各路大神解决下

**Comment by yaoyi2008** [comment]
不过我跟你不一样的是，gitpod没问题，自己服务上用sudo docker run -d -v ${PWD}/.data:/apitable -p 80:80 --name apitable apitable/all-in-one:latest部署all-in-one或者curl https://apitable.github.io/install.sh | bash方式都会出现跟你一样的Server error的情况。

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/5906825/235093360-e0e18a64-d050-4b97-9b87-f510bd24062d.png">

**Comment by yort-feng** [comment]
@yaoyi2008 We fixed it, please try to use the newest codes of the `develop` branch
