### ISSUE TITLE
Community edition not able to upload avatar for space

### ISSUE THREAD

**Issue by lowcode101** [apitable/apitable#754]
**Describe the bug**
When trying to upload an avatar for space, it just keep loading. Uploading to attachment field is ok.

**To Reproduce**
1. Go to Space setting
2. At the big icon, click edit to upload a PNG file as avatar
3. It just keep loading

**Expected behavior**
Uploaded avatar replaced the icon

**Desktop (please complete the following information):**
 - OS: Docker running on Ubuntu 22

**Comment by pengjin123** [comment]
@lowcode101 Could you please provide the corresponding screenshots and error logs? Thank you

**Comment by lowcode101** [comment]
[apitable-logo-upload.webm](https://user-images.githubusercontent.com/130434221/235980315-dc92c36e-3f4d-4e83-9a34-8f263c19b710.webm)

Hi @pengjin123 

this is the video how I do it... as you can see the logo upload screen keep spinning

**Comment by pengjin123** [comment]
@JaneSu  Could you please help me take a look? An error was reported when uploading space station images on the cockpit page of the space station，thank you！
![image](https://user-images.githubusercontent.com/108248808/236369791-fb4a72c1-43cf-4f2f-b2af-1e11824bf428.png)

**Comment by JaneSu** [comment]
@pengjin123 
I cannot reproduce this issue, you can try.
