### ISSUE TITLE
fix: robot hooks has an error

### ISSUE THREAD

**Issue by cloud0072** [apitable/apitable#757]
**Describe the bug**

https://github.com/apitable/apitable/blob/492ab31b1bda11233c8e7a80801422b8fec133c0/packages/datasheet/src/pc/components/robot/hooks.ts#L287

triggerTypes should be replaced with actionTypes

**Comment by cloud0072** [comment]
@pengjin123

**Comment by cloud0072** [comment]
@yort-feng

**Comment by yort-feng** [comment]
already fixed, please use the latest version instead.
