### ISSUE TITLE
fix: The attachment upload is quite slow，need switch APITable.com storage service CDN from Qiniu Cloud to others

### ISSUE THREAD

**Issue by pengjin123** [apitable/apitable#759]
**Describe the bug**
The attachment upload is quite slow，need switch APITable.com storage service CDN from Qiniu Cloud to others

**To Reproduce**
1. Log in to APITable and create a Wig table
2. Upload attachments in the attachment column
3.Waiting for server response has a relatively long response time
**Expected behavior**
The attachment upload is quite slow，need switch APITable.com storage service CDN from Qiniu Cloud to others

**Screenshots**

![image](https://user-images.githubusercontent.com/108248808/236615040-62cb2fe5-706e-4e75-b53d-18ee261f6afe.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser ：chrome
 - Version :112

**Comment by paylm** [comment]
CDN has been switched to GCP.
