### ISSUE TITLE
question: An internal server error will be reported

### ISSUE THREAD

**Issue by zmf0705** [apitable/apitable#761]
![1683465158813](https://user-images.githubusercontent.com/48465152/236679669-ef69fcb8-158b-4ad4-a34f-011a2657752a.jpg)

**Comment by ziqiangai** [comment]
Would it be possible for you to kindly provide additional information about the operating environment? This would greatly assist me in understanding the context and providing a more comprehensive response. Thank you.

**Comment by zmf0705** [comment]
谢谢您的来稿，正在处理。。。

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
