### ISSUE TITLE
fix: Wrong arrangement of widget center

### ISSUE THREAD

**Issue by nagisakon** [apitable/apitable#767]
**Describe the bug**

**To Reproduce**
1. Open the 'Widget Center'
2. The widgets in the widget center list show as double rows

version: v0.20.0
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/49678762/236787331-449d9eb5-1cc8-485c-8cb6-97c7d5d172a2.png">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wangkailang** [comment]
fixed
