### ISSUE TITLE
docs: Missing Python version annotation in development environment setup

### ISSUE THREAD

**Issue by JerryWen1994** [apitable/apitable#778]
When I was setting up the development environment, I found that there was no indication of the Python version. Only when errors occurred during the setup process did I troubleshoot based on the error messages.

**Comment by arucil** [comment]
AFAIK there is no dependency on python.  Could you post the error you encountered here?

**Comment by arucil** [comment]
You are right, APITable indeed depends on Python, it is a dependecy of an direct dependency of APITable. I will add a note about the required Python version.
