### ISSUE TITLE
feat: how to close time_machine

### ISSUE THREAD

**Issue by cloud0072** [apitable/apitable#780]
I have an idea for this project.

![微信截图_20230510172428](https://github.com/apitable/apitable/assets/34976399/dccd75a3-e51e-422c-a37c-4c2e9afd43e7)

When I use the delete API to remove records, I find it takes a long time
datasheet_changeset takes up quite a lot of time, is there a switch to completely turn off time_machine?

**Comment by pengjin123** [comment]
@cloud0072 Are you doing a pressure test for delete

**Comment by cloud0072** [comment]
> @cloud0072 Are you doing a pressure test for delete

@pengjin123 Yes, I have conducted pressure tests. It takes nearly 10 seconds for room-server to query 1000 records under 100k data volume, and it takes about 5-10 seconds to delete in batches. So I'm trying to improve the performance of room-server

**Comment by yort-feng** [comment]
No, we couldn't turn off the time machine feature. Some basic operations depend on it, such as undo and redo.
