### ISSUE TITLE
feat: apitable-gateway should add gzip

### ISSUE THREAD

**Issue by cloud0072** [apitable/apitable#783]
dataPack too large and we should set gzip on

https://github.com/apitable/apitable/blob/3d0015139d091c178052226e8ce4c9add65e4272/gateway/conf.d/default.conf#LL49C42-L49C42

gzip_types application/json application/javascript text/css text/xml;

gzip on;
gzip_buffers 32 4K;
gzip_comp_level 6;
gzip_min_length 100;
gzip_disable "MSIE [1-6]\."; 
gzip_vary on;

**Comment by yort-feng** [comment]
Gzip is an optional configuration and is not necessary if you are using it locally.
