### ISSUE TITLE
fix: BUG... 描述比较模糊，@一瞬间 打开一下这个Create Issue，按格式填一下”操作步骤“和截图？方便我们直接修改

### ISSUE THREAD

**Issue by jt1151989** [apitable/apitable#787]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mr-kelly** [comment]
Invalid Issue
