### ISSUE TITLE
fix: When executing 'make install' the dependency graph cannot be satisfied.

### ISSUE THREAD

**Issue by zhengyulong-cn** [apitable/apitable#791]
I followed the official documentation to install and run this project, and when I got to `make install`, an error message was displayed:
```
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 33s 756ms
```
I tried running `yarn build:pre` separately, but the same error occured. Then I attempted to run `make clean` to clean up the data, followed by `make install`, but the error still persisted.

![shot](https://github.com/apitable/apitable/assets/50773846/ae9b10b5-4af7-48b0-8443-c169bb1bcdd5)

Node.js：v18.16.0
yarn：3.4.1
Cargo：cargo 1.71.0-nightly (26b73d15a 2023-05-09)

**Comment by arucil** [comment]
Is the `yarn.lock` file changed?

**Comment by zhengyulong-cn** [comment]
The `yarn.lock` file hasn't been modified, and I'm running on the `release/0.20.0` branch.

**Comment by arucil** [comment]
Did you install a global typescript or modify some typescript config files e.g. `common-tsconfig.json`? Also, node 16.15 is required to run APITable, please switch from node 18.16 to 16.15.

**Comment by zhengyulong-cn** [comment]
Ultimately, I fixed the issue, which was caused by incomplete modifications to the type definition files under the core package. When executing `yarn build:dst`, the type error in the core package triggered TypeScript type inference errors in other places, which eventually caused the build to be forcefully interrupted.

There are two ways to solve this problem:

1. Find the root cause and revise the type definitions one by one.
2. Modify the `tsconfig.json` configuration file to disable the TypeScript type checking errors that interrupt the build phase.

**Comment by iEricKoh** [comment]
I am having the same issue, here's more details something related with `@napi-rs` from what i saw, hopefully it helps.

![CleanShot 2023-05-27 at 16 37 23@2x](https://github.com/apitable/apitable/assets/8081074/017db9de-eebb-49c5-a845-fb1b2aea3f19)

**Comment by iEricKoh** [comment]
actually works for me now after I downgrade rust to previous version. i was at nightly-2023-05-26.

works for me after i switched it to `rustc 1.71.0-nightly (9ecda8de8 2023-04-30)`
