### ISSUE TITLE
question: How to get images when setup in local environment?

### ISSUE THREAD

**Issue by shinnqy** [apitable/apitable#800]
How to get images such as `/space/2021/12/07/aaac193704834e9a9e4af27a1535826a` in local environment? 

I run the `next.js` via `yarn run sd`.

![image](https://github.com/apitable/apitable/assets/15121888/7f0576ea-bce2-4098-958e-f19733f8c7f1)

**Comment by pengjin123** [comment]
@JaneSu Could you please help investigate? Thank you

**Comment by shinnqy** [comment]
Hi, any update?

**Comment by ziqiangai** [comment]
This problem may be caused by `init-data`, fortunately it does not affect other functions, and there is no problem in the environment of [gitpod](https://gitpod.io/#https://github.com/apitable/apitable).

We are trying to solve this problem.

**Comment by shinnqy** [comment]
Sounds good. Do we have ETA?

**Comment by shinnqy** [comment]
Hello @Exclamation-mark any update?

**Comment by ziqiangai** [comment]
Hi @shinnqy.
- pull the latest code
- execute `make run`. Start three services in sequence.

It will access the images in the `minio` service. such like [this link](http://127.0.0.1:9000/assets/space/2022/12/23/c64a745ae147495b9d1ae96d822ae891).
