### ISSUE TITLE
question: The request package URL was not found in step 2 of the initialization of the widget was loaded

### ISSUE THREAD

**Issue by johnsonchu627** [apitable/apitable#803]
执行加载小程序初始化第2步的指令报错：
D:\work\apitable>widget-cli init -t uskKAihCHY9a9LOhBoZdyrD -s spcUKmY0iABSx -h http://10.28.0.117 -c MatCode -p wpkn9AP4T0PHT -u http://10.28.0.117/widget/wpk2jJ7qZS0VG/0.0.30/25e23ab80b6e49308166655da5b7417c.zip
Response Error:
{
  config: {
    url: 'http://10.28.0.117/widget/wpk2jJ7qZS0VG/0.0.30/25e23ab80b6e49308166655da5b7417c.zip',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'X-Internal-Request': 'yes',
      'User-Agent': 'axios/0.21.4'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'arraybuffer',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  responseData: <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 3c 68 74 6d 6c 3e 3c 68 65 61 64 3e 3c 6d 65 74 61 20 63 68 61 72 53 65 74 3d 22 75 74 66 2d 38 22 2f 3e ... 24106 more bytes>
}
fetching template from http://10.28.0.117/widget/wpk2jJ7qZS0VG/0.0.30/25e23ab80b6e49308166655da5b7417c.zip... !
    Error: Request failed with status code 404

**Comment by mr-kelly** [comment]
Please follow the format: https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&projects=&template=bug_report_cn.md&title=fix%3A+BUG...

**Comment by ChambersChan** [comment]
From the resource path in the screenshot, the storage bucket configuration is missing. You can confirm whether the following two environment variables are configured, and then restart the backend server.
![image](https://github.com/apitable/apitable/assets/32906036/6e700684-0855-4647-9896-78fa001cc246)

**Comment by ChambersChan** [comment]
Hello. I close this issue first.
If you still have this problem, you can reopen this issue or feel free to contact us through [discord](https://discord.gg/5WrDWxkXE9).
