### ISSUE TITLE
fix: BUG本地化维格表在小程序初始化的第2步报错

### ISSUE THREAD

**Issue by johnsonchu627** [apitable/apitable#804]
**描述Bug**
本地化维格表在加载小程序，初始化的第2步报错找不到请求包URL:
D:\work\apitable>widget-cli init -t uskKAihCHY9a9LOhBoZdyrD -s spcUKmY0iABSx -h http://10.28.0.117 -c MatCode -p wpkn9AP4T0PHT -u http://10.28.0.117/widget/wpk2jJ7qZS0VG/0.0.30/25e23ab80b6e49308166655da5b7417c.zip
Response Error:
{
  config: {
    url: 'http://10.28.0.117/widget/wpk2jJ7qZS0VG/0.0.30/25e23ab80b6e49308166655da5b7417c.zip',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'X-Internal-Request': 'yes',
      'User-Agent': 'axios/0.21.4'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'arraybuffer',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  responseData: <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 3c 68 74 6d 6c 3e 3c 68 65 61 64 3e 3c 6d 65 74 61 20 63 68 61 72 53 65 74 3d 22 75 74 66 2d 38 22 2f 3e ... 24106 more bytes>
}
fetching template from http://10.28.0.117/widget/wpk2jJ7qZS0VG/0.0.30/25e23ab80b6e49308166655da5b7417c.zip... !
    Error: Request failed with status code 404

**重现步骤**
重现行为的步骤：
1. 前往“...”
2. 点击“...”
3. 滚动到“...”
4. 看到错误

**期望行为**
清晰简洁地描述您期望发生的情况。

**屏幕截图**
如果适用，添加屏幕截图以帮助说明您的问题。
![图片](https://github.com/apitable/apitable/assets/108623613/7ea84787-e9f3-4a4a-be50-2f129972da57)

**电脑版（请填写以下信息）：**
 - 版本号：[例如 v0.22] 21H2
 - 操作系统：[例如 iOS]  win10
 - 浏览器：[例如 Chrome，Safari] Edge

**智能手机（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 设备：[例如 iPhone6]
 - 操作系统：[例如 iOS8.1]
 - 浏览器：[例如内置浏览器，Safari]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by nagisakon** [comment]
duplicate of https://github.com/apitable/apitable/issues/803
