### ISSUE TITLE
code seems to be quite bloated

### ISSUE THREAD

**Issue by weizongzuo** [apitable/apitable#805]
Your code seems to be quite bloated, causing high performance overhead and significant lag during startup. It is even leading to overheating issues on MAC laptops, resulting in noticeable sluggishness.

**Comment by arucil** [comment]
This is a known issue #323, the dev mode of web-server consumes a lot of cpu and ram, we are gradually optimizing this problem.

**Comment by arucil** [comment]
Last week we optimized the linting of web-server and reduced the cpu & ram consumption.
