### ISSUE TITLE
fix: 外部网站引用附件列的图片地址，无法显示

### ISSUE THREAD

**Issue by tianluvika** [apitable/apitable#807]
**描述Bug**
外部网站引用附件列的图片地址，无法显示

**重现步骤**
1. 复制附件列的图片地址
2. 微信小程序封面引用图片地址
3. 图片无法显示

**期望行为**
能看到看图片

**屏幕截图**
![8f1ad7a8-986f-4a15-b2ee-dd7adf2bf223](https://github.com/apitable/apitable/assets/108800382/56a7f61e-11c4-4e98-8bce-b309f5d37e82)

**其他上下文**
无

**Comment by ziqiangai** [comment]
Are you having this problem with `apitable.com` ?

**Comment by tianluvika** [comment]
oh，it's the problem with vika.cn, I submited in the wrong place

**Comment by JaneSu** [comment]
It is currently not supported to be used as an image hosting service in order to prevent theft.
cc @pengjin123
