### ISSUE TITLE
fix: Failed to set other languages

### ISSUE THREAD

**Issue by nagisakon** [apitable/apitable#810]
**Describe the bug**

**To Reproduce**
version: 0.21.0
1. Set the language as japanese
2. Successfully switched to japanese language environment
3. Set other languages like korean、italian
4. Set successfully and refresh, the language environment restores to japanese

![dPo2os1DTb](https://github.com/apitable/apitable/assets/49678762/95faa117-7aed-42ea-9a7c-2216cdbd6bec)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v0.20]

**Smartphone (please complete the following information):**
 - Version [e.g. v0.20]

**Additional context**

**Comment by ziqiangai** [comment]
language.mainfest.json possible problem

**Comment by ziqiangai** [comment]
The reason is that there are too many cookie keys with different path:

![img_v2_f98dab7c-9b7b-4f8f-b8df-6e7f87c85f8g](https://github.com/apitable/apitable/assets/18455767/9655972d-39a5-4ed1-a0eb-f11671e564c9)
