### ISSUE TITLE
fix: APITable field color display error

### ISSUE THREAD

**Issue by pengjin123** [apitable/apitable#811]
**Describe the bug**
APITable field color display error

**To Reproduce**
1. Open the APITable website and view the APITable logo font color on the APITable page
2. APITable font color display error

**Expected behavior**
The APITable field color needs to be displayed correctly

**Screenshots**
![image](https://github.com/apitable/apitable/assets/108248808/50e37804-d1ca-4069-9f86-4a0824ccd27e)

**Desktop (please complete the following information):**
 - Version ：v0.21.0-alpha+1305.4981062261.f40a2189774907ea82c20a965bf767481f0010f9
 - OS: win10
 - Browser: chrome

**Comment by wangkailang** [comment]
fixed
