### ISSUE TITLE
fix: banner Image loading failed

### ISSUE THREAD

**Issue by pengjin123** [apitable/apitable#812]
**Describe the bug**
 banner Image loading failed

**To Reproduce**
1.Log in to the APITable page to check if the image has been successfully loaded
2. All banner images failed to load
**Expected behavior**
The image needs to be loaded successfully

**Screenshots**
![image](https://github.com/apitable/apitable/assets/108248808/0815d573-6e4c-4559-80b1-ac3fee61faba)
![image](https://github.com/apitable/apitable/assets/108248808/2f2aecd5-d578-4eda-bf9b-0770a8bfbe4e)

**Desktop (please complete the following information):**
 - Version ：v0.21.0-alpha+1305.4981062261.f40a2189774907ea82c20a965bf767481f0010f9
 - OS: win10
 - Browser : chrome

**Comment by ChambersChan** [comment]
Gitpod port routing problem, just open the sharing settings.
![image](https://github.com/apitable/apitable/assets/32906036/deb0bbbf-53b4-4874-8d6a-ea200255cc01)
