### ISSUE TITLE
question: May I ask what meta.view.rows in datasheet is used for? It causes a lot of network pressure when dealing with large amounts of table data.

### ISSUE THREAD

**Issue by baiy513** [apitable/apitable#815]
docs: DOCS...请问datasheet snapshot meta.view.rows是做什么用的，表格数据量大的时候给网络造成很大压力，能不能去掉,我有一个表大概一万的数据的，关联表也有一万行，视图有10来个，加载数据时简直是灾难。

**Comment by ziqiangai** [comment]
It is used to record the row data of the view, including order and other information. The front end will render the interface according to this data structure, and each view may display different row data.

The `recordId` in rows is the index of the row data, obtained from `recordMap` and then rendered,

**Comment by ziqiangai** [comment]
We have also been exploring new solutions to make the `dataPack` have higher performance, for example: https://github.com/apitable/apitable/issues/770
