### ISSUE TITLE
docs: more clearer programming languages version requirements

### ISSUE THREAD

**Issue by Fun131n** [apitable/apitable#818]
## Now

>If you are using MacOS or Linux. We recommend sdkman and nvm for managing the versions of Java and NodeJS respectively.
```
# quick install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
# quick install sdkman
curl -s "https://get.sdkman.io" | bash
# install nodejs 
nvm install 16.15.0 && nvm use 16.15.0 && corepack enable
# install java development kit
sdk env install
# install rust toolchain
curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly --profile minimal -y && source "$HOME/.cargo/env"
```

depending on the current document, I encountered the following problem

- Use the default installation of rust (stable)，java(11)，nodejs（18.16.0 LTS），some methods that are not supported in higher versions cause ‘’make install‘’ to report errors and have to take time to reinstall lower version
- It is easy to ignore the version requirements hidden inside the recommended installation method, when I get used to using "apt" to install. actually after multiple errors were reported , i come back to the document just find the version

## What documentation do you want?
There are two parts: one is the version requirement and the other is the recommend install . just like

Programming Languages
- rust toolchain (nightly)
- java 8
- nodejs 16.15.0
...

PS: if note that later versions are not supported would be the best ❤

If you are using MacOS or Linux. We recommend sdkman and nvm for managing the versions of Java and NodeJS respectively.
```
# quick install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
# quick install sdkman
curl -s "https://get.sdkman.io" | bash
# install nodejs 
nvm install 16.15.0 && nvm use 16.15.0 && corepack enable
# install java development kit
sdk env install
# install rust toolchain
curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly --profile minimal -y && source "$HOME/.cargo/env"
```

**Comment by arucil** [comment]
Thanks, I will add a clear description about the version requirement in a minute.
