### ISSUE TITLE
fix: An error occurred while running the widget

### ISSUE THREAD

**Issue by xjl8198** [apitable/apitable#820]
Use 0.20.0 version, installation method
`curl https://apitable.github.io/install.sh | bash`
Use widgets suggests the following error
![图片](https://github.com/apitable/apitable/assets/13687226/99f2eeae-56d1-4e08-ba0a-7b2619a3b8c7)

**Comment by nagisakon** [comment]
Please pull the latest code～

**Comment by xjl8198** [comment]
@nagisakon The latest code deployment failed
<img width="727" alt="Snipaste_2023-05-17_10-58-34" src="https://github.com/apitable/apitable/assets/13687226/5bda6774-4370-48fe-8728-9825b0f9d7f5">

**Comment by arucil** [comment]
The `pre-init-db` error has just been fixed by https://github.com/apitable/apitable/pull/824. Please try pulling the latest code again :D

**Comment by xjl8198** [comment]
@arucil When will the release version be updated？
