### ISSUE TITLE
fix: "expend record" by Brave is delayed

### ISSUE THREAD

**Issue by nagisakon** [apitable/apitable#821]
**Describe the bug**
"extend record" by Brave is delayed

**To Reproduce**
1. Go into datasheet
2. Click to "expend record" by mouse
3. It takes a while to respond

**Expected behavior**
Click and expand record smoothly

**Screenshots**

https://github.com/apitable/apitable/assets/49678762/40e92893-bc5e-47cb-a0d4-350b3c9022f2

**Desktop (please complete the following information):**
 - Version [e.g. v0.20] v0.21.0-release.1+vika.build3812
 - OS: [e.g. iOS] IOS
 - Browser [e.g. chrome, safari] Brave

**Smartphone (please complete the following information):**
 - Version [e.g. v0.20]

**Additional context**

**Comment by luckyyyyy** [comment]
https://github.com/apitable/apitable/blob/a6848e01549ddaf6175acc835cc8d77b90ba277e/packages/datasheet/src/pc/components/expand_record/utils.ts#L51C4-L89

The side effect of debounce caused a delayed execution of the navigation change when closing. After a quick click, the navigation was set back to its original value. This is the reason why the same ExpandRecordComponent cannot be opened again.

**Comment by wangkailang** [comment]
When the mouse hover, a tooltip will appear and the mouse will change to a finger. The mouse in the video did not focus on the expansion icon.
