### ISSUE TITLE
fix: The latest version of apitable/init-db 0.21.0 report an error

### ISSUE THREAD

**Issue by cloud0072** [apitable/apitable#822]
**Describe the bug**

git clone

make dataenv

then report an error 

![微信截图_20230517100538](https://github.com/apitable/apitable/assets/34976399/120c7f29-6632-4602-944b-6e1dee996f3a)

**Comment by pengjin123** [comment]
@ChambersChan Could you please help me take a look? Thank you

**Comment by shawndenggh** [comment]
The problem has been found for the reason, fix as soon as possible @cloud0072

**Comment by shawndenggh** [comment]
we have repair this bug just now, please try again by pulling latest code @cloud0072
