### ISSUE TITLE
question: after install how can i visit apitable in browser

### ISSUE THREAD

**Issue by liujunjia1996** [apitable/apitable#826]
i use this command in my linux server：
```
curl https://apitable.github.io/install.sh | bash
```
and it successed
and run `docker container ls` , i get this 
![image](https://github.com/apitable/apitable/assets/43411944/84a48bec-fc3d-41fc-bc29-eba18fd5ce01)

but i can't use ip adress visit the apitable 
![image](https://github.com/apitable/apitable/assets/43411944/216e1218-9d6b-4f79-9f1c-13e2a1ac3c55)

**Comment by liujunjia1996** [comment]
looks like something wrong with pri-init-db ?

![image](https://github.com/apitable/apitable/assets/43411944/a22d0b77-e7af-4c8e-b00d-5c3b322212c8)

**Comment by pengjin123** [comment]
@liujunjia1996 Can you access it using the address shown in the screenshot below
![image](https://github.com/apitable/apitable/assets/108248808/76cd1e8d-4c45-4e35-913f-6400f30aedb3)

**Comment by liujunjia1996** [comment]
> @liujunjia1996 Can you access it using the address shown in the screenshot below ![image](https://user-images.githubusercontent.com/108248808/238894642-76cd1e8d-4c45-4e35-913f-6400f30aedb3.png)

can't too. but i use all in one script and it works.
```
sudo docker run -d -v ${PWD}/.data:/apitable -p 80:80 --name apitable apitable/all-in-one:latest

```

**Comment by horrylala** [comment]
I can visit using http://localhost:80/，but when i'm using ip address,like http://xx.120.3.11 , it doesn't work, what i'm missing?

**Comment by networkhermit** [comment]
@liujunjia1996 hi, please rerun `curl https://apitable.github.io/install.sh | bash`, it should work now.

**Comment by networkhermit** [comment]
> I can visit using [http://localhost:80/，but](http://localhost:80/%EF%BC%8Cbut) when i'm using ip address,like http://xx.120.3.11 , it doesn't work, what i'm missing?

Please check your host firewall policies or cloud security groups, the [default gateway settings](https://github.com/apitable/apitable/blob/a6848e01549ddaf6175acc835cc8d77b90ba277e/docker-compose.yaml#L81) does not bind to specific ip address.

**Comment by horrylala** [comment]
> Please check your host firewall policies or cloud security groups, the [default gateway settings](https://github.com/apitable/apitable/blob/a6848e01549ddaf6175acc835cc8d77b90ba277e/docker-compose.yaml#L81) does not bind to specific ip address.

That' right,when i changed the port 80 to 8080, it works, i can use ip address or pc name.
