### ISSUE TITLE
feat:  Docker  ARM 版本镜像（pre-init-db、init-db和init-appdata）

### ISSUE THREAD

**Issue by weitanai** [apitable/apitable#828]
### **系统信息**

操作系统：macOS 13.3.1 (22E261)

芯片类型：M1 Pro

### **Node.js 版本**

Node.js：16.15.0

### **问题描述**

在使用您的开源项目时，我注意到缺少适用于 Docker  ARM 版本镜像（pre-init-db、init-db和init-appdata）。这使得在 Apple M1 芯片上无法进行适当的预初始化、初始化数据库和初始化应用数据。

### **复现步骤**

1. 在 Apple M1 芯片上使用 Docker 构建环境或执行相关的容器部署操作。
2. 检查可用的镜像列表。

### **期望行为**

我期望能够获得适用于 Docker Apple M1 芯片的 ARM 版本镜像（pre-init-db、init-db和init-appdata），以便能够在 Apple M1 芯片上进行预初始化、初始化数据库和初始化应用数据。

### **实际行为**

当前缺少适用于 Docker Apple M1 芯片的 ARM 版本镜像（pre-init-db、init-db和init-appdata），无法在 Apple M1 芯片上进行适当的预初始化、初始化数据库和初始化应用数据。

### **截图/日志**

![image](https://github.com/apitable/apitable/assets/44537075/dd6f6ebd-0dc1-4bee-9bb6-d7ebc424f493)

### **备注**

我希望您能尽快提供适用于 Docker  ARM 版本镜像（pre-init-db、init-db和init-appdata），以便能够在 Apple M1 芯片上进行预初始化、初始化数据库和初始化应用数据。非常感谢您的支持和协助！

**Comment by ziqiangai** [comment]
Hi @weitanai , Thank you for supporting APITable, we are trying to solve this problem here: https://github.com/apitable/apitable/issues/66.
