### ISSUE TITLE
fix: The API panel of apitable.com will open a blank page when you click "more"

### ISSUE THREAD

**Issue by pengjin123** [apitable/apitable#829]
**Describe the bug**
The API panel of apitable.com will open a blank page when you click "more"

**To Reproduce**
1. Log in to the apitable environment
2. Click on the "more" tab on the API panel page
3. Page Jump to Blank Page

**Expected behavior**
If you do not support viewing more, please block the 'more' tag

**Screenshots**
![image](https://github.com/apitable/apitable/assets/108248808/11ca12e5-c21e-41e4-af4f-fdf415f19fb0)

**Desktop (please complete the following information):**
 - Version ：v0.21.0-release.3+apitable.build3869
 - OS: win10
 - Browser : 118

**Comment by wangkailang** [comment]
fixed
