### ISSUE TITLE
question: How to run the Java backend individually without docker? 

### ISSUE THREAD

**Issue by Ajeet-Meena** [apitable/apitable#830]
Hi, 

I am trying to run the Java backend of the API table without the docker image? 

I think there are few bugs which I can fix. 

Help would be appreciated. Thanks!

**Comment by shawndenggh** [comment]
feel very happy about your positive, just open project in intellij idea, then run or debug without update anything, looking forward to your PR @Ajeet-Meena

**Comment by mr-kelly** [comment]
@Ajeet-Meena 
Without IDE:
```bash
make run-local

(and input 1, backend-server)
```

**Comment by Ajeet-Meena** [comment]
@mr-kelly Thanks. I am trying your approach. I am having the following error. **SocketioAutoConfiguration      : connect fail: http://127.0.0.1:3002**



Can you please help? 

<img width="768" alt="image" src="https://github.com/apitable/apitable/assets/11815048/68f224b4-e957-4dab-94e2-298f29c399be">

**Comment by arucil** [comment]
You need to start databases (mysql, redis, minio, rabbitmq) before launching backend-server, run `make dataenv`.
