### ISSUE TITLE
question: after the applet selects the form, it keeps turning in circles

### ISSUE THREAD

**Issue by cchh2277** [apitable/apitable#846]
## Any questions?
![image](https://github.com/apitable/apitable/assets/128670031/00b20726-cdd0-447a-ad6e-5ebe85c38d1b)
我看了其他人的回复说是设置
ASSETS_BUCKET=assets
ASSETS_URL=assets
但是.env从docker哪里找哇？
感谢大佬的回复~

**Comment by pengjin123** [comment]
@ChambersChan Could you please help me take a look

**Comment by cchh2277** [comment]
![image](https://github.com/apitable/apitable/assets/128670031/183070d7-4233-4d82-89d6-e049344a806a)
报错是这些

**Comment by ChambersChan** [comment]
This problem can be solved after updating the version.
