### ISSUE TITLE
docs: Improve the document to ensure the correct version for dev environment

### ISSUE THREAD

**Issue by Kane-Kuroneko** [apitable/apitable#848]
I searched everywhere to find out what the correct version of JDK I should install, but there were no results.

Did you mention it to include the version of basic tools needed in the document? Or to make the different basic tools compatible?
![image](https://github.com/apitable/apitable/assets/40685018/28c534c9-01be-412d-b85e-5d0d1bcf2c33)

**Comment by arucil** [comment]
[The developer guide](https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md) has documented all version requirements of programming languages used in APITable. For JDK, sdkman is recommended for managing its version, whose setup guide is also shown in the developer guide.
