### ISSUE TITLE
fix: After changing the username, the text inside the default icon doesn't change with the name

### ISSUE THREAD

**Issue by gilnatab** [apitable/apitable#850]
**Describe the bug**
The text inside the default icon won't change with the username.

**To Reproduce**
1. registe a new user
2. change the username
3. the text inside the default icon doesn't change 

**Expected behavior**
When the username changed the text inside the default icon changed as well.

**Screenshots**
![20230524111738](https://github.com/apitable/apitable/assets/24959800/f758bf29-26f0-427a-9858-39d14a697adb)

**Desktop (please complete the following information):**
 - Version [develop branch, local env]
 - OS: [ubuntu 20]
 - Browser [firefox]

**Comment by nagisakon** [comment]
modify member name doesn't change the text inside the default icon. maybe you can change the nick name.
![image](https://github.com/apitable/apitable/assets/49678762/e99aa030-97d6-4199-85d5-92287a651806)

**Comment by nagisakon** [comment]
For more questions, please join our discord >>> https://discord.com/invite/2UXAbDTJTX
