### ISSUE TITLE
apitable/init-db 在docker中无法运行

### ISSUE THREAD

**Issue by Green1ee** [apitable/apitable#852]
**描述Bug**
docker run apitable/init-db
clearChecksums
ERROR: The JAVA_HOME environment variable is not defined correctly, so Liquibase cannot be started. JAVA_HOME is set to "/opt/java/openjdk" and it does not exist.
ACTION=
ERROR: The JAVA_HOME environment variable is not defined correctly, so Liquibase cannot be started. JAVA_HOME is set to "/opt/java/openjdk" and it does not exist.

**重现步骤**
重现行为的步骤：
1. docker-compose up -d
卡在：
[+] Running 12/12
 ✔ Network apitable_default                Created                                                                       0.3s 
 ✔ Container apitable-rabbitmq-1           Started                                                                       2.6s 
 ✔ Container apitable-minio-1              Started                                                                       2.7s 
 ✔ Container apitable-redis-1              Started                                                                       2.6s 
 ✔ Container apitable-mysql-1              Healthy                                                                       9.6s 
 ✔ Container apitable-imageproxy-server-1  Started                                                                       2.7s 
 ✔ Container apitable-web-server-1         Started                                                                       2.7s 
 ✔ Container apitable-room-server-1        Started                                                                       8.6s 
 ✔ Container apitable-init-db-1            Exited                                                                        9.2s 
 ✔ Container apitable-backend-server-1     Created                                                                       0.2s 
 ✔ Container apitable-init-appdata-1       Created                                                                       0.2s 
 ✔ Container apitable-gateway-1            Created                                                                       0.2s
2. 经排查，发现mysql中没有创建表
4. 手动执行 docker run apitable/init-db 报错：
clearChecksums
ERROR: The JAVA_HOME environment variable is not defined correctly, so Liquibase cannot be started. JAVA_HOME is set to "/opt/java/openjdk" and it does not exist.
ACTION=
ERROR: The JAVA_HOME environment variable is not defined correctly, so Liquibase cannot be started. JAVA_HOME is set to "/opt/java/openjdk" and it does not exist.

**期望行为**
docker-compose up -d 能直接运行成功

**电脑版（请填写以下信息）：**
 - 版本号： v0.21-beta
 - 操作系统：CentOS 7

**Comment by pengjin123** [comment]
@ChambersChan Could you please help with this? Thank you

**Comment by Green1ee** [comment]
将原来的docker 和 docker compose v2.18.1 卸载之后，重新安装
`yum install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y`
之后，可以正常运行
