### ISSUE TITLE
question: Images couldn't load after uploading when using gridview~

### ISSUE THREAD

**Issue by horrylala** [apitable/apitable#853]
## Any questions?
Images couldn't load after uploading when using gridview~

<img width="1203" alt="image" src="https://github.com/apitable/apitable/assets/12706476/709c788d-9bd1-4a33-9d8d-57e70ca28d5c">

The image src path is '_/_next/image?_url=http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fspace%2F2023%2F05%2F24%2F6aeee12696bd47ec88dfa75c3431bfe3%3FimageView2%2F0%2Fw%2F180&w=3840&q=75__'

It's a little weird, and  i'm using the url path, it got 404 error.

But when i using 'http://localhost:8080/assets/space/2023/05/24/6aeee12696bd47ec88dfa75c3431bfe3?imageView2/0/w/180&w=3840&q=75',it got the right image.

So, the image uploaded success, but i got the wrong path?
How should i solve this?

**Comment by pengjin123** [comment]
@JaneSu Could you please help with this? Thank you

**Comment by horrylala** [comment]
I deployed in another machine, the error is gone away,so it maybe not the bug,so i close the issue.
