### ISSUE TITLE
fix:  invalid JSON format issue

### ISSUE THREAD

**Issue by cchh2277** [apitable/apitable#854]
**描述Bug**
机器人的BUG，新纪录创建，使用机器人同步到选定的表。
情况1：字段内容被双引号""包裹是可以的，（记录会新增）
`请求体

{ "data": "{\n \"records\": [\n {\n \"fields\": {\n \"项目\": \"情况1\"\n }\n }\n],\n \"fieldKey\": \"name\"\n}", "type": "json" }

输出

状态码

201

返回数据

{ "code": 200, "data": { "records": [ { "fields": { "项目": "情况1" }, "recordId": "rectJBVsvlnHz", "createdAt": 1684939052000, "updatedAt": 1684939052000 } ] }, "message": "SUCCESS", "success": true }`

情况2：换成/变量就不行。（记录不会新增）
`请求体

{ "data": "{\n \"records\": [\n {\n \"fields\": {\n \"项目\": ,\n }\n }\n],\n \"fieldKey\": \"name\"\n}", "type": "json" }

输出

状态码

400

返回数据

{ "error": "Bad Request", "message": "Unexpected token , in JSON at position 49", "statusCode": 400 }`

情况3："/(变量)"那么传过去的新增一条空记录。
`请求体

{ "data": "{\n \"records\": [\n {\n \"fields\": {\n \"项目\": \"\"\n }\n }\n],\n \"fieldKey\": \"name\"\n}", "type": "json" }

输出

状态码

201

返回数据

{ "code": 200, "data": { "records": [ { "fields": {}, "recordId": "rec3IZexYF8Hu", "createdAt": 1684938992000, "updatedAt": 1684938992000 } ] }, "message": "SUCCESS", "success": true }`

**Comment by pengjin123** [comment]
@wuyitaoBoomboommm Could you please help with this? Thank you

**Comment by yort-feng** [comment]
This is not a bug. The reason why the second request received a 400 response is that the request body is not in a valid JSON format, missing value for `data.records[0].fields["项目"]`.

**Comment by cchh2277** [comment]
情况2是添加的是变量 / 。所以获取不到不也是机器人的问题麽。
