### ISSUE TITLE
fix: option search in the select field shouldn't be case-sensitive

### ISSUE THREAD

**Issue by garyli27** [apitable/apitable#855]
**Describe the bug**
The option search in the select field is currently case-sensitive, which makes it difficult to search for options easily. This appears to be a bug. The most important thing is that when I publish the form to collect information, it gets stuck completely.

**To Reproduce**
see the screen recording: https://github.com/apitable/apitable/assets/55542378/75cb90b6-b375-4cde-ae31-24bea8e5e06d

**Expected behavior**
remove the case-sensitive search.

**Screenshots**
see the screen recording: https://github.com/apitable/apitable/assets/55542378/75cb90b6-b375-4cde-ae31-24bea8e5e06d

**Desktop (please complete the following information):**
 - Version [e.g. v0.20]
 - OS: [e.g. iOS] Macos
 - Browser [e.g. chrome, safari] chrome

**Comment by kwp-lab** [comment]
@garyli27  Thank you for bringing up this issue. However, after reviewing it, we have determined that this is not a bug, but rather an optimization suggestion. When we initially designed this feature, we intentionally did not ignore case sensitivity to ensure data accuracy and consistency.

That being said, we appreciate your suggestion and will definitely consider it for future optimizations. Please let us know if you have any further questions or concerns.
