### ISSUE TITLE
fix: received 401 unauthorized error

### ISSUE THREAD

**Issue by cchh2277** [apitable/apitable#857]
**描述Bug**
机器人回复插入变量错误。
变量插入JSON格式
![image](https://github.com/apitable/apitable/assets/128670031/c3296a84-afe3-475b-812e-d4cea185e207)
返回错误
![image](https://github.com/apitable/apitable/assets/128670031/0db98216-23ee-4cee-be58-7dd5ea1b826f)

**Comment by cchh2277** [comment]
不插入变量形式，也是报错的

**Comment by cchh2277** [comment]
![image](https://github.com/apitable/apitable/assets/128670031/c1fae171-2531-4f5c-ab2d-6fc2014aaa70)
z这种也是报错的

**Comment by pengjin123** [comment]
@wuyitaoBoomboommm Could you please help with this? Thank you

**Comment by cchh2277** [comment]
传固定值是可以的 改成"项目":"新项目"

**Comment by Itou-Ng** [comment]
@cchh2277 Please send me the robot action configuration, and your datasheet if possible.

**Comment by nagisakon** [comment]
Please check if your token is filled out
![image](https://github.com/apitable/apitable/assets/49678762/070413dd-0e75-4736-80e8-992e0841a17e)

**Comment by cchh2277** [comment]
New Creat
![image](https://github.com/apitable/apitable/assets/128670031/f65d2670-7cc4-4a9c-a847-7beff7cbd1fa)
![image](https://github.com/apitable/apitable/assets/128670031/0f06cefa-8d03-4bba-832e-66396f058546)

**Comment by Itou-Ng** [comment]
@cchh2277 
My operation has been successful. May you to kindly verify your configuration? Token or other.
<img width="316" alt="image" src="https://github.com/apitable/apitable/assets/105105612/1329344c-4305-4f6e-b290-56180bba5167">
<img width="312" alt="image" src="https://github.com/apitable/apitable/assets/105105612/1af00fba-461a-49d9-b862-758dadaf72bc">

**Comment by cchh2277** [comment]
ok:
![image](https://github.com/apitable/apitable/assets/128670031/b0ca280e-169c-4f8c-8e4c-79524c601656)
bad:
![image](https://github.com/apitable/apitable/assets/128670031/d28b9637-10b4-495b-8d16-cbc08a0ba8e1)
![image](https://github.com/apitable/apitable/assets/128670031/8f36847a-7176-4f99-a295-a8a0a2b6eda1)

**Comment by cchh2277** [comment]
@wuyitaoBoomboommm

**Comment by Itou-Ng** [comment]
@cchh2277 In your previous message, your operation was successful.
<img width="830" alt="image" src="https://github.com/apitable/apitable/assets/105105612/39c4d4ff-24e8-4f67-8a09-2895ab78d8c7">

**Comment by cchh2277** [comment]
but “话”is Null.
![image](https://github.com/apitable/apitable/assets/128670031/fc5517db-2f1f-483b-b779-fe7a9d819973)

@wuyitaoBoomboommm

**Comment by cchh2277** [comment]
insert is ok.but "话" data is null

**Comment by cchh2277** [comment]
i use apitable/all-in-one:v0.21.0-alpha_1338

**Comment by cchh2277** [comment]
@wuyitaoBoomboommm 
that is ok.
![image](https://github.com/apitable/apitable/assets/128670031/772ce43d-074e-4f14-af71-e8e8ae2c60e3)

that is bad
![image](https://github.com/apitable/apitable/assets/128670031/66b7e182-601d-41b1-a93e-5d528fafce83)
![image](https://github.com/apitable/apitable/assets/128670031/3732dd78-378a-417d-ba03-56f420814ec0)
