### ISSUE TITLE
feat: FEATURE...mac silicon 什么时候能完美支持？

### ISSUE THREAD

**Issue by LucaMK** [apitable/apitable#861]
I have an idea for this project.

## Why? 
> Why we need this feature？
> What is the user story for this feature? 
现在在 m1 上安装启动 会出先 异常  什么时候才能完美支持 

## What?
> Can you describe this feature in detail?
> Who can benefit from it?

**Comment by networkhermit** [comment]
We don't have first class support for apple sillicon or m1/m2, see the [comment](https://github.com/apitable/apitable/issues/66#issuecomment-1643365136) is you are interested in the now experimental multi-arch build for linux/amd64 and linux/arm64.
