### ISSUE TITLE
question: Where is the data table involving space permissions

### ISSUE THREAD

**Issue by dongdongdonglin** [apitable/apitable#866]
管理空间中用户权限是在什么位置的，感谢~
Where is the user permission in the management space, thank you~

**Comment by nagisakon** [comment]
What version are you using? The Community Edition does not support permission settings. Please use our Cloud Edition >>> https://apitable.com/

**Comment by vinyll** [comment]
This issues relates to https://github.com/apitable/apitable/issues/429#issuecomment-1473355717 where the open source (the README) doc mentions about advanced user permission while it is actually not implemented and will not be.
