### ISSUE TITLE
fix: the typeSelectItem's tooltip flickers when scrolling fast

### ISSUE THREAD

**Issue by fadeaway1680** [apitable/apitable#871]
### :children_crossing: Two cases here:
1. The typeSelectItem's tooltip flickers when scrolling fast.
2. The typeSelectItem's tooltip disappear after scrolling fast.

:thought_balloon: _How about disabling tooltip while scrolling ?_

https://github.com/apitable/apitable/assets/14851918/c45c4745-e8f6-42e5-9cf1-76f983722cd4

- macOS Monterey 12.6.5
- Chrome 113

**Comment by wangkailang** [comment]
fixed
