### ISSUE TITLE
一个改进的建议

### ISSUE THREAD

**Issue by zhaitianye** [apitable/apitable#872]
我有一个小的改进建议。

在API 功能的返回值实例里面，可否添加按层级折叠代码的功能。

目前的 API-> 示例返回值 下面是一个解析的json。希望为此增加折叠功能。

**Comment by mr-kelly** [comment]
Can you re-format the title in the the standard github issue template we provide?

**Comment by mr-kelly** [comment]
Can you re-format the title in the the standard github issue template we provide?
