### ISSUE TITLE
question: How to pull the latest code with Docker

### ISSUE THREAD

**Issue by bookz971** [apitable/apitable#875]
Hello, I would like to know how I can update apitable, I installed it with the open source version using docker?

**Comment by yort-feng** [comment]
What did you mean by updating the APITable? 

If you'd like to contribute to it, please follow the [developer guide](https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md).

**Comment by arucil** [comment]
Just update the docker image, and make sure you run docker compose in the same folder as the older version of APITable, so that the data will not be lost (`apitable/.data`).

**Comment by arucil** [comment]
We've added the instruction to upgrade APITable into [the developer guide](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW#h-how-to-upgrade-to-the-newest-release-version).

**Comment by bookz971** [comment]
je ne peux pas avoir acces au dernier liens que vous m'avez envoyer

**Comment by arucil** [comment]
Sorry I used the internal link by mistake, I have updated the link to shared link.
