### ISSUE TITLE
fix: Help Button State Transition Issue

### ISSUE THREAD

**Issue by sevi418** [apitable/apitable#877]
**Describe the bug**
When the mouse moves over the edge of the help button, the button status flickers.

**To Reproduce**
1. Go to 'https://apitable.com/workbench'
2. Hover on the help button’s edge
3. See error

**Expected behavior**
The status should switch naturally without flickering, just like the notification button does.

**Screenshots**
https://github.com/apitable/apitable/assets/91365763/dcb213b6-c458-4b28-be91-6e09535dc929

**Desktop:**
 - Version: Latest version on https://apitable.com/
 - OS: macOs Ventura 13.5
 - Browser: Brave ( v1.51.118 - (Chromium: 113.0.5672.126) arm64)

https://github.com/apitable/apitable/assets/91365763/33407b19-fd03-49e1-8d1f-e73dd98d597e

**Comment by wangkailang** [comment]
fixed
