### ISSUE TITLE
fix: When field type is long text, words are broken in CSS

### ISSUE THREAD

**Issue by sevi418** [apitable/apitable#878]
**Describe the bug**
When the field type is set to long text, CSS line breaks will break words.

**Expected behavior**
Don't break the words 

**Screenshots**
<img width="646" alt="image" src="https://github.com/apitable/apitable/assets/91365763/2b01d4bf-eeec-4f70-b56b-756789561d82">

**Desktop:**
 - Version: Latest version on https://apitable.com/
 - OS: macOs Ventura 13.5
 - Browser: Brave ( v1.51.118 - (Chromium: 113.0.5672.126) arm64)

**Comment by wangkailang** [comment]
fixed
