### ISSUE TITLE
fix: In the public sharing window, the member drop-down list will be obscured when there are too many members.

### ISSUE THREAD

**Issue by WilliamWayne7** [apitable/apitable#879]
**描述Bug**
工作目录中的文件、文件夹分享列表被弹窗覆盖

**重现步骤**
重现行为的步骤：
1. 点击工作目录里文件/文件夹右侧设置的“分享”，
2. 点击“添加成员或小组”，
3. 显示分享成员列表不完整（模拟数据不够多，不确定多个成员会不会有同样效果）

**期望行为**
分享列表可以看到1~3个完整成员或小组选项

**屏幕截图**
![e4c6d2155e06677a7d944e33b3abe7c](https://github.com/apitable/apitable/assets/69881099/43bd8f60-4257-4a17-8193-1ceeba0deb17)

**电脑版（请填写以下信息）：**
 - 版本号：[例如 v0.22]
 - 操作系统：Windows
 - 浏览器:：Chrome

**Comment by wangkailang** [comment]
fixed

**Comment by wuzide** [comment]
您好，可以联系我么，有些问题想请教您
