### ISSUE TITLE
feat: FEATURE...

### ISSUE THREAD

**Issue by TonyYu2015** [apitable/apitable#882]
I have an idea for this project.

I guess there can be a feature that users can rotate the table

## Why? 
> Why we need this feature？
In some condition, user can get the head infomation of the table without scroll the scroll-bar. 

> What is the user story for this feature? 
In my option, i can get both data information and compare result of the data in a static interface.

## What?
> Can you describe this feature in detail?
> Who can benefit from it? 
People who want to compare data between different season or year.

**Comment by arucil** [comment]
Sorry I can't get you. What does "rotate table" mean? Turn columns into rows and vice versa?

**Comment by mr-kelly** [comment]
Can you write a title?
