### ISSUE TITLE
feat: Add an action in automation that can modify other datasheets

### ISSUE THREAD

**Issue by catynaimiao** [apitable/apitable#889]
I have an idea for this project.

## Why? 

目前在实现一些简单的自动化流程，比如两个部门分别为“A”和“B”，通过创建A部门一个订单的一条record，通过Robot直接可以设置对另一个B部门的表单新建一条记录并通知A记录中选定指定用户。

目前实现这个功能只能使用Api接口实现，同时设置Api请求在没有第三方后台时很难调试。（例如需要获取bearer token，部署开发环境）

## What

Robot 被可操作对象加入其他表单

**Comment by pengjin123** [comment]
@catynaimiao 
Can your function be achieved through the following approach：
You can use the method of sending network requests in the robot action to write the data of Department A to Department B, and then select the corresponding members of Department A in the member parameters

**Comment by catynaimiao** [comment]
@pengjin123 

Thank you very much for your proposal. I'm currently using a similar approach to solve the problem, but I'm suggesting features that simplify the process or provide better debugging support.

**Comment by xukecheng** [comment]
> @pengjin123
> 
> Thank you very much for your proposal. I'm currently using a similar approach to solve the problem, but I'm suggesting features that simplify the process or provide better debugging support.

Thank you for your response. We are currently working on optimizing the automation function, which will be a long-term project. Your mentioned requirements will be taken into consideration.
