### ISSUE TITLE
feat: Bpm approval process support

### ISSUE THREAD

**Issue by meimosor** [apitable/apitable#890]
Combining forms to achieve workflow approval related business scenarios

**Comment by nagisakon** [comment]
Please submit the feature issue in the specified format and provide more details (including what exactly you want to do, why you want to do it and how to implement it). This will help us better understand your purpose >>> https://github.com/apitable/apitable/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=feat%3A+FEATURE...

**Comment by meimosor** [comment]
> Combining forms to achieve workflow approval related business scenarios

I have an idea for this project.
Combining forms to achieve workflow approval related business scenarios
## Why? 
> Why we need this feature？
> Forms are not only about data entry, but can also assign some actions to connect the entire business flow


## What?
> Can you describe this feature in detail?
> When I submit a form, I need to send and cc the relevant personnel for review, and only after the review is approved can I proceed with the next steps

## How?
1. Create Form
2. Design workflow (such as when a certain field of the associated form reaches a certain condition)
3. Manually or automatically trigger workflows
4. Perform association operations, such as updating a field value in the associated form

**Comment by Alex-hufeng** [comment]
You can use a robot to achieve the following business scenarios:

When a form is submitted, the robot will send a message to an approver.
When the approver changes the record's status from "in progress" to "Pass," a message will be sent to the submitter.
Automatically update some related data.



![CleanShot 2023-06-06 at 15 55 11@2x](https://github.com/apitable/apitable/assets/54580109/3e8b1e96-1866-4e19-b396-8435837b3a78)
