### ISSUE TITLE
docs: 内存占用问题

### ISSUE THREAD

**Issue by zhanba** [apitable/apitable#891]
wsl2 下启动需要占用20g内存，默认wsl2的最大内存是系统的50%，内存不够会有奇怪的错误。
fork-ts-checker-webpack-plugin之类的插件很占用内存，是否有优化空间？

![image](https://github.com/apitable/apitable/assets/4224253/6c923847-4570-4cb1-b0b0-035a0d0f6bce)

**Comment by JaneSu** [comment]
We have removed the fork-ts-checker-webpack-plugin and added type checking during git commit stage through husky. We will update this part of the code next week.

If you have any better suggestions regarding this issue, you can also discuss it with us.
