### ISSUE TITLE
fix: BUG Creating a datasheet always shows a runtime error: "TypeError: this.storeProvider.createDatasheetStore is not a function"

### ISSUE THREAD

**Issue by huanghui1** [apitable/apitable#893]
**Describe the bug**
Run the code local and try to add a new datasheet, will get the runtime error: "TypeError: this.storeProvider.createDatasheetStore is not a function", and the page keep loading. Sees screenshots.

**To Reproduce**
1. Run code followed this doc: https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A
2. Open http://localhost:3000 in browser
3. Click *Add* -> *New datasheet*

**Expected behavior**
Should add datasheet success.

**Screenshots**
<img width="1783" alt="Screen Shot 2023-05-31 at 14 11 08" src="https://github.com/apitable/apitable/assets/12216380/e0d397d7-7589-4746-b275-53d6d005547b">

**Comment by arucil** [comment]
try running `yarn buid:dst:pre` before starting web-server.

**Comment by huanghui1** [comment]
@arucil Thanks. It works. But the command is ```yarn build:dst:pre```, running ```yarn buid:dst:pre``` will throw an error.😅

**Comment by arucil** [comment]
> @arucil Thanks. It works. But the command is `yarn build:dst:pre`, running `yarn buid:dst:pre` will throw an error.sweat_smile

Sorry, typo.😂
