### ISSUE TITLE
fix: BUG The version deployed by docker-compose, the configured Robot did not execute, and there is no record of any execution.

### ISSUE THREAD

**Issue by wangwox** [apitable/apitable#895]
如题

**Comment by nagisakon** [comment]
Please submit issues with the correct formatting (https://github.com/apitable/apitable/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=fix%3A+BUG) and include screenshot details. This will enable us to help you troubleshoot the issues more effectively
