### ISSUE TITLE
feat:import or export as excel file

### ISSUE THREAD

**Issue by jienian** [apitable/apitable#898]
我有想法一直想告诉你,

Excel导入导出，支持单表导出和一对多表模式导出，生成的代码带导入导出功能。

为了目的是开发一个简易Excel导入导出功能的工具可以大大提高工作效率和准确性。

**Comment by Alex-hufeng** [comment]
hi,
you can click the button "export data" of datasheet 

![CleanShot 2023-06-06 at 15 50 57@2x](https://github.com/apitable/apitable/assets/54580109/ec582417-8682-4bec-9847-9f0a11bbab6c)

**Comment by jienian** [comment]
Hi


我想去你这公司从事编程的工作。
你看可以吗？


谢谢



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apitable/apitable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月6日(星期二) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apitable/apitable] feat:import or export as excel file (Issue #898)





 
hi,
 you can click the button "export data" of datasheet

**Comment by Alex-hufeng** [comment]
> Hi 我想去你这公司从事编程的工作。 你看可以吗？ 谢谢 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apitable/apitable" ***@***.***&gt;; 发送时间:&nbsp;2023年6月6日(星期二) 下午3:53 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [apitable/apitable] feat:import or export as excel file (Issue #898) hi, you can click the button "export data" of datasheet — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


Glad to hear that.

Please send your resume to talent@apitable.com
