### ISSUE TITLE
question: map fields do not use ts generic constraints

### ISSUE THREAD

**Issue by shidengyun** [apitable/apitable#903]
like some code 

const _layout = widgetList.map(item => {
      const widgetPosition = layoutMap[item.id];
      return {
        id: widgetPosition.i,
        y: widgetPosition.y,
        height: widgetPosition.h,
      };
    });
    
    nodeList?.length ? nodeList?.map(item => {

**Comment by ziqiangai** [comment]
Hi @shidengyun , can you give more information?

**Comment by shidengyun** [comment]
您好，信息我已经收到，我会尽快阅读并给您回复。

**Comment by shidengyun** [comment]
您好，信息我已经收到，我会尽快阅读并给您回复。
