### ISSUE TITLE
fix: Add Image in Folder Description should be disabled in read-only mode

### ISSUE THREAD

**Issue by ranglang** [apitable/apitable#906]
**Describe the bug**

**To Reproduce**
1. Go to page 'workbench‘
2. Click on '+Add'
3. Scroll down to 'New Folder'
4. Click on 'Add decription'
5.  Entry '/' insert 'Image'
6. Click 'X' Button, exit on Edit mode
7.  Click 'Share',  share the folder and get the share link  eg. https://apitable.com/share/shrZCpTfeL1jemrVZs5cZ/fodoPuSE3RrQE
8.  Click 'Add Image' placeholder,  you will then be prompted with a file selection

**Expected behavior**

1. Since you are in readonly mode,  file upload should be forbidden.
2.  Tips might be needed while image is empty in description. 

**Screenshots**

<img width="1667" alt="image" src="https://github.com/apitable/apitable/assets/12862508/251cfa5f-199c-4199-88f9-494d53d79b22">

[link for shared description](https://apitable.com/share/shr1yTtfJ18BUvJi0t1M9/fodLWzGqTtrtN)
[link for empty image in description ](https://apitable.com/share/shrZCpTfeL1jemrVZs5cZ/fodoPuSE3RrQE)

**Additional context**

**Comment by pengjin123** [comment]
@ranglang 
The current read-only permission doesn't allow any other operations to be performed because the permission is controlled by the backend. Only after performing an operation will there be a corresponding information prompt
