### ISSUE TITLE
fix: Unable to start the local development environment and see the user interface

### ISSUE THREAD

**Issue by Misaka-0x447f** [apitable/apitable#907]
**描述Bug**
**Describe the bug** 
阅读 [Developer Quick Start](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A) 和 [Troubleshooting](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW) 并按照指引操作后无法启动本地开发环境并看到用户界面。
After reading and following the instructions from [Developer Quick Start](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A) and [Troubleshooting](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW) I still not able to start local development env successfully and see the GUI.

所使用的开发者面试调查表：https://apitable.com/share/shrDNBDeVlLvB1eFDMWhl/fom4DPpt6TnHaE9XnA
The interview form I used is [here](https://apitable.com/share/shrDNBDeVlLvB1eFDMWhl/fom4DPpt6TnHaE9XnA).

其中，单独启动后端服务器(`make run 1`)可以看到如下文中第一张屏幕截图的报错。看起来像是无法连接数据库。此时约使用物理内存 4G。
同时启动前端服务器(`make run 3`)可以看到如下文中第二张屏幕截图的报错。
该现象导致无法顺利完成面试流程。
For more detail, only starting the backend server(`make run 1`) resulting error in screenshot 1 which seems like a database connection error. Now its using 4G memory. 
Starting the frontend server(`make run 2`) simultaneously resulting error in screenshot 2.
In this situation I cannot complete the interview form.

另外，#891 报告启动本地开发环境需要至少 20G 物理内存，而我的开发设备的物理内存是 16G。
Plus, #891 reporting start a local development server requires at least 20G memory while I only have 16G memory in my rig.

**重现步骤**
**Step to reproduce**
按照 [Developer Quick Start](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A) 和 [Troubleshooting](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW) 操作。
详细地说，我做了如下操作：
Follow the instruction in [Developer Quick Start](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A) and [Troubleshooting](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW).
More specifically, what I have done is following:
```
sudo apt update
sudo apt install git
sudo apt install build-essential
sudo apt install python3

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
curl -s "https://get.sdkman.io" | bash
nvm install 16.15.0 && nvm use 16.15.0 && corepack enable
sdk env install
curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly --profile minimal -y && source "$HOME/.cargo/env"

make dataenv 
make install 
make run # enter 1  
make run # enter 2
make run # enter 3
```

**期望行为**
**Exception**
在低至 16G 物理内存的开发设备中正常启动本地开发环境。
Start local development env with 16G memory.

**屏幕截图**
**Screenshots**
![image](https://github.com/apitable/apitable/assets/15797507/652e0b59-12f4-4339-b322-dce5b621bff6)
![image](https://github.com/apitable/apitable/assets/15797507/5962e79f-ef7c-4cf2-b0e5-05921bbc991f)

**电脑版（请填写以下信息）：**
**env**
我在 debian 11 和 wsl2 + debian 下分别尝试了重现步骤，均可复现。

**Comment by luckyyyyy** [comment]
Hey there, starting up right now does use a lot of memory. If you have swap enabled, it should be able to kick off the development environment okay. Another thing you could try is switching off the fork-ts-checker-webpack-plugin plugin to see if that helps.

**Comment by ziqiangai** [comment]
It is a redis connection problem, check whether the redis connection password configured by `backend-server` is correct

**Comment by Misaka-0x447f** [comment]
> It is a redis connection problem, check whether the redis connection password configured by `backend-server` is correct

So how can I know the correct password?

**Comment by ziqiangai** [comment]
It is defined here:
https://github.com/apitable/apitable/blob/29caf6135b5557bd4b3183072585c1d08ff250a7/.env#L44-L48

You can try to connect to it using client tools or command line tools.
