### ISSUE TITLE
question:How to disable open registration?

### ISSUE THREAD

**Issue by Donglingfeng** [apitable/apitable#910]
Description:

Currently, APITable allows anyone to freely register. Hope to strengthen the registration process and restrict the creation of accounts to only specific users or individuals who have been approved. The goal is to prevent unauthorized users from accessing or abusing the system.

Request:

1.  User registration restriction: We seek assistance in limiting the registration process solely to specific users or approved individuals. Our goal is to prevent unauthorized users from gaining access.
    
2.  Invitation-based registration: We are interested in exploring the feasibility of an invitation-based registration system. Ideally, users should only be able to create an account if they have received an invitation or obtained approval from an administrator.

**Comment by Alex-hufeng** [comment]
Are you currently using APITable Community Edition?

**Comment by Donglingfeng** [comment]
> Are you currently using APITable Community Edition?

Yes, I am currently using the Community Edition.

**Comment by Alex-hufeng** [comment]
We can provide partial customization function in Enterprise Edtion, you can submit the form below:

https://apitable.com/share/shrdaGGppsfg3pjQLXALG/fomnfpJ9XBfDDz6Dkz?fldy5ZmHYGZx2=self-hosted-pxpage
