### ISSUE TITLE
docs: the 5 step's command of How to add supprted Languages is incorrect in Troubleshooting

### ISSUE THREAD

**Issue by Jabez13410** [apitable/apitable#913]
## What documentation do you want?
Replace `make l10n-apitable-ce` with `make settings`?

**Comment by ziqiangai** [comment]
Yes, the documentation here needs to be updated. I will Improve documentation later. [document url](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/i18n-f8YYzpOrXj)

**Comment by ziqiangai** [comment]
I have updated the [docs](https://apitable.getoutline.com/doc/troubleshooting-ogBPfk3YTW#h-how-to-change-the-default-80-port).
