### ISSUE TITLE
fix: 配置了robot但不能触发

### ISSUE THREAD

**Issue by ClearloveTwo** [apitable/apitable#915]
看板右上角配置了robot，但是在符合条件时没有触发robot的通知。

**重现步骤**
重现行为的步骤：
1. 前往看板
2. 点击右上角配置robot，设置创建新纪录时发送邮件通知
3. 新增一个task。
4. 未收到robot的邮件通知

期望应该是能触发邮件通知的，查看数据库表apitable_datasheet_changeset是可以看到变更记录，猜测是缺少了消费变更消息的代码逻辑。

**Comment by pengjin123** [comment]
@ClearloveTwo Could you please provide screenshots of the robot's configuration and operation history

**Comment by coyclei** [comment]
I also encountered the same problem in v0.21.0-rc

**Comment by ClearloveTwo** [comment]
> The problem has been resolved, and it is necessary to add enableAutomationWorker=true to the environment variable file
