### ISSUE TITLE
Robot can't run in v0.21.0-rc

### ISSUE THREAD

**Issue by coyclei** [apitable/apitable#917]
![image](https://github.com/apitable/apitable/assets/13805241/172f7c8c-ccbd-419b-a5c7-505709cf7c13)
![image](https://github.com/apitable/apitable/assets/13805241/38a8e01c-4fae-497b-b2bf-12e97b8e5cc4)
![image](https://github.com/apitable/apitable/assets/13805241/efdce7bd-e4ec-4f19-af8b-5269517641a5)

**Comment by nagisakon** [comment]
The problem has been resolved. https://github.com/apitable/apitable/issues/915
