### ISSUE TITLE
fix: Block the follow function button

### ISSUE THREAD

**Issue by nagisakon** [apitable/apitable#918]
**Describe the bug**

**To Reproduce**

version：APItable-CE
The version of Community doesn't support "watch this record"
![image](https://github.com/apitable/apitable/assets/49678762/0a99dc47-72b0-4e97-a23b-924e9a968f33)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v0.20]

**Smartphone (please complete the following information):**
 - Version [e.g. v0.20]

**Additional context**

**Comment by wangkailang** [comment]
fixed
