### ISSUE TITLE
docs: windows11 完整安装开发环境流程

### ISSUE THREAD

**Issue by pejaz** [apitable/apitable#924]
## 环境安装
1. 安装docker desktop，在设置中打开docker compose v2
2. 升级wsl至最新版，安装 Ubuntu

## 启动服务
1. 在 Ubuntu 中 `git clone` 项目代码
2. 切换至项目目录下执行命令 `curl https://apitable.github.io/install.sh | bash`

**Comment by arucil** [comment]
Thanks, however it's unnecessary to clone the repo if you are using the docker composed apitable.
