### ISSUE TITLE
question: A brief escription of your question

### ISSUE THREAD

**Issue by zy6054726** [apitable/apitable#925]
The number of long connections of apitable is easy to block and disturb the number of connections of the server, he is alive for a long time

**Comment by ziqiangai** [comment]
Hi @zy6054726 ，do you have a more detailed description of the question.

**Comment by zy6054726** [comment]
收到，谢谢！

**Comment by arucil** [comment]
We use websockets for real time communication between webpage and server, there are no HTTP long connections.

**Comment by zy6054726** [comment]
收到，谢谢！
