### ISSUE TITLE
what can it do and how does it works.

### ISSUE THREAD

**Issue by LinkCisss** [apitable/apitable#926]
## Any questions?
You have provided all the information about this product on GitHub. I can run it, and I even know how to make modifications, but I still don’t know what makes it outstanding

**Comment by arucil** [comment]
Thank you for your interest in APITable! I'm glad to hear that you've been able to run and modify the project. The achievement of APITable reaching its versatility and friendliness today is the result of years of hard work by all APITable team members.

**Comment by arucil** [comment]
You can visit our [help center](https://help.apitable.com/) to learn the capabilities of APITable, and [APITable cookbook](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41) reveals the internal working model of APITable, from which you can learn about how data of APITable flows, transformed, and stored.
