### ISSUE TITLE
docs: The detail of “Developer Quick Start” guide document.

### ISSUE THREAD

**Issue by dage233** [apitable/apitable#928]
## 1
The first step is to clone the project, but it's not mentioned in the documentation, it may failed in the following line of commands because missing file `.sdkmanrc`.

```
nvm install 16.15.0 && nvm use 16.15.0 && corepack enable
```

## 2

the sdkman package depend package `zip`, must install `zip` before the following line of commands.
```
curl -s "https://get.sdkman.io" | bash
```

**Comment by pengjin123** [comment]
@networkhermit Could you please help me check? Thank you

**Comment by arucil** [comment]
We've reorganized the [developer guide](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A) to make it more clear and added missing dependencies.
