### ISSUE TITLE
docs: MySQL service keeps being unhealthy in WSL2

### ISSUE THREAD

**Issue by cheny-00** [apitable/apitable#929]
我用docker-compose 在wsl2上搭建APITABLE，但是MySQL一直提示unhealthy。https://github.com/apitable/apitable/issues/331 有提到这个问题。如果可以的话，在readme中加一下提示会不会更好呢？

**Comment by arucil** [comment]
Good idea, we've added this problem in [Troubleshooting](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW#h-container-mysql-keeps-being-unhealthy-in-wsl2).
