### ISSUE TITLE
question: Does the sorting of table fields not support numbers?Or I use in the right way?

### ISSUE THREAD

**Issue by Vanmin** [apitable/apitable#930]
<img width="1058" alt="image" src="https://github.com/apitable/apitable/assets/48267200/16806236-685d-4496-8a53-e7c898321eb8">

**Comment by arucil** [comment]
The `序号` column in  your screenshot is text type, it's not number.

**Comment by Vanmin** [comment]
When I choose to sort from smallest to largest, the content disappears and appears from largest to smallest.
<img width="1115" alt="1" src="https://github.com/apitable/apitable/assets/48267200/14ccda6a-7f66-4fb3-b73d-705df9a97ef2">
<img width="1145" alt="2" src="https://github.com/apitable/apitable/assets/48267200/242a421c-66e6-4232-882b-2f774054bdb7">

**Comment by arucil** [comment]
Looks like they are empty records. When sorting in ascending order, empty records will go before non-empty ones.
