### ISSUE TITLE
question: What is the purpose of generating these core files in bulk every morning?每天早上开始大批量生成的这些core文件是什么用的？

### ISSUE THREAD

**Issue by dongdongdonglin** [apitable/apitable#931]
如图所示：
![image](https://github.com/apitable/apitable/assets/134598082/e30dd331-7d09-4ea1-83b9-8924739a07b5)

**Comment by pengjin123** [comment]
@arucil Could you please help me check? Thank you

**Comment by arucil** [comment]
`core.<number>` are core dump files generated by Linux when a process crashes. Run `file core.26995` to check out what process has crashed, and check out the logs of that container. Then post the error here for me to look into the problem, thanks.

**Comment by arucil** [comment]
We have a release yesterday, this problem should've been solved, please pull the latest image.
