### ISSUE TITLE
fix: 手机号登录校验规则不严谨问题

### ISSUE THREAD

**Issue by CCJCSF** [apitable/apitable#932]
**描述Bug**
登录页面手机号登录校验有问题

- 问题1国内手机号位数校验有问题,12位依然能够校验通过
<img width="1488" alt="image" src="https://github.com/apitable/apitable/assets/86881672/3765ec61-db71-4149-b0a3-614c72dc3d9f">

- 问题2切换国家区号代码后,校验规则应该匹配当前国家对应的手机号规则,并且最好是清楚之前国家区域对应的手机号 
<img width="1519" alt="image" src="https://github.com/apitable/apitable/assets/86881672/038c5900-2782-4063-9caa-d9565b9bbb4b">

**重现步骤**
重现行为的步骤：
1. 前往“[https://vika.cn/login](url)”
2. 点击“手机号/邮箱登录”
3. 滚动到“默认在手机号登录的tab下”
4. 输入12位手机号后,光标离开手机号输入框校验依旧能通过
5. 切换国家代码为美国后错误手机号依旧能够校验通过

**期望行为**

- 期望匹配不同国家不同的校验规则
- 国家区号切换后或许清空输入框并且匹配当前国家手机号验证规则

**电脑版（请填写以下信息）：**
 - 版本号：MBP14-2021
 - 操作系统：[mac os]
 - 浏览器：[Chrome 113.0.5672.126(正式版本)(arm64)]

**Comment by pengjin123** [comment]
@ccj-csf When you input, there will be no verification, only when you click the login/registration button will the account and verification code be verified

**Comment by pengjin123** [comment]
@ccj-csf 
When you input, there will be no verification. Account and verification code verification will only be performed by clicking the login/registration button after the input is completed
