### ISSUE TITLE
Question: 可不可以将本地开发文档中写的更详细一些

### ISSUE THREAD

**Issue by xdyz** [apitable/apitable#933]
I have an idea for this project.

## Why? 
> Why we need this feature？
> What is the user story for this feature? 

本地开发文档中，只是说明了 封装了make 命令等  
当时其中遇到的一些问题，好像并没有能够询问的地方，有时候会出现某些组件无法访问问题等
## What?
> Can you describe this feature in detail?
> Who can benefit from it?

**Comment by luckyyyyy** [comment]
Can you tell me about the issues you've faced?

**Comment by arucil** [comment]
We cannot predict all possible problems during the development of APITable, so we only listed a bunch of FAQs in [Troubleshooting](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW), if you encountered a problem not listed in it, feel free to open an issue.

Also, trying to search for similar issues before opening a new one is a good practice.
