### ISSUE TITLE
fix: 在docker上拉的all in one镜像，机器人功能不起作用

### ISSUE THREAD

**Issue by minren118** [apitable/apitable#934]
我在docker上拉了all in one镜像，版本是latest版本。
在windows上的docker for windows启动了镜像，其他一切都正常，但唯独机器人就不可以用。

配置机器人的流程是可以的，就是看支行记录里，都是显示【暂无运行历史】，试了好几个触发条件如创建表单触发，字段记录更新时触发都不管用。

![image](https://github.com/apitable/apitable/assets/28550438/e59e3ced-bfbe-4044-8ed3-c12fd71b23ce)

**Comment by minren118** [comment]
看到colsed的issue提到了需要设置环境变量才能用，亲测成功了。

![image](https://github.com/apitable/apitable/assets/28550438/c11cf17d-bb29-4c1b-ba4b-3aaf5b76bcbe)

**Comment by Kaiyuan** [comment]
在那个加？我直接用安装脚本安装的不知道怎么修改。
