### ISSUE TITLE
Cannot find module '@apitable/core'

### ISSUE THREAD

**Issue by choiking** [apitable/apitable#935]
Issue:
Module not found: Can't resolve '@apitable/core'

What I tried:
1. npm list @apitable/core
so the packages is installed
2. delete all node-modules and do make install again.

edit:
The @apitable/core packages are downloaded correctly both in Root and sub modules. But still saying Cannot find module '@apitable/core'

**Comment by arucil** [comment]
Did you use nodejs 16.15?

**Comment by Hunter-857** [comment]
node v16.14.2. has meet the same problem ,any update?

**Comment by Hunter-857** [comment]
I have meet this too，I checked the error log  , it just due to some network issue，fixed after add proxy server

**Comment by choiking** [comment]
> Did you use nodejs 16.15?
no I am on node v20

**Comment by choiking** [comment]
> I have meet this too，I checked the error log , it just due to some network issue，fixed after add proxy server

what proxy server do you mean?

**Comment by choiking** [comment]
> Did you use nodejs 16.15?

I used 16.15 now, delete node_modules and reinstall, still error

**Comment by Hunter-857** [comment]
> 

In face I find the some error due can not reach github to download file,then I just try to used some proxy server for download. may be you should check check the error log

**Comment by choiking** [comment]
> The @apitable/core packages are downloaded correctly both in Root and sub modules. But still saying Cannot find module '@apitable/core'

The download is successful for @apitable/core, both in Root and sub modules. But still saying Cannot find module '@apitable/core' I am guessing the symbolic link issue?

**Comment by arucil** [comment]
`@apitable/core` is inside this repo, so there won't be downloading of `@apitable/core`, may be there is other package failed downloading.

**Comment by choiking** [comment]
> `@apitable/core` is inside this repo, so there won't be downloading of `@apitable/core`, may be there is other package failed downloading.

I did yarn install and it says: ".. is successful, with some warnings." I think all the packages are downloaded successful.

**Comment by arucil** [comment]
Have you modified some files in the repo?

**Comment by fengjianying** [comment]
did you solve this problem? i meet the same question

**Comment by arucil** [comment]
> did you solve this problem? i meet the same question

@fengjianying Make sure the `yarn.lock` isn't changed, or if you need to add a dependency, don't delete `yarn.lock`, just run `yarn add xxx`.
