### ISSUE TITLE
feat: A brief description of your requested feature

### ISSUE THREAD

**Issue by dcy652701** [apitable/apitable#936]
I have an idea for this project.

## Why? 
> I have used an another product, this product can use table to interact with your csv or Excel file.

## What?
> You can write some code in table cell and run, and the table cell will return the computing result
> Who can benefit from it?  I think people who is doing data analyzing will very like this feature.

**Comment by arucil** [comment]
Are you refering to the formulas in Excel like `=A1+B1`?

**Comment by mr-kelly** [comment]
Talking about a "Scripting Column"?

**Comment by mr-kelly** [comment]
1. Lack of clarity 
2. Lack of title
