### ISSUE TITLE
When can you support one click switching between Chinese and English？

### ISSUE THREAD

**Issue by Cara-yy** [apitable/apitable#937]
## Any questions?

**Comment by luckyyyyy** [comment]
This doesn't seem to be a feature that's used very often. In what scenarios would it be used?

**Comment by arucil** [comment]
APITable aims to be an international application, so a feature dedicated to Chinese is unlikely to be added. Instead, if you want to toggle language, you can click the avatar image on the left bottom corner on the page -> Preferences -> Language, and choose your desired language.
