### ISSUE TITLE
fix: exportBundle备份数据时，缺少recordMeta，导致创建用户，自增字段不能备份

### ISSUE THREAD

**Issue by baiy513** [apitable/apitable#955]
**描述Bug**
用exportBundle导出数据时，没有导出数据表apitable_datasheet_record中的field_updated_info信息,导致创建用户，自增字段不能备份

**重现步骤**
重现行为的步骤：
1. 用 exportBundle随意导出一张表格数据
2. 解压导出的数据，用base64解码，观察recordMeta是否为空
**期望行为**
希望能把apitable_datasheet_record的field_updated_info导出来，然后能导入进行备份

**Comment by ziqiangai** [comment]
This feature is being refactored.

**Comment by baiy513** [comment]
非常感谢，但这个功能大概什么时候会完成，我们需要备份功能。




byxsir
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apitable/apitable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apitable/apitable] fix: exportBundle备份数据时，缺少recordMeta，导致创建用户，自增字段不能备份 (Issue #955)





 
This function is being refactored.

**Comment by ziqiangai** [comment]
> 非常感谢，但这个功能大概什么时候会完成，我们需要备份功能。 byxsir ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apitable/apitable" ***@***.***&gt;; 发送时间:&nbsp;2023年6月15日(星期四) 下午4:54 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [apitable/apitable] fix: exportBundle备份数据时，缺少recordMeta，导致创建用户，自增字段不能备份 (Issue #955) This function is being refactored. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

We will release this feature in version `v0.23.0`, next month.
