### ISSUE TITLE
question: m1版本的mac是否能启动前端代码？

### ISSUE THREAD

**Issue by wangqiqi95** [apitable/apitable#956]
> 前提：node版本为： v16.15.0。python版本为：python3
## 2：我手动安装`canvas`后，运行`yarn run sd`，页面卡死

<img width="1033" alt="image" src="https://github.com/apitable/apitable/assets/47977537/4a982045-d11e-4015-a216-0d3716d73082">

**Comment by ziqiangai** [comment]
execute `make run`.

Here is more detailed [documentation](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A)

**Comment by wangqiqi95** [comment]
还是一样的问题。m1版本的mac是可以正常通过源码启动吗？我看了文档说明，所需的版本也是按照文档上面来的，能不能加个启动流程的文档

**Comment by wangzhongqi1995** [comment]
还是一样的问题。m1版本的mac是可以正常通过源码启动吗？我看了文档说明，所需的版本也是按照文档上面来的，能不能加个启动流程的文档

**Comment by wangqiqi95** [comment]
我把代码重新clone了一下，执行`mark install-local`后报错如下：
<img width="1664" alt="image" src="https://github.com/apitable/apitable/assets/47977537/1e3c1edc-13ea-4112-8334-e5dd13c598a0">

**Comment by ziqiangai** [comment]
I am sure that the mac environment can start the code. Have you executed the command according to the [documentation](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A): 

```shell
brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman zip
```

For the first startup, it is recommended to execute the following command:

<img width="589" alt="image" src="https://github.com/apitable/apitable/assets/18455767/fc6b0c5c-8d38-4502-818e-758728c251f2">

**Comment by luckyyyyy** [comment]
I confirm that the apple silicon can initiate the apitable. Just follow the instructions in the development documentation to proceed

<img width="1460" alt="image" src="https://github.com/apitable/apitable/assets/9210430/2288552d-04ab-4405-b711-781c33c2e29b">

<img width="837" alt="image" src="https://github.com/apitable/apitable/assets/9210430/4a9af4ba-2dd5-4f5e-8204-28dd2803585a">

**Comment by wangqiqi95** [comment]
我把最新代码下载后试了一下可以在m1上运行了，感谢
