### ISSUE TITLE
make install 执行了47m24s，但是报错了

### ISSUE THREAD

**Issue by jmxsxwyzjdwl** [apitable/apitable#959]
## Any questions?
![image](https://github.com/apitable/apitable/assets/93360368/1ff32817-20df-42dd-a10a-447cdcc8dc5f)

**Comment by luckyyyyy** [comment]
If you are using the China internet, please install via a proxy server

**Comment by arucil** [comment]
Take a look at these logs files
![image](https://github.com/apitable/apitable/assets/5410312/332e6bc0-272a-4eec-83bf-d522758fd700)

**Comment by zhengyulong-cn** [comment]
开启终端代理
