### ISSUE TITLE
question: 社区办有计划开放权限功能么,这个功能还蛮重要的

### ISSUE THREAD

**Issue by GuoRanYiMao** [apitable/apitable#960]
如题 一般企业级构建社区办 如果没有权限 就感觉像是玩具了 没有办法作为公司级项目使用 只能局限于部门级 
想问问咱们社区办有没有计划做权限 大概是个什么规划 非常感谢
ps:感谢这么好的产品开源

**Comment by mr-kelly** [comment]
On Enterprise edition: https://vikadata.com and https://apitable.com

**Comment by mr-kelly** [comment]
Our Enterprise editions at https://vikadata.com and https://apitable.com include the following features. 

We also offer self-hosted Enterprise editions. If you're interested, please feel free to contact us at sales@apitable.com.

**Comment by GuoRanYiMao** [comment]
我知道咱们企业版和托管版有 公司这边今年可能没有相关预算 想问问咱们社区版有没有计划开放权限功能

**Comment by mr-kelly** [comment]
no

**Comment by mr-kelly** [comment]
Sorry. No. Only for enterprise
