### ISSUE TITLE
发现mysql文件夹下有59个分别占用1G的文件，疑似是LOG文件

### ISSUE THREAD

**Issue by jhk5263** [apitable/apitable#961]
![344db5f5-b7fe-4f4c-8c07-54321d291102](https://github.com/apitable/apitable/assets/71970354/fe59d4c8-0a2d-4214-a07d-f526df66793d)
这些文件是否是可以删除的？

**Comment by ziqiangai** [comment]
Hi @jhk5263. You can handle them like you manage mysql's binlog files, like [here](https://www.casesup.com/category/knowledgebase/howtos/how-to-remove-and-purge-old-mysql-binary-log-files).

**Comment by jhk5263** [comment]
> Hi @jhk5263. You can handle them like you manage mysql's binlog files, like [here](https://www.casesup.com/category/knowledgebase/howtos/how-to-remove-and-purge-old-mysql-binary-log-files).

got it thanks
