### ISSUE TITLE
question: Customize the numerical field, in ascending order of the value, the table data disappears

### ISSUE THREAD

**Issue by joezhouplus** [apitable/apitable#966]
Custom numerical fields or imported data contain numerical fields, the table data is displayed normally in descending order according to the numerical value, but the table data is not displayed in ascending order according to the numerical value。
ascending order
![image](https://github.com/apitable/apitable/assets/128361592/63a39aed-2cc5-4e08-8ddf-2e3724eed8f0)
descending order
![image](https://github.com/apitable/apitable/assets/128361592/b57d87f1-eb1a-4665-92e4-682e78151f08)

**Comment by arucil** [comment]
I see there are many empty records in your datasheet, when sorting in ascending order, do the 4 non-empty records appear at the bottom of your datasheet? If it is, this is normal, because empty records always come before non-empty ones when sorted in ascending order.

**Comment by mr-kelly** [comment]
> Custom numerical fields or imported data contain numerical fields, the table data is displayed normally in descending order according to the numerical value, but the table data is not displayed in ascending order according to the numerical value。 ascending order ![image](https://user-images.githubusercontent.com/128361592/246664786-63a39aed-2cc5-4e08-8ddf-2e3724eed8f0.png) descending order ![image](https://user-images.githubusercontent.com/128361592/246664770-b57d87f1-eb1a-4665-92e4-682e78151f08.png)

Sorry I don't get it.. Looks correct from your screenshots...?
