### ISSUE TITLE
question: starting web-server reports `Can't resolve '@apitable/core'`

### ISSUE THREAD

**Issue by fengjianying** [apitable/apitable#971]
## front page Unable to start
node：16.15.0
yarn: 3.4.1

1. yarn install
2. yarn run sd
3.  An error occurred

![image](https://github.com/apitable/apitable/assets/33747632/6fa9751b-1cd5-422e-a900-6021a46ead2c)

**Comment by arucil** [comment]
Have you deleted yarn.lock file and regenerate it with `yarn` command?

**Comment by fengjianying** [comment]
no i do not

**Comment by arucil** [comment]
Run `yarn build:dst:pre` before `yarn sd`
