### ISSUE TITLE
apitable 本地化部署参考哪的文档

### ISSUE THREAD

**Issue by jmxsxwyzjdwl** [apitable/apitable#976]
请问各位大佬，你们本地跑apitable，都是参考哪的文档？我参考的是https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A "Developer Quick Start"，但是总是遇到一些问题导致启动失败，所以想问一下。
我的环境是windows11 wsl2 Ubuntu docker desktop.

**Comment by jmxsxwyzjdwl** [comment]
![image](https://github.com/apitable/apitable/assets/93360368/68c72271-de74-4431-8d32-c5c9d37d5422)
例如make dataenv

**Comment by luckyyyyy** [comment]
Please check your mysql container log

**Comment by maxage** [comment]
这个怎么设置中文？部署完成后是英文。。。

**Comment by networkhermit** [comment]
Don't use Windows drive when running `make dataenv` in WSL.

**Comment by mr-kelly** [comment]
https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md

**Comment by liuJchun** [comment]
I hava a error "docker compose --env-file $ENV_FILE -p $DEVENV_PROJECT_NAME -f docker-compose.yaml -f docker-compose.dataenv.yaml up -d mysql minio redis rabbitmq init-db init-appdata
unknown flag: --env-file", when i use command " make dataenv ". how to run it
Environment：m1 macos

**Comment by mr-kelly** [comment]
update to docker compose v2
