### ISSUE TITLE
fix: A brief description of the BUG

### ISSUE THREAD

**Issue by jakob1379** [apitable/apitable#978]
**Describe the bug**
When using the `apitable/init-appdata` container with an external MySQL instance, the container does not correctly resolve the IP address. It always resolves to `10.0.2.232`. However, when using a Docker network and the service name "mysql", it works as expected. My mysql is tested and available from any host with `mysql -h mysql.shared.now -uapitable -p` using the reverse proxy traefik.

**To Reproduce**
 1. Start the apitable/init-appdata container with an external MySQL instance.
 2. Observe that the container resolves the IP address for mysql.shared.now as 10.0.2.232.
 3. Use a Docker network and the service name "mysql".
 4.  Observe that the container correctly resolves the IP address for mysql.shared.now.

**Expected behavior**
The apitable/init-appdata container should resolve the IP address for mysql.shared.now correctly when using an external MySQL instance.

**Desktop (please complete the following information):**
 - [v0.21.0-alpha_build136](https://hub.docker.com/layers/apitable/init-appdata/v0.21.0-alpha_build136/images/sha256-feab09e7d9c0875b64c8c00a5c0a16bf003e29c81c8253872e37b99c237f4213?context=explore)
 - Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:32:03 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.4
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       cbce331
  Built:            Fri Apr 14 10:32:03 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by networkhermit** [comment]
Sorry. I don't get the details of how to reproduce this issue. Could you please add more detail?

As `mysql.shared.now` is not a real domain, if it got resolved to 10.0.2.232, then there is something wrong about the local dns resolution. I suggest to use the ip address to connect to the external mysql.

Also, you can using `dig` or `ping` to troubleshoot the dns resolution in the test container.

**Comment by jakob1379** [comment]
Found the issue, which of cause had nothing to do with apitable
