### ISSUE TITLE
fix: Failed to start backend server and room server by following the developer guide

### ISSUE THREAD

**Issue by MarkoCen** [apitable/apitable#982]
**Describe the bug**
When I followed the [developer guide](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A) to setup the local environment, I am not able to run the backend server and room server.

Both servers failed to start due to passing the wrong Redis password. For example, when started the room server, I saw this error.

```bash
[WARN] This Redis server's `default` user does not require a password, but a password was supplied
[ROOM_SERVER] Error	2023-06-24 14:32:19.320 [RedisAdapterFactory] RedisClient:REDIS_PUBLISHER_CLIENT:reconnectOnError - {
  stack: [
    'ReplyError: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?\n' +
      '    at parseError (/Users/markocen/repos/apitable/node_modules/redis-parser/lib/parser.js:179:12)\n' +
      '    at parseType (/Users/markocen/repos/apitable/node_modules/redis-parser/lib/parser.js:302:14)'
  ]
}
```

To make it work, I had to comment out the `REDIS_PASSWORD` in the `.env`, then both servers started successfully.

I suspect that when using `make dataenv` to start the Redis container, the required Redis password (`apitable@com`) wasn't correctly passed to the Redis server. 

**To Reproduce**
1. pull down the latest master
2. `make dataenv`
3. `make install`
4. `make run` then select `2`

**Expected behavior**
Should be able to run dev servers by following the developer guide

**Desktop (please complete the following information):**
 - Version 14.3
 - OS: Mac OS Ventura 14
 - Browser Chrome

**Comment by networkhermit** [comment]
Can't be reproduced on a clean gitpod workspace. I suspect there are multiple redis instances in local host.
