### ISSUE TITLE
question: I would like to make a list of the key feature differences between the Community Edition and the Enterprise Edition.

### ISSUE THREAD

**Issue by Green1ee** [apitable/apitable#984]
## ATT
我有看到在readme文件中的“Features”标签特意提到了“Powerful Rows/Columns Permissions”，但实际安装了该项目的最新发布版，也没有找到有关行或列的权限管理的功能，不知道该功能是未来是否会开源，有没有相应的计划。该功能在实际使用中非常重要，非常感谢回答该问题！

I have noticed that the "Features" tag in the readme file specifically mentions "Powerful Rows/Columns Permissions", but I have actually installed the latest release of the project and have not found any features related to row or column permission management. I am not sure if this feature will be sourced in the future and if there are any corresponding plans. This function is very important in practical use, thank you very much for answering this question!

**Comment by Green1ee** [comment]
![image](https://github.com/apitable/apitable/raw/develop/docs/static/feature-permissions.gif)

**Comment by nagisakon** [comment]
This feature is available in our Enterprise Edition >>> https://apitable.com/

**Comment by Green1ee** [comment]
> This feature is available in our Enterprise Edition >>> https://apitable.com/

可不可以列一个清单，标明哪些功能在社区版可用，哪些只在企业版中可用，并将该清单放到readme文件中，以帮助大家更好的进行选择。

Can you make a list of which features are available in the community version and which are only available in the enterprise version, and place the list in the readme file to help everyone make better choices.

**Comment by nagisakon** [comment]
Thank you for your suggestions.

**Comment by mr-kelly** [comment]
https://apitable.com/pricing

There's a table here.

**Comment by Green1ee** [comment]
> https://apitable.com/pricing
> 
> There's a table here.

I found, Thank you @mr-kelly !
![image](https://github.com/apitable/apitable/assets/9738666/22b236d2-7a0a-475f-ad97-a83930333913)
