### ISSUE TITLE
question: install.sh flash my stdout 50 times?

### ISSUE THREAD

**Issue by Cherrymelon** [apitable/apitable#985]
I found it check and exec docker command 50 times?Why do that?
I think that it  is not necessary faild-retry for do such unreasonable loop

**Comment by networkhermit** [comment]
Yes. Maybe we should only retry the `docker compose pull` step so much times. The main reason for that loop is that dockerhub is not very stable (i.e. for users in China) and retrying often fix that issue.

**Comment by Cherrymelon** [comment]
@networkhermit How about considering use `curl -I https://hub.docker.com/`  then catch status code to avoid the failed-retry branch？

**Comment by networkhermit** [comment]
> @networkhermit How about considering use `curl -I https://hub.docker.com/`  then catch status code to avoid the failed-retry branch？

No. That's not a reliable way to retry image pulling, as it may fail in the middle of operation.
