### ISSUE TITLE
bug: robot zh info encode exception

### ISSUE THREAD

**Issue by yacy123** [apitable/apitable#995]
**场景**：
当我们进入到APITable的时候，在个性化设置中选择语言为**中文**，然后在工作台中，我们去添加“**机器人**”，选择创建机器人之后，在**选择触发条件**和**选择操作**的可选单选选项中，都是**乱码**，但英文并没有这个问题产生。
**英文**：
![e15044775d81f96e90c3391f3a9e070](https://github.com/apitable/apitable/assets/57926991/6668a44e-5e84-4cbf-84ba-3d9ef3cd4df6)

![666909f939406a16c972d9ba11bab64](https://github.com/apitable/apitable/assets/57926991/1c94a4fb-13a9-43e3-9de4-734acb457123)
**中文**：
![8f464a8f47c28ca5db90e37ca8e402c](https://github.com/apitable/apitable/assets/57926991/a1de6532-6657-4643-a500-b6a9c01de802)
![15729e49e63e28609d7a44612e85689](https://github.com/apitable/apitable/assets/57926991/ea623a5a-2dc1-465c-8e4a-330f3ee0dcb6)

**Comment by ChambersChan** [comment]
@yacy123 感谢你的反馈，问题已经修复。可以重新`make up`启动，或者根据自己的启动方式，主动拉取更新最新的 init-appdata 镜像后即可恢复。
