### ISSUE TITLE
feat: Developer Quick Start guide descript not detailed

### ISSUE THREAD

**Issue by yo-ooiii** [apitable/apitable#998]
## Why? 
按照开发者指南使用contos7进行本地化部署时，会遇到一些版本上的问题导致安装环境时不流畅。
<img width="1280" alt="屏幕截图 2023-06-28 031350" src="https://github.com/apitable/apitable/assets/111508006/cc982829-7e58-4214-9857-7c1873d2017b">

**Comment by ziqiangai** [comment]
Try again several times, it may be a network connection problem.

reference: [link](https://lightrun.com/answers/jonnyzzz-teamcity-node-often-get-random-error-version-10-not-found---try-nvm-ls-remote-to-browse-available-versions)
